@extends('layouts.app')

@section('title', 'Raport dotyczący badania: "Wpływ tożsamości wspólnotowej i wiedzy ekonomicznej na wybory konsumenckie studentów"')

@section('content')

    <!-- BLOG DETAILS HOME START -->
    <section class="section" style="padding: 170px 0px 75px 0px; background-size: cover; position: relative; background-position: center center;" id="home">
        <div class="bg-overlay"></div>
        <div class="home-center">
            <div class="home-desc-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="home-page-title text-center">
                                <h1 class="text-white mb-2">Raport dotyczący badania: "Wpływ tożsamości wspólnotowej i wiedzy ekonomicznej na wybory konsumenckie studentów"</h1>
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb justify-content-center bg-transparent">
                                        <li class="breadcrumb-item text-white"><a href="/" class="text-white">Strona główna</a></li>
                                        <li class="breadcrumb-item active" aria-current="page"><a href="{{ url('/domanska-artykul') }}" class="text-custom">Raport dotyczący badania: "Wpływ tożsamości wspólnotowej i wiedzy ekonomicznej na wybory konsumenckie studentów"
                                        </a></li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- BLOG DETAILS HOME END -->

    <!-- BLOG DETAILS START -->
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">


                    <div class="blog-info p-3">
                        <h1 class="text-dark mb-3">Prof. Agnieszka Domańska</h1>

                        <div class="blog-info-desc">
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Raport dotyczący badania: &quot;Wpływ tożsamości wsp&oacute;lnotowej i wiedzy ekonomicznej na wybory konsumenckie student&oacute;w&quot;</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <h2>Wstęp</h2></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kwestia promowania rodzimych produkt&oacute;w jako narzędzie, albo też jeden ze sposob&oacute;w &nbsp; wspierania krajowych firm jest jednym z istotniejszych aspekt&oacute;w polityki gospodarczej każdego państwa. Wydaje się jednak, że społeczna odpowiedź na tego rodzaju działania, a więc faktyczne przekonanie do kupowania produkt&oacute;w krajowego pochodzenia uwarunkowane jest&nbsp; całym szeregiem jeszcze innych czynnik&oacute;w, związanych np. z wychowaniem, wyznawanymi wartościami, ale też nabytymi doświadczeniami konsument&oacute;w, tj. poziomem satysfakcji osiągniętej w przeszłości z zakup&oacute;w d&oacute;br wyprodukowanych i oferowanych na rynku przez krajowe firmy.&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tej oczywistej relacji od dawna świadomi są państwa i firmy, kt&oacute;re de facto nie odżegnują się od oczywistości jaką jest &ldquo;kapitał ma narodowość&rdquo;. Zresztą widać ją też w wynikach ankiet przeprowadzonych wśr&oacute;d konsument&oacute;w przez międzynarodowe firmy doradcze.&nbsp; Przykładowo w 2020 roku hasło &bdquo;Proudly Local, Going Global&rdquo; &ndash; pojawiło się w raporcie organizacji badania rynku Euromonitor w top 10 najważniejszych globalnych trend&oacute;w konsumenckich.&nbsp; Konsumenci coraz częściej nie tylko wspierają lokalne firmy, lecz także od międzynarodowych korporacji wymagają, aby dostosowały się do lokalnych zwyczaj&oacute;w i korzystały z lokalnych dostawc&oacute;w.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dla lepszego zilustrowania ważkości tej kwestii dla wynik&oacute;w ekonomicznych kraju warto przypomnieć, iż np. według wyliczeń firmy doradczo-audytorskiej Grant Thornton dotyczącej rynku polskiego, jeśli podczas zakup&oacute;w wybieramy towar zagraniczny, to z każdej wydanej nań złot&oacute;wki&nbsp; 75 gr &bdquo;wycieka&rdquo; za granicę (ang. leakage), a tylko 25 gr pozostaje w Polsce. W przypadku wyboru produktu polskiego z każdej wydanej złot&oacute;wki - 79 gr zostaje w naszej gospodarce. Biorąc pod uwagę, że Polacy wydają rocznie 1,2 bln zł, nawet skromna zmiana nawyk&oacute;w konsumenckich mogłaby przynieść polskiej gospodarce dodatkowo rocznie nawet kilkadziesiąt miliard&oacute;w złotych.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W niniejszym opracowaniu zaprezentowano wyniki przeprowadzonego przez Instytut Staszica&nbsp; badania dotyczącego wpływu&nbsp; tożsamości wsp&oacute;lnotowej i wiedzy ekonomicznej na wybory konsumenckie młodych Polak&oacute;w. Badanie miało postać ankiety, a więc opierało się na metodologii powszechnie przyjętej w naukach ekonomicznych (i innych społecznych) w przypadku braku dostępności adekwatnych danych ilościowych.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Badanie przyniosło szereg istotnych spostrzeżeń i wniosk&oacute;w, zar&oacute;wno w obszarze aktualnego &bdquo;stanu&rdquo; etnocentryzmu konsumenckiego młodych Polak&oacute;w, ich świadomości makroekonomicznego znaczenia pro-polskich preferencji zakupowych dokonywanych&nbsp; na poziomie wybor&oacute;w indywidulanych, a także pewnych systemowych słabości jeśli chodzi o promocję polskich produkt&oacute;w.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <h2>2. Wyniki ankiety &quot;Wpływ tożsamości wsp&oacute;lnotowej i wiedzy ekonomicznej na wybory konsumenckie student&oacute;w&quot;.</h2></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;&nbsp; Początkowe pytania zamieszczone w badaniu nakierowane były na wstępną identyfikację poziomu etnocentryczności preferencji (home bias) i tego, na ile w og&oacute;le polskie pochodzenie produktu odbierane jest w spos&oacute;b pozytywny przez ankietowanych. W pierwszym rzędzie respondenci zapytani zostali o to, czy mając do wyboru polski lub zagraniczny produkt w tej samej cenie, decydują się na ten polski. Z tak postawionym stwierdzeniem jednoznacznie zgodziło się 43% badanych student&oacute;w, a 34% &bdquo;raczej się zgodziło&rdquo;. Jedynie 14% nie miało zdania. Jeśli chodzi o postawę przeciwną, tj. brak preferencji w kierunku produktu krajowego, to reprezentowało ją zaledwie kilka procent ankietowanych (6% &bdquo;raczej nie zgodziło&rdquo;, ok. 2% wybrało opcję &bdquo;zdecydowanie nie zgadzam się&rdquo;). Średnia w przedziale na skali Likierta 1-5: wyniosła 3,9, co należy uznać za wynik wskazujący na wysoki poziom zdeterminowania wyboru zakupowego polskim pochodzeniem produktu. Warto zwr&oacute;cić uwagę, że swego rodzaju &bdquo;echo&rdquo; tego pytania i tu uzyskanych wynik&oacute;w możemy r&oacute;wnież usłyszeć w pytaniu 9, gdzie ankietowani mieli wyrazić poziom swojego poparcia dla stwierdzenia &bdquo;Zawsze lepiej jest kupować polskie produkty&rdquo;.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rys. 1</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Źr&oacute;dło: opracowanie własne &nbsp;&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; Og&oacute;lnym wnioskiem z tego otwierającego ankietę pytania jest fakt, iż na poziomie deklaratywnym po stronie młodych konsument&oacute;w występuje wysoki poziom zaufania i silna preferencja w stosunku do produkt&oacute;w rodzimego pochodzenia (ich krzywa obojętności &bdquo;kładzie&rdquo; się w ich kierunku, ale to tylko w sytuacji por&oacute;wnywalnego poziomu cen dobro krajowe versus zagraniczne). Można uznać to za pewien sukces i występujące w tej grupie przekonanie o dobrej (a przynamniej por&oacute;wnywalnej) jakości polskich wyrob&oacute;w, zwłaszcza wobec agresywnych działań marketingowych zagranicznych koncern&oacute;w.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Warto w tym miejscu - dla uzupełnienia ustaleń ankiety zrealizowanej przez Instytut Staszica &ndash; przytoczyć wnioski, jakie prezentuje w swoim badaniu na podobny temat Centrum Badania Opinii Społecznej (CBOS) z 2018 roku. Dla ok jednej piątej (19%) żadne z kryteri&oacute;w odnoszących się polskości produktu nie ma znaczenia przy podejmowaniu decyzji konsumenckiej. Jak czytamy w raporcie &ldquo;Sceptyczni wobec wszystkich trzech kryteri&oacute;w patriotyzmu relatywnie często są respondenci z największych aglomeracji miejskich, niezaangażowani w praktyki religijne oraz na og&oacute;ł w większym stopniu zwolennicy pogląd&oacute;w lewicowych i centrowych niż prawicowych. Postrzeganie płacenia podatk&oacute;w i kupowania polskich produkt&oacute;w jako przejaw&oacute;w patriotyzmu częściej niż inni kwestionują badani mający poniżej 45 lat.&rdquo;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;W kolejnym kroku w spos&oacute;b domyślny wprowadzono jako drugi czynnik warunkujący decyzję o wyborze pomiędzy dobrem krajowym a dobrem zagranicznym &ndash; cenę produktu (patrz rys. 2).&nbsp; Stwierdzenie &bdquo;produkt zagraniczny wybieram tylko wtedy, gdy nie ma polskiego odpowiednika w podobnej cenie&rdquo; sugeruje bowiem możliwość alternatywy pomiędzy droższym produktem krajowym a tańszym zagranicznym, co relatywnie (tj. w por&oacute;wnaniu z sytuacją z pkt. 1) zmienia nachylenie linii ograniczenia budżetowego. Siła &bdquo;home bias&rdquo; zostaje więc skonfrontowana z tym nowym nachyleniem, a ostateczny wyb&oacute;r staje się wypadkową obydwu z czynnik&oacute;w.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; Otrzymane odpowiedzi wskazują z jednej strony na podtrzymanie pozytywnej tendencji z pytania pierwszego, z drugiej - widzimy r&oacute;wnież wyraźne przesunięcie akcent&oacute;w ze &bdquo;zdecydowanie&rdquo; (16%) na &bdquo;raczej zgadzam się&rdquo; (35%) oraz wymierne zwiększenie liczby wskazań, w kt&oacute;rych respondenci nie zgodzili się z takim stwierdzeniem (patrz rys. 2). Średnia w przedziale 1-5 wyniosła: 2,8. Powyższa modyfikacja preferencji wynika oczywiście z typowej wrażliwości konsumenta na cenę (ściślej biorąc ze z reguły ujemnej wartości elastyczności cenowej popytu).</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dalej pojawiła się kolejna modyfikacja postawionej tezy, co przyniosło ponowne przesunięcie akcentu co do preferencji zakupowej - krajowy versus zagraniczny produkt. Mianowicie w odniesieniu do stwierdzenia &bdquo;Produkt zagraniczny wybieram tylko wtedy, gdy nie ma polskiego odpowiednika w dowolnej cenie&rdquo; (rys. 3) liczba wskazań zar&oacute;wno na zdecydowanie- jak i &bdquo;raczej zgadzam się&rdquo;, zmniejszyły się o ok. połowę. Natomiast odsetek odpowiedzi przeczących zwiększył się o ok.1/3. W efekcie średnia w przedziale 1-5 wyniosła: 2,6. Wyraźnie więc widać, iż dokonywanie wyboru polskich produkt&oacute;w przez konsument&oacute;w młodego pokolenia dokonywany jest nie &bdquo;za wszelką cenę&rdquo;, a uwarunkowania dochodowe w dalszym ciągu odgrywają niestety znaczącą rolę w stosunku do przyznawania pierwszoplanowej roli wartościom jako szerokorozumianemu wyznacznikowi codziennych decyzji zakupowych. &nbsp; &nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Warto zwr&oacute;cić uwagę na odpowiedzi związane z identyfikacją polskiego pochodzenia, czy też &bdquo;polskości&rdquo; produktu. Przeprowadzona przez zesp&oacute;ł IS ankieta pokazuje znaczny stopień rozeznania, wręcz dojrzałości respondent&oacute;w, kt&oacute;rzy jednoznacznie identyfikują produkty wytworzone poza terytorium RP, a na terenie Unii Europejskiej jako zagraniczne &ndash; tym samym odr&oacute;żniając je od polskich. Bowiem ze stwierdzeniem &bdquo;produkt z UE powinien być traktowany jako produkt zagraniczny&rdquo; zdecydowanie zgodziło się prawie 62% badanych, a &bdquo;raczej&rdquo; zgodziło się z nim ok. 23,5%. Tylko 4% wybrało opcję trudno powiedzieć; 5,5% wskazało na odpowiedź &bdquo;raczej nie zgadzam się&rdquo;, a niespełna 5% młodych respondent&oacute;w zdecydowanie nie zgodziło się z takim stwierdzeniem. W tym pytaniu średnia w przedziale 1-5 wyniosła 4,14 - co było najwyższym wynikiem w tej serii pytań. Produkty wytworzone na terenie innych kraj&oacute;w członkowskich UE są więc powszechnie postrzegane jako zagraniczne.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rozszerzając kontekst można powiedzieć, że pytani postrzegają Unię nie jako na quasi-państwo, ale &ndash; zgodnie z traktatowymi zasadami - jako związek suwerennych państw o swoistych, często odmiennych interesach ekonomicznych czy politycznych. Nie kł&oacute;ci się to jednak z faktem, iż młodzi Polacy są jednym z najbardziej pro-unijnych młodych populacji w Europie &ndash; przynależność do Wsp&oacute;lnoty Europejskiej nie zastępuje u nas poczucia tożsamości narodowej.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dalsza część ankiety zawierała bardziej szczeg&oacute;łowe pytania, w tym: zmierzające do określenia, w jaki spos&oacute;b definiowany czy rozumiany jest przez młodych respondent&oacute;w&nbsp; polski (krajowy, lokalny) charakter produktu.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Starania dotyczące większej wizualnej identyfikacji polskich produkt&oacute;w w świetle kolejnych ustaleń ankiety wydają się kwestią kluczową. Mamy tu na myśli wiedzę dotyczącą znaczenia kodu kreskowego 590, kt&oacute;ra w świetle wynik&oacute;w ankiety wydaje się niezbyt duża. Wobec stwierdzenia &bdquo;Polski produkt to taki, kt&oacute;rego kod kreskowy zaczyna się na 590&rdquo; ponad 45% badanych wskazało opcję &bdquo;trudno powiedzieć&rdquo;, zaś blisko 15% orzekło, iż raczej się nie zgadza. Zdecydowanie nie zgadza się natomiast 8% &nbsp; (patrz rys. 5 ). Średnia w przedziale 1-5: 3,2. Na podstawie wynik&oacute;w badania w tej części widzimy jednak bardzo słabą rozpoznawalność kodu 590 wśr&oacute;d polskich konsument&oacute;w.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W tym miejscu nasuwa się dodatkowy komentarz,&nbsp; iż samo nadanie kodu 590 danemu produktowi na gruncie obecnego prawa nie jest de facto jednoznacznym wskaźnikiem całkowicie polskiego pochodzenia produktu<span style="text-decoration:underline;" class="wixui-rich-text__text">[1]</span>. Stosunkowo niska rozpoznawalność tego kodu nie musi więc przeczyć etnocentrycznemu nastawieniu młodych konsument&oacute;w, a świadczy jedynie o niewystarczającym &bdquo;rozeznaniu&rdquo; w tej kwestii. Uzupełnieniem tej tezy mogą być ustalenia raportu Centrum Analiz Klubu Jagiellońskiego. Możemy w nim przeczytać, iż dla klient&oacute;w kluczowe znaczenie w identyfikacji polskości produktu ma &bdquo;wyraźne oznaczenie produktu (nalepka/metka/ informacja nadrukowana na opakowaniu)&rdquo; (54%), a także &bdquo;Informacja na p&oacute;łce sklepowej&rdquo; (49%). Kwestia kodu nie jest więc kluczowa przy omawianej identyfikacji. Wydaje się zrozumiałe, że w toku codziennej rutyny w trakcie robienia zakup&oacute;w &nbsp; szybciej wzrokowo identyfikujemy wyraźnie oznaczone produkty np. godłem &bdquo;Teraz Polska&rdquo; czy też &bdquo;Produkt Polski&rdquo;. Można w tym miejscu wysnuć og&oacute;lny wniosek o potrzebie jeszcze szerszej realizacji kampanii promocyjnych polskich produkt&oacute;w oznaczonych dla tymi logo.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;W dalszej kolejności zapytano respondent&oacute;w, czy według nich polska firma to taka, kt&oacute;ra płaci podatki w Polsce, a zagraniczna to odprowadzająca podatki poza naszym krajem (rys.6).</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;&nbsp; Rozkład odpowiedzi wskazuje na og&oacute;lne przekonanie o takim właśnie stanie rzeczy. &nbsp; Niestety liczne doniesienia przeczą jakoby jest tak w rzeczywistości. Na przykład, przy odpowiedniej i skutecznej promocji wizerunkowej z użyciem argumentu &bdquo;płacenia podatk&oacute;w w Polsce&rdquo; importer zagranicznych produkt&oacute;w, płacący podatki (CIT) w Polsce będzie z reguły postrzegany przez znaczną część tych konsument&oacute;w jako polski producent. Choć powyższe wyniki implikują zdroworozsądkowe podejście konsument&oacute;w (płacenie podatk&oacute;w wiąże się z jakąś lokalnością i pozytywnym wkładem do wsp&oacute;lnoty), dodatkowo pozostaje jeszcze kwestia skali podatku płaconego przez taką firmę tj. czy i jaki procent zysku jest transferowany zagranicę etc. Jak wiemy statystycznie firmy (de iure bądź de facto) zagraniczne płacą znacznie mniejsze podatki w Polsce w por&oacute;wnaniu do rodzimych.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W kolejnym pytaniu określono polski produkt jako taki, kt&oacute;rego producent zatrudnia pracownik&oacute;w w naszym kraju. Podobnie jak w przypadku poprzedniego twierdzenia, respondenci dużego znaczenia przydali tu wykorzystaniu lokalnych pracownik&oacute;w dla nadania produktowi krajowego charakteru, choć w tym przypadku siła tej identyfikacji była nieco słabsza, tj. odpowiedzi &nbsp;&bdquo;raczej zgadzam się&rdquo; udzieliło 38% ankietowanych, a &bdquo;zdecydowanie zgadzam się&rdquo; - 17%. Wydaje się to przeczyć intuicyjnemu sądowi, że rodzimy kapitał ludzki (czy według dawniejszego określenia &bdquo;siła robocza&rdquo;) będzie w potocznym rozumieniu bardziej oczywistym wyznacznikiem rodzimego pochodzenia niż kwestie podatkowe (do 2015 roku jako wiadomo podlegające z reguły daleko posuniętej &bdquo;kreatywnej księgowości&rdquo;). Fakt zatrudnienia polskich pracownik&oacute;w przy wytworzeniu produktu (zakładamy, iż nie chodzi o importera zatrudniającego handlowc&oacute;w etc.) jest bardzo istotny dla jego polskiej identyfikacji, ale wydaje się, iż niewystarczający. Sam fakt wytworzenia produktu przez pracownik&oacute;w polskich nie oznacza jeszcze przecież, iż mamy do czynienia z produktem polskim w najściślejszym sensie.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ze stwierdzeniem &ldquo;Polski produkt to taki, kt&oacute;rego producent płaci podatki w Polsce&rdquo; zgodziło się ponad 63% (20% zdecydowanie tak i 43% raczej tak). Tylko 8% nie zgodziło się zdecydowanie, zaś 17% raczej się nie zgodziło.&nbsp; Średnia w przedziale 1-5: wyniosła wysokie 3,4 pkt.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dalsza część badania zmierzała do rozpoznania rodzaju zapatrywań na gospodarkę rynkową wśr&oacute;d młodych ludzi, tj. na ile dopuszczają oni ingerencję państwa w &bdquo;słusznej sprawie&rdquo; w relacji do zapatrywań stricte wolnorynkowych. W związku z tym padło pytanie, na ile identyfikują się oni z poniższym twierdzeniem &bdquo;Państwo powinno administracyjnie ograniczać możliwość sprzedaży zagranicznych produkt&oacute;w, by wspierać polskich producent&oacute;w&rdquo;. Tutaj przewaga zwolennik&oacute;w nieskrępowanej wymiany handlowej (np. nie stosowania ceł) okazała się dość znaczna (ponad 52%), zaś ponad 20% głos&oacute;w poparło odpowiedź &bdquo;trudno powiedzieć&rdquo;, co wzmacnia tendencje popierania rozwiązań wolnorynkowych. Średnia w przedziale 1-5 wyniosła: 2,5.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Z pewnością tak powszechne przekonanie jest to efekt wieloletniego wpływu neoliberalnej ideologii i członkostwa w UE. Przy tej analizie warto zwr&oacute;cić uwagę, iż historycznie większość kraj&oacute;w na podobnym etapie rozwoju, co Polska stosowała ochronę swojego rynku (m.in. azjatyckie tygrysy). Cła są naturalnym narzędziem działań ochronnych i powinny być stosowane dla realizacji określonych cel&oacute;w ekonomicznych, w przypadku Jednolitego Rynku Europejskiego - jeśli wymaga tego interes wsp&oacute;lnoty. Cła stosowane są na całym świecie przez wiele kraj&oacute;w, przede wszystkim - przez największego globalnego eksportera, tj. Chiny. Przy tej okazji warto r&oacute;wnież zwr&oacute;cić uwagę, na ograniczone możliwości stosowania tego narzędzia w związku z członkostwem Polski w UE i strategicznych rozbieżności państw członkowskich (np. Niemcy, przeciwnicy ceł mają nadwyżkę w bilansie z Chinami, Polska zaś wynik ujemny -1000%)</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Podobne wyniki uzyskano w przypadku pytania o akceptację stwierdzenia &bdquo;Polacy nie powinni kupować zagranicznych produkt&oacute;w, ponieważ szkodzi to polskiemu biznesowi i powoduje bezrobocie&rdquo;. Wyniki zaprezentowano na rys. 11.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Por&oacute;wnując tutaj wyrażone przekonania z deklaracjami z początkowej fazy kwestionariusza, w kt&oacute;rych młodzi ankietowani wyrażali znaczną skłonność do zakupu polskich produkt&oacute;w, tutaj widać swego rodzaju załagodzenie tych preferencji. &bdquo;Konsumencka wolność wyboru&rdquo; za kt&oacute;rą opowiada się ponad 41% respondent&oacute;w w powszechnym odbiorze jest jednak konfrontowana z takimi wartościami, jak wspomaganie rodzimego biznesu i rodzimych przedsiębiorc&oacute;w (oraz generowanego dzięki nim zatrudnienia). Te ostatnie pozostają jednak wartościami nadrzędnymi dla prawie 53% ankietowanych. Trudno osądzić, czy takie przesunięcie akcent&oacute;w jest wynikiem braku znajomości pewnych mechanizm&oacute;w ekonomicznych (jako konsument &bdquo;głosuję&rdquo; za pośrednictwem moich pieniędzy i moich wydatk&oacute;w na określone dobra per se &ndash; na określone firmy i producent&oacute;w, kt&oacute;rzy dostarczają je na rynek). Praktycznie bowiem taki negatywny dla polskich wytw&oacute;rc&oacute;w (i krajowego rynku pracy) jest skutek zakupu produkt&oacute;w zagranicznych, z zyskiem pozostającym w rękach zagranicznego wytw&oacute;rcy.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Podobne zależności występują przy wynikach badania stwierdzenia: &bdquo;Powinniśmy sprowadzać z zagranicy tylko te produkty, kt&oacute;rych nie możemy wytworzyć w Polsce&rdquo; ze średnią w przedziale 1-5 na poziomie 2,2. Wydaje się, iż w stanowisku wyrażonym w odpowiedziach (patrz rys. 12) istotne miejsce zajmuje &bdquo;wolnościowa&rdquo; perspektywa tj. chęć posiadania wyboru, nawet jeśli oznacza to potencjalnie osłabienie pozycji konkurencyjnej polskich wytw&oacute;rc&oacute;w.&nbsp; Choć ujęcie pytania jest dość radykalne, odczytanie go nieco łagodniej pozwalałoby zastanowić się nad koniecznością zbudowania preferencji dla rodzimej przedsiębiorczości i produkcji oraz wspierania rozwiązań &bdquo;edukacyjnych&rdquo; wspierających etnocentryczną optykę konsument&oacute;w. &nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kolejny zestaw pytań odnosił się do skuteczności istniejącej promocji polskich produkt&oacute;w w odbiorze młodych konsument&oacute;w. Otwierało go stwierdzenie: &bdquo;Polskie produkty są dobrze promowane wśr&oacute;d Polak&oacute;w&rdquo;. Średnia w przedziale 1-5 wyniosła: 2,5. Przewaga głos&oacute;w negatywnych, spora liczba głos&oacute;w trudno powiedzieć (oraz brak choćby jednego głosu zdecydowanie zgadzam się!) jednak zaskakuje, ale i pokazuje potrzebę poprawienia promocji polskich produkt&oacute;w. Natomiast, w kontekście deklarowanych preferencji dotyczących zakupu polskich produkt&oacute;w warto zwr&oacute;cić uwagę, iż podkreślają one potencjał patriotyczny polskich konsument&oacute;w ponieważ te deklaracje mają miejsce niejako przy słabej promocji tych produkt&oacute;w. Z całą pewnością to zjawisko wymaga głębszego przebadania, wyjaśnienia przyczyn takich wskazań oraz opracowania planu działań zaradczych mogących poprawić zar&oacute;wno promowanie polskich produkt&oacute;w, jak i ich pozytywną konsumencką percepcję.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wartym odnotowania wnioskiem była stosunkowo niewysoka ocena skuteczności polskich firm w przekonywaniu konsument&oacute;w do wspierania swoich marek. Tylko niespełna 5% ankietowanych zdecydowanie nie zgodziło się z tym, natomiast aż 41% &bdquo;raczej&rdquo; nie zgodziło się. &nbsp;(średnia w przedziale 1-5: 2,7). Znaczna przewaga głos&oacute;w negatywnych oraz bardzo niewielki odsetek os&oacute;b, kt&oacute;re identyfikują się z takim twierdzeniem wskazuje, iż młodzi polscy konsumenci wykazują daleko posunięta rezerwę względem umiejętności promocyjnych krajowych firm. Ustalenie faktycznych przyczyn takiego stanu rzeczy wymaga pogłębionych badań, niemniej obecnie możemy pokusić się o pewne przypuszczenia. Jednym z gł&oacute;wnych powod&oacute;w może być w dalszym ciągu &bdquo;garb PRL&rdquo; powodujący, iż produkty polskie, marka &bdquo;made in Poland&rdquo; postrzeganie są jako mniej atrakcyjne a zatem trudniejsze do wypromowania.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W kontekście deklarowanych wysokich preferencji w kierunku zakupu polskich produkt&oacute;w warto zwr&oacute;cić uwagę, iż dokonują one się przy słabej promocji rodzimych wyrob&oacute;w. Podkreśla to tylko wielkość pozytywnego potencjału wśr&oacute;d polskich konsument&oacute;w.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Następne pytanie ogniskowało się wok&oacute;ł efektywności działań państwa jeśli chodzi o przekonywanie do nabywania d&oacute;br polskiego pochodzenia (rys. 15). &nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W pytaniu o ustosunkowanie się do twierdzenia &bdquo;polskie państwo skutecznie przekonuje konsument&oacute;w do wspierania polskich marek&rdquo; widoczna była dość znaczna przewaga głos&oacute;w negatywnych, tj. prawie 56% pytanych wskazało na opcję raczej- lub &bdquo;zdecydowanie nie zgadzam się&rdquo;. Blisko jedna czwarta respondent&oacute;w okazała się nie mieć na ten temat zdania. Taki rozkład odpowiedzi (średnia w przedziale 1-5 wyniosła: 2,4) przynosi bardzo krytyczny obraz og&oacute;lnej oceny działań administracji publicznej na omawianym polu. Dodatkowo wyniki te wskazują na istnienie wyraźnych oczekiwań młodych konsument&oacute;w wobec aktywności państwa w promowaniu krajowych produkt&oacute;w, a per se polskich przedsiębiorc&oacute;w. Wziąwszy pod uwagę m.in. pewne ograniczenia, kt&oacute;re nakładają tu przepisy Unii Europejskiej, większa aktywności państwa w pośrednim wspieraniu polskich firm wiąże się z koniecznością wspierania inicjatyw edukacyjnych m.in. NGO popularyzujących wiedzę o korzyściach mikro i makroekonomicznych a w konsekwencji społecznych związanych z silnym rozwojem polskich firm (odprowadzających podatki w Polsce).</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <h2>3. Wnioski i rekomendacje dla dalszych badań</h2></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Badanie przeprowadzone w ramach projektu przyniosło szereg istotnych spostrzeżeń i wniosk&oacute;w, zar&oacute;wno w obszarze aktualnego &bdquo;stanu&rdquo; etnocentryzmu konsumenckiego młodych Polak&oacute;w, ich świadomości makroekonomicznego znaczenia pro-polskich preferencji zakupowych dokonywanych&nbsp; na poziomie wybor&oacute;w indywidulanych, a także pewnych systemowych słabości jeśli chodzi o promocję polskich produkt&oacute;w. Niemniej jednak, aby wnioski te mogły w spos&oacute;b skuteczny zostać przetransformowane w takie działania, kt&oacute;re faktycznie doprowadzą do szerokiego nakłonienia młodych konsument&oacute;w do kupowania produkt&oacute;w i usług rodzimego pochodzenia, pożądane wydaje się rozwinięcie i pogłębienie rozpoczętych badaniem studi&oacute;w. Projekt jest więc niezbędną bazą, a jego kontynuacja pozwoliłaby na wypracowanie skutecznych narzędzi marketingowych &bdquo;trafiających w punkt&rdquo; do przekonania młodych ludzi - najlepiej w ramach jednolitej, sp&oacute;jnej, og&oacute;lnopolskiej strategii budowania marki narodowej (być może z wykorzystaniem/wzorowaniem się na sprawdzonych &bdquo;chwytach&rdquo; brandingowych stosowanych przez wielkie korporacje; umiejętnie dostosowanych do narracji patriotyzmu konsumenckiego). Narzędzia te winny docelowo doprowadzić do wytworzenia swoistej mody na kupowanie produkt&oacute;w/usług &bdquo;made in Poland&rdquo;, a wydaje się efektywnym zaangażowanie tu tzw. celebryt&oacute;w, lider&oacute;w opinii (tw&oacute;rcy popularnych wśr&oacute;d młodzieży kanał&oacute;w na YouTube itp., &bdquo;vlogerzy&rdquo; itp.).</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W tym celu należałoby niniejsze badanie rozszerzyć między innymi w niżej wymienionych aspektach.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
                            <li class="wixui-rich-text__text">
                            <p class="font_8 wixui-rich-text__text" style="font-size:18px;">Bardziej szczeg&oacute;łowe wyodrębnienie poszczeg&oacute;lnych podgrup w ramach badanej &ndash;ujmowanej szeroko jako &bdquo;młodzi Polacy&rdquo; pr&oacute;by badawczej. Chodziłoby o zbadanie, jak kształtują się preferencje w kierunku kupowania produkt&oacute;w rodzimego pochodzenia ze względu przykładowo na:</p>
                            </li>
                            </ol></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">- wielkość ośrodka z kt&oacute;rego pochodzą badani (duży ośrodek miejski, miasto średniej wielkości, wieś itp.).</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">- kierunek studi&oacute;w (w podziale np. na techniczne, ekonomiczne, humanistyczne etc.)</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">- preferencje polityczne i przekonania światopoglądowe.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Pogłębienie badania w tym kierunku pozwoliłoby przede wszystkim na zbadanie elastyczności poziomu etnocentryzmu konsumenckiego względem tego rodzaju czynnik&oacute;w (podano powyżej przykładowe kryteria podziału na grupy w ramach analizowanej społeczności). Dzięki temu można wyciągnąć bardziej szczeg&oacute;łowe wnioski co do ewentualnego &bdquo;wyprofilowania&rdquo; pro-polskiej edukacji konsumenckiej, wyodrębnienia grup docelowych kampanii nakłaniającej do nabywania &bdquo;made in Poland&rdquo; &ndash; reprezentowanych przez osoby o być może odmiennych: świadomości, potencjale, potrzebach, oczekiwaniach itp. w omawianym zakresie).&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
                            <li class="wixui-rich-text__text">
                            <p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rozszerzenie badania na inne kraje, tj. zbadanie poziomu etnocentryzmu konsumenckiego np. w innych państwach Unii Europejskiej. Pozwoliłoby to na wyciągnięcie bardzo ciekawych wniosk&oacute;w por&oacute;wnawczych na temat zar&oacute;wno &bdquo;zastanych&rdquo; preferencji młodych ludzi w przedmiotowym zakresie (czy młodzi Niemcy preferują niemieckie produkty i dlaczego, czy włoskie pochodzenie jest istotnym argumentem &bdquo;za&rdquo; przy dokonywaniu zakup&oacute;w przez młodych Włoch&oacute;w, czy młodzi Szwedzi skłonni są nabywać szwedzkie produkty i usługi itd..), jak i siły oraz skuteczności promocji marek narodowych. Przy takim ujęciu merytorycznym konieczny byłby oczywiście szeroki przegląd zagranicznej literatury naukowej, badań (metodologia, wnioski) nad zagadnieniem zrealizowanych w innych krajach. &nbsp;</p>
                            </li>
                            </ol></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
                            <li class="wixui-rich-text__text">
                            <p class="font_8 wixui-rich-text__text" style="font-size:18px;">Szczeg&oacute;łowa analiza realnych możliwości promowania produkt&oacute;w polskiego pochodzenia przez instytucje państwowe bez narażania się na zarzuty o łamanie zasad wolnej konkurencji na terenie Jednolitego Rynku UE. W tym zakresie warto byłoby wykorzystać wiedzę na temat modeli/kampanii stosowanych w innych krajach oraz form pośredniego wspierania przez państwo rodzimych producent&oacute;w (np. poprzez organizacje pozarządowe promujące i reklamujące patriotyzm konsumencki); ewentualnie dr&oacute;g &bdquo;obejścia&rdquo; obostrzeń wynikających z unijnych przepis&oacute;w.<br class="wixui-rich-text__text">
                            &nbsp;</p>
                            </li>
                            </ol></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Do pogłębienia studium w tym aspekcie skłaniają zwłaszcza wnioski z niniejszego projektu dotyczące oceniania przez młodych konsument&oacute;w aktywności w zakresie promowania produkt&oacute;w polskiego pochodzenia zar&oacute;wno ze strony państwa, jak i samych polskich producent&oacute;w (niska ocena!).</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
                            <li class="wixui-rich-text__text">
                            <p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zbadanie, jakie skojarzenia towarzyszące dla hasła &bdquo;made in Poland&rdquo; powinny znaleźć się w og&oacute;lnopolskiej strategii/kampanii tak, by jej przekaz najlepiej trafił do przekonania młodego konsumenta (co jest dla niego istotne). Podobnie istotny jest dob&oacute;r form/narzędzi przekazu w dostosowaniu do percepcji i systemu wartości młodych ludzi (ewentualnie &ndash; jak powiedziano &ndash; w dostosowaniu do poszczeg&oacute;lnych wyodrębnionych grup reprezentujących zr&oacute;żnicowane poglądy/świadomość itp.)&nbsp; &nbsp;&nbsp;</p>
                            </li>
                            </ol></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- BLOG DETAILS END -->

@endsection
