@extends('layouts.app')

@section('title', 'Porażki polskiej polityki wschodniej lat 2007-2015')

@section('content')

    <!-- BLOG DETAILS HOME START -->
    <section class="section" style="padding: 170px 0px 75px 0px; background-size: cover; position: relative; background-position: center center;" id="home">
        <div class="bg-overlay"></div>
        <div class="home-center">
            <div class="home-desc-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="home-page-title text-center">
                                <h1 class="text-white mb-2">Porażki polskiej polityki wschodniej lat 2007-2015</h1>
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb justify-content-center bg-transparent">
                                        <li class="breadcrumb-item text-white"><a href="/" class="text-white">Strona główna</a></li>
                                        <li class="breadcrumb-item active" aria-current="page"><a href="{{ url('/gursztyn-artykul') }}" class="text-custom">Porażki polskiej polityki wschodniej lat 2007-2015</a></li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- BLOG DETAILS HOME END -->

    <!-- BLOG DETAILS START -->
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">


                    <div class="blog-info p-3">
                        <h2 class="text-dark mb-3">Piotr Gursztyn</h2>

                        <div class="blog-info-desc">
                            <p style='text-align: justify;'>
                                <h1>Porażki polskiej polityki wschodniej lat 2007-2015</h1><br class="wixui-rich-text__text">
                                <br class="wixui-rich-text__text">
                                Polska polityka wschodnia lat 2007-2015 była kompletną porażką. Szczeg&oacute;lnie względem Rosji. Najgorsze w tym wszystkim jest to, że była klęską na własne życzenie.
                            </p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Przegrana przegranej nier&oacute;wna. Jedne biorą się stąd, że siły obu stron były nier&oacute;wne i trudno było spodziewać się innego wyniku. Najgorsze zaś są te klęski, do kt&oacute;rych nie musiało dojść. A zdarzyły się z powodu błędnych założeń, pychy, głupoty, tch&oacute;rzostwa i innych zawstydzających cech ludzi podejmujących kluczowe decyzje. I ta ocena dotyczy polityki polskiej wobec Rosji w latach 2007-2015.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;Choć mamy swoje poglądy na sytuację w Rosji, chcemy dialogu z Rosją, taką, jaką ona jest. Brak dialogu nie służy ani Polsce, ani Rosji. Psuje interesy i reputację obu kraj&oacute;w na arenie międzynarodowej. Dlatego jestem przekonany, że czas na dobrą zmianę w tej kwestii właśnie nadszedł. Jestem zadowolony, że sygnały ze strony naszego wschodniego sąsiada potwierdzają, że także tam dojrzewają do tego poglądu&rdquo; &ndash; tak brzmiała zapowiedź Donalda Tuska, jako świeżo powołanego premiera, w jego expose z 23 listopada 2007 roku.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Działo się to w czasie, gdy trwały już prace nad gazociągiem Nordstream, dziewięć miesięcy po osławionym przem&oacute;wieniu Władymira Putina w Monachium (kt&oacute;re potraktowano jako agresywne wyzwanie rzucone USA) i p&oacute;ł roku po cyberataku na Estonię. Nie był to już czas, gdy można było żywić jakieś złudzenia co do putinowskiej Rosji. W spacyfikowanej Czeczenii niedługo wcześniej zginęły dziesiątki tysięcy niewinnych ludzi. Od roku nie żyła dziennikarka Anna Politkowska, zamordowana w dzień urodzin Putina jako makabryczny &bdquo;prezent&rdquo; dla niego. Znane były też słowa Putina o upadku ZSRS jako największej katastrofie geopolitycznej XX wieku. Zatem wiadomo, kto wtedy m&oacute;gł słać sygnały zadawalające polskiego premiera.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Osoby krytyczne wobec polityki Donalda Tuska wyciągają z tego typu informacji wniosek, że prowadził on politykę prorosyjską. W sensie jakiejś sympatii do Rosji, czy może nawet uzależnienia. Takie wrażenie u niekt&oacute;rych widz&oacute;w wywołuje też serial dokumentalny TVP &bdquo;Reset&rdquo;. Widać to w komentarzach internaut&oacute;w, choć zapewne nie taka była intencja autor&oacute;w tego serialu. Polityka Donalda Rosji wynikała z czego innego niż sympatia wobec Rosji. Tej raczej nie miał. Jej przyczyny były inne, co nie zmienia faktu, że premier Tusk obrał bardzo zły kierunek i od razu było widać, że będzie to polityka, kt&oacute;ra przyniesie korzyści Moskwie, a nie Polsce.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Do wybor&oacute;w 2007 r. w polskiej polityce zagranicznej obowiązywał nurt &bdquo;giedroyciowski&rdquo;. Czyli wspieranie niepodległości państw takich jak Ukraina, Litwa, Białoruś i innych, kt&oacute;re powstały na gruzach ZSRS. Nie oznaczał ten nurt antyrosyjskości a priori. Jego przedstawiciele, tak jak większość mieszkańc&oacute;w Polski, uważali, że można pogodzić wsparcie dla nowych państw z dobrymi stosunkami z Rosją, jeśli ta będzie demokratyczna i zrezygnuje z zapęd&oacute;w imperialistycznych. Wtedy zakładano, że jest na to szansa. W zasadzie podzielali ten pogląd wszyscy &ndash; najbardziej antyrosyjskie środowisko prawicowe, czyli PiS, prawie identycznie ze środowiskiem &bdquo;Gazety Wyborczej&rdquo;. Po przyjęciu Polski do NATO także prawie całe środowisko postkomunistyczne zaczęło popierać ten kierunek ze szczeg&oacute;lnym udziałem prezydenta Aleksandra Kwaśniewskiego. Platforma Obywatelska też nie była wyjątkiem. Odr&oacute;żniało się Polskie Stronnictwo Ludowe, kt&oacute;rego politycy często twierdzili, że z polskiej winy nasz kraj tracił szanse na &bdquo;zyskowny&rdquo; handel z Rosją. Podobną retorykę można było usłyszeć także z ust reprezentant&oacute;w Samoobrony i Ligi Polski Rodzin z Romanem Giertychem na czele.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Expose Tuska jeszcze nie było zaskoczeniem, bo uznano, że były to tylko słowa, niezobowiązująca deklaracja dobrej woli. Po słowach przyszły decyzje, kt&oacute;re wzbudziły z początku zdumienie. Donald Tusk zerwał z dziedzictwem Jerzego Giedroycia. Była to jego indywidualna i arbitralna decyzja, kt&oacute;ra nie wynikała z jakichś zmian ideologicznych wewnątrz samej Platformy i jej elektoratu. Jak twierdził Paweł Kowal &ndash; wtedy krytyczny wobec polityki wschodniej Tuska, dzisiaj jego podwładny &ndash; ambasador rosyjski był pierwszym dyplomatą, kt&oacute;rego nowy premier przyjął po objęciu funkcji szefa rządu: &bdquo;Grinin był pierwszym ambasadorem przyjętym przez Tuska po zwycięstwie, odni&oacute;sł sukces&rdquo;. Trzy lata p&oacute;źniej Grinin odegrał kluczową rolę w rozgrywaniu polskich elit politycznych za pomocą zaproszeń na uroczystości do Katynia. A za nim to się stało to efektem spotkania było to, że pierwszą wizytę zagraniczną poza Unię Europejską premier Tusk odbył do Moskwy. Wywołał tym szok i krytykę, bo zakładano, że najpierw powinien być Kij&oacute;w. Tusk jednak zlekceważył Ukrainę, a jedynie minimalnym dla niego usprawiedliwieniem jest to, że część tamtejszych elit też popełniła błędy wobec Polski. Możemy jednak je potraktować jako pretekst, bo Rosja postępowała znacznie gorzej, a Donald Tusk uznał, że woli z nią rozmawiać. Latem tego samego 2008 r., w czasie agresji rosyjskiej na Gruzję, Platforma bardziej zaangażowała się w dyskredytowanie działań prezydenta Lecha Kaczy��skiego niż pomoc napadniętym Gruzinom. W wywiadzie dla &bdquo;Newsweeka&rdquo; Tusk m&oacute;wił, że &bdquo;chciałby uniknąć&rdquo; tego, aby Polska była &bdquo;harcownikiem&rdquo; w konflikcie z Rosją. To co dla kogoś może brzmieć jako ostrożność w istocie było biernością i zezwoleniem dla Rosji na jej agresywne działania. Agresja na Gruzję ani na trochę nie zmieniła kursu Tuska wobec Moskwy.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Prorosyjska zmiana została jednak szeroko zaakceptowana, a to z powodu coraz silniejszej polaryzacji polskiej polityki. &bdquo;Antypisizm&rdquo; był jednym z powod&oacute;w nowej polityki wobec Rosji. Skoro bracia Kaczyńscy byli krytyczni wobec Moskwy, a Rosja robiła im r&oacute;żne &bdquo;psikusy&rdquo; w postaci embarga na produkty żywnościowe wprowadzonego w dniu zaprzysiężenia rządu Kazimierza Marcinkiewicza, to trzeba było się odr&oacute;żnić. Skoro oni nie mogą &bdquo;dogadać się&rdquo;, to Tusk pokaże, że on potrafi. Bo &ndash; w domyśle &ndash; Kaczyńscy nie potrafią negocjować, tak dobrze jak on. Grunt był tym bardziej podatny, że polska opinia publiczna oczekiwała zgody. Był to czas obowiązywania naszej siermiężnej wersji &bdquo;końca historii&rdquo;. Globalny liberalizm miał zmieniać świat na lepsze, więc Rosjanie też przecież nie mogli oprzeć się urokom konsumpcjonizmu i demokracji. Twarda postawa była odbierana jako coś agresywnego i niedobrego. Działał też miraż gigantycznego rosyjskiego rynku, kt&oacute;ry miał rzekomo czekać na polskie produkty. Wreszcie &ndash; wstyd dzisiaj o tym pisać &ndash; ale wielu Polak&oacute;w bało się Rosji. Tacy ludzie uważali, że ustępstwami i miłymi gestami kupimy sobie jej życzliwość i tym samym bezpieczeństwo. Zarzuty o &bdquo;potrząsaniu szabelką&rdquo; i oskarżenia o rusofobię skutecznie redukowały popularność polityk&oacute;w, kt&oacute;rzy byli bardziej krytyczni wobec Rosji.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Najważniejszym powodem zmiany było to, co działo się w Berlinie i Paryżu. Jak przyznał w niedawnej rozmowie w TVN24 Radosław Sikorski polski reset był wcześniejszy niż reset amerykański. Wspomniany już Nordstream narodził się latem 2006 r., kiedy odpowiednią umowę Gazprom podpisał z dwiema niemieckimi firmami E-ON-Ruhrgas i BASF. Niemcy i Francja coraz bardziej oddalały się od USA, odcinając się od działań Ameryki w Iraku. Berlin i Paryż widziały się w roli organizatora wielkiej polityczno-gospodarczej przestrzeni od Lizbony do Władywostoku. Władymir Putin r&oacute;wnież był entuzjastę tej wizji, zwłaszcza, że najbardziej uderzała ona w USA. W tradycyjnym polskim myśleniu taka wersja &bdquo;wsp&oacute;lnego europejskiego domu&rdquo; budziła przerażenie. W pierwszym odruchu to przecież Radosław Sikorski (jeszcze w&oacute;wczas w PiS) nazywał Nordstream nowym paktem Ribbentrop-Mołotow. P&oacute;źniej przeszedł na całkowicie inne pozycje i apelował do Niemiec, aby przejęły całkowicie przyw&oacute;dztwo w Unii Europejskiej. Donald Tusk nigdy nie zamierzał walczyć z pomysłami Berlina. Przynajmniej nie ma na to żadnych wskaz&oacute;wek. Gdy Nordstream rozpędzał się jedyne, co miał do powiedzenia to przywołanie argumentu stricte oportunistycznego: &bdquo;Nasze możliwości przeciwdziałania takim projektom są obiektywnie niewielkie. Możemy tłumaczyć, utrudniać, przekonywać, nie dawać akceptacji &ndash; i to Polska robi. Natomiast jeśli Niemcy i Rosja się uprą, to rurociąg powstanie. Jednak przekonujmy jednych i drugich, że może powstać wariant zadowalający i Rosję, i Niemcy, i Polskę&rdquo; &ndash; m&oacute;wił w wywiadzie dla tygodnik &bdquo;Przekr&oacute;j&rdquo; już w styczniu 2008 roku. Nic nie wiemy o wspomnianych utrudnieniach ze strony Polski. Wiadomo za to &ndash; z wypowiedzi samej Angeli Merkel &ndash; że podczas szczytu Rady Państw Morza Bałtyckiego w Stralsundzie w 2012 r. nikt nie zgłaszał zastrzeżeń co do budowy gazociągu. Donald Tusk był tam obecny, czyli wygląda na to, że milczał w tej strategicznej sprawie.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Z tym łączył się jeszcze jeden czynnik, kt&oacute;ry miał ogromny wpływ na polski reset. Jest to fakt mało znany, ale będziemy się upierać, że Donald Tusk ma poglądy antyamerykańskie. Nie eksponuje ich publicznie, bo to w Polsce niepopularne, i nie pomogło by mu też w funkcjonowaniu międzynarodowym. Jako polityk nadzwyczaj dbały o sw&oacute;j wizerunek skutecznie ukrywa ten resentyment. M&oacute;wi słodkie słowa, ale &ndash; trawestując znane powiedzenie prezydenta Theodora Roosevelta &ndash; za plecami trzyma kij, kt&oacute;rym, gdy tylko może poszturchuje Amerykę. Nie powinno to dziwić &ndash; antyamerykanizm jest popularny w Europie Zachodniej, a zwłaszcza Niemczech. Niemcy, a szczeg&oacute;lnie ich elity, mają negatywnego hopla na punkcie Ameryki. Nie lubią jej, gardzą nią, ale z oportunistycznych powod&oacute;w zawsze odgrywają dobrą minę do tej złej gry.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tusk już w czasie debaty wyborczej jesienią 2007 r. atakował Jarosława Kaczyńskiego za uległość wobec USA: &bdquo;A jak wygląda wasz stosunek do USA? To nie jest uległość? A do Iraku? A tarcza?&rdquo;. Sabotował rozmowy z Georgem W. Bushem na temat tarczy przeciwrakietowej. Podobnie robił to z Barackiem Obamą. Manifestacyjnie wypowiedział porozumienie 4 lipca 2008 roku, w dniu amerykańskiego święta niepodległości, a przy okazji w momencie narastającej presji rosyjskiej na Gruzję. W tym czasie Tusk i inni politycy Platformy zaczęli m&oacute;wić &bdquo;twardych negocjacjach z USA&rdquo; w sprawie tarczy. Paweł Kowal odnotował wtedy z pewnym zdumieniem: &bdquo;Zastanawiające, że nikt nie zapowiada twardych relacji np. z Rosją czy unijnymi sojusznikami &ndash; Niemcami lub Francuzami. &bdquo;Twardy&rdquo; język został zarezerwowany dla Amerykan&oacute;w&rdquo; (w książce &bdquo;Krajobrazy z Mistralami w tle&rdquo;).</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Żenującym szczeg&oacute;łem są drobne, ale zrozumiałe sygnały, kt&oacute;re w&oacute;wczas Tusk dawał Obamie. W czasie wizyty w Polsce, podarował mu pi&oacute;ro, kt&oacute;re nie pisało, więc amerykański prezydent wpisywał się do księgi pamiątkowej podanym mu przez wsp&oacute;łpracownika. Innym razem &bdquo;Washington Post&rdquo; opublikował ranking prezent&oacute;w, kt&oacute;re Obama dostał na 53. urodziny. Podarki z Polski zostały zakwalifikowane jako absolutnie najgorsze na miejscu 274 tuż za Rosją (co też było symbolem). Tusk wysłał Obamie grę komputerową &bdquo;Wiedźmin&rdquo;. To nie jest anegdota bez znaczenia. Były to czytelne sygnały. Tusk nigdy nie posunął się do takiego afrontu wobec Angeli Merkel, czy Władymira Putina. Donald Tusk zawsze miał skłonność do małych złośliwostek, kt&oacute;re były znakiem jego nastawienia do danej osoby. Znane i opisane są historie o tym, jak wytarł buty w zrzuconą na podłogę marynarkę Rafała Grupińskiego lub gdy kopał piłką w roślinę, kt&oacute;ra została w KPRM po Leszku Millerze. Efektem tych antyamerykańskich gier i gierek było to co napisał w swoich wspomnieniach &oacute;wczesny sekretarz obrony USA Robert Gates: &bdquo;Polska zgodziła się przyjąć na swoje terytorium rakiety przechwytujące&hellip; ale jej rosnące wymagania dotyczące gwarancji bezpieczeństwa, wykraczające poza zobowiązania NATO &hellip; sprawiły, że negocjacje utknęły. W momencie, gdy Obama objął urząd, było oczywiste, że politycznie nasza inicjatywa jest martwa i w Polsce i w Czechach&rdquo; (fragment za ostatnim tomem &bdquo;Historii cywilizacji amerykańskiej&rdquo; Zbigniewa Lewickiego).</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">No i ostatnia, ale nie mniej ważna, przyczyna. Donald Tusk nie wierzy w tradycyjnie prowadzoną politykę. Jest wyznawcą post-polityki i piaru. Zawsze było widać, także w obecnej kampanii wyborczej, że całkowicie lekceważył prace programowe na rzecz &bdquo;polityki ciepłej wody&rdquo; i kampanijnych odwołań do emocji. Miał podobne podejście do relacji z Władymirem Putinem. Przyłożył do niego swoją miarkę sądząc, że dla Putina też liczy się wizerunek i słupki poparcia wewnątrz własnego kraju. Stąd być może te w sumie zabawne słowa w expose sugerujące, że Rosja przejmowała się swoją reputacją w kontekście złych relacji z Polską. Strona rosyjska dobrze wyczuła, że Tuskowi zależy przede wszystkim na wizerunku i ładnych kampanijnych zdjęciach. Stąd jej propozycja spotkania z Putinem w Katyniu, ale bez Lecha Kaczyńskiego. Pokusa nie do odparcia, więc Tusk zgodził się na rozdzielenie wizyt z znanym nam wszystkim efektem.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Silne wsparcie krajowych medi&oacute;w pozwalało długo jechać na tym paliwie. &bdquo;Wizyta Putina w Polsce w 2009 roku była relacjonowana w niekt&oacute;rych stacjach krok po kroku niczym wizyta Gorbaczowa w 1988 roku&rdquo; &ndash; drwił w&oacute;wczas Kowal. Zwarcie szereg&oacute;w przez ob&oacute;z liberalny, w tym media, po 10 kwietnia 2010 r., nadal dawało Tuskowi poczucie, że jego polityka wobec Rosji da mu zyski. Przynajmniej na arenie krajowej, gdzie była chwalona. Aleksander Hall w &bdquo;Osobistej historii III Rzeczypospolitej&rdquo; wydanej w 2011 r., a pisanej jesienią 2010 roku, snuł optymistyczne prognozy: &bdquo;Spotkanie Tuska i Putina nad grobami katyńskich ofiar było kolejnym ważnym krokiem na drodze przełamywania lod&oacute;w w polsko-rosyjskich stosunkach. Rząd Tuska dążył do tego celu konsekwentnie. Potwierdzała to obecność i przem&oacute;wienie Putina na Westerplatte 1 września 2009 roku, w siedemdziesiątą rocznicę rozpoczęcia II wojny światowej&rdquo;. Hall wykazał się tutaj nie tylko naiwnym optymizmem, ale też brakiem umiejętności czytania oczywistych komunikat&oacute;w. We wspomnianym przem&oacute;wieniu na Westerplatte Putin stwierdził, że II wojna światowa miał swoje źr&oacute;dła w traktacie wersalskim i &bdquo;poniżeniu&rdquo; Niemiec. Czyli powt&oacute;rzył przedwojenne niemieckie hasło propagandowe o &bdquo;hańbie Wersalu&rdquo; i sugerował polską wsp&oacute;łwinę za wybuch wojny.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Mały kryzys wizerunkowy nastąpił w styczniu 2011 po opublikowaniu rosyjskiego raportu smoleńskiego, kt&oacute;ry całkowitą winę przerzucił na stronę polską, pomijając np. stan techniczny lotniska smoleńskiego. Tusk jeździł wtedy na nartach we Włoszech, tabloidy dawały jego zdjęcia z cygarem w ustach i cały ten wizerunek wyluzowanego nowoczesnego polityka stał się obciążeniem, gdy Rosjanie wystawili polskiego premiera do wiatru. Został przez nich całkowicie zlekceważony, co zresztą pozwoliło odsuniętemu na boczny tor Grzegorzowi Schetynie ubolewać, że premierowi zabrakło refleksu i zbyt p&oacute;źno zareagował. Tusk jednak nie zrezygnował z polityki resetu. Jednym z najbardziej kuriozalnych przykład&oacute;w był sp&oacute;r polityczny o kwalifikację prawną zbrodni katyńskiej. Nie był to sp&oacute;r między Polską a Rosją, lecz między Platformą i jej medialnymi akolitami a ... gł&oacute;wną polską partią opozycyjną. Sejmowa większość, czyli PO i PSL, nie chciała, aby w rocznicowej uchwale katyńskiej nazwać zbrodnię ludob&oacute;jstwem. &ndash; To była zbrodnia wojenna. Ludob&oacute;jstwo to zagłada narodu &ndash; polemizował z PiS-em Stefan Niesiołowski. Platformę w walce z określeniem &bdquo;ludob&oacute;jstwo&rdquo; wsparła też &bdquo;Gazeta Wyborcza&rdquo; przekonując, że ostry ton zaszkodzi relacjom z Rosją. Problem w tym, że dwa lata wcześniej ten sam Niesiołowski był autorem senackiej uchwały katyńskiej, gdzie pisał o ludob&oacute;jstwie. Podobnie &bdquo;Wyborcza&rdquo; przez wszystkie poprzednie lata pisała o ludob&oacute;jstwie w Katyniu i nigdy nie polemizowała z tą klasyfikacją zbrodni.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">To były jednak tylko utarczki na maleńkim polskim podw&oacute;rku. Reset trwał dalej w najlepsze, bo był fundamentem wielkiego niemieckiego planu. Po polskiej stronie nie było woli, aby temu się przeciwstawić lub przynajmniej się wycofać. Dowodem tego były reakcje polityk&oacute;w koalicji PO-PSL na aneksję Krymu przez Rosję i wspieranie przez nią rebelii w Donbasie w 2014 roku. Tusk m&oacute;wił wtedy, że Polska nie będzie prowadziła polityki aktywnego wsparcia dla broniącej się Ukrainy: &bdquo;ja bym nie chciał, żeby Polska była w jakiejś awangardzie antyrosyjskiej czy krucjacie antyrosyjskiej. P&oacute;ki ja będę o tym decydował, Polska nie będzie krajem agresywnej koncepcji antyrosyjskiej&rdquo;. W lutym 2014 r. stanowczo odrzucił apel Jarosława Kaczyńskiego o okazanie pomocy materialnej Ukrainie, m&oacute;wiąc, że nie będziemy dla niej &bdquo;wypruwać żył&rdquo;. Echem tych sł&oacute;w była żenująca wypowiedź jego następczyni Ewa Kopacz o tym, że Polska powinna zachować się jako kobieta, czyli &bdquo;zamknąć się we własnym domu&rdquo;. Innym przebłyskiem resetowego myślenia były ulotki wyborcze PSL z 2014 r. ukazujący grzyb atomowy i oskarżające PiS o chęć wywołania wojny z Rosją. W tej samej kampanii politycy PO dalej twierdzili, że PiS to partia rusofobiczna, kt&oacute;rej z tego powodu nie można dopuścić do władzy. &bdquo;Nikomu nie jest potrzebna rusofobiczna donkiszoteria &ndash; tak np. m&oacute;wił w&oacute;wczas Andrzej Halicki.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">***</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Od 22 lutego 2023 powszechne jest wrażenie, że nie będzie powrotu do polityki resetu z Rosją. Żyjemy w przekonaniu, że jest to idea całkowicie skompromitowana i że nie ma alternatywy dla kierunku atlantyckiego. Niestety może być to uczucie złudne i tylko kwestią czasu będzie powr&oacute;t do pr&oacute;b &bdquo;wysiudania&rdquo; Ameryki z Europy. Ogłoszone 100 konkret&oacute;w wyborczych Koalicji Obywatelskiej zawiera kilka punkt&oacute;w, kt&oacute;re mogą sugerować chęć powrotu do polityki prowadzonej pod niemieckim przyw&oacute;dztwem. Jedną jest zapowiedź zakończenia &bdquo;zimnej wojny&rdquo; z Niemcami, choć to Berlin skompromitował się w ostatnich latach swą polityką międzynarodową, obronną, energetyczną, czyli każdą, od kt&oacute;rej zależy bezpieczeństwo Polski i całego regionu. Zarzut, że to polityka Angeli Merkel &ndash; promotorki międzynarodowej kariery Tuska &ndash; doprowadziła do agresji Rosji na Ukrainę nie został wymyślony przez polską prawicę. Publicznie m&oacute;wiła o tym ważna niemiecka polityk &ndash; przewodnicząca komisji obrony w Bundestagu Marie-Agnes Strack-Zimmermann.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Niepokojącą zapowiedzią w programie KO jest dołączenie Polski do tzw. europejskiej tarczy antyrakietowej. To pomysł Niemiec i Francji na ratowanie własnych przemysł&oacute;w zbrojeniowych, na razie pozostający na papierze i będący konkurencją dla istniejących już rozwiązań amerykańskich. Polska kończy już budowę własnej obrony przeciwrakietowej, więc wejście do papierowego projektu mogłoby oznaczać zmarnowanie dotychczasowych gigantycznych wydatk&oacute;w i wysiłk&oacute;w. A opr&oacute;cz tego popsucie dobrych relacji z USA.</p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
                            <p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Niepokoi też postawa samego Donalda Tuska względem Ukrainy. Oczywiście, we wpisach twitterowych wielokrotnie deklarował sympatię dla napadniętego kraju, ale to jedyna jego aktywność w tym zakresie. Człowiek, kt&oacute;rego przedstawiano jako drugiego po Janie Pawle II Polaka, kt&oacute;ry zrobił największą karierę międzynarodową nie wykorzystał swych rzekomych wpływ&oacute;w dla pomocy Ukrainie. Nie spotkał się z nikim ważnym, ani razu nie odwiedził Ukrainy (co może też sugerować, że tamtejsze władze nie chcą go widzieć), nie podjął żadnych działań związanych z akcjami humanitarnymi. Znalazł za to czas, w maju 2022, aby wesprzeć kampanię wyborczą Silvio Berlusconiego, kt&oacute;ry cały czas &ndash; także wtedy &ndash; publicznie deklarował swoją gorącą sympatię wobec Władymira Putina. Tusk był wtedy szefem Europejskiej Partii Ludowej. 22 lutego 2022 deklarował w tej roli, że wszystko zrobi, aby Europa zrozumiała, że tylko &bdquo;nieustępliwość i odwaga&rdquo; powstrzymają agresora. Trudno jednak jest odnotować realne &bdquo;wszystko&rdquo;, kt&oacute;re zrobił w tym celu Tusk. Wygląda jednak na to, że to zaniechanie nie było skutkiem przypadku i lenistwa, lecz było świadomą decyzją polityka czekającego na wielką geopolityczną zmianę.</p></div><!--/$--></div></div></div><!--/$--></div></section><!--/$--><!--/$--></div></div></section><!--/$--><!--$-->



 

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
