
@extends('layouts.app')

@section('title', 'Home - Kevix Template')

@section('content')

<body>
<section class="section" style="padding: 170px 0px 75px 0px; background-size: cover; position: relative; background-position: center center;" id="home">
<div class="bg-overlay"></div>
        <div class="home-center">
            <div class="home-desc-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="home-page-title text-center">
                                <h1 class="text-white mb-2">Polski atom - piętnaście lat wahań, trzy lata działań</h1>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">


                    <div class="blog-info p-3">
                        <h2 class="text-dark mb-3">Marcin Rosołowski</h2>

                        <div class="blog-info-desc">
                            <p style='text-align: justify;'>


<span style="font-weight:bold;" class="wixui-rich-text__text">Polski atom - piętnaście lat wahań, trzy lata działań</span></p></p>

<span style="font-weight:bold;" class="wixui-rich-text__text">1.Polski atom &ndash; piętnaście lat wahań, trzy lata działań</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Historia polskiego atomu w III RP to przede wszystkim historia zapowiedzi i wahań. Dopiero w ostatnich latach udało się podjąć kierunkowe decyzje i rozpocząć prace nad &bdquo;dużym&rdquo; atomem. W agendzie polskich firm znalazł się r&oacute;wnież &bdquo;mały&rdquo; atom, czyli reaktory CSR.</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Przedstawmy pokr&oacute;tce historię &bdquo;atomowych wahań&rdquo; w ostatnim dwudziestoleciu.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><ul class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Styczeń 2005: rząd Marka Belki przyjmuje strategiczny dokument &bdquo;Polityka energetyczna Polski do 2025 roku&rdquo;. Znajduje się w nim stwierdzenie, że z przyczyn klimatycznych i ze względu na konieczność dywersyfikacji nośnik&oacute;w energii, uzasadnione staje się wprowadzenie do krajowego systemu energetyki jądrowej. Wg autor&oacute;w dokumentu Polska będzie potrzebować tego rodzaju energii już w latach 2015-2025.</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Listopad 2008: premier Donald Tusk zapowiada budowę co najmniej dw&oacute;ch elektrowni atomowych w p&oacute;łnocno-wschodniej Polsce &ndash; na Pomorzu i na Podlasiu. Zaczynają się przygotowania organizacyjne</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Styczeń 2009: Donald Tusk ogłasza, że rząd formalnie zdecydował o rozpoczęciu programu energetyki atomowej, zaś pierwszy reaktor ma być uruchomiony w 2020 roku</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Styczeń 2010: Ministerstwo Gospodarki podaje listę 28 potencjalnych lokalizacji dla pierwszej z planowanych elektrowni jądrowych</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Listopad 2010: Polska Grupa Energetyczna zawęża wspomnianą listę do trzech lokalizacji na Pomorzu &ndash; Choczewo, Gąski, Żarnowiec</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">2010: powołanie sp&oacute;łki PGE EJ1, mającej przygotować inwestycję w elektrownię jądrową; koszty jej funkcjonowania w latach 2010-19 wyniosły 553 mln zł</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Planowane do końca 2011 r. ogłoszenie przetargu na dostawę reaktor&oacute;w zostało przesunięte i nie doszło do skutku</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">2016: PGE EJ1 dokonuje wyboru dw&oacute;ch lokalizacji &ndash; Lubiatowo-Kopalino oraz Żarnowiec &ndash; do przeprowadzenia badań lokalizacyjnych i środowiskowych; w 2017 roku rozpoczęto tam badania lokalizacyjne i środowiskowe w pełnym zakresie</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Październik 2020: Rada Ministr&oacute;w przyjęła Uchwałę w sprawie aktualizacji programu wieloletniego pod nazwą &bdquo;Program polskiej energetyki jądrowej&rdquo;. Jako cel określono w niej budowę w Polsce od 6 do 9 GWe zainstalowanej mocy jądrowej w oparciu o sprawdzone, wielkoskalowe, wodne ciśnieniowe reaktory jądrowe generacji III i III+. Harmonogram zakładał budowę i oddanie do eksploatacji 2 elektrowni jądrowych po 3 reaktory każda. Wyb&oacute;r technologii zaplanowano na 2021 rok, wyb&oacute;r lokalizacji dla pierwszej elektrowni &ndash; rok 2022. Rozpoczęcie budowy pierwszego reaktora przewidziano na rok 2026, jego uruchomienie zaś na 2033; oddanie do eksploatacji ostatniego reaktora w drugiej elektrowni miałoby nastąpić w roku 2043</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Październik 2021: francuski państwowy koncern EDF złożył polskiemu rządowi wstępną, niewiążącą ofertę na budowę od czterech do sześciu reaktor&oacute;w EPR w Polsce o całkowitej mocy zainstalowanej od 6,6 do 9,9 GWe</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Grudzień 2021: &nbsp;decyzja o lokalizacji pierwszej polskiej elektrowni jądrowej w nadmorskiej gminie Choczewo (Lubiatowo-Kopalino)</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">2021: Ministerstwo Klimatu i Środowiska przyjmuje program wsparcia krajowego przemysłu do wsp&oacute;łpracy z energetyką jądrową. Obejmuje on m.in. takie działania jak szkolenia, wsparcie w pozyskiwaniu certyfikacji, promocję na rynkach międzynarodowych i wsparcie prac badawczo-rozwojowych. Wedle szacunk&oacute;w resortu, w naszym kraju działa około 80 firm, kt&oacute;re już uczestniczyły w r&oacute;żnych projektach jądrowych na świecie i niemal 200, kt&oacute;re mają taki potencjał</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kwiecień 2022: ofertę na budowę elektrowni atomowej składa koreański koncern KHNP</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Październik 2022: Ministerstwo Aktyw&oacute;w Państwowych, Ministerstwo Handlu, Przemysłu i Energii Korei, polskie firmy energetyczne ZE PAK i PGE, Korea Hydro &amp; Nuclear Power (KHNP) ogłosiły zawarcie listu intencyjnego w sprawie planu rozwoju elektrowni jądrowej w Pątnowie oraz zawarcie porozumienia o wsp&oacute;łpracy pomiędzy resortami. Porozumienie dotyczy budowy trzeciej potencjalnej &ndash; obok dw&oacute;ch zaplanowanych w &bdquo;Programie polskiej energetyki jądrowej&rdquo; &ndash; elektrowni atomowej w Polsce</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Listopad 2022: Rada Ministr&oacute;w w drodze uchwały zdecydowała o wskazaniu amerykańskiego koncernu Westinghouse jako dostawcy technologii i partnera strategicznego dla pierwszej elektrowni jądrowej, w skład kt&oacute;rej wejść mają trzy reaktory AP1000. Należy podkreślić, że Polska zdecydowała się na wyb&oacute;r partnera z pominięciem procedury zam&oacute;wień publicznych &ndash; inaczej, niż obecnie robią to władze Czech</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wrzesień 2023: podpisano umowę projektową między Polskimi Elektrowniami Jądrowymi (PEJ) a amerykańskimi firmami Westinghouse i Bechtel ws. budowy pierwszej elektrowni jądrowej na Pomorzu. Umowa umożliwi rozpoczęcie prac konstrukcyjnych przy pierwszym w Polsce bloku jądrowym na Pomorzu planowanym przez PEJ, Bechtel i Westinghouse na 2033 rok. Jej celem jest dostosowanie sprawdzonej na świecie technologii Amerykan&oacute;w do lokalizacji Lubiatowo-Kopalino.<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ul></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Pierwsze piętnastolecie &ndash; 2005-2020 &ndash; było zatem raczej dyskusją o celowości budowy energetyki atomowej w Polsce, niż podjęciem&nbsp; konkretnych działań, kt&oacute;re wiodły do tego celu. Na początku tego okresu stosunek Polak&oacute;w do energii jądrowej był w dużej części sceptyczny. Z badań Millward Brown dla portalu Money.pl, przeprowadzonych w sierpniu 2008 roku na reprezentatywnej grupie 1004 os&oacute;b wynikało, że 48% respondent&oacute;w opowiedziało się przeciw, a 42% za budową w naszym kraju elektrowni jądrowej. Wśr&oacute;d zwolennik&oacute;w atomu aż 83% nie obawiało się mieszkać w pobliżu elektrowni jądrowej<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[1]</a></span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dla por&oacute;wnania, z badania przeprowadzonego na zlecenie Ministerstwa Klimatu i Środowiska w listopadzie 2020 r. wynikało, że za budową elektrowni jądrowej opowiadało się 62,5% Polak&oacute;w, a 31,6% - przeciwko. Niemal co druga osoba (46%) poparła zlokalizowanie elektrowni jądrowej w bezpośredniej okolicy swojego miejsca zamieszkania. 51,4% wyraziło sprzeciw wobec tego rozwiązania, przy czym aż 32% wyraziło sw&oacute;j sprzeciw w spos&oacute;b zdecydowany. Jednocześnie wg tego badania 70% Polak&oacute;w uważa, że budowa elektrowni jądrowej będącej niskoemisyjnym źr&oacute;dłem wytwarzania energii jest dobrym sposobem na walkę ze zmianami klimatycznymi. Podobny odsetek respondent&oacute;w sądzi, że budowa w Polsce elektrowni jądrowej jest dobrym sposobem na zwiększenie bezpieczeństwa energetycznego kraju (72,6%)<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[2]</a></span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">O ile schyłek rząd&oacute;w SLD i kr&oacute;tki okres rząd&oacute;w PiS (2005-07) nie przyniosły żadnych konkret&oacute;w, to osiem lat rząd&oacute;w koalicji PO-PSL można nazwać okresem wahań. Z jednej strony kierunkowe deklaracje i powołanie celowych sp&oacute;łek, z drugiej &ndash; brak wykonania zasadniczego kroku, jakim jest uruchomienie procesu negocjacji z wykonawcami. Co istotne, w tym czasie wśr&oacute;d Polak&oacute;w sukcesywnie rosło poparcie dla budowy energetyki atomowej. Sprawujący władzę w latach 2014-15 gabinet Ewy Kopacz oficjalnie odłożył plany atomowe na p&oacute;łkę. Premier argumentowała to tym, że &bdquo;bezpieczeństwo energetyczne Polski oparte jest na naszych naturalnych surowcach, a więc i węglu brunatnym i węglu kamiennym&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[3]</a></span>. W p&oacute;źniejszym okresie politycy PO wskazywali, że w budżecie państwa nie było pieniędzy na budowę elektrowni atomowej <span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[4]</a></span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jednak i po objęciu rząd&oacute;w przez PiS decyzja o budowie energetyki jądrowej nie zapadła szybko. Dopiero w drugiej kadencji Rada Ministr&oacute;w przyjęła Polski Program Energetyki Jądrowej i &ndash; co należy podkreślić &ndash; szybko rozpoczęły się konkretne prace. Na razie z dw&oacute;ch zapowiedzianych w programie rządowym elektrowni mamy wyb&oacute;r partnera dla pierwszej lokalizacji &ndash; konsorcjum amerykańskich firm Westinghouse i Bechtel. Na tę chwilę nie są sfinalizowane rozmowy z tym konsorcjum w kluczowych kwestiach, nie wiadomo r&oacute;wnież, kiedy poznamy drugą lokalizację i partnera dla niej. Co ważne &ndash; w Polsce decyzja o wyborze partner&oacute;w odbywa się z całkowitym pominięciem procedury zam&oacute;wień publicznych i jest decyzją na szczeblu rządowym. Eksperci zwracali uwagę na zagrożenia związane z takim właśnie trybem &ndash; szczeg&oacute;lnie w sytuacji konfliktu obecnego rządu z Komisją Europejską<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[5]</a></span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dla odmiany, w Republice Czeskiej procedura wyłonienia partnera, kt&oacute;ry zbuduje nowy blok elektrowni jądrowej Dukovany prowadzona jest w trybie zam&oacute;wień publicznych. Ofertę notabene złożyły ci sami oferenci, kt&oacute;rzy są zainteresowani budową &bdquo;dużego atomu&rdquo; w Polsce &ndash; EDF, Westinghouse i KHNP<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[6]</a></span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">2.&bdquo;Duży atom&rdquo; &ndash; kluczowe argumenty</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Oto kluczowe argumenty za uzupełnieniem polskiego miksu energetycznego energią jądrową:<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><ul class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Elektrownie jądrowe są całkowicie bezpieczne; dzisiejsze reaktory atomowe, w kt&oacute;rych dochodzi do reakcji chemicznych, są bardzo dobrze zabezpieczone i chłodzone, a systemy zabezpieczeń sprawiają, że nie ma groźby katastrofy. W por&oacute;wnaniu z innymi źr&oacute;dłami energii takimi jak węgiel czy ropa naftowa, energia jądrowa ma niski wskaźnik śmiertelności związanej z jej produkcją. Weźmy jako przykład węgiel brunatny. Jak wynika z wyliczeń Geopolitical Intelligence Services Reports, na każdą TWh wytworzonej energii przypada 32,72 zgon&oacute;w z powodu wypadk&oacute;w i zanieczyszczenia powietrza związanego z tym źr&oacute;dłem energii. W przypadku energii jądrowej liczba ta spada do 0,07 zgon&oacute;w. Na tę liczbę składają się np. wypadki podczas budowy czy modernizacji elektrowni, a nie &ndash; jak byśmy myśleli &ndash; z powodu choroby popromiennej. W elektrowniach projektowanych i użytkowanych według standard&oacute;w zachodnich nigdy nie doszło do awarii, w kt&oacute;rej człowiek zginąłby od promieniowania.</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wytworzenie energii jądrowej jest znacznie tańsze od produkcji prądu w tradycyjnych, węglowych elektrowniach. Jest też zdecydowanie bardziej przyjazne dla środowiska: podczas pracy elektrownia atomowa charakteryzuje się mniejszą emisją spalin do atmosfery. Elektrownia jądrowa nie emituje szkodliwych dla środowiska i zdrowia gaz&oacute;w, w szczeg&oacute;lności dwutlenku węgla, związk&oacute;w azotu i siarki oraz pył&oacute;w. Powstające w elektrowni niewielkie ilości odpad&oacute;w można bezpiecznie składować</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Elektrownia jądrowa wytwarza mniej hałasu, dzięki czemu jest mniej uciążliwa dla mieszkańc&oacute;w obszar&oacute;w znajdujących się w jej bezpośrednim sąsiedztwie od na przykład farm wiatrowych</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Elektrownia jądrowa nie jest w żaden spos&oacute;b uzależniona od zmiennych warunk&oacute;w atmosferycznych (w odr&oacute;żnieniu od fotowoltaiki czy energetyki wiatrowej)</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Odpady z elektrowni atomowej w większości nadają się do recyklingu, choć okres radioaktywności odpad&oacute;w może wynosić nawet 300 lat</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Energia atomowa to bardzo istotny element zapewnienia niezależności i stabilności energetycznej &ndash; budowa elektrowni atomowych może zwiększyć stabilność i niezależność dla sektora energetycznego, szczeg&oacute;lnie w kontekście wahań cen takich surowc&oacute;w, jak ropa czy gaz</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Nowoczesna elektrownia jądrowa może pracować od 60 do nawet 80 lat. Wysoki koszt inwestycji rozkłada się na wiele lat pracy obiektu. Po uwzględnieniu niskich koszt&oacute;w eksploatacji umożliwia to łatwe przewidywanie cen energii.</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Specyfika wykorzystywanego paliwa i rodzaj procesu pozyskiwania energii jądrowej pozwalają na produkcję dużej ilości energii z małej ilości surowca, co przyczynia się do jego racjonalnego wykorzystywania</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Inwestycje w energię atomową pobudzają gospodarkę, pozwalając na kreowanie nowych miejsc pracy dla fachowc&oacute;w i rozw&oacute;j kompetencji polskich firm. Budowa w Polsce energetyki jądrowej wzmocni r&oacute;wnież polskie instytuty naukowe i przedsiębiorstwa, kt&oacute;re&nbsp; już teraz prowadzą działalność związaną z tą dziedziną</p>
</li>
</ul></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">3. SMR-y &ndash; ważny element miksu energetycznego i uzupełnienie dla &bdquo;dużego atomu&rdquo;</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Duże reaktory nie wystarczą do zapełnienia luki energetycznej, kt&oacute;ra będzie dużo większa, niż planowane moce dużej energetyki. SMR (małe reaktory modułowe, small modular reactor) to jedna z najbardziej efektywnych, najtańszych i bezpiecznych technologii produkcji energii. W polskich warunkach jest ważnym elementem dywersyfikacji źr&oacute;deł wytwarzania energii. zwiększającym bezpieczeństwo i niezależność energetyczną Polski oraz regionu.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Szacowany koszt produkcji 1 MWh energii elektrycznej z SMR będzie docelowo o około 30 proc. niższy niż w przypadku energii z gazu. Pojedynczy reaktor modułowy o mocy około 300 MWe może zapobiec emisji do od 0,3 do 2 mln ton dwutlenku węgla rocznie, w zależności od rodzaju zastępowanego paliwa, np. węgla kamiennego lub brunatnego. Co istotne, elektrownia jądrowa SMR może być zbudowana już w ciągu 24-36 miesięcy na terenie stanowiącym zaledwie 10 proc. dużej siłowni atomowej, przy czym sama tzw. wyspa jądrowa zajmie jedynie powierzchnię boiska piłkarskiego.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Według szacunk&oacute;w Międzynarodowej Agencji Energii Atomowej (MAEA), obecnie na świecie jest realizowanych około 70 projekt&oacute;w tego typu o r&oacute;żnym stopniu zaawansowania. W technologię małych reaktor&oacute;w inwestuje kilkanaście kraj&oacute;w z całego świata m.in.&nbsp; USA, Wielka Brytania, Francja, a także Czechy, Estonia, Litwa, Finlandia i Rumunia. Dla przykładu analiza Departamentu Energii USA opublikowana we wrześniu 2022 r. wskazuje, że w USA ponad 300 elektrowni węglowych może zostać zastąpionych przez technologie jądrowe, w tym SMR-y.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W Polsce Orlen Synthos Green Energy (OSGE) rozpoczął proces prelicencjonowania składając w lipcu 2022 roku do Prezesa Państwowej Agencji Atomistyki wniosek o wydanie og&oacute;lnej opinii w sprawie technologii BWRX-300. Firma prowadzi analizy dotyczące lokalizacji dla planowanej floty reaktor&oacute;w BWRX-300.&nbsp; Polski BWRX-300, dzięki wykorzystaniu w procesie budowy doświadczeń z USA i Kanady, ma szansę powstać już jako drugi na świecie, po kanadyjskim Darlington. Z uwagi na znacznie mniejsze nakłady inwestycyjne oraz szybkość budowy reaktora BWRX-300 z moduł&oacute;w, program tworzenia sieci małych elektrowni nuklearnych uznawany jest obecnie za najskuteczniejszy i najszybszy spos&oacute;b przeprowadzenia transformacji polskiej energetyki i ciepłownictwa w kierunku dekarbonizacji i osiągnięcia zerowej emisji gaz&oacute;w cieplarnianych.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Międzynarodowe firmy zaangażowane w budowę małych reaktor&oacute;w modułowych (SMR) zawarły w marcu 2023 r. umowę, zgodnie z kt&oacute;rą przeznaczą ponad 400 mln USD na rozw&oacute;j technologii BWRX-300. Jednym z sygnatariuszy jest Synthos Green Energy &ndash; partner PKN ORLEN, z kt&oacute;rym koncern utworzył sp&oacute;łkę joint venture (ORLEN Synthos Green Energy) posiadającą w Polsce wyłączność na budowę tego typu obiekt&oacute;w. Podpisany dokument przyspieszy prace nad technologią oraz przyczyni się do obniżenie koszt&oacute;w związanych z jej wdrożeniem. Opr&oacute;cz Synthos Green Energy umowę o wsp&oacute;łpracy zawarli: amerykański koncern energetyczny &ndash; Tennessee Valley Authority, największy w Kanadzie wytw&oacute;rca bezemisyjnej energii &ndash; Ontario Power Generation oraz tw&oacute;rca reaktora BWRX-300 &ndash; GE Hitachi Nuclear Energy.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">BWRX-300 należy do rodziny reaktor&oacute;w wodno-wrzących (BWR). Jednocześnie, ze względu na stosunkowo niewielką moc (300 MWe), zaliczany jest do tzw. SMR, czyli małych reaktor&oacute;w modułowych. BWRX-300 jest projektowany w celu obniżenia koszt&oacute;w budowy i eksploatacji w stosunku do innych technologii wytwarzania energii jądrowej. Projekt opiera się na sprawdzonych technologiach i komponentach wykorzystanych, m.in. w licencjonowanym w USA reaktorze ESBWR, a także będzie wykorzystywał certyfikowane i produkowane od lat paliwo jądrowe. W ostatnim czasie decyzję o budowie BWRX-300 podjęła Estonia. Zainteresowanie technologią GEH, na r&oacute;żnym poziomie, wykazuje blisko 30 kraj&oacute;w.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Konstrukcja reaktora uwzględnia możliwości kogeneracji i wykorzystania ciepła dla cel&oacute;w przemysłowych i komunalnych, dopasowanie do zmiennych wymagań sieci energetycznej (&bdquo;load-follow&rdquo;)&nbsp; tudzież produkcję wodoru.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Przygotowania do budowy pierwszego BWRX-300 prowadzone są przez OPG na terenie elektrowni jądrowej w Darlington pod Toronto. Elektrownia zostanie oddana do użytku do końca 2028 roku. Pod koniec 2022 roku OPG złożyło wniosek o pozwolenie na budowę do kanadyjskiego dozoru jądrowego (CNSC), a w styczniu 2023 roku zawarło umowę na realizację inwestycji. Z kolei TVA przygotowuje się do złożenia wniosku o pozwolenie na budowę BWRX-300 w Clinch River w stanie Tennessee, a jednocześnie analizuje możliwości budowy kolejnych SMR-&oacute;w od GEH na terenach południowych stan&oacute;w USA, na kt&oacute;rych dostarcza mieszkańcom energię elektryczną.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jakie są, w polskich warunkach, atuty SMR-&oacute;w. Po pierwsze, jak wyżej nadmieniono, zajmują mniej miejsca. BWRX-300 zajmie zaledwie 10% powierzchni dużej elektrowni atomowej. Cała instalacja z reaktorem BWRX-300 w całości mieści się na terenie o wymiarach 260 x 332 m. Blok energetyczny zajmuje obszar o wymiarach boiska piłkarskiego. Po drugie, elektrownie z małymi reaktorami potrzebują znacznie mniej wody (jako chłodziwa) niż większe instalacje &ndash; nie zakł&oacute;cą zatem lokalnej gospodarki wodnej. Po trzecie, ze względu na umieszczenie pod ziemią, SMR potrzebuje niewielkiej strefy bezpieczeństwa &ndash; ok. 300/400 m &ndash; bez ingerencji w pobliskie budynki czy instalacje.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wg danych OSGE jeden reaktor BWRX-300 to 175 mln ton mniej emisji CO2, mniej o 65 mln ton zużycia węgla, 0,32 mln ton mniej emisji SO, 0,28 mln ton &ndash; NO, 0,75 mln ton pyłu.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Warto dodać, iż SMR są szansą na utrzymanie w elektrowni czy ciepłowni miejskich po wyłączeniu mocy węglowych co rozpocznie się w najbliższych latach. Moc BWRX300 odpowiada mocy tradycyjnego bloku węglowego, co pozwala na ich zastępowanie przy wykorzystaniu dotychczasowej infrastruktury przesyłowej.<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[7]</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">4. Zagrożenia dla budowy &bdquo;dużego atomu&rdquo; w Polsce</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Polski program energetyki jądrowej, choć realizowany zgodnie z założeniami, może być zagrożony. Należy wyr&oacute;żnić trzy gł&oacute;wne obszary zagrożeń:<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><ul class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zagrożenia związane z finansowaniem projektu;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zagrożenia związane z trybem wyłaniania partner&oacute;w / relacjami z Komisją Europejską</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zagrożenia związane z możliwą zmianą polityczną w Polsce.<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ul></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zagrożenia związane z finansowaniem projektu. Z przekazywanych opinii publicznej informacji wynika, że udział państwa w finansowaniu projektu ma być dominujący. Model finansowania pierwszej lokalizacji przez władze amerykańskie (np. w postaci kredyt&oacute;w) jest, zdaniem ekspert&oacute;w, mało realny. R&oacute;wnież pozyskanie finansowania z rynku jest niezbyt prawdopodobne, a to ze względu na zbyt długi czas zysku z inwestycji. Możliwą opcją jest obciążenie odbiorc&oacute;w prądu specjalną opłatą, ale byłoby to zapewne społecznie nieakceptowalne<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[8]</a></span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;Grzechem pierworodnym&rdquo; polskiego podejścia do budowy dużego atomu jest odwr&oacute;cenie priorytet&oacute;w. Kluczową sprawą dla tak poważnej inwestycji jest ustalenie modelu jej finansowania. To dopiero po ustaleniu tych warunk&oacute;w należałoby podjąć rozmowy z partnerami. W Polsce najpierw &ndash; decyzją polityczną, bez trybu zam&oacute;wień publicznych &ndash; wyłoniono partnera dla pierwszej z lokalizacji, a p&oacute;źniej dopiero podjęto rozmowy o najważniejszej kwestii, czyli finansowaniu inwestycji. A trzeba przypomnieć, że koszt budowy dw&oacute;ch elektrowni atomowych w ramach programu rządowego może sięgnąć 200 mld zł<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[9]</a></span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ten tryb, jak zaraz się przekonamy, stwarza jeszcze innego rodzaju zagrożenia &ndash; szczeg&oacute;lnie w kontekście napiętych relacji między polskim rządem i Komisją Europejską oraz antyatomowego lobbingu w Europie.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dyskusyjny tryb wyłaniania partner&oacute;w. Jak wspomniano, Polska &ndash; w odr&oacute;żnieniu np. od sąsiednich Czech &ndash; zrezygnowała z trybu przetargowego przy wyłanianiu partner&oacute;w do budowy elektrowni atomowych. Decyzja o wyborze partner&oacute;w jest podejmowana przez rząd uznaniowo.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;Z dużym prawdopodobieństwem można ocenić, że decyzja taka zostanie zablokowana przez Komisję Europejską, jako podjęta z pominięciem zasady konkurencyjnego postępowania. Wskazany wykonawca nie będzie więc m&oacute;gł zacząć budowy elektrowni w terminie pozwalającym na uruchomienie pierwszego reaktora w 2033 r., zgodnie z rządowymi planami&rdquo; &ndash; czytamy w stanowisku Instytutu Staszica z października 2022 r.<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[10]</a></span>. Zdaniem ekspert&oacute;w Instytutu, Komisja może użyć argumentu, że wyb&oacute;r dostawcy technologii elektrowni jądrowych, od jego &bdquo;odmrożenia&rdquo; w 2020 r. po wieloletnim zastoju, prowadzony był spos&oacute;b całkowicie jednostronny. Tylko z USA zawarto międzyrządową umowę umożliwiającą złożenie formalnej oferty. Tylko amerykańskie firmy Westinghouse i Bechtel otrzymały dane pozwalające na przygotowanie szczeg&oacute;łowej propozycji. Zaś kluczowy dokument na drodze przygotowań do budowy pierwszej elektrowni &ndash; raport o oddziaływaniu na środowisko &ndash; przygotowany został jedynie z uwzględnieniem technologii amerykańskiej.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zgodnie z unijnymi regulacjami, wyb&oacute;r przez kraj członkowski wykonawcy tego typu inwestycji z pominięciem konkurencji musi być uzasadniony. Takim uzasadnieniem może być fakt, że tylko jeden dostawca dysponuje odpowiednią technologią, że inwestycja jest kontynuacją wdrażania wybranej już uprzednio technologii lub też że tylko jeden dostawca zainteresowany był wsp&oacute;łpracą. Żadna z wymienionych przesłanek nie zaistniała w przypadku Polski.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Mamy zatem do czynienia z sytuacją, w kt&oacute;rej realizacja polskiego programu energetyki jądrowej zależy od czynnik&oacute;w politycznych nie tylko w Polsce, ale i w Komisji Europejskiej. Będzie ona zależeć nie tylko od relacji Warszawa-Bruksela, lecz i w pewnej mierze od relacji Waszyngton-Bruksela. Dotychczasowy brak wyboru europejskiego partnera dla jednej z lokalizacji r&oacute;wnież utrudnia sytuację Polski.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Koalicja Obywatelska &ndash; sceptycznie o &bdquo;dużym atomie&rdquo;, życzliwie o SMR-ach. Jeżeli po październikowych wyborach parlamentarnych rządy w Polsce obejmie większość oparta o opozycyjną Koalicję Obywatelską, należy być przygotowanym na weryfikację założeń odnośnie energetyki atomowej, przyjętych przez PiS.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W zaprezentowanej 21 września br. przez KO Strategii Transformacji Energetyki zaproponowano audyt polskiego programu energetyki jądrowej oraz projektu pierwszej elektrowni. Zgłoszono także postulat rozpoczęcia konsultacji z Komisją Europejską ws. finansowania budowy pierwszej elektrowni &ndash; a także rozm&oacute;w z dostawcą technologii. Jednocześnie w Strategii zaproponowano szybsze wdrażanie reaktor&oacute;w SMR, m.in. dzięki specjalnej ustawie i działań na szczeblu unijnym, kt&oacute;re doprowadzą do uwzględnienia tych jednostek w strategiach Unii Europejskiej oraz uznania ich za technologie bezemisyjne. Pojawił się r&oacute;wnież postulat wprowadzenia kontrakt&oacute;w r&oacute;żnicowych oraz długoterminowych um&oacute;w sprzedażowych dla takich jednostek. KO chce r&oacute;wnież wprowadzenia SMR-&oacute;w do Polityki Energetycznej Polski do 2040 roku oraz do Programu Rozwoju Sieci do roku 2032 a także wzmocnienia Państwowej Agencji Atomistyki<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[11]</a></span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jak należy odczytywać te zapowiedzi? Jako deklarację dużego sceptycyzmu wobec szans na realizację polskiego programu energetyki jądrowej według dzisiejszych założeń. Koalicja Obywatelska słusznie zwr&oacute;ciła uwagę na dwa aspekty &ndash; nierozstrzygniętą kwestię finansowania i zagrożenie negatywną reakcją KE. Jednocześnie zapowiedziany nacisk na szybszą i w większej skali budowę SMR-&oacute;w pokazuje, że to ma być kluczowy element polskiego atomu dla KO.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wprost o możliwości rezygnacji z plan&oacute;w budowy energetyki jądrowej m&oacute;wiła w kampanii wyborczej kandydatka z list KO, Urszula Sara Zielińska, wspominając o konieczności sprawdzenia, czy umowa z Westinghouse może być wypowiedziana. Ze strony władz KO zabrakło dementi<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[12]</a></span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">6. Geopolityczny aspekt polskich plan&oacute;w w zakresie energetyki jądrowej</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Program budowy energetyki jądrowej w Polsce należy postrzegać r&oacute;wnież jako wydarzenie o charakterze geopolitycznym, wpływające zar&oacute;wno na strategiczne międzypaństwowe sojusze naszego kraju, jak i na pozycję Polski w Unii Europejskiej.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Na ten aspekt projekt&oacute;w z zakresu &bdquo;dużego atomu&rdquo; zwracali uwagę eksperci. O tym, że budowa dw&oacute;ch elektrowni jądrowych w ramach rządowego programu może być szansą i na zacieśnianie relacji z USA, i na budowę strategicznego partnerstwa z Francją, pisała m.in. prezes Instytutu Staszica, prof. SGH dr hab. Agnieszka Domańska. &bdquo;Wyb&oacute;r r&oacute;żnych partner&oacute;w z innych kraj&oacute;w do budowy elektrowni jądrowych może nieść za sobą korzyści natury politycznej, gdyż decyzja taka zawsze oznacza stworzenie silnej i długotrwałej politycznej więzi z krajem dostawcy technologii (cykl życia elektrowni jądrowej od decyzji o budowie do jej dekonstrukcji/utylizacji wynosi około stu lat), szczeg&oacute;lnie że projekt tej skali zawsze prowadzony jest w udziałem państwa (np. poprzez jego finansowanie, lub też ze względu na udział firm państwowych). Wyb&oacute;r dw&oacute;ch technologii oznacza więc możliwość jednoczesnego zacieśnienia relacji z dwoma państwami, z kt&oacute;rych pochodzić będą dwaj ich dostawcy&rdquo; &ndash; podkreślała Domańska. <span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[13]</a></span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">O tym, że i polski rząd podobnie patrzy na kwestię wyboru partner&oacute;w do budowy elektrowni atomowych, wspominały nieoficjalnie media. Premier Mateusz Morawiecki jesienią ub. r. miał rozmawiać z francuskim prezydentem Emmanuelem Macronem o wsparciu Francji przy odblokowaniu środk&oacute;w dla Polski z Krajowego Planu Odbudowy w zamian za kontrakt dla EDF na budowę elektrowni jądrowej w naszym kraju. <span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[14]</a></span> Niezależny ekspert energetyczny Piotr Maciążek zwraca uwagę, że &bdquo;Kluczowe &lt;&lt;asy&gt;&gt; Francuz&oacute;w to możliwość mediacji pomiędzy władzami w Warszawie i Komisją Europejską; potencjalna możliwość pr&oacute;b blokowania wyboru Amerykan&oacute;w przez polski rząd w Komisji Europejskiej z powodu nieprzeprowadzenia postępowania konkurencyjnego na pierwszą lokalizację (więcej o tym tutaj) lub presja na podwykonawc&oacute;w&rdquo;.<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[15]</a></span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jakie mogłyby być korzyści z podzielenia kontraktu między partnera amerykańskiego i europejskiego? Należy podkreślić, że EDF &ndash; w odr&oacute;żnieniu od Westinghouse &ndash; obecnie buduje elektrownie atomowe w Europie (Wielka Brytania &ndash; Sizewell C)<span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[16]</a></span>. Wydaje się, że Polska &bdquo;przespała&rdquo; kluczowe miesiące po wybuchu wojny rosyjsko-ukraińskiej i etap rozdźwięku między Berlinem a Paryżem, kt&oacute;re były okazją do zbudowania porozumienia z Francją dla ochrony tych polskich interes&oacute;w, kt&oacute;re stoją w sprzeczności ze strategicznymi planami Niemiec. Obecnie, gdy francusko-niemiecki tandem znowu jest faktem (oba państwa lobbują za de facto likwidującymi suwerenność państw członkowskich zmianami w europejskich traktatach), jest to znacznie trudniejsze, choć cały czas możliwe. Oferta EDF jest wciąż na stole, a wyniki październikowych wybor&oacute;w w Polsce i następnie pr&oacute;by powołania rządu będą z uwagą śledzone w europejskich stolicach.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Omawiając polityczne korzyści wsp&oacute;łpracy atomowej z Francją, trzeba zwr&oacute;cić uwagę na jeszcze jeden istotny aspekt. Ot&oacute;ż Niemcy dążą do znacznego ograniczenia, jeśli nie zablokowania rozwoju energetyki atomowej w Europie. Projekt realizowany w partnerstwie z francuskim konsorcjum daje pewność, że w przypadku pr&oacute;b takiego uderzenia w państwa naszego regionu, Polska będzie mogła liczyć na wsparcie Paryża.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">7. Podsumowanie</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Polski program energetyki atomowej, kt&oacute;ry przez dwie dekady był tylko w sferze &ndash; kosztochłonnych &ndash; plan&oacute;w, nareszcie zaczyna być realizowany. Wok&oacute;ł tego, że Polska potrzebuje atomu (i &bdquo;dużego&rdquo;, i &bdquo;małego&rdquo;) powstał konsensus gł&oacute;wnych sił politycznych. Niestety, nie jest on na tyle silny, by uznać, że plany budowy elektrowni atomowych nie są zagrożone. Tu dużą rolę odgrywają zagraniczne (niemieckie) naciski i kwestia dużych koszt&oacute;w oraz braku porozumienia ws. finansowania. Groźną niewiadomą jest postawa Komisji Europejskiej, a brak decyzji o wyborze dla jednej z dwu lokalizacji w ramach rządowego programu europejskiego partnera te zagrożenia zwiększa.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kluczowe dla tego, czy i w jakiej formie Polska zyska energię jądrową, będzie to, kto obejmie ster rząd&oacute;w po październikowych wyborach parlamentarnych. Duże prawdopodobieństwo powstania rządu w wyniku koalicji r&oacute;żnych ugrupowań dodatkowo komplikuje tę kwestię. Pozytywnym czynnikiem jest duże poparcie opinii publicznej i ekspert&oacute;w dla energetyki jądrowej i niepodlegający dyskusji fakt, że bez atomu nie da się Polsce zapewnić suwerenności energetycznej. A, jak pokazały ostatnie lata, jest ona kluczowa dla szeroko pojętego bezpieczeństwa Polski i dla konkurencyjności jej gospodarki.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><a dataquery="bnVsbA==" style="" class="wixui-rich-text__text"><span style="text-decoration-line:underline;" class="wixui-rich-text__text">[1]</span>&nbsp;</a><span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.money.pl/gospodarka/wiadomosci/artykul/42;procent;polakow;chce;elektrowni;atomowych,173,0,366253.html" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.money.pl/gospodarka/wiadomosci/artykul/42;procent;polakow;chce;elektrowni;atomowych,173,0,366253.html</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[2]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.gov.pl/web/polski-atom/625-polakow-popiera-budowe-elektrowni-jadrowych-w-polsce" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.gov.pl/web/polski-atom/625-polakow-popiera-budowe-elektrowni-jadrowych-w-polsce</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[3]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://serwisy.gazetaprawna.pl/energetyka/artykuly/897559,kopacz-nie-mam-w-tyle-glowy-budowania-po-cichu-elektrowni-atomowych.html" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://serwisy.gazetaprawna.pl/energetyka/artykuly/897559,kopacz-nie-mam-w-tyle-glowy-budowania-po-cichu-elektrowni-atomowych.html</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[4]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.tvp.info/64323251/dlaczego-platforma-obywatelska-nie-wybudowala-elektrowni-atomowej-tomasz-siemoniak-tlumaczy" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.tvp.info/64323251/dlaczego-platforma-obywatelska-nie-wybudowala-elektrowni-atomowej-tomasz-siemoniak-tlumaczy</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[5]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://strefainwestorow.pl/artykuly/oze/20220712/polski-program-atomowy-opoznienie" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://strefainwestorow.pl/artykuly/oze/20220712/polski-program-atomowy-opoznienie</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[6]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://energia.rp.pl/atom/art35890431-czesi-rozpisuja-przetarg-na-rozbudowe-atomu" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://energia.rp.pl/atom/art35890431-czesi-rozpisuja-przetarg-na-rozbudowe-atomu</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[7]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.cire.pl/artykuly/opinie/polska-ma-szanse-zostac-liderem-w-technologii-malych-reaktorow-atomowych-smr" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.cire.pl/artykuly/opinie/polska-ma-szanse-zostac-liderem-w-technologii-malych-reaktorow-atomowych-smr</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://swiatoze.pl/smr-czyli-male-reaktory-modulowe-jak-dzialaja-i-czy-sa-bezpieczne/" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://swiatoze.pl/smr-czyli-male-reaktory-modulowe-jak-dzialaja-i-czy-sa-bezpieczne/</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://300gospodarka.pl/300klimat/modulowe-reaktory-jadrowe-wszystko-co-trzeba-wiedziec-o-smr-ach-explainer" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://300gospodarka.pl/300klimat/modulowe-reaktory-jadrowe-wszystko-co-trzeba-wiedziec-o-smr-ach-explainer</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[8]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://strefainwestorow.pl/w-zielonej-strefie/energetyka/atom-polska-finansowanie" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://strefainwestorow.pl/w-zielonej-strefie/energetyka/atom-polska-finansowanie</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[9]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.wnp.pl/energetyka/polskie-elektrownie-atomowe-moga-kosztowac-az-184-mld-zl,625743.html" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.wnp.pl/energetyka/polskie-elektrownie-atomowe-moga-kosztowac-az-184-mld-zl,625743.html</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[10]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.instytutstaszica.org/pazdziernik2022/stanowisko-instytutu-staszica-w-kontek%C5%9Bcie-spodziewanej-decyzji-o-wyborze-partnera-%2F-partner%C3%B3w-do-budowy-elektrowni-atomowej-w-polsce" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.instytutstaszica.org/pazdziernik2022/stanowisko-instytutu-staszica-w-kontek%C5%9Bcie-spodziewanej-decyzji-o-wyborze-partnera-%2F-partner%C3%B3w-do-budowy-elektrowni-atomowej-w-polsce</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[11]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://energetyka24.com/atom/analizy-i-komentarze/koalicja-kontratakuje-chce-audytu-programu-jadrowego-i-przyspieszenia-smr-analiza" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://energetyka24.com/atom/analizy-i-komentarze/koalicja-kontratakuje-chce-audytu-programu-jadrowego-i-przyspieszenia-smr-analiza</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[12]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://biznes.interia.pl/gospodarka/news-kandydatka-ko-nie-wyklucza-rezygnacji-z-atomu-glos-zabral-pr,nId,7065003" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://biznes.interia.pl/gospodarka/news-kandydatka-ko-nie-wyklucza-rezygnacji-z-atomu-glos-zabral-pr,nId,7065003</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[13]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://obserwatorgospodarczy.pl/2022/10/13/instytut-staszica-w-sprawie-atomu-powinnismy-grac-na-dwa-fronty/" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://obserwatorgospodarczy.pl/2022/10/13/instytut-staszica-w-sprawie-atomu-powinnismy-grac-na-dwa-fronty/</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[14]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://wyborcza.pl/magazyn/7,124059,28996599,wielowieyska-w-sprawie-budowy-elektrowni-jadrowej-w-polsce.html" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://wyborcza.pl/magazyn/7,124059,28996599,wielowieyska-w-sprawie-budowy-elektrowni-jadrowej-w-polsce.html</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[15]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://strefainwestorow.pl/w-zielonej-strefie/energetyka/orban-morawiecki-atom-z-francji" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://strefainwestorow.pl/w-zielonej-strefie/energetyka/orban-morawiecki-atom-z-francji</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a class="wixui-rich-text__text">[16]</a></span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.pb.pl/wielka-brytania-wyklada-700-mln-gbp-na-nowa-elektrownie-jadrowa-1161529" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.pb.pl/wielka-brytania-wyklada-700-mln-gbp-na-nowa-elektrownie-jadrowa-1161529</a></span></p></div><!--/$--></div></div></div><!--/$--></div></section><!--/$--><!--/$--></div></div></section><!--/$--><!--$-->

