
@extends('layouts.app')

@section('title', 'Home - Kevix Template')

@section('content')

<body>
<section class="section" style="padding: 170px 0px 75px 0px; background-size: cover; position: relative; background-position: center center;" id="home">
<div class="bg-overlay"></div>
        <div class="home-center">
            <div class="home-desc-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="home-page-title text-center">
                                <h1 class="text-white mb-2">Europa murami podzielona</h1>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">


                    <div class="blog-info p-3">
                        <h2 class="text-dark mb-3">Grzegorz Rutke</h2>

                        <div class="blog-info-desc">
                            <p style='text-align: justify;'>


<span style="font-weight:bold;" class="wixui-rich-text__text">Europa murami podzielona</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Na granicach państwowych w r&oacute;żnych zakątkach świata wznoszą się obecnie 74 zapory fizyczne, a 15 kolejnych jest na r&oacute;żnym etapie planowania. Paradoksalnie od czasu, gdy runęła Żelazna Kurtyna, liczba tego typu konstrukcji wzrosła sześciokrotnie. Przeciwnicy takich rozwiązań nawołują do ich demontażu. Wskazują na ich niehumanitarny charakter, szkodliwość dla lokalnych ekosystem&oacute;w, niekorzystny wpływ na ekonomię teren&oacute;w przygranicznych, wysokie koszty budowy i utrzymania. Wreszcie sięgają po koronny argument &ndash; że bariery po prostu nie działają. Czy jest tak w istocie? I dlaczego zatem liberalne rządy promujące ideę otwartych granic i swobodnego przepływu ludności, nie tylko nie rozbierają istniejących zap&oacute;r granicznych, lecz nierzadko je rozbudowują lub modyfikują?</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Gdy w listopadzie 1989 roku zburzono Mur Berliński, wydawało się, że ten symbol uciemiężenia odcisnął takie piętno na świadomości Europejczyk&oacute;w, że na Starym Kontynencie podobna konstrukcja już nie powstanie. Kraje Unii Europejskiej, a zwłaszcza znajdujące się w Strefie Schengen przybierały stopniowo formę globalnej wioski, kt&oacute;rej fundament stanowił swobodny przepływ towar&oacute;w i usług, pieniędzy oraz ludzi. Nie było r&oacute;wnież zewnętrznych czynnik&oacute;w geopolitycznych przemawiających za budową barier granicznych. Do czasu. Zwrot nastąpił już w 1993 r. Co prawda nie na terenie Europy, lecz w Afryce P&oacute;łnocnej &ndash; w dw&oacute;ch hiszpańskich eksklawach otoczonych terytorium Maroka &ndash; Ceucie i Melilli.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Przegradzanie Starego Kontynentu</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W nowym millenium na terenie Europy powstało kilkanaście instalacji granicznych o r&oacute;żnej wielkości i stopniu zaawansowania. I tak na przełomie lat 1999 i 2000 Litwa zbudowała na granicy z Białorusią ogrodzenie o długości 71,5 km. Stało się ono częścią zewnętrznej granicy UE po przystąpieniu tego kraju do Wsp&oacute;lnoty w 2004 r. W latach 2021-2022 wzmocniono je i rozbudowano. Obecnie ma długość 502 km (większość granicy lądowej Litwy i Białorusi). W latach 2017-2018 Litwa zbudowała także 45-kilometrowy płot na granicy z okręgiem Kr&oacute;lewieckim.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W 2012 roku Grecja zbudowała 12,5-kilometrowy płot na granicy z Turcją, w dolinie rzeki Ewros, a w sierpniu 2021 kolejny (40-kilometrowe ogrodzenie na obszarze znanym jako Maritsa i Meri&ccedil;). W sierpniu ubiegłego roku rząd w Atenach ogłosił plany rozbudowy ogrodzenia do łącznej długości 220 km<span style="text-decoration:underline;" class="wixui-rich-text__text">[i]</span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W 2014 roku Bułgaria postawiła wzdłuż granicy z Turcją ogrodzenie z drutu kolczastego o długości 33 km. Ogrodzenie było sukcesywnie rozbudowywane. W roku 2017 jego łączna długość wynosiła 235 km.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W 2015 roku Macedonia P&oacute;łnocna zbudowała kilka zap&oacute;r o długości 37 km biegnących wzdłuż granicy z Grecją.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Pomiędzy rokiem 2015 a 2016, Austria postawiła dwie zapory graniczne &ndash; jedną na granicy ze Słowenią w pobliżu przejścia&nbsp; Spielfeld-&Scaron;entilji<span style="text-decoration:underline;" class="wixui-rich-text__text">[ii]</span> oraz w pobliżu Przełęczy Brenner w Południowym Tyrolu na granicy z Włochami<span style="text-decoration:underline;" class="wixui-rich-text__text">[iii]</span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W latach 2015-2017 Węgry zbudowały 158 km ogrodzeń na granicy z Serbią.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W 2015 roku Estonia ogłosiła zamiar budowy 115-kilometrowego ogrodzenia wzdłuż granicy z Rosją. Prace rozpoczęły się w 2018 r. Do 2021 r. wybudowano stałe ogrodzenie stalowe o długości 25 km, a w ub. roku &ndash; 40 km zapory tymczasowej.<br class="wixui-rich-text__text">
<br class="wixui-rich-text__text">
<span style="font-weight:bold;" class="wixui-rich-text__text">Budowa kolejnych odcink&oacute;w trwa.</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W 2015 r. Łotwa rozpoczęła budowę ogrodzenia na granicy z Rosją, z czego do 2019 r. ukończono 93 km. W sierpniu 2022 r. rząd w Tallinie ogłosił plany przedłużenia ogrodzenia do 148,8 km. W 2021 r. Łotwa zbudowała tymczasowe ogrodzenie o długości 37 km na granicy z Białorusią; do 2024 r. mają zostać ukończone prace nad budową docelowej konstrukcji o długości 150 km<span style="text-decoration:underline;" class="wixui-rich-text__text">[iv]</span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W 2016 roku Norwegia zbudowała 200-metrowy płot na przejściu granicznym Storskog z Rosją nieopodal Kirkenes<span style="text-decoration:underline;" class="wixui-rich-text__text">[v]</span> .</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">We wrześniu 2016 r. Francja, przy wsp&oacute;łfinansowaniu przez Wielką Brytanię, przystąpiła do budowy zapory o długości 1 mili, mającej na celu zabezpieczenie tunelu pod Kanałem La Manche przed migrantami<span style="text-decoration:underline;" class="wixui-rich-text__text">[vi]</span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W 2022 r. Polska zainstalowała stalową barierę o długości 186 km wzdłuż granicy z Białorusią<span style="text-decoration:underline;" class="wixui-rich-text__text">[vii]</span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W październiku 2022 r. Finlandia ogłosiła plan budowy 200-kilometrowej zapory wyposażonej w elektroniczne systemy monitorowania na ciągnącej się 1300 km granicy z Rosją. Projekt wyceniono na 380 mln euro i ma zostać oddany do końca 2026 roku<span style="text-decoration:underline;" class="wixui-rich-text__text">[viii]</span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Opr&oacute;cz zap&oacute;r, kt&oacute;rych powstanie było podyktowane sytuacją geopolityczną lub społeczną, a więc skoncentrowane na ograniczeniu przenikania przez granice ludzi, w Europie powstały też dwie instalacje mające uniemożliwić migrację zwierząt. W 2019 roku Dania na granicy z Niemcami postawiła ogrodzenie w celu zabezpieczenia się przed dzikami mogącymi roznosić afrykański pom&oacute;r świń<span style="text-decoration:underline;" class="wixui-rich-text__text">[ix]</span>, natomiast w tym roku Norwegia przystąpiła do budowy zapory na granicy z Rosją, kt&oacute;ra ma zapobiegać wchodzeniu norweskich renifer&oacute;w &bdquo;w szkodę&rdquo; sąsiadom, za co Moskwa wystawia słone rachunki<span style="text-decoration:underline;" class="wixui-rich-text__text">[x]</span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">&bdquo;Dojrzałe demokracje&rdquo; też grodzą</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">O ile fakt, że w powyższym wykazie figurują państwa byłego Bloku Wschodniego lub będące niegdyś republikami radzieckimi, a więc kraje, kt&oacute;rych społeczeństwa mają wpisaną w genotyp obawę przed imperialnymi zakusami Moskwy, to nie spos&oacute;b przeoczyć, że są tam r&oacute;wnież państwa takie jak Hiszpania, Austria czy Francja. A więc zarządzane przez deklarujące idee promigracyjne ugrupowania lewicowe. W przypadku tych państw, gdy wystąpiła sytuacja kryzysowa, jej rozwiązaniem, albo pr&oacute;bą rozwiązania, była budowa zap&oacute;r granicznych. Świadczy to o cynizmie wynikającym z krytyki budowy podobnych konstrukcji w krajach wschodniej flanki NATO, lecz r&oacute;wnież o braku pomysł&oacute;w na inne &ndash; skuteczniejsze, bardziej humanitarne i zgodne z duchem czas&oacute;w rozwiązania.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W obliczu presji migracyjnej mieszkańc&oacute;w Afryki Subsaharyjskiej na dwie hiszpańskie eksklawy otoczone terytorium Maroka &ndash; Ceutę i Melillę, rząd w Madrycie, na kt&oacute;rego czele stał w&oacute;wczas Felipe Gonz&aacute;lez z Hiszpańskiej Socjalistycznej Partii Robotniczej, w 1993 roku powziął decyzję o rozbudowie instalacji granicznych z lat 70. XX wieku oraz budowie nowych. Dwa lata p&oacute;źniej instalację graniczne rozbudowano o kolejną trzymetrową zaporę, a w 2005 r. następną &ndash; dwukrotnie wyższą. Warto wspomnieć, że projekt modernizacji tych barier w latach 1995-2000 został w 75 proc. sfinansowany przez Unię Europejską<span style="text-decoration:underline;" class="wixui-rich-text__text">[xi]</span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W październiku 2015 roku Austria ogłosiła, że zamierza wybudować zaporę fizyczną o wysokości 2,2 m na prawie 4-kilometrowym odcinku granicy ze Słowenią. Miała to być pierwsza taka konstrukcja pomiędzy państwami Strefy Schengen<span style="text-decoration:underline;" class="wixui-rich-text__text">[xii]</span>. Projekt ukończono w styczniu 2016 r., a jeszcze w tym samym roku, pomimo silnego sprzeciwu Unii Europejskiej, Włoch i Niemiec, powstała kolejna zapora &ndash; w pobliżu Przełęczy Brenner na granicy z Włochami<span style="text-decoration:underline;" class="wixui-rich-text__text">[xiii]</span>. Analizując stosunek rządu we Wiedniu do polityki twardego zamykania granic w świetle znacznego napływu migrant&oacute;w docierających do tego kraju szlakiem zachodniobałkańskim, należy wspomnieć, że kanclerz Karl Nehammer na początku tego roku wszedł w rolę ambasadora rozbudowy infrastruktury na granicy Bułgarsko-Tureckiej. Pierwotnie wnioskował o przyznanie środk&oacute;w unijnych (2 mld euro) na rozbudowę zapory. W obliczu nieprzejednanego stanowiska Brukseli, kt&oacute;rej urzędnicy przekonywali, że nie mają środk&oacute;w na ten cel, a po wt&oacute;re &bdquo;istnieją pewne czerwone linie, kt&oacute;rych Unia nie przekroczy&rdquo; (w kontekście bezpośredniego finansowania barier granicznych), wypracowano rozwiązanie polegające na tym, że UE przeznaczy znaczne środki na opłacenie bułgarskiego personelu granicznego oraz wyposażenie go w sprzęt, co pozwoli Bułgarii przeznaczyć własne zasoby na wzmocnienie zapory. Nehammer podsumował wypracowane porozumienie, że UE de facto płaci za bariery, chociaż twierdzi, że tak nie jest. Raczej trudno odczytać ten układ w inny spos&oacute;b<span style="text-decoration:underline;" class="wixui-rich-text__text">[xiv]</span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Na przeciwległym krańcu Unii Europejskiej, kt&oacute;ra &ndash; pomimo kryzysu wynikającego z niekontrolowanego napływu migrant&oacute;w &ndash; twierdzi, że dokłada starań, żeby kontynent nie stał się twierdzą, we wrześniu 2016 Francja przystąpiła do realizacji projektu, kt&oacute;ry &ndash; w tym rozumieniu &ndash; od definicji twierdzy Europy nie oddalał. Przy wsp&oacute;łudziale finansowym Brytyjczyk&oacute;w, kt&oacute;rzy wyłożyli na ten cel 2,7 mln funt&oacute;w, a potem zgodzili się przeznaczyć kolejne 44,5 mln funt&oacute;w na system zabezpieczeń elektronicznych, wok&oacute;ł francuskiego portu Calais stanęły białe zapory<span style="text-decoration:underline;" class="wixui-rich-text__text">[xv]</span>. Miały one udaremnić pr&oacute;by nielegalnego przedostania się przez port i Eurotunel do Wielkiej Brytanii. W szczytowym momencie w 2015 roku takich pr&oacute;b podejmowano nawet 2 tys. I to w ciągu jednej nocy. Wzdłuż autostrady prowadzącej do tunelu pod kanałem La Manche zamontowano ponad 40-kilomerowe ogrodzenie zwieńczone zwojami drutu kolczastego. System paneli z gęstej siatki ma zapobiegać pr&oacute;bom przecięcia lub wspinania się. Wzdłuż drogi, w pobliżu terenu byłego nielegalnego obozu dla uchodźc&oacute;w zwanego &bdquo;Dżunglą&rdquo;, w kt&oacute;rym w szczytowym momencie kryzysu przebywało nawet 9 tys. os&oacute;b, zbudowano czterometrowy betonowy mur. Zainstalowano system monitorowania portu, a przejeżdżające ciężar&oacute;wki są skanowane za pomocą urządzeń zdolnych wychwycić bicie serca<span style="text-decoration:underline;" class="wixui-rich-text__text">[xvi]</span>. Natomiast na początku sierpnia tego roku infrastruktura mająca na celu zapobieganie pr&oacute;bom nielegalnego przedarcia się do Wielkiej Brytanii wzbogaciła się o zaporę na rzece Canche uchodzącej do Kanału La Manche. Przegroda składająca się z systemu pływak&oacute;w i łańcuch&oacute;w powstała z inicjatywy władz prefektury Pas-de-Calais. Te uzasadniają jej istnienie dążeniem do ograniczenia działalności siatek przemycających ludzi, co wiąże się dla ich klient&oacute;w z olbrzymim ryzykiem w czasie przeprawy przez Kanał La Manche. Tymczasem, jak przekonują eksperci, konstrukcja ani nie zmniejsza chęci zysku przemytnik&oacute;w, ani nie studzi zapału migrant&oacute;w, żeby dostać się na Wyspę, natomiast sama w sobie stanowi kolejne poważne zagrożenie w czasie i tak niebezpiecznej przeprawy<span style="text-decoration:underline;" class="wixui-rich-text__text">[xvii]</span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Czy zapory graniczne działają?</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W internecie można znaleźć bezlik materiał&oacute;w publicystycznych i opracowań naukowych wykazujących, że każda bariera to olbrzymi wydatek, zazwyczaj z kieszeni podatnika. Przy czym każdy taki projekt jest nie tylko głęboko niehumanitarny, cofa nas w mroki średniowiecza, zaburza rytm życia lokalnej fauny i wreszcie sprawia, że gospodarka teren&oacute;w przylegających do takich struktur się zwija, bowiem nie ma tradycyjnej przygranicznej wymiany handlowej. Wreszcie autorzy tych publikacji wskazują, że żadna zapora nie jest w stu procentach szczelna, a sprytnym przemytnikom i tak udaje się z czasem znaleźć alternatywny szlak. Formułowanie takich tez ułatwia fakt, że na działanie takich struktur składa się wiele czynnik&oacute;w: wysokość i materiał konstrukcji, zastosowane środki elektroniczne, długość granicy i uwarunkowania geograficzne teren&oacute;w, przez kt&oacute;re przebiega, sytuacja społeczna, militarna i polityczna po obu stronach, a także w krajach, często odległych, w kt&oacute;rych generowana jest presja na daną granicę. Wreszcie fakt, że presja ta rzadko miewa stały charakter, a jej intensywność podyktowana jest wieloma, często złożonymi czynnikami. Wszystko to sprawia, że nie ma jasnych wskaźnik&oacute;w powalających jednoznacznie ocenić, czy dana konstrukcja spełnia swoją funkcję, czy nie. W tej sytuacji można bezpiecznie przyjąć, że miarą jej skuteczności jest po prostu ocena służb granicznych zabezpieczających na co dzień granicę wyposażoną w daną barierę.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zaczynając od naszego podw&oacute;rka, można stwierdzić, że budowa fizycznej zapory na 186 km granicy z Białorusią oraz montaż bariery elektronicznej znacząco zmniejszyły presję migracyjną wywołaną sztucznie w 2021 roku przez reżim Aleksandra Łukaszenki. Podczas gdy sierpniu 2021 roku (przypomnijmy że szczyt presji przypadł na jesień) odnotowano ponad 3500 pr&oacute;b nielegalnego przekroczenia granicy polsko-białoruskiej, to w sierpniu tego roku Straż Graniczna odnotowała ich 2800<span style="text-decoration:underline;" class="wixui-rich-text__text">[xviii]</span>. Należy przy tym podkreślić, że w czasie poprzedzającym postawienie zapory pr&oacute;b tych mogło być sporo więcej niż figuruje w oficjalnych statystykach. Jak tłumaczyła serwisowi FakeHunter Polskiej Agencji Prasowej rzecznik Straży Granicznej por. Anna Michalska, przed instalacją systemu monitoringu, precyzyjne określenie liczby pr&oacute;bujących się przedrzeć przez granicę było właściwie niemożliwe: &bdquo;Jeśli w&oacute;wczas nasz funkcjonariusz zgłaszał, że pod linię granicy podchodzi grupa os&oacute;b, ale jest ciemno i trudno stwierdzić, ile ich jest, ale tak na oko z 15, to dzięki systemom, kt&oacute;re teraz mamy, wiemy, że jest ich na przykład 17&rdquo; &ndash; wyjaśnia Anna Michalska i zaznacza, że bariera nie tylko utrudnia nielegalne przekroczenie granicy, lecz r&oacute;wnież ułatwia pracę straży, bo dzięki monitoringowi, ta ma wystarczająco dużo czasu, aby zareagować, wysyłając w miejsce zdarzenia patrol. Za przykład skuteczności działania bariery elektronicznej może posłużyć zdarzenie z 13 września w Podcerk&oacute;wce, gdzie, dzięki elektronicznemu powiadomieniu, zatrzymano 19 Syryjczyk&oacute;w.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">System elektronicznych czujnik&oacute;w nierzadko ratuje też życie. I to nie tyle funkcjonariuszy, co pr&oacute;bujących się przedrzeć migrant&oacute;w. SG, otrzymując informacje o wszelkich zdarzeniach na granicy, może też na czas udzielić migrantom pomocy medycznej. Od początku kryzysu na granicy z Białorusią odnotowano łącznie 840 wyjazd&oacute;w Zespoł&oacute;w Ratownictwa Medycznego do cudzoziemc&oacute;w nielegalnie przekraczających granicę. Wielu z tych wezwań dokonywali funkcjonariusze SG. Zdarzało się r&oacute;wnież, że sami ratowali migrant&oacute;w. &bdquo;Od początku kryzysu migracyjnego funkcjonariusze SG przeprowadzili 23 akcje ratowania życia, w ciężkich warunkach, gł&oacute;wnie na bagnach, podczas kt&oacute;rych uratowano 73 cudzoziemc&oacute;w&rdquo; &ndash; m&oacute;wi por. Michalska.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Powod&oacute;w do narzekań w związku z wyposażeniem linii granicznej w barierę nie mają r&oacute;wnież służby litewskie. O ile w 2021 r. odnotowały 8106 pr&oacute;b przedarcia się przez granicę ich kraju z Białorusią, to po zbudowaniu wysokiej na 3,5 metra zapory ciągnącej się na długości 500 km (oddanej do użytku w listopadzie 2022 r.)<span style="text-decoration:underline;" class="wixui-rich-text__text">[xix]</span>, liczba ta spadła do 11 tysięcy w roku 2022 r. Natomiast w tym roku, do czasu sporządzenia tej analizy było ich 1597.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Choć, jak wspomnieliśmy wcześniej, nie ma jasnych kryteri&oacute;w, kt&oacute;re pozwoliłyby określić, czy dana bariera graniczna spełnia swoją funkcję, należy wspomnieć, że już nawet te najskromniejsze konstrukcje skutkowały zmniejszeniem presji. Według &oacute;wczesnego ministra spraw wewnętrznych Hiszpanii Jos&eacute; Ram&oacute;na &Oacute;negi, w Melilli w lutym 1998 roku notowano 152 pr&oacute;b nielegalnego przekroczenia granicy, ale latem &ndash; już tylko 45. Z kolei we Francji latach 2016-2017 nastąpił znaczny spadek (z 33.807 do 15.457) liczby migrant&oacute;w trafiających do Calais i pr&oacute;bujących przedostać się do Wielkiej Brytanii. Podobną tendencję odnotowano też w Coquelles i Dunkierce. W tym okresie bardzo wydatnie spadła też przestępczość w tym rejonie. Należy jednak mieć na uwadze, że to zjawisko mogło wynikać nie tylko montażu zabezpieczeń w rejonie portu i wjazdu do Eurotunelu, lecz r&oacute;wnież likwidacji przez francuskie władze w październiku 2016 roku &bdquo;Dżungli&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[xx]</span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Krytycy budowy zap&oacute;r granicznych, skupiając się na ich &bdquo;p&oacute;łprzepuszczalności&rdquo;, pomijają jeszcze jeden bardzo ważny aspekt. To umożliwienie służbom granicznym zaangażowania mniejszej liczby personelu w zabezpieczenie newralgicznych rejon&oacute;w. Co prawda ściągnięcie po śmierci Jewgienija Prigożyna kilkuset wagnerowc&oacute;w na Białoruś wymusiło na Polsce wzmocnienie sił przy granicy, skutkiem czego służy tam obecnie 5 tys. strażnik&oacute;w granicznych, 4 tys. żołnierzy oraz p&oacute;ł tysiąca policjant&oacute;w<span style="text-decoration:underline;" class="wixui-rich-text__text">[xxi]</span>. Jednak brak zapory i systemu monitoringu wymuszałby obecność jeszcze bardziej licznego personelu. Co prawda w tej analizie skupiliśmy się na Europie, jednak w tym miejscu warto przywołać przykład tzw. muru Trumpa na południowych granicach Arizony, Nowego Meksyku i Teksasu. Po pierwsze dlatego, że zjawisko napływu migrant&oacute;w z Meksyku ma tam w miarę stały charakter, a po południowej stronie zapory nie dokonują się tak drastyczne działania, jak te, kt&oacute;rymi raczą sąsiad&oacute;w Moskwa i Mińsk. Po drugie zaś dlatego, że Amerykanie są bardzo skrupulatni. W 2020 roku, po wzniesieniu ponad 380 mil (ponad 600 km) nowoczesnej zapory na granicy z Meksykiem, amerykańskie służby graniczno-skarbowe (Customs and Border Protection) zanotowały, że tylko niewielki (niespełna 20-kilometrowy) odcinek muru w okolicach San Diego można było obsadzić znacznie mniej liczną załogą &ndash;&nbsp; pomniejszoną o 150 os&oacute;b. A tylko to dawało oszczędności rzędu 28 mln USD rocznie<span style="text-decoration:underline;" class="wixui-rich-text__text">[xxii]</span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W charakterze podsumowania, warto przywołać słowa byłego oficera armii USA w czynnej służbie, weterana wojny w Iraku, politologa w bezpartyjnej organizacji non-profit RAND Corporation oraz adiunkta studi&oacute;w nad bezpieczeństwem na Uniwersytecie Georgetown Raphaela S. Cohena. Twierdzi on, że &bdquo;mury są taktyką (choć czasami kluczową), ale ostatecznie nie strategią. Ponieważ mogą natychmiast ulżyć bieżących problemach, pozwalają decydentom kupić czas i przestrzeń polityczną, potrzebną do użycia innych narzędzi (&hellip;) Jeśli mur graniczny zapewni przestrzeń polityczną do rozwiązania tych bardziej systemowych problem&oacute;w, w&oacute;wczas może to być opłacalną inwestycją&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[xxiii]</span>.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Europejskie rządy, zar&oacute;wno państw byłego Bloku Wschodniego, jak i Europy Zachodniej oraz Skandynawii swoimi poczynaniami zdają się potwierdzać jego słowa. Budowa zap&oacute;r granicznych to rozwiązanie budzące kontrowersje i nieidealne pod względem skuteczności. Jednak gdy dany kraj staje w obliczu poważnego kryzysu, często okazuje się, że innego po prostu nie ma.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Kraje, w kt&oacute;rych istnieją fizyczne zapory graniczne wraz z ich łączną długością (w kilometrach)</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Afganistan &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 2,670 &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Arabia Saudyjska 75</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Bangladesz &nbsp; &nbsp; &nbsp; &nbsp; 3,268 &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Birma &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1,624</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Botswana &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 500 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Brunei &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 20 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Bułgaria &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 30</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Chiny &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 32 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Chorwacja &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 41</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Cypr &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 180 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Egipt &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Estonia &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 108 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Grecja &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 200</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Hiszpania &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 8 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Hongkong &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 32 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Indie &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3,268</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Irak &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 193 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Iran &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 959 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Izrael &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 708 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jemen &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 75 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kazachstan &nbsp; &nbsp; &nbsp; &nbsp; 45</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kirgistan &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 870 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kuwejt &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 193 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Korea Południowa &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 248</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Korea P&oacute;łnocna &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 1,416 &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Liban &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 11</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Libia &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 460</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Macedonia P&oacute;łnocna &nbsp; &nbsp; 30</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Malezja &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 20 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Maroko &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 8</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Meksyk &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 1,000 &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Mozambik &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 120 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Norwegia &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 200 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Oman &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 410</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Pakistan &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 550 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Palestyna &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 708</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Polska &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 186</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Republika Południowej Afryki &nbsp;&nbsp; 120 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rosja &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 108 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Serbia &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 175 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Słowenia &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 220 &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Stany Zjednoczone &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 1,000</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Syria &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 828</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tajlandia &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 650</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tunezja &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 460</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Turcja &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 30</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ukraina &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 2,000</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Węgry &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 175</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Uzbekistan &nbsp; &nbsp; &nbsp; &nbsp; 45 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zimbabwe &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 500</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zjednoczone Emiraty Arabskie &nbsp; 410</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Źr&oacute;dło: World Population Review</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[i]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.europarl.europa.eu/RegData/etudes/BRIE/2022/733692/EPRS_BRI(2022)733692_EN.pdf" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.europarl.europa.eu/RegData/etudes/BRIE/2022/733692/EPRS_BRI(2022)733692_EN.pdf</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[ii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.dw.com/en/austria-begins-erecting-fence-on-border-with-slovenia/a-18900764" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.dw.com/en/austria-begins-erecting-fence-on-border-with-slovenia/a-18900764</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[iii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.bbc.com/news/world-europe-36022914" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.bbc.com/news/world-europe-36022914</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[iv]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.schengenvisainfo.com/news/eu-countries-are-building-fences-all-around-their-borders-with-third-countries-this-is-how-they-look/" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.schengenvisainfo.com/news/eu-countries-are-building-fences-all-around-their-borders-with-third-countries-this-is-how-they-look/</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[v]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.bbc.com/news/world-europe-37577547" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.bbc.com/news/world-europe-37577547</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[vi]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.dailymail.co.uk/news/article-3776897/Britain-build-Great-Wall-Calais-Taxpayers-pay-2million-13ft-high-one-mile-long-concrete-barrier-migrants-out.html" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.dailymail.co.uk/news/article-3776897/Britain-build-Great-Wall-Calais-Taxpayers-pay-2million-13ft-high-one-mile-long-concrete-barrier-migrants-out.html</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[vii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.strazgraniczna.pl/pl/aktualnosci/9752,Ruszyla-budowa-bariery-na-granicy-polsko-bialoruskiej.html" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.strazgraniczna.pl/pl/aktualnosci/9752,Ruszyla-budowa-bariery-na-granicy-polsko-bialoruskiej.html</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[viii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.reuters.com/world/europe/finland-starts-fence-russian-border-amid-migration-security-concerns-2023-04-14/" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.reuters.com/world/europe/finland-starts-fence-russian-border-amid-migration-security-concerns-2023-04-14/</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[ix]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.dw.com/en/denmark-completes-contentious-fence-along-german-border/a-51496704" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.dw.com/en/denmark-completes-contentious-fence-along-german-border/a-51496704</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[x]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://apnews.com/article/norway-russia-reindeer-fence-b4ffdc7e7dd1b0a84fd8ebdf9e44fe3c" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://apnews.com/article/norway-russia-reindeer-fence-b4ffdc7e7dd1b0a84fd8ebdf9e44fe3c</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xi]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.cpsa-acsp.ca/papers-2010/Saddiki.pdf" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.cpsa-acsp.ca/papers-2010/Saddiki.pdf</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.dw.com/en/austria-begins-erecting-fence-on-border-with-slovenia/a-18900764" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.dw.com/en/austria-begins-erecting-fence-on-border-with-slovenia/a-18900764</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xiii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.bbc.com/news/world-europe-36022914" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.bbc.com/news/world-europe-36022914</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xiv]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.politico.eu/article/euco-eu-crosses-into-the-border-fence-game-migration/" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.politico.eu/article/euco-eu-crosses-into-the-border-fence-game-migration/</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xv]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.theguardian.com/politics/2018/jan/18/uk-to-pay-extra-445m-for-calais-security-in-anglo-french-deal" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.theguardian.com/politics/2018/jan/18/uk-to-pay-extra-445m-for-calais-security-in-anglo-french-deal</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xvi]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.globalsecurity.org/military/world/europe/uk-calais-fence.htm" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.globalsecurity.org/military/world/europe/uk-calais-fence.htm</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xvii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.express.co.uk/news/world/1806123/Channel-migrant-crossings-Calais-barrier" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.express.co.uk/news/world/1806123/Channel-migrant-crossings-Calais-barrier</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xviii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://fake-hunter.pap.pl/node/103" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://fake-hunter.pap.pl/node/103</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xix]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://szczecin.tvp.pl/64371124/ponad-500-kilometrow-plotu-litwa-juz-odgrodzona-od-bialorusi" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://szczecin.tvp.pl/64371124/ponad-500-kilometrow-plotu-litwa-juz-odgrodzona-od-bialorusi</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xx]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.globalsecurity.org/military/world/europe/uk-calais-fence.htm" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.globalsecurity.org/military/world/europe/uk-calais-fence.htm</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xxi]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://infosecurity24.pl/bezpieczenstwo-wewnetrzne/dwa-razy-wiecej-zolnierzy-przy-granicy-z-bialorusia" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://infosecurity24.pl/bezpieczenstwo-wewnetrzne/dwa-razy-wiecej-zolnierzy-przy-granicy-z-bialorusia</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xxii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.cbp.gov/frontline/border-security" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.cbp.gov/frontline/border-security</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xxiii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.rand.org/blog/2019/01/what-border-walls-can-and-cannot-accomplish.html" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.rand.org/blog/2019/01/what-border-walls-can-and-cannot-accomplish.html</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></div>



