
@extends('layouts.app')

@section('title', 'Home - Kevix Template')

@section('content')

<body>
    <section class="section" style="padding: 170px 0px 75px 0px; background-size: cover; position: relative; background-position: center center;" id="home">
        <div class="bg-overlay"></div>
        <div class="home-center">
            <div class="home-desc-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="home-page-title text-center">
                                <h1 class="text-white mb-2">Wojska Obrony Terytorialnej (WOT) w latach 2016-2022 – geneza, perspektywy i historia kampanii dyskredytacyjnej</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="blog-info p-3">
                        <h2 class="text-dark mb-3">Dr Piotr Balcerowski</h2>
                        <div class="blog-info-desc">
                            <p style='text-align: justify;'>


<span style="font-weight:bold;" class="wixui-rich-text__text">Wojska Obrony Terytorialnej (WOT) w latach 2016-2022 – geneza, perspektywy i historia kampanii dyskredytacyjnej</span></p></p>


<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;W obecnej sytuacji geopolitycznej Wojska Obrony Terytorialnej są jedynym, relatywnie szybkim, tanim i skutecznym sposobem odbudowy naszego bezpieczeństwa militarnego.&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[i]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;Warunki wsp&oacute;łczesnej wojny wymagają, aby wszyscy ludzie zdolni do noszenia broni brali w niej udział, a ponieważ przygotowanie do tej służby wymaga długiego okresu edukacji, etyka wojskowa jest ważna nie tylko dla żołnierza stałej służby, ale dla wszystkich ludzi w og&oacute;le. Innymi słowy, zaw&oacute;d żołnierza powinien być drugim zajęciem każdego człowieka &rdquo;- J&oacute;zef I.M. Bocheński OP (&bdquo;Patriotyzm, Męstwo, Prawość żołnierska&rdquo;)</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zbliża się 6 rocznica powołania Wojsk Obrony Terytorialnej dlatego warto pokusić się o pierwsze oceny dorobku formacji, kt&oacute;rej trzon stanowią młodzi żołnierze. Zwłaszcza w sytuacji, w kt&oacute;rej formacja ta zyskała, między innymi dzięki poświęceniu tysięcy młodych i starszych Terytorials&oacute;w, uznanie nie tylko w oczach polskich i zagranicznych specjalist&oacute;w, ale r&oacute;wnież w oczach zwykłych Polak&oacute;w, co jednoznacznie pokazują badania. <span style="text-decoration:underline;" class="wixui-rich-text__text">[ii]</span> Stało się to pomimo bardzo negatywnego i nieobiektywnego nastawienia medi&oacute;w gł&oacute;wnego nurtu do tworzącej się formacji Wojska Polskiego, zjawiska w historii Polski bez precedensu (za wyjątkiem może aktywności &bdquo;Sztandaru Socjalizmu&rdquo; Komunistycznej Partii Polski &bdquo;w przededniu&rdquo; napaści bolszewik&oacute;w w 1920 r.). Dlatego przedmiotem tej pracy będzie r&oacute;wnież analiza contentu najbardziej emblematycznych negatywnych artykuł&oacute;w oraz pr&oacute;ba systematyki gł&oacute;wnych mechanizm&oacute;w dyskredytacyjnych zastosowanych w nich. Dodatkowo, podejmę pr&oacute;bę znalezienia w nich punkt&oacute;w stycznych z propagandową narracją rosyjską, kt&oacute;ra r&oacute;wnież nie sprzyjała rozbudowie Wojska Polskiego o piąty rodzaj sił zbrojnych. Te rozważania będą osadzone w szerszej perspektywie historii i myślenia o bezpieczeństwie Polski. Będę chciał zachęcić Czytelnika m.in. do zastanowienia się nad przyczynami braku rozpoczęcia budowy tej potrzebnej formacji w latach 2008 &ndash; 2015, kt&oacute;rych klamrami są dwie napaści Rosji na swoich sąsiad&oacute;w, Gruzję i Ukrainę.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Geneza i powstanie WOT w Polsce w 2016 roku</p>
</li>
</ol></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Polska posiada bogate tradycje zinstytucjonalizowanej Obrony Terytorialnej. Pomijając tradycje pospolitego ruszenia I Rzeczpospolitej, kiedy to każdy obywatel był zobowiązany bronić swego terytorium, wsp&oacute;łcześnie najlepszymi przykładami są Obrona Narodowa stworzona w 1937 r. oraz podziemna ZWZ/AK oraz NSZ stworzone pomimo okupacyjnych warunk&oacute;w w bardzo kr&oacute;tkim okresie lat 1940-42.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W PRL-u, min. ze względu na dużą, blisko 0,5 mln armię, w ścisłym rozumieniu OT nie funkcjonowała, choć&nbsp; występowały w LWP jednostki o zbliżonym profilu. III Rzeczpospolita nie była dla idei odbudowy WOT łaskawa, choć np. już w 2000r. Minister ON zatwierdził dokument powstały w skutek pracy zespołu pod kierownictwem prof. Romualda Szeremietiewa. Do rozwoju formacji we wczesnych latach dwutysięcznych jednakże ostatecznie nie doszło, na co mogło mieć wpływ przejęcie władzy przez Lewice w 2001 roku.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Już napaść Rosji na Gruzję w 2008 roku a w szczeg&oacute;lności wydarzenia na Ukrainie w 2013/2014 związane z inwazją de facto wojsk rosyjskich na ten kraj, w spos&oacute;b krytyczny uzmysłowiły konieczność przeformułowania polskiej doktryny wojskowej, co wiązało się min. z koniecznością zwiększenia liczebności PSZ oraz większego zaangażowania społeczeństwa w obronność państwa. Było to tym łatwiejsze, iż inicjatywa taka mogła się spotkać z dużym społecznym odzewem i zainteresowaniem samoorganizującej się od końca lat 90 w licznych organizacjach pro obronnych polskiej młodzieży. Niejako w odpowiedzi na te wydarzenia i trendy, w 2014 roku, MON podjęło pewne działania min. powołało pełnomocnika ds. społecznych inicjatyw pro obronnych. Niestety do szybkiego powołania formacji w typie WOT ostatecznie w latach 2014-2015 nie doszło, zaś inicjatywy MON miały charakter raczej pozorowany, co było całkowicie niezrozumiałe. Do powołania WOT z prawdziwego zdarzenia doszło ostatecznie w 2016 r., w wyniku&nbsp; zmiany politycznej&nbsp; w Polsce pod koniec&nbsp; 2015 roku.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Istota wsp&oacute;łczesnego WOT. Stan obecny i perspektywy rozwoju w najbliższych latach.</p>
</li>
</ol></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><br class="wixui-rich-text__text">
Zanim przejdę do gł&oacute;wnej treści analizy w skr&oacute;cie przedstawię gł&oacute;wne funkcje WOT definiujące ich istotę. W największym skr&oacute;cie WOT to lekka piechota. Żołnierzami WOT są ochotnicy, szkoleni przede wszystkim w systemie weekendowym. Kadrę dow&oacute;dczą stanowią natomiast żołnierze zawodowi. WOT w większości kraj&oacute;w ma najczęściej strukturę odpowiadającą podziałowi administracyjnemu kraju, co związane jest z terytorialnym profilem tych wojsk. Podobnie jest w Polsce, gdzie funkcjonuje brygada na poziomie każdego wojew&oacute;dztwa (wyjątki to woj. mazowieckie &ndash; 3 brygady, woj. podkarpackie i lubelskie &ndash; 2 brygady, woj. opolskie i lubuskie dysponują na razie batalionami). Jak możemy przeczytać na stronie Terytorials&oacute;w do podstawowych zadań WOT należy: prowadzenie działań obronnych we wsp&oacute;łdziałaniu z wojskami operacyjnymi i wsparcia oraz elementami układu pozamilitarnego (UPM); prowadzenie samodzielnych działań niekonwencjonalnych, przeciwdywersyjnych i przeciwdesantowych; udział w zabezpieczeniu przyjęcia i rozwinięcia sojuszniczych sił wzmocnienia w nakazanych rejonach; realizacja przedsięwzięć z zakresu zarządzania kryzysowego; prowadzenie działań informacyjnych.&rdquo; Kto służy w WOT? 22% to kobiety, reszta to mężczyźni. Ok. 33 proc. z nich ma wyższe wykształcenie, a co piąta osoba jeszcze studiuje. Jak ujął to w ostatnim wywiadzie dla PAP dow&oacute;dca jednostki gen. Wiesław Kukuła &bdquo;Gdy zsumujemy te dwie ostatnie liczby to można powiedzieć, że ponad 50 proc. naszych żołnierzy ma wyższe wykształcenie lub wkr&oacute;tce je będzie miało. To jeden z najwyższych wskaźnik&oacute;w na świecie. Średnia wieku naszych żołnierzy to 33 lata i to jest trochę modelowane przez nas, bo chcemy łączyć ludzi w takie zespoły, gdzie jest trochę młodości, świeżości, ale r&oacute;wnież doświadczenia życiowego&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[iii]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Po blisko 6 latach od utworzenia WOT możemy m&oacute;wić o sukcesie w tworzeniu nowej formacji. Po pierwsze, udało się sformować 20 brygad w kt&oacute;rych trwają szkolenia żołnierzy. Ich liczba zbliża się do 35 tysięcy, z czego ok. 10% stanowią żołnierze zawodowi a reszta to nowi żołnierze Terytorialnej Służby Wojskowej. Postępuje nie tylko proces szkoleniowy i rozbudowa infrastruktury szkoleniowej (min. centrum szkoleniowe WOT w Toruniu i Zegrzu, utworzenie szkoły/kursu podoficerskiego/ oficerskiego o nazwie SONDA/AGRYKOLA, czy też Zespołu Działań Cyberprzestrzennych), ale i systematyczne uzbrajanie żołnierzy w najnowocześniejszy polski sprzęt dla lekkiej piechoty min. nowoczesny karabin &bdquo;Grot&rdquo; czy drony Flyeye.&nbsp; Cieszy r&oacute;wnież perspektywa dostarczenia granatnik&oacute;w przeciwpancernych (m.in. Javelin czy M72 EC Mk1), kt&oacute;re wkr&oacute;tce powinny znaleźć się na wyposażeniu prawie każdej drużyny WOT. Dozbrajanie WOT skorelowane jest r&oacute;wnież z updatowaniem zadań na polu walki z wykorzystaniem wiedzy i doświadczenia ukraińskich jednostek WOT, o czym wspominał ostatnio dow&oacute;dca WOT, gen. Wiesław Kukuła. <span style="text-decoration:underline;" class="wixui-rich-text__text">[iv]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Przy okazji Ukrainy warto też wspomnieć o szczeg&oacute;lnej roli jaką w pomocy uchodźcom odegrali żołnierze WOT w ramach swoich obowiązk&oacute;w związanych z zarządzaniem kryzysowym. W akcji &bdquo;Niezawodna pomoc&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[v]</span>uczestniczyło blisko 6 tysięcy Terytorials&oacute;w, kt&oacute;rzy wspierali obsługę os&oacute;b w punktach informacyjnych, dystrybucję pomocy humanitarnej, transport czy budowę miejsc tymczasowego zakwaterowania.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">To była zresztą kolejna aktywność&nbsp; jednostek WOT w ramach tego obszaru. Wcześniej bowiem, przez blisko 2 lata, żołnierze WOT pomagali przy organizacji szczepień na Covid -19, czy wspierali weteran&oacute;w/osoby starsze, hospitalizowane etc. W szczytowych momentach akcji &bdquo;Odporna wiosna&rdquo; a następnie &bdquo;Trwała odporność&rdquo; brało udział każdego dnia blisko 6 tysięcy Terytorials&oacute;w.<span style="text-decoration:underline;" class="wixui-rich-text__text">[vi]</span>&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ale, jak podkreślił gen. Kukuła we wspomnianym wywiadzie, &bdquo;Wiele os&oacute;b sądziło, że jesteśmy tacy bardziej cywilnocentryczni, tak stoimy trochę obok wojska, skoncentrowani na zarządzaniu antykryzysowym. Kompletnie umyka ludziom jednak to prawdziwe oblicze WOT-u, kt&oacute;re jest obliczem zbrojnym, wojskowym. Nasze szkolenie żołnierza w 90 proc. jest skoncentrowane na szkoleniu bojowym. Ale cieszmy się, że taki +cywilny+ obraz WOT się wyłania, bo to oznacza, że nie testowano nas bojowo, czyli Polska była bezpieczna, nie było wojny&rdquo;.<span style="text-decoration:underline;" class="wixui-rich-text__text">[vii]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ale jak wiemy, choćby ze znanego powiedzenia, aby mieć pok&oacute;j, trzeba się szykować do wojny, dlatego r&oacute;wnież w świetle wydarzeń za naszą wschodnia granicą, wojskowa rola WOT będzie sukcesywnie rosła. Aby osiągnęła ona sw&oacute;j właściwy status potrzebne są przynajmniej 2-3 rzeczy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Po pierwsze, kadry. Można prognozować, biorąc pod uwagę średnią liczbę aplikacji i &bdquo;przepustowość&rdquo; szkoleniową WOT na poziomie ok 10 tys. żołnierzy, iż proces terminowej budowy formacji do swego stanu docelowego tj. 53 tys. żołnierzy w pełnej gotowości&nbsp; bojowej w roku 2026 jest niezagrożony.&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Po drugie, uzbrojenie. Wydaje się, iż należyte uzbrojenie większości jednostek w broń rozpoznawczą, przeciwpancerną i być może przeciwlotniczą kr&oacute;tkiego zasięgu w zarysowanej perspektywie jest realne. Pilną potrzebą chwili wydaje się r&oacute;wnież broń wyborowa. Jak podkreślił w wywiadzie gen.Kukuła &bdquo;Ten rodzaj broni okazał się najlepszy, jeśli chodzi o działania w Ukrainie i też w działaniach przeciwokupacyjnych. To jeden z podstawowych wniosk&oacute;w wojsk ukraińskich, że ten obszar strzelc&oacute;w wyborowych i snajper&oacute;w był niedoinwestowany u nich. My o tym pomyśleliśmy, projektując WOT, wszystko czego nam brakuje, aby rozwinąć skrzydła w tym obszarze, to właśnie dostęp do dobrej jakości broni wyborowej. Mamy coraz lepszą broń polską więc mam nadzieję, że wkr&oacute;tce to się ziści&rdquo; <span style="text-decoration:underline;" class="wixui-rich-text__text">[viii]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tym samym należy mieć nadzieję, iż komponent WOT do 2026 r. już w pełni, w wymiarze kadrowym i &bdquo;wyposażeniowym&rdquo; będzie, zgodnie z założeniami Strategicznego Przeglądu Obronnego, uzupełnieniem zdolności antydostępowych Polskich Sił Zbrojnych na terytorium Rzeczpospolitej Polskiej.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ale nie będzie to możliwe, bez trzeciego, kluczowego elementu jakim jest zrozumienie i wsparcie społeczne dla WOT. Skalę i siłę tego zjawiska dobrze oddają słowa Marszałka Piłsudskiego &bdquo;Do obrony granic państwa społeczeństwo winno dać (żołnierzom -PB) przede wszystkim to, co w języku wojennym nazywa się morale&rdquo;. I choć w Polakach drzemie naturalny, historycznie i charakterologicznie uwarunkowany potencjał &bdquo;morale&rdquo; dla polskiego żołnierza, w ostatnich latach środowiska polskie, kt&oacute;re go najwyraźniej nie posiadają, były, obok ośrodk&oacute;w rosyjskich, niezmiernie aktywne. Co gorsza, r&oacute;wnież w sferze wpływu na opinię publiczną, czyli mass medi&oacute;w. Ich swoistemu modus operandi będę chciał się przyjrzeć w trzeciej części pracy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kampania dyskredytacyjna wobec WOT w latach 2016-2022</p>
</li>
</ol></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Bezsilna wściekłość dusiła mnie nieraz, że w niczym zaszkodzić wrogom nie mogę, że muszę w milczeniu znosić deptanie mej godności i słuchać kłamliwych i pogardliwych sł&oacute;w o Polsce, Polakach i naszej historii - J&oacute;zef Piłsudski</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rosyjskie historyczne tło. Dyskredytacja poznawcza jako element&nbsp; rosyjskiej strategii informacyjnej</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zanim przejdę do analizy contentu prasy polskojęzycznej w kontekście WOT warto przypomnieć, iż właściwie od początku rozpoczęcia polskich starań o akcesję do NATO, rosyjskie agencje/wojska dezinformacyjne rozpoczęły systematyczną pracę zmierzającą do osłabienia możliwości obronnych RP. Z jednej strony były to oczywiście działania dyplomatyczne (czego skutecznym efektem było min. &bdquo;nieformalne&rdquo; uzgodnienie dotyczące nierozlokowywania wojsk NATO na terytoriach byłych państw Układu Warszawskiego), z drugiej strony podejmowano szereg operacji wpływu na opinie publiczne państw zachodnich, w tym państwa polskiego, korzystając ze starej metody &bdquo;marchewki i kija&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Marchewką było inspirowanie opinii, iż nie będzie konfliktu z Rosją, bo Rosja go nie chce, jest już pokojowym krajem chcącym jedynie uszanowania (co zrozumiałe zwłaszcza przez Ruslandvershte&rsquo;r&oacute;w) jej wielkości i stref wpływ&oacute;w. Całkowicie bezpodstawne straszenie nią to jedynie nakręcanie koniunktury zbrojeniowej, kt&oacute;ra jest szkodą dla narodowej ekonomii i obywateli bowiem &bdquo;zasoby skierowane na zbrojenia to zasoby zmarnowane&rdquo;. Wariantem tej pacyfistycznej narracji, było wykluczenie wojny jako narzędzia uprawiania polityki. Agenci wpływu argumentowali, iż&nbsp; nie będzie już wojny w Europie, bo państwa europejskie są świadome (po historycznych doświadczeniach) z czym się to wiąże. Poza tym jest bomba atomowa, kt&oacute;ra powstrzymuje od konflikt&oacute;w i zbrojenia konwencjonalne są pozbawione sensu etc.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;Kijem&rdquo; zaś był przekaz &bdquo;lepiej nie drażnić niedźwiedzia&rdquo;.&nbsp; Argumentowano, iż choć Rosją rządzą obecnie osoby miłujące pok&oacute;j, to w dalszym ciągu jest tam wpływowa grupa &bdquo;siłownik&oacute;w&rdquo;, kt&oacute;ra może przejąć władzę w sytuacji w kt&oacute;rej Zach&oacute;d, NATO etc. będzie się zbroił i rozszerzał swoja sferę wpływ&oacute;w.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Oczywiście przełamywanie wielkiej smuty po rozpadzie ZSRR,&nbsp; sukcesywna reforma sił zbrojnych, bardzo ofensywne działania wywiadu rosyjskiego i coraz bardziej&nbsp; agresywna polityka wobec &bdquo;bliskiej zagranicy&rdquo; (czego najdobitniejszym przykładem była wojna gruzińska w 2008 roku),&nbsp; była coraz trudniejsza do ukrycia przed światem i utrudniała sp&oacute;jność&nbsp; oraz efektywność tej narracji.&nbsp; Prawdziwym jednak game changer&rsquo;em&nbsp; były wydarzenia na Ukrainie w 2014 roku tzn. okupacja Krymu i wojna w Donbasie.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dla większości analityk&oacute;w stało się aktualne znane powiedzenie&nbsp; Enocha Powella o tym iż &bdquo;Historia pełna jest wojen, o kt&oacute;rych każdy wiedział, że nie wybuchną&quot; zaś dotychczasowe pokojowe deklaracje Rosji były de facto wizerunkową maskirowką, czyli ofensywną dyskredytacją poznawczą mającą zakł&oacute;cić właściwą ocenę rzeczywistości&nbsp; rosyjskiej wśr&oacute;d decydent&oacute;w i społeczeństw zachodnich. Oficjalna napaść Rosji na Ukrainę w 2022 roku tylko to ostatecznie potwierdziła.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dyskredytacja kompetencyjna WOT jako element kontynuacji strategii osłabiania odbudowy PSZ</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wobec ewidentnych trudności z budowaniem narracji postrzegającej &bdquo;Rosję jako państwo miłujące pok&oacute;j&rdquo; środowiska niechętne WOT uznały, iż faktycznie nie warto otwarcie krytykować wzmacniania obronności PSZ, ale jednocześnie należy przekonywać, iż tworzenie WOT jest całkowicie nieefektywne z punktu widzenia obronności państwa, gdyż &bdquo;weekendowi żołnierze&rdquo; nie będą w stanie należycie wykonywać swoich obowiązk&oacute;w. Bardzo symptomatyczne było tu inspirowanie dziennikarzy do zadawania decydentom i przyw&oacute;dcy formacji pytań w stylu &bdquo;Czy Terytorials będzie umiał strzelać?&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[ix]</span> Dodatkowo, wytwarzano wrażenie min. poprzez sugestywne tytuły/leady, iż Terytorialsi to typowe &bdquo;mięso armatnie&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[x]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Narracja ta całkowicie ignorowała rozumienie zadań żołnierza formacji typu WOT. Do jego zadań przecież nie należy realizowanie skomplikowanych działań ofensywnych z użyciem zaawansowanego sprzętu (w tym elektronicznego), co jest domeną wojsk operacyjnych i co faktycznie wiąże się z koniecznością prowadzenia wręcz permanentnych ćwiczeń koordynująco &ndash; usprawniających. Zadaniami każdej lekkiej piechoty jest zabezpieczenie, w tym przypadku 2 lub 3 linii ewentualnego frontu, do kt&oacute;rego nie potrzeba aż tak intensywnych szkoleń. Doprawdy strzelanie, minowanie, odpalanie RPG etc. etc. nie jest aż tak wymagającą sztuką, aby należało ją robić codziennie.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Całkowicie pomijano fakt, iż wraz ze zwijaniem stosunkowo dużej liczbowo armii polskiej i zawieszeniem poboru, silnie rozwijał się oddolny ruch pro obronny, kt&oacute;ry tworzył dość silne zaplecze os&oacute;b zainteresowanych wojskiem, sztukami walki etc. etc. Cokolwiek by nie powiedzieć o mankamentach szkolenia w tego typu organizacjach (wynikających min. z braku należytego finansowania, specjalist&oacute;w), integrując pasjonat&oacute;w przyczyniały się one do stworzenia naturalnego zaplecza WOT, grupując niemałe liczby członk&oacute;w mających przyswojone elementarne podstawy działania lekkiej piechoty. Sukcesy żołnierzy WOT wywodzących się z tego środowiska (min. w r&oacute;żnorakich konkursach w strzelaniu ) są tego dobitnym potwierdzeniem<span style="text-decoration:underline;" class="wixui-rich-text__text">[xi]</span>. Dodatkowo, narracja ta całkowicie ignorowała dwa bardzo istotne elementy dla rzemiosła żołnierskiego, kt&oacute;rego częścią jest szkolenie nowego żołnierza. Po pierwsze wysokie morale, kt&oacute;re z reguły charakteryzuje wszystkich ochotnik&oacute;w, po drugie ich naturalne predyspozycje psycho-fizyczne do &bdquo;wojaczki&rdquo; czyniące z nich &bdquo;natural born warriors&rdquo; (w literaturze przedmiotu nazywanymi&nbsp; na podstawie analizy zachowań na polu walki min. przez dr Wigrama &rdquo;jastrzębiami&rdquo; (walczącymi) w przeciwieństwie do &bdquo;gołębi&rdquo; (padającymi) i &bdquo;kurczak&oacute;w&rdquo; (uciekającymi).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Aby zdyskredytować przede wszystkim morale nowych żołnierzy WOT w oczach publiki, skoncentrowano się na ich (rzekomych) finansowych motywacjach (służba jest płatna w kwocie 500 zł/mc). Elementem tej dyskredytacji było podawanie całkowicie fałszywych informacji dotyczących wykształcenia i braku zatrudnienia nowych rekrut&oacute;w.<span style="text-decoration:underline;" class="wixui-rich-text__text">[xii]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kolejnym aspektem budowania krytycznej narracji wobec WOT, było całkowite ignorowanie hybrydowego aspektu wsp&oacute;łczesnych wojen i jej wymiaru dezinformacyjnego w społeczeństwie. W tym sensie fakt, iż żołnierze są na co dzień osadzeni w społeczeństwie jest ogromnym atutem. I nie chodzi tu jedynie o możliwość bezpośredniego wykorzystania żołnierzy WOT do zatrzymywania np. prowokator&oacute;w na ulicach miast etc, ale ich &bdquo;potencjalność prewencyjną&rdquo; objawiającą się min. obecnością, czujnością&nbsp; i aktywnością w social mediach.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W aspekcie szkoleniowym, kt&oacute;ry oczywiście jest bardzo istotny, nie dostrzegano r&oacute;wnież faktu, iż proces pełnego szkolenia żołnierzy WOT będzie trwał 3 lata, zaś kadra dow&oacute;dczą będą stanowili żołnierze zawodowi, często najwyższej klasy, pochodzący r&oacute;wnież z elitarnych jednostek specjalnych. Zresztą ten ostatni atut, r&oacute;wnież starano się przekuć na słabość, zarzucając drenaż kadry wojsk specjalnych i operacyjnych. Choć w przypadku tych pierwszych dotyczyło to ok 40 os&oacute;b, co stanowiło ok 1% całego stanu. Tego typu zarzuty były kolejnym etapem dyskredytacji kompetencyjnej idącej w kierunku wzniecenia podział&oacute;w i dezintegracji w samym środowisku wojskowym, przeciwstawiając sobie żołnierzy wojsk operacyjnych i żołnierzy nowo powstającej formacji.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tym samym np. całkowicie ignorowano fakt, iż utrzymanie żołnierza WOT jest 6 razy tańsze od żołnierza wojsk operacyjnych i nie wpłynie na systematycznie powiększany budżet wojsk operacyjnych (kt&oacute;ry, m&oacute;wiąc nawiasowo,&nbsp; w przeszłości nigdy nie był wykorzystywany w 100% i część pieniędzy musiała z reguły wracać do budżetu etc.)</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W narracji tej r&oacute;wnież ignorowano oczywisty fakt, iż budowa WOT przyczyni się do rozwoju polskiego przemysłu obronnego, bo to bowiem właśnie w produkcji na wyposażenie lekkiej piechoty (min. karabiny, noktowizory, RPG, radiostacje, kamizelki kuloodporne etc. etc.) ma się czym chwalić. Nawet powstanie nowoczesnego karabinu MBDS &bdquo;Grot&rdquo; i duże zlecenie dla radomskiej fabryki &bdquo;Łucznik&rdquo;, starano się wykorzystać do dzielenia żołnierzy, poprzez wykazywanie, iż pierwszeństwo w otrzymaniu nowej partii karabin&oacute;w powinny mieć wojska operacyjne.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dyskredytacja ideologiczna</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kolejnym ważnym elementem krytycznej narracji wrog&oacute;w WOT była i do pewnego stopnia jest dyskredytacja historyczno - ideologiczna. W największym skr&oacute;cie w tego typu dyskredytacji chodzi o wykazanie, iż nawiązywanie do określonej tradycji jest złe, anachroniczne i koniec końc&oacute;w szkodliwe.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Temu min. miała służyć kampania szkalująca Żołnierzy Wyklętych, kt&oacute;rzy zostali patronami WOT. Prowadzona ona była wedle sprawdzonych w latach 40 i 50, sowieckich wzorc&oacute;w, oskarżających Wyklętych o min. o bandytyzm.<span style="text-decoration:underline;" class="wixui-rich-text__text">[xiii]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Podobnie rzecz się miała w przypadku legalnie działających organizacji społeczno - politycznych odwołujących się do spuścizny obozu narodowego takich jak ONR.&nbsp; W tym samym czasie podjęto zintensyfikowaną kampanię nawołująca do delegalizacji ONR i jednocześnie insynuacyjną, zmierzającą do wm&oacute;wienia odbiorcom przekazu, iż do WOT przyjmowani są (właściwie jedynie) radykalni członkowie organizacji narodowych (w podtekście &bdquo;faszystowskich&rdquo;)<span style="text-decoration:underline;" class="wixui-rich-text__text">[xiv]</span> , co jest niezgodne z prawem.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dyskredytacja (pseudo) prawna</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Aspekt rzekomego naruszania bądź naciągania prawa był r&oacute;wnież bardzo często w tej kampanii wykorzystywany. Takie działanie wiąże się z odwołaniem do zabiegu dyskredytacji (pseudo) prawnej, kt&oacute;ra ma na celu delegimityzację &bdquo;oskarżonego&rdquo; uczestnika gry w państwie demokratycznym poprzez implikowanie odbiorcom komunikat&oacute;w niebezpieczeństwa wynikającego z działań bezprawnych etc.&nbsp; Tego typu narrację uruchomiono zarzucając rządzącym i dow&oacute;dcom WOT bezpośrednie podporządkowanie MON, co jakoby było bezprawne i niekonstytucyjne (choć żaden przepis tego nie zabraniał). Tak jak wspomniałem, istotą tego zarzutu w wymiarze informacyjnym była tzw. erystyczna fabrykacja konsekwencji poprzez sugerowanie możliwości wykorzystania WOT do działań bezprawnych i &bdquo;samowolnych&rdquo; (w podtekście &bdquo;przestępczych&rdquo;) i tym samym wywołanie niepokoju wśr&oacute;d zwykłych obywateli.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Osobowa dyskredytacja charakterologiczna</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kolejnym elementem składowym szeroko zakrojonej kampanii dezinformacyjnej było skupienie się na konkretnych liderach projektu, przede wszystkim tw&oacute;rcy WOT, byłym szefie MON, Antonim Macierewiczu.&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dyskredytacja osobowa, jest często dopełnieniem dyskredytacji grupowej i bazuje na dość dużym poziomie personalizacji w postrzeganiu zjawisk/działań politycznych. W omawianym przypadku, mechanizm dyskredytacyjny sprowadza się do przeciągnięcia mniej lub bardziej realnych mankament&oacute;w osobowościowych lidera na całość projektu i doprowadzenie do postrzegania go przez ich pryzmat.&nbsp; Tendencyjna i złośliwa koncentracja na mankamentach, kt&oacute;re posiada każdy człowiek, przy odpowiednich warunkach i skali dezinformacji może doprowadzić do wykreowania jego całkowicie zafałszowanego wizerunku.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Budowanie czarnej legendy Antoniego Macierewicza&nbsp; rozpoczęło się jeszcze w czasach PRL&nbsp; w czasie jego aktywności opozycyjnej i trwało nieprzerwanie po &lsquo;89 roku w mediach gł&oacute;wnego nurtu, kontrolowanych przez środowiska postkomunistyczne. Istotą deformacji wizerunku Antoniego Macierewicza&nbsp; było przedstawienie takich koniecznych dla przyw&oacute;dcy cech jak energiczność, dynamizm, dobrze rozumiana &bdquo;sangwiniczność&rdquo;, zdecydowanie etc . w krzywym zwierciadle tj. jako bezrefleksyjna nadpobudliwość, brak wyobraźni etc.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ta czarna legenda została ze zdwojona siłą wykorzystana do dezinformacji podczas formowania WOT, bowiem z punktu widzenia dezinformujących była &bdquo;bardzo poręczna&rdquo;. Implikowała bowiem, iż w rekach człowieka od wielu lat negatywnie profilowanego jako &bdquo;ktoś niebezpieczny&rdquo;, znalazła się formacja zbrojna, co powinno wywołać niepok&oacute;j u odbiorc&oacute;w etc.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Potwierdzało to min. uporczywe powtarzanie w mainstrimie informacji o zagrożeniu użycia WOT przy tłumieniu manifestacji KOD.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dodatkowo, używając mechanizmu &bdquo;fabrykacji konsekwencji&rdquo; straszono &bdquo;dążeniem do wojny&rdquo; przyw&oacute;dztwa politycznego i dow&oacute;dztwa wojskowego na czele z gen.Kukułą. Te działania były wyjątkowo perfidne, chciałby bowiem (wykorzystując zjawisko paradoksu), przekonać, iż zwiększenie sił zbrojnych Polski de facto pogarsza jej bezpieczeństwo.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Swoistą wisienka na tym niesmacznym torcie było ukucie wobec piątej części PSZ określenia &bdquo;boj&oacute;wki Macierewicza&rdquo;. Istotą tej leksykalnej manipulacji było/jest zestawienie Wojska Polskiego z grupą stosującą terror polityczny/kryminalny oraz utożsamienie go z jedną osobą, w tym przypadku z ministrem Macierewiczem. Doprawdy trudno o bardziej perfidne działania koniec końc&oacute;w hańbiące ich (polskich?) autor&oacute;w.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Działania dywersyjne jako środek i cel dyskredytacji nowego przyw&oacute;dztwa wojskowego</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kolejna aktywnością (dez)informacyjną obliczoną na wprowadzenie podział&oacute;w, zamętu i obaw wśr&oacute;d Polak&oacute;w, były działania stymulujące podziały w polskiej armii. Powstanie WOT (kt&oacute;re przecież było koniecznym uzupełnieniem istniejących PSZ a nie ich zastąpieniem etc.) przedstawiano min. jako &bdquo;przekreślanie ostatnich 25 lat działań w sferze obronności Polski&rdquo; (w domyśle dorobku polskiej myśli wojskowej etc.). W polityce kadrowej zarzucano faworyzowanie młodszych oficer&oacute;w kosztem tych, kt&oacute;rzy zaczynali swoją służbę w PRL, a potem służyli Polsce na misjach w Iraku i w Afganistanie. Pr&oacute;bowano r&oacute;wnież wykorzystać pewne promocyjne skr&oacute;ty myślowe, kt&oacute;re trzeba stosować (z punktu psycho-technicznego zwłaszcza na bardzo ważnym etapie tworzenia formacji), aby wzmacniać morale etc. Słowa o &bdquo;walce ze Specnazem&rdquo; czy &bdquo;o najlepszej formacji wojskowej&rdquo; zostały wykorzystane do wyśmiewania (choć jako żywo WOT ma zadania przeciwdesantowe i konfrontacji ze Specnazem nie można wykluczyć), bądź dalszego dzielenia żołnierzy na lepszych i gorszych etc.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Druga faza dyskredytacji 2021-2022</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Okrzepnięcie formacji, kt&oacute;ra zyskała po kilku latach nie tylko swe zaplanowane zdolności, ze zdolnością bojową na czele, ale i zaufanie Polak&oacute;w, musiało wpłynąć na modyfikację sposob&oacute;w dezinformacji środowisk będących pod bezpośrednim wpływem Rosji i tych, kt&oacute;rzy wpisują się w jej narracje &bdquo;chcąc nie chcąc&rdquo;. W mniejszym zakresie, poza epigonami, kwestionowano samo rationale istnienia WOT-u, w większym zaś koncentrowano się na patologiach organizacyjnych takich jak rzekomy nepotyzm połączony z brakiem należytego finansowania &bdquo;prostego żołnierza&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[xv]</span>, wykorzystywanie żołnierzy do aktywności pozaregulaminowej czy nadużywanie swych kompetencji. Wszystkie te elementy oczywiście możemy przyporządkować&nbsp; do powyższej systematyki (dyskredytacja kompetencyjna, prawna etc), ale ujmuję je w tej części pracy, aby podkreślić jednak pewien rodzaj przeniesienia ciężkości przez dezinformator&oacute;w, kt&oacute;ry można by ująć (znajomo im brzmiącym skądinąd) hasłem: &bdquo;WOT tak, wypaczenia nie&rdquo;. Rok 2021 obfitował tu w prawdziwy wysyp pseudo faktograficznych publikacji, napisanych dodatkowo niezgodnie ze sztuką dziennikarską (m.in. brak prośby o odniesienie się do zarzut&oacute;w &bdquo;bohater&oacute;w&rdquo; artykułu przed publikacją etc.). Prym, tak jak przed laty, wi&oacute;dł w tym procederze portal Onet.pl. Do jego &bdquo;rewelacji&rdquo; odnosiły się służby prasowe WOT kilkukrotnie.<span style="text-decoration:underline;" class="wixui-rich-text__text">[xvi]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text">[xvii]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text">[xviii]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Podsumowanie</p>
</li>
</ol></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Podkreślmy raz jeszcze, iż&nbsp; budowa ochotniczego i terytorialnego&nbsp; komponentu sił zbrojnych jest sprawdzonym modelem funkcjonującym w większości kraj&oacute;w o wysokiej kulturze wojskowej (jak USA, WB czy Szwecja etc.). Zalety istnienia takich formacji w systemie bezpieczeństwa państwa są wielowektorowe i bezsporne. Po pierwsze i najważniejsze, grupują dość wysokiej klasy rekruta z pożądanymi predyspozycjami i wysokim morale, po (ii) są względnie nisko kosztowym uzupełnieniem wojsk operacyjnych mając jednocześnie bardzo ważną funkcję zabezpieczenia 2 -3 linii frontu, po (iii) znają r&oacute;wnież sw&oacute;j teren i mogą być wykorzystani do działań przeciwdywersyjnych (oraz dywersyjnych w przypadku okupacji terenu), po (iv) ich codzienna obecność wśr&oacute;d cywili/społeczeństwa nie tylko może się pozytywnie przyczyniać do wymiany doświadczeń między tymi dwoma światami (co ma walory edukacyjne), ale tworzy swoistą 50 tysięczna armię przeciw dywersyjna w sieci oraz przyczynia się do wzmacniania patriotycznego morale, co nie jest bez znaczenia wobec zmasowanych kampanii dezinformacyjnych, będących najczęściej elementem wojny hybrydowej prowadzonej przez Rosjan. Tego ostatniego elementu z całą pewnością nie można lekceważyć, pamiętajmy chociażby o słowach Marszałka Piłsudskiego &bdquo;Do obrony granic państwa społeczeństwo winno dać przede wszystkim to, co w języku wojennym nazywa się morale&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Z faktu zaś, iż na etapie formowania (&bdquo;faza wieku dziecięcego&rdquo;) &bdquo;sytuacja jest dynamiczna&rdquo; m&oacute;wiąc kolokwialnie, nie należy wyciągać wniosk&oacute;w przekreślających całą formację. A o kondycji WOT oczywiście warto rozmawiać i ją analizować. Ale nie w spos&oacute;b w przewrotny. Np. często w (pseudo) merytorycznych analizach podnosi się zarzut, iż WOT ma problemy z retencją żołnierzy.&nbsp; Choć dane na ten temat są tajne, należy faktycznie domniemywać, iż w formacji mogą występować pewne fluktuacje. Ale jest to zjawisko zrozumiałe i całkowicie naturalne. Z jednej strony, część nowych żołnierzy, &bdquo;zasmakowawszy w wojaczce&rdquo; decyduje się na przejście na zawodowstwo, do wojsk operacyjnych.&nbsp; Z drugiej zaś, część przekonuje się, iż trudy wojaczki są nie dla nich i że dokonali swoistego przeszacowania swoich możliwości. Dodatkowo, mogą dochodzić tu kwestie zawodowe i prywatne (zdrowotne, rodzinne etc), kt&oacute;re faktycznie uniemożliwiają efektywne stawiennictwo w jednostkach. Niemniej, podstawowe przeszkolenie&nbsp; wojskowe jakie uzyskują takie osoby i powiększenie bazy rezerwy WP, ma przecież swoje znaczenie w kontekście braku powszechnej służby wojskowej.&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ale opr&oacute;cz analizy tego relatywnego, zwłaszcza zważywszy na (dez) informacyjne &bdquo;okoliczności przyrody&rdquo;, success story, nasza uwaga w myśleniu o polskiej wojskowości powinna być r&oacute;wnież skierowana na przeszłość, tak aby lepiej zrozumieć pewne jej uwarunkowania i mechanizmy. Dzięki temu łatwiej będzie nam wyciągnąć wnioski na przyszłość.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tym samym, szczeg&oacute;łowej analizy wymaga okres w kt&oacute;rym nie dochodziło do powstania WOT. Co najmniej od 2008 roku (napaść Rosji na Gruzję) było jasne, iż &bdquo;Imperium kontratakuje&rdquo; i będzie to robić coraz agresywniej. Zwłaszcza zaś okres 2013-2015, kiedy na skutek hybrydowej wojny na Ukrainie doszło do &bdquo;zmiany zasad gry&rdquo; (game changing) powinien uruchomić proces, tym bardziej , że już wtedy silnie rozwijał się oddolny ruch proobronny. Nie stało się to jednak, zaś Polacy musieli czekać na zmianę władzy i rok 2016, aby proces formacji ruszył. Czy w latach 2008-2015 były to kwestie związane z brakiem wizji strategicznej? Kompetencji zarządczych &oacute;wczesnego leadershipu politycznego i wojskowego, braku elastyczności i otwartości na nowe wyzwania? Czy też może braku zabezpieczenia finansowego? Tak czy inaczej, brak decyzyjności w tym okresie musi zastanawiać i musi być dla dobra wsp&oacute;lnego wyjaśniony.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Szczeg&oacute;łowo przeanalizowana natomiast musi być kampania dezinformacyjna wymierzona w WOT w latach 2016-2022, szkody bowiem jakie przyniosła (a właściwie przynosi,&nbsp; choć szczęśliwie na skutek kolejnej napaści Rosji na Ukrainę, znalazła się w fazie &bdquo;pauzy operacyjnej&rdquo;)&nbsp; są znaczne. Bez wątpienia, zgodnie z prawidłami masowej komunikacji społecznej, podawanie nieprawdziwych informacji w wysokonakładowych mediach (Onet.pl, GW, Polityka, NIE, OkoPress etc) musiało mieć wpływ na skalę akcesji (i być może retencji) Polak&oacute;w do V rodzaju Sił Zbrojnych WP. Tym samym uprawnionym wydaje się wniosek , iż było to działanie osłabiające potencjał Polskich Sił Zbrojnych, co ma swoją szczeg&oacute;lną wagę w kontekście toczącej się obecnie przy naszej granicy wojnie.&nbsp; Na marginesie, można roboczo założyć, iż gdyby te wysokonakładowe media od początku zachęcały Polak&oacute;w do wstępowania do WOT, ambitne liczbowe plany z 2016 roku (osiągnięcie ok 50 tys. żołnierzy w 2022 r.) mogłyby zostać zrealizowane.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jedno jest jednakowoż pewne. Nie zatrzymała ona dalszego rozwoju WOT i rozszerzania akceptacji społecznej dla szybkiej odbudowy polskiej armii.&nbsp; Pozostaje wszakże wiele dalszych pytań, na kt&oacute;re warto dla dobra publicznego znaleźć odpowiedź. Przede wszystkim, jak to jest możliwe, iż trwała ona tak długo, choć wspomniane pozytywy związane z powstaniem WOT (obronne, społeczne, ekonomiczne etc. etc.) były przecież oczywiste dla wszystkich znających podstawową problematykę wojskową i założenia koncepcji antydostępowej? I co tak wymiernie zostało potwierdzone na Ukrainie przez ukraińską WOT po 24.02.2022 r.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wreszcie, zwłaszcza patrząc na kierunki ataku, warto na poważnie rozważyć na ile budowane formacji (niepodległościowej i silnie osadzonej w polskiej społeczności cywilnej) w oparciu o etos Żołnierzy Niezłomnych (czy szerzej tradycji polskiej irredenty mającej historycznie antyrosyjską tradycję) mogło być ważnym czynnikiem indolencji i p&oacute;źniejszej niebywałej niechęci do rozwoju V części Polskich Sił Zbrojnych. Nadaktywność środowisk postkomunistycznych<span style="text-decoration:underline;" class="wixui-rich-text__text">[xix]</span> <span style="text-decoration:underline;" class="wixui-rich-text__text">[xx]</span> w PRL &ndash; owskiej przeszłości przecież ściśle kooperujących z sowiecką Rosją, oraz &bdquo;liberalnych&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[xxi]</span> w opisanej kampanii dezinformacyjnej na to wskazuje. Wskazuje jednak r&oacute;wnież na to, jak bardzo historyczne i antyniepodległościowe resentymenty wpływają negatywnie na wsp&oacute;łczesne bezpieczeństwo Polski i Polak&oacute;w.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[i]</span><span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://terytorialsi.wp.mil.pl/" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://terytorialsi.wp.mil.pl/</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[ii]</span><a data-auto-recognition="true" href="https://www.cbos.pl/PL/publikacje/news/newsletter_ver3.php?news_r=2022&amp;news_nr=19" target="_blank" class="wixui-rich-text__text">https://www.cbos.pl/PL/publikacje/news/newsletter_ver3.php?news_r=2022&amp;news_nr=19</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[iii]</span><a data-auto-recognition="true" href="https://www.pap.pl/aktualnosci/news%2C1485053%2Cdowodca-wot-nigdy-nie-zawiodlem-sie-na-swoich-zolnierzach.html" target="_blank" class="wixui-rich-text__text">https://www.pap.pl/aktualnosci/news%2C1485053%2Cdowodca-wot-nigdy-nie-zawiodlem-sie-na-swoich-zolnierzach.html</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[iv]</span><a data-auto-recognition="true" href="https://www.pap.pl/aktualnosci/news%2C1485053%2Cdowodca-wot-nigdy-nie-zawiodlem-sie-na-swoich-zolnierzach.html" target="_blank" class="wixui-rich-text__text">https://www.pap.pl/aktualnosci/news%2C1485053%2Cdowodca-wot-nigdy-nie-zawiodlem-sie-na-swoich-zolnierzach.html</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[v]</span><a data-auto-recognition="true" href="https://www.gov.pl/web/obrona-narodowa/niezawodna-pomoc-do-6-tysiecy-terytorialsow-bedzie-niesc-pomoc-uchodzcom-z-ukrainy" target="_blank" class="wixui-rich-text__text">https://www.gov.pl/web/obrona-narodowa/niezawodna-pomoc-do-6-tysiecy-terytorialsow-bedzie-niesc-pomoc-uchodzcom-z-ukrainy</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[vi]</span><a data-auto-recognition="true" href="https://media.terytorialsi.wp.mil.pl/informacje/734737/zolnierze-wot-cisi-bohaterowie-trudnego-czasu-i-wielkiej-proby-spolecznej-solidarnosci-podsumowanie-operacji-odporna-wiosna-i-trwala-odpornosc" target="_blank" class="wixui-rich-text__text">https://media.terytorialsi.wp.mil.pl/informacje/734737/zolnierze-wot-cisi-bohaterowie-trudnego-czasu-i-wielkiej-proby-spolecznej-solidarnosci-podsumowanie-operacji-odporna-wiosna-i-trwala-odpornosc</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[vii]</span><a data-auto-recognition="true" href="https://www.pap.pl/aktualnosci/news%2C1485053%2Cdowodca-wot-nigdy-nie-zawiodlem-sie-na-swoich-zolnierzach.html" target="_blank" class="wixui-rich-text__text">https://www.pap.pl/aktualnosci/news%2C1485053%2Cdowodca-wot-nigdy-nie-zawiodlem-sie-na-swoich-zolnierzach.html</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[viii]</span><a data-auto-recognition="true" href="https://www.pap.pl/aktualnosci/news%2C1485053%2Cdowodca-wot-nigdy-nie-zawiodlem-sie-na-swoich-zolnierzach.html" target="_blank" class="wixui-rich-text__text">https://www.pap.pl/aktualnosci/news%2C1485053%2Cdowodca-wot-nigdy-nie-zawiodlem-sie-na-swoich-zolnierzach.html</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[ix]</span><a data-auto-recognition="true" href="https://wiadomosci.dziennik.pl/opinie/artykuly/551315,wieslaw-kukula-wot-obrona-terytorialna-rigamonti-rozmowa.html" target="_blank" class="wixui-rich-text__text">https://wiadomosci.dziennik.pl/opinie/artykuly/551315,wieslaw-kukula-wot-obrona-terytorialna-rigamonti-rozmowa.html</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[x]</span><a data-auto-recognition="true" href="https://www.fakt.pl/polityka/wieslaw-kukula-wyjasnia-strategie-wojsk-obrony-terytorialnej/8byt58x" target="_blank" class="wixui-rich-text__text">https://www.fakt.pl/polityka/wieslaw-kukula-wyjasnia-strategie-wojsk-obrony-terytorialnej/8byt58x</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xi]</span><a data-auto-recognition="true" href="https://echodnia.eu/swietokrzyskie/swietokrzyscy-terytorialsi-na-podium-grotowiska-2022-zobacz-zdjecia/ar/c1-16424813" target="_blank" class="wixui-rich-text__text">https://echodnia.eu/swietokrzyskie/swietokrzyscy-terytorialsi-na-podium-grotowiska-2022-zobacz-zdjecia/ar/c1-16424813</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xii]</span><a data-auto-recognition="true" href="https://www.polityka.pl/tygodnikpolityka/spoleczenstwo/1770990,1,kosztowne-wojska-obrony-terytorialnej.read" target="_blank" class="wixui-rich-text__text">https://www.polityka.pl/tygodnikpolityka/spoleczenstwo/1770990,1,kosztowne-wojska-obrony-terytorialnej.read</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xiii]</span><a data-auto-recognition="true" href="https://wpolityce.pl/historia/541270-lewacy-szargaja-pamiec-o-zolnierzach-wykletych-wideo" target="_blank" class="wixui-rich-text__text">https://wpolityce.pl/historia/541270-lewacy-szargaja-pamiec-o-zolnierzach-wykletych-wideo</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xiv]</span><a data-auto-recognition="true" href="https://oko.press/onr-front-nacjonaliscie-mozna-dac-karabin" target="_blank" class="wixui-rich-text__text">https://oko.press/onr-front-nacjonaliscie-mozna-dac-karabin</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xv]</span><a data-auto-recognition="true" href="https://media.terytorialsi.wp.mil.pl/informacje/665898/oswiadczenie-rzecznika-prasowego-wot" target="_blank" class="wixui-rich-text__text">https://media.terytorialsi.wp.mil.pl/informacje/665898/oswiadczenie-rzecznika-prasowego-wot</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xvi]</span><a data-auto-recognition="true" href="https://media.terytorialsi.wp.mil.pl/informacje/671863/oswiadczenie-oficera-prasowego-7pbot" target="_blank" class="wixui-rich-text__text">https://media.terytorialsi.wp.mil.pl/informacje/671863/oswiadczenie-oficera-prasowego-7pbot</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xvii]</span><a data-auto-recognition="true" href="https://media.terytorialsi.wp.mil.pl/informacje/473577/stanowisko-dowodztwa-wot-do-artykulu-tygodnika-newsweek" target="_blank" class="wixui-rich-text__text">https://media.terytorialsi.wp.mil.pl/informacje/473577/stanowisko-dowodztwa-wot-do-artykulu-tygodnika-newsweek</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xviii]</span><a data-auto-recognition="true" href="https://media.terytorialsi.wp.mil.pl/informacje/711020/oswiadczenie" target="_blank" class="wixui-rich-text__text">https://media.terytorialsi.wp.mil.pl/informacje/711020/oswiadczenie</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xix]</span><a data-auto-recognition="true" href="https://twitter.com/AM_Zukowska/status/1464211904533041156" target="_blank" class="wixui-rich-text__text">https://twitter.com/AM_Zukowska/status/1464211904533041156</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xx]</span><a data-auto-recognition="true" href="https://twitter.com/__lewica/status/1215352369132777472" target="_blank" class="wixui-rich-text__text">https://twitter.com/__lewica/status/1215352369132777472</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[xxi]</span><a data-auto-recognition="true" href="https://www.pap.pl/aktualnosci/news%2C663581%2Cszef-mon-wybor-trzaskowskiego-na-prezydenta-prosta-droga-do-likwidacji-wot?fbclid=IwAR20SAu0WjBE_RwN_EoEwekDY85dkPTTWGDQzuhtip-ZEKXICp4AJSuuiFI" target="_blank" class="wixui-rich-text__text">https://www.pap.pl/aktualnosci/news%2C663581%2Cszef-mon-wybor-trzaskowskiego-na-prezydenta-prosta-droga-do-likwidacji-wot?fbclid=IwAR20SAu0WjBE_RwN_EoEwekDY85dkPTTWGDQzuhtip-ZEKXICp4AJSuuiFI</a></p></div></div></div></div></div></section></div></div></section>




    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
@endsection
