
@extends('layouts.app')

@section('title', 'Home - Kevix Template')

@section('content')

<body>
    <section class="blog-details-home section" id="home">
        <div class="bg-overlay"></div>
        <div class="home-center">
            <div class="home-desc-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">

                    <div class="blog-info p-3">
                        <h2 class="text-dark mb-3">Dr Piotr Balcerowski</h2>

                        <div class="blog-info-desc">
                            <p style='text-align: justify;'>


<span style="font-weight:bold;" class="wixui-rich-text__text">O pojęciu Nacjonalizm. Wprowadzenie. Część I</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text"><span class="wixGuard wixui-rich-text__text">​</span></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">I. Wstęp</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;Naprawę państwa należy zacząć od naprawy pojęć&rdquo; - Konfucjusz</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;[Wsp&oacute;łcześnie]zmienił się w potocznym języku status słowa &bdquo;nacjonalizm&rdquo;. Przed wojną było to normalne samookreślenie się polityczne, kt&oacute;re ktoś m&oacute;gł przyjmować lub nie, ale nikogo ono nie dziwiło, ani z założenia nie gorszyło. Dzisiaj natomiast słowo nacjonalizm stało się bad term, oskarżeniem, desygnacją wroga publicznego (hostis) i wykluczeniem. I to trzeba zmienić, przywr&oacute;cić mu neutralny sens i status &ndash; prof. Władysław Bartyzel</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W poniższym tekście podzielonym na dwie gł&oacute;wne części, będę chciał zarysować historię pojęcia narodowości i nacjonalizmu oraz spr&oacute;bować ująć w ramy teoretyczne to, co sprzyja rozwojowi narodu. A contrario, w drugiej części, będę chciał przedstawić gł&oacute;wne czynniki niesprzyjające jego trwaniu i rozwojowi. Ten zarys myśli jest wprowadzeniem do szerszych badań zjawiska, kt&oacute;re planujemy badać i opisywać na łamach CASN.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tytułem wstępu i w największym skr&oacute;cie najconalizm jest przede wszystkim doktryną polityczną, kt&oacute;ra choć niedoskonała, w najlepszy spos&oacute;b przyczynia się do urzeczywistnienia fundamentalnych cel&oacute;w każdej wspolnoty politycznej, tj. sprawiedliwości, efektywności/dobrobytu, harmonii i jak dodają wierzący nacjonaliści, &bdquo;chwały bożej&rdquo;, składających się na dobro wsp&oacute;lne. Wedle założeń dokrtyny nacjonalistycznej nie można skutecznie go realizować nie opierając się na konkretnym (&bdquo;spokrewnionym&rdquo; m&oacute;wiąc prof. Konecznym czy prof. Wolniewiczem) etnosie połączonym &bdquo;wsp&oacute;lną pamięcią, ziemią, językiem i wiarą&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wsp&oacute;łcześnie, na skutek aktywności &bdquo;liberalno-demokratycznych&rdquo; (a wcześniej komunistycznych) sił politycznych, nacjonalizm jest dyskredytowany przede wszystkim na trzech polach. Primo, jako &bdquo;groźny&rdquo;, w swej najłagodniejszej wersji &bdquo;zatruwający wsp&oacute;lnotę nienawiścią&rdquo;, zaś najostrzejszej przygotowujący do Holocaustu 2.0. Secundo, jako nieatrakcyjny intelektualnie i moralnie (wsteczny, zakłamany, antychrześcijański, nieprzyjazny etc.). Tertio, pośrednio w konsekwencji poprzedniego, jako antykreatywny, demotywujacy do rozwoju, r&oacute;wnież dobrobytu etc. Obszar&oacute;w dyskredytacji jest naturalnie więcej, niemniej są one de facto podgrupami trzech gł&oacute;wnych pseudoargument&oacute;w, z pewnymi wyjątkami oczywiście. O nich więcej napiszę w rozwinięciu tej pracy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tymczasem, pragnę jeszcze zwr&oacute;cić uwagę na zjawisko &bdquo;przesunięcia pojęć&rdquo;, kt&oacute;re będę rozwijał w tekście. Jak wiemy od Arystotelesa, każdy z modelowych ustroj&oacute;w (monarchia, arystokracja, demokracja) posiada swe zwyrodnienia. Mądry i sprawiedliwy monarcha może &bdquo;zwyrodnieć&rdquo; stając się despotycznym tyranem, &bdquo;rządy najlepszych&rdquo; mogą przekształcić się w rządy oligarchiczne zaś rządy statecznego ludu w rządy tłumu. Nie inaczej jest z nacjonalizmem, nawet jeśli jest on zagadnieniem z pogranicza ideii i doktryny a nie formą ustrojową sensu stricte. Zwyrodniałą formą nacjonalizmu jest szowinizm, kt&oacute;ry faktycznie żywi się przede wszystkim nienawiścią do innych zamiast miłością do swojej kultury i potencjał&oacute;w. Szowinizm ma też &bdquo;swoje na sumieniu&rdquo; w postaci choćby kolonialnego podboju tudzież zbrodniczego nazizmu, ale nie jest to doświadczenie polskie (chyba że w roli ofiary). Takie manipulacyjne przesunięcie semiotyczne jest co do zasady nieuprawnione, w szczeg&oacute;lności w polskim kontekście nie tylko ze względu na wspomniany fakt doświadczenia szowinizmu niemieckiego i rosyjskiego (a pośrednio żydowskiego), ale r&oacute;wnież ze względu na szczeg&oacute;lny katolicki rys polskiego nacjonalizmu.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W każdym razie, analizując wsp&oacute;łcześnie poszczeg&oacute;lne (successful) case studies, można odnieść wrażenie, iż nacjonalizm zachowuje swą żywotność, tyle, że jest dość ekskluzywny, rzec by można, &bdquo;dla wybranych&rdquo;, kt&oacute;rzy dają sobie prawo i nie widzą nic wstecznego i niepokojącego w tym, aby określona grupa ludzi sub sole, w swej zdecydowanej większości pośrednio powiązana &bdquo;więzami krwi&rdquo;, o podobnym kolorze sk&oacute;ry etc., chce żyć tak, jak wyraził to przedstawiciel narodu żydowskiego Beniamin Netanjahu: &bdquo;Żydzi to jedyny nar&oacute;d żyjący w kraju nazywającym się tak samo jak 3000 lat temu, na tych samych ziemiach, z tym samym językiem i z tą samą wiarą&rdquo; nakreślając tym samym bardzo podstawowe wymogi dotyczące funkcjonowania narodowej wsp&oacute;lnoty.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zaś jego rodak, znany dość dobrze w Polsce dr Lejba Fogelman tak w sumie tw&oacute;rczo i pięknie idee nacjonalizmu (żydowskiego) rozwinął m&oacute;wiąc w programie <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.youtube.com/watch?v=kiORY1Sfy40&embeds_referring_euri=https%3A%2F%2Fwww.salon24.pl%2F&feature=emb_imp_woyt" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">&bdquo;Jank&amp;Kozak&quot;&nbsp;</a></span>m.in.: &bdquo;Jestem Żydem przede wszystkim. To jest to czym ja jestem w świecie...Bycie Żydem to jest wszystko, to jest światopogląd, to jest jakby wsp&oacute;lnota pamięci, wsp&oacute;lnota przeznaczenia, wsp&oacute;lnota celu (&hellip;) Przynależność narodowa jest bardzo ważna (&hellip;)&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W tej z wielu względ&oacute;w bardzo interesującej poznawczo rozmowy (&bdquo;co myśmy musieli tyle lat robić bez w&oacute;dki...&rdquo;), kt&oacute;rej wysłuchanie wszystkim polecam, opr&oacute;cz w/w wsp&oacute;lnot będących paliwem dla zbożnego nacjonalizmu, wysłuchujemy jeszcze szereg innych zdroworozsądkowych i potrzebnych nam do dzisiejszych rozważań uwag, takich jak: &bdquo;Uważam że społeczeństwa nie są w stanie funkcjonować dobrze bez kolektywnego etosu, jeżeli nie jest on internalizowany przez odpowiednią ilość ludzi, a ten kolektywny etos to jest ta kultura, ta świadomość (narodowa &ndash; PB). Bez tego nie da się dobrze zorganizować społeczeństwa bo inaczej trzeba rządzić autorytarnie....kapitał ma narodowość, bo ten kapitał do kogoś przynależy. A ten do kogo przynależy myśli w taki czy inny spos&oacute;b, ma takie zachowania czy lojalności...&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">II. Geneza i definicja narodu. &bdquo;Tak, Polska dla Polak&oacute;w! A dla kogo innego?&rdquo; - prof. JM Chodakiewicz</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Bezpośrednim impulsem do napisania tej pracy była środowiskowa styczność z jednym z antynarodowych &bdquo;argument&oacute;w&rdquo; z grupy wyjątkowej, o kt&oacute;rej wspominałem wcześniej. Nazywam je roboczo typowo &bdquo;hagadowymi&rdquo;. Ot&oacute;ż grupa znajomych, z przejęciem godnym innej sprawy, przekownywała mnie, iż nar&oacute;d polski to stosunkowo &bdquo;bardzo młode zjawisko&rdquo;. I jeszcze na początku XX wieku, jakby zapytać statystycznego włoscianina jakiej jest narodowości to...Jednocześnie tym zapewnieniem towarzyszyły tylko lekko ukrywane sentymenty do narodu, znaczy się narod&oacute;w, mających 3000 lat. W tym przykładzie żadnych wątpliwości nie odnotowano, narody te naturalnie &bdquo;od zawsze&rdquo; spełniały wszystkie wsp&oacute;łczesne kryteria zaś wszelkie wątpliwości (jak chociażby niemały dorobek intelektualny diaspory w USA z przełomu XX w. gromadzący na użytek bieżącej polityki amerykańskiej argumentację, iż w skr&oacute;cie &bdquo;żydowskość to wyznanie, nie narodowość&rdquo; a zatem nie mogą być traktowani jak mniejszośc narodowa etc) były w dyskusji skrzętnie pomijane.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ten rodzaj (pseudo)argumentu, z grupy wyjątkowej (nie utożsamiającej nardowości jako złej w samej sobie) nazwałbym roboczo argumentum ad puerillis względnie argumentum ad artificium czyli de facto zabiegiem erystycznym odwołującym się do pozbawienia przeciwnika zakorzenienia, odwołania do długiej tradycji będącej źr&oacute;dłem siły. Na niewypowiedzianym wprost mniemaniu, iż do narodowości to może maja prawa wybrani, ale przecie nie takie ahistoryczne &bdquo;byle co&hellip;&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">I o ile proces wykształcania się narod&oacute;w europejskich i doktryny nacjonalistycznej jest faktycznie procesem złożonym i długotrwałym (najciekawiej zagadnienie jest opisane w polskiej politologii przez prof. Jacka Bartyzela i Adama Wielomskiego) i niestety nie miejsce tu na opisanie całej tej złożoności, z cała pewnością, m&oacute;wiąc tym pierwszym, &bdquo;kilka pokoleń nacjonalist&oacute;w było nimi faktycznie, nie wiedząc o tym&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wsp&oacute;łcześnie przyjęło się, iż o nacjonalizmie m&oacute;wi się od czas&oacute;w rewolucji (anty) francuskiej. Dla mnie jest to o tyle ścisłe, o ile dotyczy kryterium masowości tj. zniesienia (przynajmniej nominalnie) ograniczenia w życiu politycznym. Ale z faktu, iż z czasem to krwawe wydarzenie doprowadziło do upodmiotowienia mas, nie można wyciągać wniosku, iż do wykształcania się podstaw narodu nie dochodziło znacznie wcześniej, przed wiekami. Np. przecież z faktu, iż młody, 18 letni Żyd w X wieku, nie miał &bdquo;prawa wyborczego&rdquo; do wyboru rabina czy władz swojej wsp&oacute;lnoty, nie wynika jeszcze, iż przestawał być Żydem. W Polsce, choć p&oacute;źniej od czas&oacute;w antycznych, historyczny nar&oacute;d w sensie politycznym dotyczył (podobnie jak na &bdquo;całym cywilizowanym świecie&rdquo;) po prostu węższej grupy, elity tj. szlachty. Ale wymiar polityczny nie był przecież jedynym dla kształtowania się narodu, to jest grupy ludzi mieszkających na ziemiach polskich od dziada pradziada, katolik&oacute;w, emocjonalnie związanych jeśli nie z całym krajem to na pewno z własna ziemią i co bardzo ważne dla naszych rozważań, organizujących swoje wyobrażenie o życiu społecznym w oparciu o katolicka antropologię i tym samym odpowiedzialnych za swoją rodzinę i najbliższą wsp&oacute;lnotę. Tak o tych procesach pisze prof. Chodakiewicz &bdquo;sama koncepcja wywodzi się co najmniej z antyku. Biblia jest naszym punktem odniesienia, B&oacute;g stworzył bowiem plemienia i narody. A potem w średniowieczu wykształcił się nar&oacute;d historyczny, czyli w polskim (czy węgierskim) kontekście &ndash; rycerstwo, szlachta.&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Słusznym zatem wydaje się odwoływanie do kategorii narodu w najszerszym jego rozumieniu w związku z dwoma fundamentalnymi wydarzeniami dla jego formacji tj. przyjęcia Chrztu Polski oraz koronacji pierwszego kr&oacute;la Polski, jak czynił to chociażby święty in spe kardynał tysiąclecia Stefan Wyszyński, kiedy w 1966 roku m&oacute;wił: &bdquo;Dla nas po Bogu, największa miłość to Polska! Musimy po Bogu dochować wierności przede wszystkim naszej Ojczyźnie i narodowej kulturze polskiej. Będziemy kochali wszystkich ludzi na świecie, ale w porządku miłości. Po Bogu więc, po Jezusie Chrystusie i Matce Najświętszej, po całym ładzie Bożym, nasza miłość należy się przede wszystkim naszej Ojczyźnie, mowie, dziejom i kulturze, z kt&oacute;rej wyrastamy na polskiej ziemi. I chociażby obwieszczono na transparentach najrozmaitsze wezwania do miłowania wszystkich lud&oacute;w i narod&oacute;w, nie będziemy temu przeciwni, ale będziemy żądali, abyśmy mogli żyć przede wszystkim duchem, dziejami, kulturą i mową naszej polskiej ziemi, wypracowanej przez wieki życiem naszych praojc&oacute;w.&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Odnośnie zaś koronacji, podobnież uchwyca istotę rzeczy nasz święty in spe, kiedy m&oacute;wi &bdquo;Przypomina mi się tak wspaniale przedstawiony w powieści Gołubiewa &bdquo;Bolesław Chrobry&rdquo; i Parnickiego &bdquo;Srebrne orły&rdquo; fragment. Oto cesarz Otto III kusi Bolesława Chrobrego, czyni go patrycjuszem rzymskim i chce go ściągnąć do Rzymu. Ale kr&oacute;l nie dał się wyciągnąć z Polski, z ubogiego Gniezna, na forum rzymskie. Został w swoim kraju, bo był przekonany, że jego zadanie jest tutaj. Naprz&oacute;d umocnić musi swoją ojczyznę, a gdy to zrobi, pomyśli o innych, o sąsiadach.&rdquo; Choć oferta chyba jednak była jedynie fikcją literacką, to jeśli popatrzeć na fakty historyczne, to przecież koronacja Chrobrego niejako wbrew Cesarzowi, miała swe źr&oacute;dła w faworyzowaniu przez tego ostatniego swoich ziomk&oacute;w, zamieszkujących strony cesarskie, m&oacute;wiących w języku cesarza, ludzi &bdquo;innej narodowości&rdquo;. Te okoliczności wyrażają istotę rzeczy konstytutywną dla powstania narodu polskiego tj samostanowienia. Tak o tym fenomenie pisał prof. Chodakiewicz &bdquo;Samostanowienie narod&oacute;w napędza nacjonalizm. Bez tego nie ma impulsu, aby uznać, że wolność czy niepodległość zbiorowości zwanej &bdquo;narodem&rdquo; jest warunkiem sine qua non, aby taki byt istniał i prosperował. Nar&oacute;d jako organizacja nie ma sensu bez masowego poparcia dla takiego bytu. Nacjonalizm jest bowiem ideologią kolektywistyczną. Oznacza organizację społeczeństwa według zasady wsp&oacute;lnoty języka, obszaru geograficznego, kultury, religii i historii. Nacjonalizm uzewnętrznia się przekonaniem, że ze wsp&oacute;lnoty tradycji, instytucji i wierzeń wynika pewna możliwa do zdefiniowania wsp&oacute;lnota interes&oacute;w. Zapewni ona harmonijny rozw&oacute;j wewnętrzny narodu, chociaż nie musi być przyczyną konfliktu zewnętrznego z narodem ościennym.&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jednocześnie taki impuls ideowy jest w stanie wytworzyć ustr&oacute;j społeczny, kt&oacute;ry jest ustrojem umiarkowanie indywidualistycznym, merytokratycznym i hierarchicznym. Ale jednocześnie sprzyja sp&oacute;jności i jednolitości kulturowej i etnicznej społeczeństwa. W takim społeczeństwie klasy społeczne mogą wsp&oacute;łżyć względnie harmonijnie istnieją bowiem dodatkowe mechanizmy ograniczające skrajny indywidualizm członk&oacute;w elity. Silna tendencja do tworzenia tego typu społeczeństw istniała na zachodzie przynajmniej od średniowiecza, choć wiele jego element&oacute;w można odnaleźć już w klasycznych cywilizacjach, jak np. republika rzymska. Od schyłku cesarstwa rzymskiego ideał hierarchicznej harmonii jest rdzeniem programu społecznego Kościoła Katolickiego i w najwyższej postaci został urzeczywistniony w średniowieczu, r&oacute;wnież w Polsce.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Podsumujmy zatem najważniejsze kwestie. Początek rozwoju narodu polskiego i idei porządkującej jego rozw&oacute;j tj. nacjonalizmu a tym samym proces rozwoju polskiej narodowości jest ściśle powiązany z chrztem Polski i powstaniem państwowości polskiej, kt&oacute;re wsp&oacute;łkształtowała ludzi znad Wisły do tego stopnia, iż postanowili być Polakami bez suwerennej państwowości i będąc poddawanym szykanom religijnym. I choć nar&oacute;d taki nie był etniczny (w sensie najściślejszym, bowiem w szerszym ujęciu jednak zbliżał ludzi z bliskich sobie okolic geograficznych i w pewnym sensie kulturowych &ndash; Gente Ruthenus, natione Polonus), zaś tylko jego część miała prawa i przywileje polityczne, możemy przyjąć, iż w całym kr&oacute;lestwie do pewnego stopnia, każdy mieszkaniec historycznej Polski identyfikował się z podobnymi sobie (zwłaszcza w wymiarze religijnym) oraz z monarchą jako emanacją i symbolem systemu.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Brak monarchy i państwowości polskiej przez ponad wiek tylko potwierdził siłę tej identyfikacji. Determinacja w jej utrzymaniu wynikała nie tylko z sentyment&oacute;w, ale r&oacute;wnież z przekonania, iż model w kt&oacute;rym rządzą daną wsp&oacute;lnotą ludzie organicznie z nią związani, nie zaś niejako przysłani z zewnątrz jest dla wsp&oacute;lnoty najlepszy. Jest zgodny z porządkiem rzeczy, zdrowym rozsądkiem, zaś wierzący dodaliby i wolą Boga. Skoro przy Bogu jesteśmy raz jeszcze oddajmy głos kard. Wyszyńskiemu, kt&oacute;ry tak ujmował kwestię pomyślności nas wszystkich: &bdquo;Jakże wielka jest więc odpowiedzialność za nasze miejsce tutaj i za wypełnienie wszystkich obowiązk&oacute;w, kt&oacute;re ciążą dziś na Narodzie polskim. Abyśmy jednak mogli wypełniać swoje zadania, niezbędna jest suwerenność narodowa, moralna, społeczna, kulturalna i ekonomiczna! Każdy Nar&oacute;d pracuje przede wszystkim dla siebie, dla swoich dzieci, dla swoich rodzin, pracuje dla swoich obywateli i dla własnej kultury społecznej. A chociaż dzisiaj tak jest, że pełnej suwerenności między narodami powiązanymi r&oacute;żnymi układami i blokami nie ma, to jednak są granice dla tych układ&oacute;w, granice odpowiedzialności za własny Nar&oacute;d, za jego prawa, a więc i za prawo do suwerenności.&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Skoro wiemy w zarysie jak powstał nar&oacute;d, co go spaja i co jest przyczyna jego wzrostu, zastan&oacute;wmy się, a contrario, co powoduje, iż narody słabną a czasami wręcz zanikają.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">III. U źr&oacute;deł dekonstrukcji</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Brak spoistości narodowej</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zar&oacute;wno nasza historia jak i zdrowy rozsadek podpowiada nam, iż istnienie mniejszości narodowej jest utrudnieniem, gdyż niemożliwe jest osiągnięcie jedności, wytworzenia kolektywnego etosu o kt&oacute;rym wspominał Lejba Fogelman. Istnienie takiej mniejszości, ni mniej ni więcej, oznacza, iż ta grupa ceni sobie wyżej swoją kulturę narodową i świadomie nie chce z niej rezygnować. Dodatkowo wreszcie sprawa &bdquo;niewykorzystanych szans&rdquo; to jest nienaturalnej sytuacji, w kt&oacute;rej nie wykorzystujemy swojego &bdquo;przyrodzonego&rdquo; potencjału de facto tylko ze względu na narodowość. Jednak taka sytuacja wydaje się naturalnym kosztem związanym z koniecznością utrzymania ładu we wsp&oacute;lnocie narodowej w kt&oacute;rej elitę konsystuje emanacja większości a nie mniejszości narodowej.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Większość mniejszości uznaje ten porządek rzeczy, nie powodując napięć społecznych, ale nie wszystkie. Niekt&oacute;re nie chcąc poddawać się regule narodowej dążą do takiego przeformatowania zasad życia społecznego, kt&oacute;re nie będzie stawiało im żadnych ograniczeń. Naturalnie oznacza to odrzucenie idei państwa narodowego i promocje multikulturalizmu. Tak o tym problemie i o tym czy &bdquo;Chincyki trzymają się mocno&rdquo; ;-) pisał prof. Kevin Macdonald: &bdquo;I Żydzi, i zamorscy Chińczycy, są wysoce inteligentni i przedsiębiorczy, lecz zamorscy Chińczycy nie uformowali wrogiej kulturalnej elity w krajach Azji południowo-wschodniej, gdzie gł&oacute;wnie się osiedlili i nie koncentrują się na posiadaniu medi&oacute;w czy konstruowaniu kultury. Nie czytamy o chińskich ruchach kulturowych propagowanych w liczących się uniwersytetach i organizacjach medialnych, kt&oacute;re poddają tradycyjną kulturę południowo-wschodnich Azjat&oacute;w i anty-chińskie odczucia radykalnej krytyce, czy o chińskich organizacjach prowadzących kampanię na rzecz usuwania rodzimych symboli kulturowych i religijnych z miejsc publicznych&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Te sprawy komplikują się jeszcze bardziej, jeśli weźmiemy pod uwagę, że mogą też zachodzić naturalne konflikty lojalności między państwem w kt&oacute;rym mniejszości zamieszkują zwłaszcza w sytuacji, kiedy państwo macierzyste mniejszości ma z nim konflikt interes&oacute;w. Mieliśmy w Polsce dość wymowny przykład działalności mniejszości niemieckiej i żydowskiej (dotyczy zwłaszcza tej części, kt&oacute;ra za swą ojczyznę traktowała ZSRR) przed i w czasie II wojny światowej. Wsp&oacute;łcześnie, obserwując zachowanie części mniejszości, zwłaszcza żydowskiej, można r&oacute;wnież odnieść wrażenie o wyraźnym konflikcie interes&oacute;w o czym szerzej napiszę w dalszej części pracy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Brak spoistości religijnej</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wydaje się, iż dla sp&oacute;jności wsp&oacute;lnoty ważnym czynnikiem jest też perspektywa eschatologiczna będąca dopełnieniem życia ziemskiego. W Polsce w wymiarze społeczno-politycznym odegrała ona szczeg&oacute;lną rolę ze względu na łatwość w odr&oacute;żnieniu od zaborc&oacute;w (protestant&oacute;w, prawosławnych, wojujących ateist&oacute;w) oraz Żyd&oacute;w. Kości&oacute;ł odegrał szczeg&oacute;lną rolę w zachowaniu polskiej idei narodowej i przyczynił się do ugruntowania teoretycznego tzw. nacjonalizmu chrześcijańskiego, kt&oacute;rego tw&oacute;rcami byli wybitni myśliciele duchowni oraz świeccy. Przedstawiciel tej pierwszej grupy, o. J&oacute;zef Maria Bocheński z Zakonu Kaznodziej&oacute;w tak m.in. pisał o&nbsp; &bdquo;To czym jesteśmy duchowo (a jest to czynnik w człowieku najważniejszy), jest w znacznej mierze Polski zasługą; żadna rodzinna, gmina, dzielnica, a także &ndash; zdaniem piszącego te słowa &ndash; Europa jako całość, nie mogą się r&oacute;wnać z nią wpływem....Do Ojczyzny podchodzić możemy dwojako: jak do czegoś bardzo nam bliskiego (ojcowskiego) i jako pewnego narzędzia i odblasku boskiej chwały, z kt&oacute;rym jesteśmy szczeg&oacute;lnie związani. Te dwa podejścia opierają się z punktu widzenia katolickiego ostatecznie na tej samej podstawie, a mianowicie na miłości ku Bogu, kt&oacute;rego nasza Ojczyzna jest narzędziem i kt&oacute;rego chwalę reprezentuje.&rdquo; Z kolei Roman Dmowski z &bdquo;drugiej grupy&rdquo; teoretyk&oacute;w nacjonalizmu, pisał &bdquo;Katolicyzm nie jest dodatkiem do polskości, zabarwieniem jej na pewien spos&oacute;b, ale tkwi w jej istocie, w znacznej mierze stanowi jej istotę. Usiłowanie oddzielenia u nas katolicyzmu od polskości, oderwania narodu od religii i od Kościoła, jest niszczeniem samej istoty narodu.&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wydaje się, iż pomimo upływu czasu ten podział się utrzymuje i osoby będące kulturowo poza Kościołem Katolickim są orędownikami idei antynarodowych.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Brak spoistości etnicznej</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Już w latach siedemdziesiątych, były szpieg KGB Jurii Bezimienow, pisał w swej pracy poświęconej tajnikom działalności wywrotowej KGB, iż kwestie rasowe, obok narodowych i religijnych, mają sw&oacute;j dodatkowy &bdquo;potencjał zapalny&rdquo; i dlatego chętnie są używane do osłabiania poprzez mulitkulturyzowanie/etnizowanie względnie jednolitych narod&oacute;w. &bdquo;Doskonale wiemy, że żadne rasy czy jednostki nie są r&oacute;wne pod żadnym względem. Mamy świadomość, iż każda nacja ma sw&oacute;j specyficzny charakter, zdolności, tradycje, mentalność i umiejętność uczenia się oraz indywidualne tempo rozwoju.&rdquo; W Polsce, te oczywistości dostrzegał już prof. Koneczny, kiedy pisał &bdquo;Nar&oacute;d nie może się wytworzyć inaczej, jak tylko z lud&oacute;w pokrewnych, lecz do narodowości już wytworzonej i historycznie rozwiniętej, mogą się przyłączać (oczywiście dobrowolnie) ludy także nie pokrewne, lecz sąsiednie.&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">O ile powyższe braki mają pewne znaczenie (mniejsze bądź większe w zależności od skali zasob&oacute;w osobowych, finansowych, intelektualnych etc) to w dalszym ciągu odczytując &bdquo;na opak&rdquo; nasze definicyjne zapisy, do najważniejszych należy zaliczyć te związane z morale, racjonalnością i bezpośrednim interesem materialnym uzasadniającym, dlaczego warto być Polakiem. Można by rzec, iż już od czas&oacute;w antycznych, spowodowanie z kolei brak&oacute;w w tych obszarach u wrog&oacute;w to nie tylko elementarz wojny psychologicznej, ale i &bdquo;klucze do sukcesu&rdquo;. Warto pamiętać, iż najważniejszym kluczem jest oczywiście sfera idei, do kt&oacute;rej w najszerszym ujęciu polskość zaliczamy. Historycznie rzecz ujmując, niewiele jest sfer życia człowieka za kt&oacute;re gotowy by był zaryzykować/poświecić swoje szczęście lub życie. Za kluczowe przekonania ideowe już tak (&bdquo;...co nam obca przemoc wzięła szablą odbierzemy&rdquo;)</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Brak morale</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Częścią sfery idei jest tzw. morale. Morale to w największym skr&oacute;cie najgłębsze etyczne przekonanie o słuszności określonych wartości i gotowość do poświęceń dla ich obrony. Im większa duchowość danego narodu im szersza perspektywa eschatologiczna tym gotowość do poświęcenia jest większe, dlatego zawsze warto pamiętać o przestrodze kard. Tysiąclecia &ldquo;Jeśli przyjdą zniszczyć ten Nar&oacute;d, zaczną od Kościoła, gdyż Kości&oacute;ł jest siłą tego narodu&rdquo;. Ale morale &bdquo;lepi się&rdquo; się r&oacute;wnież z innych inspiracji, przede wszystkim wojskowych, czyli m.in. brak kompleks&oacute;w wobec przeciwnika (nawet jeśli ma przewagę), dużą odporność psychiczna (m.in. na destrukcyjne oddziaływanie przeciwnika) i wiara w zwycięstwo.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Psychologowie twierdza, że poczucie prawości moralnej jest istotnym składnikiem szacunku do siebie, a szacunek ten należy do czynnik&oacute;w motywujących, kt&oacute;re uczestniczą w procesach kształtowania się tożsamości społecznej. Dlatego jednym z kluczowych element&oacute;w osłabiania morale jest obniżanie własnej wartości (na poziomie indywidualnym i grupowym) danego narodu poprzez wywoływanie niekorzystnych analogii historycznych lub winy historycznej (tzw. pedagogika wstydu). O ile z &bdquo;polinische wirthschaft&rdquo; w zasadzie już się uporaliśmy zamykając buzie propagandystom, o tyle pr&oacute;by plamienia polskiego honoru jeszcze, miejmy nadzieję już niedługo, trwają.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ale to zjawisko jest nieco szersze i zdaje się w obecnych okolicznościach to gł&oacute;wnie na Polsce będzie spoczywać obowiązek opowiadania go światu cywilizacji łacińskiej. Oddaję głos prof. Kevinowi Macdonaldowi: &bdquo;...z punktu widzenia interesu kolektywistycznej grupy mniejszości narodowej, takiej jak Żydzi, najlepszym sposobem zniszczenia Europejczyk&oacute;w (narod&oacute;w europejskich - PB) jest przekonanie ich, ze są bankrutami moralnymi. Następstwem odrazy moralnej uruchamiającej odruch wymierzenia kary altruistycznej będzie og&oacute;lny rozpad kultury zachodu a w ostatecznym rozrachunku jej wymazanie jako uchwytnej wsp&oacute;lnoty etnicznej. Dlatego intelektualiści żydowscy niezmordowanie rozwijają z jednej strony ideologie wyższości moralnej i ich dziejowej, niezawinionej krzywdy, z drugiej zaś nie ustają w podważeniu moralnej prawowitości zachodu.&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Brak ultima ratio</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Starożytni Chińczycy podbijający ościenne narody w swej (meta) socjotechnicznej triadzie starali się przekonać elity wrog&oacute;w, iż (i) ich op&oacute;r nie ma sensu, bowiem zostanie prędzej czy p&oacute;źniej złamany (&bdquo;jest nieracjonalny&rdquo;); (ii) ulegając, będą mogli zachować twarz (pewne emblematy dawnej władzy np. flagę/godło, język etc.); (iii) ulegając, będą mogli poprawić sw&oacute;j indywidualny stan materialny</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ale oczywiście ze względu na uwarunkowania 2.0 tj. min umasowienia metody działań wsp&oacute;łczesnych narod&oacute;w imperialnych, podbijających inne są bardziej rozbudowane. Poza starymi pogr&oacute;żkami i przynętami, dekonstrukcją systemu wartości opartego na wartościach religijnych i narodowych oferują szereg nowych.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Szerzej większość tej &bdquo;oferty&rdquo; om&oacute;wię przy okazji analizy gł&oacute;wnych argument&oacute;w legalizujących a używanych w narracji środowisk de facto antypolskich, teraz zaś wspomnę jedynie o wolności, redukowaniu życia duchowego na rzecz życia impulsywnego koncentrującego się na jak najczęstszym doświadczaniu przyjemności i nieodległym od tego konsumpcjonizmie.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Człowiek obdarty z silnej tożsamości indywidualnej i grupowej, pozbawiony osadzenia w dziejach rodowych i wsp&oacute;lnotowych, bez perspektywy echatologicznej, pozbawiony licznej rodziny, skupiony na kolekcjonowaniu przyjemności na kt&oacute;re go nie stać (kredyt) i całkowicie niegotowy na b&oacute;l i poświecenie, jest z punktu widzenia wojny psychologiczno &ndash; informacyjnej &bdquo;pokonany&rdquo; bowiem jest szalenie plastyczny, podatny na manipulację.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">IV. Zakończenie</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Bez wątpienia zar&oacute;wno pojęcie nacjonalizmu jak i jego podstawa tj. nar&oacute;d polski jest ideą/doktryną w dalszym ciągu żywotną i mająca realną ofertę dla Polak&oacute;w (o śmierci kt&oacute;rych &bdquo;podawane informacje są przedwczesne&rdquo;). Czasy dla niego i nich są bez wątpienia trudne, niemniej tak jak wiele razy w historii bywało, atrakcyjność polskości i godności przeważy nad roztopieniem się tożsamości i poddaniem pod zarząd innym narodowościom, nawet jeśli ich tradycja jest dłuższa. Nie w liczbach wszak rzecz a etycznej atrakcyjności, będącej fundamentem dobra wsp&oacute;lnego.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text"><span class="wixGuard wixui-rich-text__text">​</span></span></p></div><!--/$--></div></div></div><!--/$--></div></section><!--/$--><!--/$--></div></div></section><!--/$--><!--$-->




                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
@endsection
