

<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Streszczenie:</p></p>


<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Celem niniejszej analizy jest przedstawienie rozwoju polityki młodzieżowej jako polityki publicznej, ze szczeg&oacute;lnym uwzględnieniem partycypacji młodzieży we władzy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Słowa kluczowe:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">młodzież; polityka młodzieżowa; Rada Dzieci i Młodzieży; Rada Dialogu z Młodym Pokoleniem, Pełnomocnik rządu ds. polityki młodzieżowej;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rozw&oacute;j otoczenia instytucjonalnego polityki młodzieżowej w Polsce po 2015 roku</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Wprowadzenie</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Pojęcie &bdquo;młodzieży&rdquo; jest stałym elementem debaty publicznej. Wyodrębnienie młodzieży w dyskursie politycznym, a następnie w ramach polityk publicznych, jest wynikiem uznania, że stanowi ona specyficzną grupę społeczną pod względem społecznym, ale r&oacute;wnież ekonomicznym, posiadającą szczeg&oacute;lną role w społeczeństwie. Z perspektywy rozwoju społeczno-gospodarczego wykorzystanie potencjału młodzieży oraz odpowiednie programowanie polityki młodzieżowej jest szczeg&oacute;lnie istotne, ponieważ młodzież stanowi grupę charakteryzującą się znacznym poziomem innowacyjności.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Polityka młodzieżowa to całokształt działań podejmowanych przez władze publiczną, kt&oacute;rych adresatem są ludzie młodzi. Kluczowym zagadnieniem polityki młodzieżowej jest zapewnienie młodzieży odpowiedniej partycypacji we władzy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Definiując &bdquo;politykę młodzieżową&rdquo; w doktrynie dokonuje się zasadnego rozr&oacute;żnienia na dwa sposoby rozumienia polityki młodzieżowej: &bdquo;politykę młodzieżową sensu stricto&rdquo; (wąskie rozumienie) i &bdquo;politykę młodzieżową sensu largo&rdquo; (szerokie rozumienie). Polityka młodzieżowa w wąskim rozumieniu dotyczy działań na rzecz młodzieży podejmowanych w ramach realizacji poszczeg&oacute;lnych polityk sektorowych. Natomiast w szerokim rozumieniu polityka młodzieżowa jest systemem międzysektorowych, sp&oacute;jnych i planowanych działań skoncentrowanych na rozwiązaniu istotnych problem&oacute;w młodzieży (wymiar przedmiotowy) z uwzględnieniem opinii i potrzeb tej grupy społecznej oraz włączaniem jej w procesy wsp&oacute;łdecydowania (wymiar podmiotowy).<span style="text-decoration:underline;" class="wixui-rich-text__text">[1]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Niniejsza analiza koncentrować będzie się na tym jak funkcjonuje otoczenie instytucjonalne polityki młodzieżowej w Polsce przed i po 2015 roku. Pod pojęciem otoczenia instancjonalnego na potrzeby niniejszej analizy rozumie się og&oacute;ł instytucji publicznych podejmujących działania na rzecz partycypacji młodzieży we władzy oraz organ&oacute;w podejmujących działania włączające młodzież w kształtowanie polityki młodzieżowej.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Celem niniejszej analizy jest przeprowadzenie przeglądu działań podejmowanych przez władze w ramach polityki młodzieżowej, ze szczeg&oacute;lnym uwzględnieniem otoczenia instytucjonalnego, służącego do realizacji partycypacji młodzieży we władzy. Włączanie i udział młodzieży w charakterze konsultacyjnym, doradczym, decyzyjnym jest fundamentalny do kreowania polityki młodzieżowej odpowiadającej na realne potrzeby tej grupy społecznej. Analiza ma r&oacute;wnież wskazać na właściwy kierunek kształtowania polityki młodzieżowej biorąc pod uwagę dotychczasową realizację jej założeń przez poszczeg&oacute;lne rządy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Polityka młodzieżowa w latach 2003-2015</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Do rozpoczęcia w Polsce debaty o polityce młodzieżowej przyczynił się trwający proces akcesyjny do UE i związana z tym konieczność dostosowania się do zaleceń Komisji Europejskiej zawartych w Białej księdze z 2001 roku<span style="text-decoration:underline;" class="wixui-rich-text__text">[2]</span> oraz p&oacute;źniejszych rezolucji Rady Unii Europejskiej z 2003 i 2004 roku. Mając na uwadze zawarte w tych dokumentach zalecenia oraz obowiązujące w UE tendencje do rozwijania polityki młodzieżowej, zdecydowano się na opracowanie programowego dokumentu określającego kierunki i cele polityki młodzieżowej w Polsce.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W DNIU 19 sierpnia 2003 roku polski rząd zatwierdził &bdquo;Strategię Państwa dla Młodzieży na lata 2003-2012&rdquo;. Strategia powstała we wsp&oacute;łpracy Ministerstwa Edukacji Narodowej i Sportu z innymi urzędami centralnymi, instytucjami działającymi na rzecz młodzieży, naukowcami zajmującymi się problematyką młodzieżową i organizacjami młodzieżowymi.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Według &bdquo;Strategii Państwa dla Młodzieży na lata 2003&ndash;2012&rdquo;:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;polityka młodzieżowa uznawana jest w krajach europejskich za międzyresortową, zintegrowaną politykę wobec młodych ludzi, wywodzącą się z ich potrzeb. Celem polityki młodzieżowej jest stworzenie odpowiednich warunk&oacute;w bytowych dla młodych ludzi, umożliwienie im uczestnictwa w życiu publicznym, udziału w życiu społecznym, kulturalnym i politycznym na r&oacute;wni z innymi grupami społecznymi&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[3]</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Należy wskazać, że &bdquo;Strategia Państwa dla Młodzieży na lata 2003-2012&rdquo; wskazywała, że realizacja cel&oacute;w określonych w tym dokumencie wymaga stworzenia sp&oacute;jnego systemu prawno-instytucjonalnego wsparcia młodzieży.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W ocenie ekspert&oacute;w pierwsza rządowa strategia na rzecz młodzieży nie zawierała oryginalnych rozwiązań, stanowiła powielenie og&oacute;lnych założeń zawartych w aktach prawnych przyjmowanych na poziomie Unii Europejskiej. Dowodzą temu obszary interwencji, takie jak: edukacja, zatrudnienie, partycypacja publiczna, ochrona zdrowia i profilaktyka czy czas wolny, sport i turystyka. Należy jednak zaznaczyć, że kwestie zatrudnienia czy partycypacji publicznej młodych ludzi nie były w Polsce dotąd sygnalizowane. W dokumencie uwzględniono także polskie realia początku XXI w. i wynikające z nich problemy młodzieży, np. niski poziom kształcenia na obszarach wiejskich czy słabą edukację sportową.<span style="text-decoration:underline;" class="wixui-rich-text__text">[4]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zasadnicze wady &bdquo;Strategii Państwa dla Młodzieży na lata 2003&ndash;2012&rdquo; to przede wszystkim brak og&oacute;lnopolskiego podmiotu reprezentującego środowiska młodzieżowe (za taką organizację uważano nieoficjalnie powołaną w 2011 roku PROM). Brak reprezentacji, w tym r&oacute;wnież brak koncentracji kompetencji do zarządzania polityka młodzieżowa na poziomie rady ministr&oacute;w, był poważną słabością strategii, powodująca, że pozostała ona de facto zbiorem deklaracji. &nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Na potrzeby dokumentu zdefiniowano grupę docelową jako osoby w przedziale wiekowym 15&ndash;24 lata. Ten przedział wiekowy, zdaniem ekspert&oacute;w, nie był zgodny z rozpiętością grupy społecznej, kt&oacute;rą należało zakwalifikować jako młodzież.<span style="text-decoration:underline;" class="wixui-rich-text__text">[5]</span> Kolejnym problemem wynikającym z dokumentu było oparcie realizacji strategii na niezdefiniowanej &bdquo;międzyresortowość&rdquo; polityki młodzieżowej. Spowodowało to podział zadań na poszczeg&oacute;lne ministerstwa, kt&oacute;rym brakowało koordynacji.<span style="text-decoration:underline;" class="wixui-rich-text__text">[6]</span> Słabość polityki młodzieżowej wynikała r&oacute;wnież z faktu, że nie podano źr&oacute;deł finansowania planowanych działań.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Brakowało r&oacute;wnież powołania og&oacute;lnopolskiej reprezentacji młodzieży. Za taką reprezentację rząd uznawał nieformalnie powołaną w 2011 r. Polską Radę Organizacji Młodzieżowych, kt&oacute;ra nie posiadała żadnego formalnego statusu o charakterze publicznym. Po zakończeniu okresu obowiązywania &bdquo;Strategii Państwa dla Młodzieży na lata 2003&ndash;2012&rdquo; rząd nie przeprowadził monitoringu i ewaluacji dokumentu.<span style="text-decoration:underline;" class="wixui-rich-text__text">[7]</span> Takie podejście wskazuje na lekceważący stosunek &oacute;wczesnej rady ministr&oacute;w, kt&oacute;rej prezesem był Donald Tusk (Platforma Obywatelska) do polityki młodzieżowej oraz brak rokowań odnośnie do zmiany tego podejścia. R&oacute;wnież w toku realizacji &bdquo;Strategii Państwa dla Młodzieży na lata 2003&ndash;2012&rdquo; rząd pod kierownictwem Donalda Tuska nie reagował na krytyczne stanowiska ekspert&oacute;w i analizy wskazujące na niewłaściwy i nieskuteczny spos&oacute;b realizowania założeń polityki młodzieżowej. Wskazywano r&oacute;wnież, że właściwym rozwiązaniem mogłoby być powołanie koordynatora polityki młodzieżowej na poziomie Kancelarii Prezesa Rady Ministr&oacute;w<span style="text-decoration:underline;" class="wixui-rich-text__text">[8]</span>, na co rząd się nie zdecydował. R&oacute;wnież w 2012 roku zakończono działalność Departamentu Młodzieży i Organizacji Pozarządowych powołanego dwa lata wcześniej w Ministerstwie Edukacji Narodowej w celu realizacji założeń polityki młodzieżowej.<span style="text-decoration:underline;" class="wixui-rich-text__text">[9]</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W 2013 roku powstał projekt &bdquo;Krajowego Programu na rzecz Młodzieży &ndash; Rządowy Program na rzecz Młodzieży. Aktywna Młodzież&rdquo;.<span style="text-decoration:underline;" class="wixui-rich-text__text">[10]</span> Dokument ten został opracowany przez Doraźny zesp&oacute;ł ds. polityki na rzecz młodzieży funkcjonujący w ramach Rady Działalności Pożytku Publicznego. We wrześniu 2013 roku Rada zarekomendowała projekt Programu do realizacji przez Ministerstwo Pracy i Polityki Społecznej<span style="text-decoration:underline;" class="wixui-rich-text__text">[11]</span>, jednak ostatecznie rząd nie zdecydował się na przyjęcie nowego dokumentu programowego i strategicznego dla młodzieży.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Na bazie wyżej wskazanego projektu, w 2014 roku powstał kolejny projekt &bdquo;Rządowego Programu Aktywności Społecznej Młodzieży na lata 2015&ndash;2016 &bdquo;Aktywna Młodzież&rdquo;. W dokumencie tym wskazano zdecydowanie na konieczność opracowania rządowego dokumentu, w kt&oacute;rym zostanie określona polityka na rzecz młodzieży. Projekt ten nie został ostatecznie przyjęty przez rząd Ewy Kopacz (Platforma Obywatelska).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Brak priorytetu rządu koalicji PO-PSL dla realizacji polityki młodzieżowej dopełnia przyjęcie zarządzenia nr 31 z dnia 27 sierpnia 2015 roku MPiPS w sprawie przyjęcia Programu Aktywności Społecznej Młodzieży na 2015 r.<span style="text-decoration:underline;" class="wixui-rich-text__text">[12]</span> Program ten miał charakter wyłącznie resortowy, koncentrował się na kompetencjach MPiPS. Podkreślić należy, że dokument został przyjęty na rok 2015 dopiero z końcem sierpnia, w toku trwającej kampanii wyborczej, a na sfinansowanie programu przeznczona została kwota 5 mln złotych, a więc środki pieniężne o charakterze śladowym.&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Należy w tym miejscu poczynić r&oacute;wnież uwagę, że dotychczasowe regulacje prawne oraz praktyka orzecznicza miały negatywny wpływ na rozw&oacute;j młodzieżowych rad. W okresie 1990 &ndash; 2001 roku nie istniały żadne przepisy określające możliwość tworzenia młodzieżowych rad. Jedyny kierunek interpretacji w tej sprawie wyznaczył wyrok Naczelnego Sądu Administracyjnego oz. w Rzeszowie z 21 maja 1997 r., sygn. akt SA/Rz 139/97, w kt&oacute;rym NSA stwierdziło, że: &bdquo;żaden przepis ustawy o samorządzie terytorialnym, będący podstawą działania tego samorządu nie daje uprawnień radzie gminy do swobodnego kształtowania jej struktury wewnętrznej i tworzenia innych ciał niż przewidziane ustawy&rdquo;. Po wejściu w życie Konstytucji RP z dnia 2 kwietnia 1997 roku w doktrynie istniał sp&oacute;r, czy możliwe jest przyznanie gminom kompetencji do kreowania młodzieżowych rad z powołaniem na domniemanie właściwości gminy zawarte w art. 164 ust. 3 Konstytucji RP. W 2001 roku ustawodawca zdecydował się na wprowadzenie do systemu prawa art. 5b ustawy o samorządzie gminnym, kt&oacute;ry regulował kwestie kompetencji gminy w zakresie polityki młodzieżowej, w tym powoływania młodzieżowych rad gmin. Przepisy te były jednak skonstruowane bardzo niestarannie, przez co wywoływały liczne kontrowersje, przy jednoczesnym niewielkim zakresie uprawnień młodzieżowej rady na poziomie gminy. Uregulowania te dawały r&oacute;wnież radzie gminy znaczną swobodę uznaniową wobec młodzieżowej rady.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Z kolei, w analizowanym okresie, na szczeblu wojew&oacute;dzkim i powiatowym w og&oacute;le nie istniały przepisy pozwalające na tworzenie młodzieżowych sejmik&oacute;w i rad.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Polityka młodzieżowa po 2015 roku</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Po wyborach zakończonych jesienią 2015 roku zwycięstwem Prawa i Sprawiedliwości powołany został rząd Beaty Szydło (Prawo i Sprawiedliwość), a następnie Mateusza Morawieckiego (Prawo i Sprawiedliwość) co dało początek znaczącym zmianom w zakresie rozwoju polityki młodzieżowej w Polsce w zakresie partycypacji młodzieży we władzy, ale r&oacute;wnież realizowania przez powyższe rządy polityki ułatwiającej funkcjonowanie ludzi młodych (m.in. zwolnienie z podatku dochodowego do 26 roku życia). W dalszej części analiza skoncentruje się na rozwoju otoczenia instytucjonalnego.</p></p>
<p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rada Rady Dzieci i Młodzieży przy Ministrze Edukacji Narodowej</p>
</li>
</ol></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Pierwszą istotną decyzją było powołanie w 2016 roku Rady Dzieci i Młodzieży przy Ministrze Edukacji Narodowej<span style="text-decoration:underline;" class="wixui-rich-text__text">[13]</span>. Decyzja o powołaniu RDiM został przekazana przez Anna Zalewską &ndash; ministra edukacji narodowej w czasie posiedzenia Sejmu Dzieci i Młodzieży i spotkała się z bardzo pozytywnym przyjęciem przez uczestnik&oacute;w obrad. RDiM działa od 2016 roku, a do gł&oacute;wnych zadań tego organu doradczego należy wyrażanie opinii, w tym przedstawianie propozycji w kwestiach dotyczących dzieci i młodzieży w zakresie spraw objętych działem administracji rządowej oświata i wychowanie, w szczeg&oacute;lności przedstawianie opinii na temat planowanych zmian, w tym propozycji rozwiązań. Kadencja RDiM trwa rok. W skład RDiM powoływanych chodzi 16 członk&oacute;w i ich zastępc&oacute;w (po jednym z każdego wojew&oacute;dztwa).<span style="text-decoration:underline;" class="wixui-rich-text__text">[14]</span> Nab&oacute;r członk&oacute;w RDiM polega na ocenie nadesłanych kandydatur.&nbsp; Ocenie podlega przede wszystkim uzasadnienie przygotowane przez kandydata, a także informacje dotyczące spełniania następujących kryteri&oacute;w:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><ul class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">zaangażowania w wolontariat,</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">zaangażowania w działalność społeczną oraz życie społeczności lokalnych i życie publiczne,</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">osiągane wyniki w nauce.<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ul></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Powołanie RDiM należy ocenić pozytywnie. Po raz pierwszy powołany został organ o charakterze og&oacute;lnopolskim, zapewniającym udział młodzieży ze wszystkich wojew&oacute;dztw. Powołanie RDiM wyznaczyło kierunek rządu Beaty Szydło (Prawo i Sprawiedliwość) w zakresie realizacji polityki młodzieżowej, wskazując na aktywny udział przedstawicielstwa młodzieży jako partnera w realizacji tej polityki publicznej. Już samo powołanie RDiM stanowiło odpowiedź na postulaty młodzieży w zakresie powołania reprezentacji młodzieży na poziomie centralnym.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Krytycznie należy natomiast ocenić motywowane politycznie ataki niekt&oacute;rych przedstawicieli opozycji wobec młodzieży powoływanej w skład RDiM z uwagi na zaangażowanie polityczne niekt&oacute;rych członk&oacute;w tego organu. Taka forma piętnowania i atakowania młodzieży zaangażowanej społecznie miała na celu wywoływanie &bdquo;efektu mrożącego&rdquo;. Stanowiła r&oacute;wnież wyraz niezadowolenia wobec słabnącego znaczenia PROM.&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dodatkowo pozytywnym aspektem działania RDiM jest jej charakter integrujący aktywnych działaczy społecznych młodego pokolenia oraz przygotowanie do dalszego zaangażowania publicznego. Analiza skład&oacute;w osobowych kolejnych kadencji RDiM wskazuje, że zdecydowana większość członk&oacute;w tego organu podejmuje kolejne wyzwania w obszarze społecznym i publicznym, co stanowi znaczący kapitał społeczny pozwalający na rozw&oacute;j społeczeństwa obywatelskiego w obszarze młodzieży.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wraz z powołaniem Rady Dialogu z Młodym Pokoleniem spadło znaczenie RDiM, kt&oacute;ra stała się radą o charakterze sektorowym odnoszącą się do kwestii wychowania i edukacji młodzieży.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><br class="wixui-rich-text__text">
<span style="font-weight:bold;" class="wixui-rich-text__text">Rada Dialogu z Młodym Pokoleniem</span><br class="wixui-rich-text__text">
​</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kluczowym działaniem w zakresie rozwoju polityki młodzieżowej stanowiło powołanie Rady Dialogu z Młodym Pokoleniem.<span style="text-decoration:underline;" class="wixui-rich-text__text">[15]</span> Rada powstała z inicjatywy Piotra Glińskiego pełniącego funkcję wicepremiera i Przewodniczącego Komitetu do spraw Pożytku Publicznego. Jest to pierwszy w historii Polski organ dialogu obywatelskiego pomiędzy młodym pokoleniem Polak&oacute;w a najważniejszymi instytucjami państwowymi. Powstanie Rady stanowiło odpowiedź na postulaty zgłaszane przez środowiska młodzieżowe.<span style="text-decoration:underline;" class="wixui-rich-text__text">[16]</span> Ważny element procesu formułowania założeń RDzMP stanowiły posiedzenia Parlamentarnego Zespołu ds. Wspierania Młodzieżowych Rad przy Jednostkach Samorządu Terytorialnego. Dostrzeżono, że po 2015 roku nastąpił dynamiczny rozw&oacute;j młodzieżowych rad przy jednostkach samorządu terytorialnego, kt&oacute;re wyrażały zainteresowanie powołania og&oacute;lnopolskiego organu dialogu obywatelskiego wyspecjalizowanego w temacie młodego pokolenia, w kt&oacute;rym znaleźliby się m.in. przedstawiciele młodzieżowych rad przy jednostkach samorządu terytorialnego.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rada powstała na podstawie na mocy ustawy o zmianie ustawy o działalności pożytku publicznego i o wolontariacie z dnia 19 lipca 2019 roku.<span style="text-decoration:underline;" class="wixui-rich-text__text">[17]</span> Istotne znaczenie ma to, że kompetencje i spos&oacute;b funkcjonowania Rady został określony ustawą, czyli aktem normatywnym o wysokiej randze w hierarchii źr&oacute;deł prawa.<span style="text-decoration:underline;" class="wixui-rich-text__text">[18]</span> Warto podkreślić, że zmiana ustawy powołująca RDzMP została przyjęta przez Sejm RP aż 410 głosami &bdquo;za&rdquo; oraz w stosunkowo kr&oacute;tkim czasie (34 dni od chwili wpływu projektu do podpisania ustawy przez Prezydenta RP) i braku poprawek Senatu RP, w kt&oacute;rym większość posiada opozycja. Oznacza to, że powstanie RDzMP w kształcie zaproponowanym przez rząd Prawa i Sprawiedliwości odbyło się przy politycznym konsensusie.<span style="text-decoration:underline;" class="wixui-rich-text__text">[19]</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rada jest stałym organem opiniodawczo-doradczym Przewodniczącego Komitetu do spraw Pożytku Publicznego. Zgodnie z art. 411 ust. 2 ustawy o działalności pożytku publicznego i o wolontariacie<span style="text-decoration:underline;" class="wixui-rich-text__text">[20]</span>, do zadań Rady Dialogu z Młodym Pokoleniem należy w szczeg&oacute;lności:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">wyrażanie opinii w sprawach dotyczących stosowania ustawy w zakresie dotyczącym młodego pokolenia;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">wyrażanie opinii o projektach akt&oacute;w prawnych oraz programach rządowych w zakresie dotyczącym młodego pokolenia;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">inicjowanie i wspieranie działań na rzecz zwiększania poziomu partycypacji obywatelskiej młodych ludzi w Rzeczypospolitej Polskiej;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">tworzenie forum dialogu między organizacjami pozarządowymi i innymi instytucjami społecznymi a organami władzy publicznej w zakresie dotyczącym młodego pokolenia;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">wspieranie działalności instytucji dialogu obywatelskiego działających na rzecz młodego pokolenia, w tym dzieci i młodzieży, ze szczeg&oacute;lnym uwzględnieniem młodzieżowych rad gmin.<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ol></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Skład RDzMP ma mieszany charakter (łączący stronę publiczną ze stroną społeczną). Członkami są przedstawiciele: Prezydenta Rzeczypospolitej Polskiej, Rzecznika Praw Dziecka, Prezesa Rady Ministr&oacute;w, ministra właściwego do spraw oświaty i wychowania, ministra właściwego do spraw szkolnictwa wyższego i nauki, ministra właściwego do spraw kultury fizycznej, Przewodniczącego Komitetu do spraw Pożytku Publicznego, Rady Działalności Pożytku Publicznego oraz jednostek samorządu terytorialnego, a także przedstawiciele organizacji pozarządowych, związk&oacute;w i porozumień organizacji pozarządowych oraz podmiot&oacute;w wymienionych w art. 3 ust. 3 ustawy z dnia 24 kwietnia 2003 r. o działalności pożytku publicznego i o wolontariacie, oraz młodzieżowych rad gmin oraz Parlamentu Student&oacute;w Rzeczypospolitej Polskiej, kt&oacute;rzy stanowić będą w sumie co najmniej połowę składu Rady.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jak wskazano powyżej, gł&oacute;wnym zadaniem RDzMP jest wyrażanie opinii w sprawach dotyczących stosowania ustawy o działalności pożytku publicznego i o wolontariacie oraz o projektach akt&oacute;w prawnych oraz programach rządowych, kt&oacute;re dotyczą młodego pokolenia. Na czele RDzMP stoi dw&oacute;ch Wsp&oacute;łprzewodniczących (jeden reprezentuje stronę rządową, a drugi pozarządową) wybieranych w odrębnych głosowaniach przez dane strony zwykłą większością głos&oacute;w przy obecności co najmniej połowy uprawnionych członk&oacute;w Rady.<span style="text-decoration:underline;" class="wixui-rich-text__text">[21]</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rada wyraża opinie w drodze uchwał podejmowanych na posiedzeniach zwykłą większością głos&oacute;w w obecności co najmniej połowy członk&oacute;w, natomiast między posiedzeniami istnieje możliwość podejmowania uchwał w trybie obiegowym. Dotychczas w okresie od dnia 2 grudnia 2019 roku do dnia 14 października 2022 roku RDzMP przyjęła aż 111 uchwał. Z uwagi na określone ustawą kompetencję przedmiotem uchwał RDzMP było opiniowanie m.in. rządowych program&oacute;w dotacyjnych skierowanych do młodzieży oraz organizacji pozarządowych, program&oacute;w nauczania w szkołach, ustaw oświatowych, wniosk&oacute;w o powołanie młodzieżowych sejmik&oacute;w wojew&oacute;dzkich. Dużą cześć uchwał stanowi objęcie patronatem przez RDzMP wydarzeń organizowanych w gł&oacute;wnej mierze przez młodzieżowe organizacje pozarządowe. Patronat RDzMP należy ocenić pozytywnie, gdyż stanowi on ważne docenienie inicjatyw młodzieży oraz stanowi ważne wsparcie promocyjne. W zakresie swojej działalności RDzMP zajmowała się r&oacute;wnież powoływaniem przedstawicieli m.in. na Unijną Konferencję Młodzieży, do Rady Programowej Programu Stażowego, a także Komisji Konkursowej mającej wyłonić kandydat&oacute;w na Młodzieżowego Delegata RP na Sesję Zgromadzenia Og&oacute;lnego ONZ. Oznacza to de facto, że RDzMP z uwagi na to, że stanowi powszechnie uznawane przedstawicielstwo młodzieży, a swoją działalnością zyskuje poważanie, otrzymuje coraz szersze uprawnienia, a przez to realnie wpływa na zwiększenie partycypacji młodzieży w realizacji polityki publicznej.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W doktrynie pojawił się głos H. Taładaja<span style="text-decoration:underline;" class="wixui-rich-text__text">[22]</span>, kt&oacute;ry choć zawiera pozytywną ocenę RDzMP, to krytycznie ocenia spos&oacute;b powoływania członk&oacute;w RDzMP wskazując na m.in. upolitycznienie, brak pluralizmu oraz uzależnienie wyboru wyłącznie od decyzji Przewodniczącego Komitetu Pożytku Publicznego. Autor proponuje de lege ferenda, aby wyb&oacute;r członk&oacute;w strony pozarządowej był przeprowadzany przez same zainteresowane podmioty pozarządowe, przyznając jednocześnie, że to duże wyzwanie logistyczne. Stanowisko cytowanego autora jest jednak wewnętrznie sprzeczne. Autor aprobuje doradczy i konsultacyjny charakter uprawnień RDzMP, przy czym nie dostrzega i nie akceptuje tego, że niejako w tę funkcję immamentnie wpisane jest to, że to podmiot, kt&oacute;ry zwraca się o opinię (Przewodniczący Komitetu Pożytku Publicznego) samodzielnie decyduje o doborze kadrowym konsultant&oacute;w (członk&oacute;w RDMP) przy uwzględnieniu doświadczenia, wiedzy i kompetencji zgłoszonych kandydatur. Wydaje się przeciwnie, że właśnie uczynienie z RDzMP miejsca, w kt&oacute;rym z mocy prawa zasiadać będą przedstawiciele młodzież&oacute;wek partyjnych oraz osoby pochodzące z wybor&oacute;w powszechnych (jak postuluje H. Taładaj) może doprowadzić do zwiększenia rozpolitykowania tego organu, a przez to utrudnienia w realizacji polityki młodzieżowej przez władze publiczne. Celem funkcjonowania organ&oacute;w konsultacyjnych nie jest tworzenie alternatywnego systemu rząd&oacute;w, ale wsparcie organ&oacute;w władzy w realizacji zadań publicznych poprzez wykorzystanie wiedzy, doświadczenia, kompetencji, a także odczuć i preferencji os&oacute;b pełniących funkcję w organach doradczych.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Młodzieżowe rady o charakterze sektorowym</span><br class="wixui-rich-text__text">
​</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Potencjał wynikający z funkcjonowania Rady Dzieci i Młodzieży przy MEiN oraz Rady Dialogu z Młodym Pokoleniem został r&oacute;wnież dostrzeżony przez niekt&oacute;re ministerstwa, kt&oacute;re uznały za zasadne powołanie sektorowych młodzieżowych rad. Z uwagi na to, że powołanie RDzMP spowodowało, że RDiM skoncentrowała się na kwestiach edukacji i wychowania, aktualnie w Polsce funkcjonują trzy rady o charakterze sektorowym:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rada Dzieci i Młodzieży przy MEiN</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Młodzieżowa Rada Klimatyczna</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Młodzieżowa Rada Sprawiedliwości</p>
</li>
</ol></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Młodzieżowa Rada Klimatyczna</span><br class="wixui-rich-text__text">
​</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zarządzeniem Ministra Klimatu z dnia 30 marca 2020 r.<span style="text-decoration:underline;" class="wixui-rich-text__text">[23]</span> została powołana Młodzieżowa Rada Klimatyczna, będąca organem doradczym i opiniodawczym, działającym przy Ministrze Klimatu i Środowiska.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Do zadań Młodzieżowej Rady Klimatycznej należy:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><ul class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">wyrażanie opinii w zakresie spraw objętych działami administracji rządowej klimat, energia i środowisko, w szczeg&oacute;lności przedstawianie opinii na temat planowanych zmian polityki, strategii i zmian legislacyjnych w zakresie właściwości Ministra, w tym propozycji rozwiązań;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">kreowanie i promowanie wśr&oacute;d młodzieży postaw proekologicznych i proklimatycznych;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">podnoszenie poziomu wiedzy wśr&oacute;d młodzieży w zakresie spraw objętych działami administracji rządowej klimat, energia i środowisko.<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ul></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W skład Rady wchodzi 32 młodych ludzi reprezentujących r&oacute;żne środowiska, a wsp&oacute;lnym celem wszystkich Członk&oacute;w Rady jest aktywne działanie na rzecz ochrony klimatu.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Młodzieżowa Rada Sprawiedliwości</span><br class="wixui-rich-text__text">
​</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kolejnym młodzieżowym organem doradczym jest Młodzieżowa Rada Sprawiedliwości, działająca przy Ministrze Sprawiedliwości powołana na podstawie zarządzeniem Ministra Sprawiedliwości z dnia 21 grudnia 2020 r. w sprawie powołania Młodzieżowej Rady Sprawiedliwości.<span style="text-decoration:underline;" class="wixui-rich-text__text">[24]</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Do zadań Młodzieżowej Rady Sprawiedliwości należy m.in.:<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><ul class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">kreowanie i promowanie postaw nastawionych na rozw&oacute;j świadomości prawnej wśr&oacute;d młodzieży;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">kształtowanie i utrwalanie postaw obywatelskich i patriotycznych;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">zwiększenie zainteresowania młodzieży w zakresie spraw związanych z wymiarem sprawiedliwości;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">wspieranie działań Ministra Sprawiedliwości.<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ul></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W skład Rady wchodzić będzie od 12 do 24 członk&oacute;w, wybranych spośr&oacute;d kandydatur zgłoszonych do udziału w rekrutacji. Uczestnikiem naboru może być osoba fizyczna, kt&oacute;ra w dniu ogłoszenia naboru ukończyła 16 lat, a jednocześnie nie ukończyła 26 lat.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Pełnomocnik Rządu ds. Polityki Młodzieżowej</span><br class="wixui-rich-text__text">
​</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jak wyżej wskazano, realizacja polityki młodzieżowej ma charakter polityki publicznej o charakterze &bdquo;międzyresortowym&rdquo;. Takie ukształtowanie i rozproszenie wynikają przede wszystkim z tego, że młodzież i działania na rzecz tej grupy społecznej pozostają w merytorycznej właściwości wielu resort&oacute;w (np. edukacja &ndash; minister właściwy ds. edukacji i nauki, zatrudnienie &ndash; minister właściwy ds. pracy). Problemem będącym skutkiem takiego ukształtowania i rozproszenia jest utrudniona koordynacja realizacji zadań wynikających z przyjętej przez rząd polityki młodzieżowej. Odpowiedzią na ten problem jest utworzenie stanowiska niejako koordynatora tej polityki publicznej. Co do zasady w praktyce spotykane są trzy gł&oacute;wne modele:<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><ul class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">wyodrębnienia polityki młodzieżowej jako działu administracji rządowej w ramach jednego ministerstwa;<span style="text-decoration:underline;" class="wixui-rich-text__text">[25]</span></p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">międzyresortowy organ o charakterze korodującym;<span style="text-decoration:underline;" class="wixui-rich-text__text">[26]</span></p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">pełnomocnictwo udzielone przez rząd do koordynowania polityki młodzieżowej.<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ul></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W Polsce w III RP dotychczas brak było podmiotu odpowiedzialnego wyłącznie za koordynacje polityki młodzieżowej na poziomie centralnym. W związku z tym na podstawie rozporządzenia Rady Ministr&oacute;w w sprawie ustanowienia Pełnomocnika Rządu do spraw polityki młodzieżowej z dnia 22 września 2020 roku.<span style="text-decoration:underline;" class="wixui-rich-text__text">[27]</span> Na funkcję tę Mateusz Morawiecki &ndash; prezes rady ministr&oacute;w, powołał Piotra Mazurka &ndash; podsekretarza stanu.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zgodnie z &sect;2 rozporządzenia Rady Ministr&oacute;w w sprawie ustanowienia Pełnomocnika Rządu do spraw polityki młodzieżowej, do zadań Pełnomocnika należy:<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">inicjowanie aktywności i wsp&oacute;łpraca z organami administracji rządowej, organami jednostek samorządu terytorialnego i organizacjami pozarządowymi w zakresie działań wpływających na zwiększanie zaangażowania młodzieży w życie publiczne;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">koordynowanie dialogu między administracją rządową a partnerami społeczno-gospodarczymi, organizacjami pozarządowymi i organami jednostek samorządu terytorialnego w zakresie inicjatyw w obszarze polityki młodzieżowej;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">monitorowanie prac podejmowanych przez organy administracji rządowej i organy jednostek samorządu terytorialnego w sprawach związanych z sytuacją młodzieży w Polsce;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">wsp&oacute;łpraca z RDzMP w zakresie opiniowania projekt&oacute;w akt&oacute;w prawnych oraz przedstawiania rekomendacji wobec działań organ&oacute;w administracji rządowej i organ&oacute;w jednostek samorządu terytorialnego w sprawach dotyczących młodzieży;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">koordynowanie przygotowania i wdrożenia &ndash; w oparciu o konsultacje przeprowadzone z szerokim kręgiem interesariuszy &ndash; dokumentu strategicznego dotyczącego działań państwa w obszarze polityki młodzieżowej.</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Obsługę merytoryczną, organizacyjną, techniczną i kancelaryjno-biurową Pełnomocnika zapewnia Kancelaria Prezesa Rady Ministr&oacute;w. Pełnomocnik przedstawia Radzie Ministr&oacute;w sprawozdanie ze swojej działalności, do dnia 31 marca każdego roku, za rok poprzedni. Pierwszy rok działalności pełnomocnika rządu ds. młodego pokolenia przypadła na okres pandemii COVID-19, co miało wpływ na spos&oacute;b funkcjonowania. Jednak pomimo tej trudności oraz budowaniem zaplecza przez pełnomocnika, udało się przeprowadzić kilka kluczowych projekt&oacute;w, odpowiadając na wyzwania stawiane pełnomocnikowi przez Radę ministr&oacute;w.</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Działalność pełnomocnika rządu ds. polityki młodzieżowej w 2021 roku<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ol></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Najważniejszym zadaniem zrealizowanym przez pełnomocnika w 2021 roku było zorganizowanie og&oacute;lnopolskich konsultacji Strategii RP na rzecz Młodego Pokolenia, kt&oacute;re miały na celu włączenie młodych ludzi w procesy decyzyjne, aby mogli oni zdecydować o swojej przyszłości, aktywnie projektując założenia programowego dokumenty rządu w sprawie polityki młodzieżowej. Jak wynika ze Sprawozdania z działalności Pełnomocnika Rządu do spraw polityki młodzieżowej za 2021 rok<span style="text-decoration:underline;" class="wixui-rich-text__text">[28]</span>, w ramach konsultacji zorganizowano 16 konsultacji wojew&oacute;dzkich, w kt&oacute;rych wzięło udział ok. 30 tys. młodych ludzi z całej Polski, kt&oacute;rzy zgłosili 7170 potrzeb i problem&oacute;w dotyczących stanu obecnego oraz aż 4695 propozycji rozwiązań. Oznacza to, że przeprowadzone konsultacje były największymi publicznymi konsultacjami dokumentu rządowego w historii III RP.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Przeprowadzone w 2021 roku konsultacje Strategii RP na rzecz Młodego Pokolenia są r&oacute;wnież pierwszym w Polsce zastosowaniem crowdsourcingu przez administrację publiczną. Taka formuła tworzenia dokumentu strategicznego państwa dla młodzieży ma charakter innowacyjny i nowoczesny, jest odpowiedzią na powszechne trendy występujące w państwach rozwiniętych.<span style="text-decoration:underline;" class="wixui-rich-text__text">[29]</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dostrzegając pozytywne skutki dynamicznego rozwoju partycypacji młodzieży na poziomie centralnym, uwaga pełnomocnika rządu ds. polityki młodzieżowej skoncentrowała się na wzmocnieniu partycypacji młodzieży we władzy na poziomie samorządowym.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W związku z tym przedstawiono projekt ustawy nowelizujący cztery ustawy: o samorządzie gminnym, o samorządzie powiatowym, o samorządzie wojew&oacute;dztwa oraz ustawy o działalności pożytku publicznego i o wolontariacie. Ustawa weszła w życie w dniu 23 czerwca 2021 r.<span style="text-decoration:underline;" class="wixui-rich-text__text">[30]</span> Cały proces przygotowania projektu ustawy oraz przebieg procesu legislacyjnego był koordynowany przez pełnomocnika rządu ds. polityki młodzieżowej.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ustawa wprowadziła prawne ramy funkcjonowania młodzieżowych rad i sejmik&oacute;w na poziomie powiat&oacute;w i wojew&oacute;dztw oraz zmodyfikowała dotychczas istniejące przepisy o młodzieżowych radach gmin. Poza uporządkowaniem ustrojowej pozycji młodzieżowych rad i sejmik&oacute;w, zagwarantowaniem obsługi radom i sejmikom ze strony urzęd&oacute;w, w tym finansowania, wprowadzono szereg realnych kompetencji, w szczeg&oacute;lności uprawnienie do:<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><ul class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">wnioskowania o podjęcie inicjatywy uchwałodawczej przez organ stanowiący jednostki samorządu terytorialnego, w kt&oacute;rym działa określona rada bądź sejmik;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">opiniowania projekt&oacute;w uchwał dotyczących młodych mieszkańc&oacute;w;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">udziału w tworzeniu i monitorowaniu samorządowych i rządowych strategii polityki wobec młodzieży;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">inicjowania własnych działań na rzecz młodzieży.<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ul></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wraz z nowelizacją pełnomocnik rządu ds. polityki młodzieżowej przedstawił poradnik pt. &bdquo;Jak założyć młodzieżową radę&rdquo;, kt&oacute;rego celem była promocja wśr&oacute;d młodych os&oacute;b zainteresowanych działalnością społeczną ułatwień w zakresie zakładania młodzieżowych rad oraz przyznanych kompetencji.<span style="text-decoration:underline;" class="wixui-rich-text__text">[31]</span> Założeniem poradnika było szybkie i efektywne implementowanie nowelizacji ustawy.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Działania te przyczyniły się do rozwoju młodzieżowych rad i zostały pozytywnie ocenione:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;23 czerwca 2021 r. odnotowano 242 działające MR (Wyrzykowska, Zapolski-Downar, 2021: 80), natomiast 1 kwietnia 2022 r.&nbsp; &ndash;&nbsp; 324 przypadki w takiej samej grupie badawczej (badania własne z 2022 r.). Nie są to zawrotne liczby, ale należy szczeg&oacute;lnie docenić tutaj strategię władz państwowych, samorządowych oraz ponowną aktywność młodzieży, ponieważ dzięki tym czynnikom w ciągu niecałego roku liczba tak ważnych i obecnie docenionych przez ustawodawcę oraz samorząd terytorialny organ&oacute;w pomocniczych JST wzrosła o ponad jedną trzecią (dokładnie o ok. 34%).&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[32]</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Działalność pełnomocnika rządu ds. polityki młodzieżowej w 2022 roku</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Z uwagi na to, że pełnomocnikowi rządu ds. polityki młodzieżowej udało się bardzo szybko, gdyż już w pierwszym roku działalności, ustrukturyzować i stworzyć podstawy regulacyjne o charakterze ustawowym, drugi rok działalności koncentrował się na wzmacnianiu otoczenia regulacyjnego polityki młodzieżowej:<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">- na szczeblu centralnym poprzez wzrost znaczenia RDzMP;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">- na szczeblach wojew&oacute;dzkich, powiatowych i gminnych poprzez rozw&oacute;j ilościowy i jakościowy młodzieżowych rad i sejmik&oacute;w.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Elementem wzmocnienia partycypacji młodzieży jest r&oacute;wnież przygotowany przez pełnomocnika rządu ds. polityki młodzieżowej Rządowy Program Fundusz Młodzieżowy na lata 2022-2033. Po raz pierwszy publiczne dofinansowania dla projekt&oacute;w społecznych objęty wszelkie poziomy i formy asocjacji młodzieży: od poziomu samorząd&oacute;w uczniowskich, akademickich i doktoranckich, a także młodzieżowych rad na wszystkich szczeblach samorządu terytorialnego, a także organizacje młodzieżowe. Środki przeznaczone na realizację Programu to 10 mln zł w roku 2022, a następnie co roku 20 mln zł.<span style="text-decoration:underline;" class="wixui-rich-text__text">[33]</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Inną formą wzmacniania młodzieżowych rad była Og&oacute;lnopolską Konferencję Młodzieżowych Rad i Środowisk Młodzieżowych, kt&oacute;ra odbyła się 19 września 2022 roku w Kancelarii Prezesa Rady Ministr&oacute;w. Sam wyb&oacute;r miejsca konferencji stanowi symbol partycypacji młodzieży we władzy. W konferencji wzięło udział ok. 350 uczestnik&oacute;w &ndash; młodych działaczy społecznych. Gł&oacute;wnym celem Konferencji była integracja środowisk młodzieżowych oraz dyskusja na temat sposob&oacute;w zwiększenia zaangażowania młodych ludzi w życie publiczne.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W dniu 15 grudnia 2022 roku Sejm RP przyjął niemal jednogłośnie uchwałę w sprawie ustanowienia 19 września Dniem Młodzieżowych Rad i Sejmik&oacute;w przy Jednostkach Samorządu Terytorialnego.<span style="text-decoration:underline;" class="wixui-rich-text__text">[34]&nbsp;</span>W czasie pierwszego i drugiego roku działalności pełnomocnika rządu ds. polityki młodzieżowej podejmowano cały szereg r&oacute;wnież innych aktywności związanych z koordynacją tej polityki publicznej, jednak niniejsza analiza koncentruje się na otoczeniu instytucjonalnym.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Polityka młodzieżowa w ramach Unii Europejskiej</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Z uwagi na to, że niekt&oacute;re z działań z zakresu polityki młodzieżowej realizowane przez Polskę jako państwo członkowskie Unii Europejskiej, zasadne jest kr&oacute;tkie przedstawienie polityki młodzieżowej realizowanej w ramach unii Europejskiej.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Polityka młodzieżowa nie podlega harmonizacji na poziomie Unii Europejskiej z uwagi na to, że jest obszarem polityk państw członkowskich. Podstawą działań organ&oacute;w Unii Europejskiej w obszarze polityki młodzieżowej wyznaczają art. 165-166 Traktatu o funkcjonowaniu Unii Europejskiej. Działania te objęte są zwykłą procedurą ustawodawczą, jednocześnie wskazując na brak harmonizacji prawodawstwa państw członkowskich. Rada może przyjąć zalecenia w oparciu o wnioski Komisji.<span style="text-decoration:underline;" class="wixui-rich-text__text">[35]</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Działania Unii Europejskiej mają r&oacute;żnorodny charakter. Można je podzielić na działania:<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><ol class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">strategiczne;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">finansowe;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">promocyjne.<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ol></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W ramach działań o charakterze strategicznym w dniu 26 listopada 2018 r. Rada przyjęła rezolucję w sprawie nowej strategii UE na rzecz młodzieży na lata 2019-2027.<span style="text-decoration:underline;" class="wixui-rich-text__text">[36]&nbsp;</span>Strategia UE na rzecz młodzieży stanowi ramy dla wsp&oacute;łpracy w zakresie unijnej polityki młodzieżowej na lata 2019&ndash;2027. Wsp&oacute;łpraca na rzecz młodzieży w maksymalnym stopniu wykorzystuje potencjał polityki młodzieżowej. Wspiera uczestnictwo młodzieży w życiu demokratycznym, zaangażowanie społeczne i obywatelskie młodzieży i ma na celu zapewnienie wszystkim młodym ludziom niezbędnych zasob&oacute;w do udziału w życiu społecznym. Strategia UE na rzecz młodzieży skupia się na trzech gł&oacute;wnych obszarach działania, zdefiniowanych trzema słowami: &bdquo;angażowanie&rdquo;, &bdquo;łączenie&rdquo; i &bdquo;wzmacnianie pozycji&rdquo;, przy jednoczesnym działaniu na rzecz wsp&oacute;lnego wdrażania strategii w r&oacute;żnych sektorach. W ramach dialogu prowadzonego w latach 2017&ndash;2018, w kt&oacute;rym uczestniczyli młodzi ludzie z całej Europy, opracowano 11 europejskich cel&oacute;w młodzieżowych. Cele te określają obszary międzysektorowe, kt&oacute;re mają wpływ na życie młodych ludzi, a także wyzwania, kt&oacute;rym należy stawić czoła. Strategia UE na rzecz młodzieży powinna przyczynić się do urzeczywistnienia tej wizji sformułowanej przez młodzież.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W czerwcu 2021 r. w ramach tej strategii Komisja Europejska mianowała pierwszą osobę na funkcję koordynatora Unii Europejskiej ds. młodzieży. Mianowano Bilianę Sirakovą.<span style="text-decoration:underline;" class="wixui-rich-text__text">[37]</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W zakresie działalności finansowej, Unia Europejska prowadzi dwa programy:<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><ul class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Erasmus+</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Europejski Korpus Solidarności<br class="wixui-rich-text__text">
&nbsp;</p>
</li>
</ul></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Program Erasmus+ na lata 2021-2027 przeznacza 10,3% swojego budżetu na działania w sektorze młodzieży, tj. ponad 2,5 mld EUR, co stanowi zdecydowany wzrost w por&oacute;wnaniu z 1,48 mld EUR w latach 2014-2020. Beneficjentami DiscoverEU są uczniowie i studenci, a także stażyści i młodzi pracownicy. W por&oacute;wnaniu z poprzednią edycją Erasmus+ oferuje specjalny system finansowania &bdquo;małych partnerstw&rdquo;, z kt&oacute;rego powinny korzystać w szczeg&oacute;lności organizacje młodzieżowe. Jednym z cel&oacute;w programu jest r&oacute;wnież rozwijanie poczucia przynależności do Unii Europejskiej, w oparciu o nową inicjatywę o nazwie &bdquo;DiscoverEU&rdquo;, kt&oacute;ra daje młodym ludziom możliwość odkrywania r&oacute;żnorodności Europy poprzez jej dziedzictwo kulturowe.<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Europejski Korpus Solidarności, uruchomiony w grudniu 2016 r., jest inicjatywą mającą na celu umożliwienie osobom młodym (w wieku od 18 do 35 lat) uczestnictwa w działaniach solidarnościowych w ich kraju lub za granicą w drodze wolontariatu, stażu lub umowy o pracę. Do chwili obecnej z programu skorzystało już ponad 60 tys. młodych ludzi.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Pozostałe działania Unii Europejskiej można określić zbiorczo jako działania o charakterze promocyjnym. Nalezą do nich m.in. Europejski Portal Młodzieżowy, Europejski Tydzień Młodzieży, Europejski Rok Młodzieży 2022, Europejska Stolica Młodzieży.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">Wnioski i podsumowanie analizy</span><br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Przedstawiony w niniejszej analizie przegląd dotychczasowej realizacji polityki młodzieżowej przez władze publiczne przed i po 2015 roku, opinii przedstawicieli doktryny prawa oraz ekspert&oacute;w, prowadzi do następujących wniosk&oacute;w:<br class="wixui-rich-text__text">
&nbsp;</p></p>
<p style='text-align: justify;'><ul class="font_8 wixui-rich-text__text" style="font-size:18px;">
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">W latach 1989-2002 nie istniała strategia na rzecz młodzieży, kolejne rządy nie realizowały żadnej konkretnej wizji polityki młodzieżowej, nie powstały r&oacute;wnież partycypacyjne organy dla młodzieży; do 2001 roku r&oacute;wnież legalność powoływania młodzieżowych rad gminnych była kwestionowana przez orzecznictwo i doktrynę;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rozpoczęcie akcesji do Unii Europejskiej rozpoczęło w Polsce rozw&oacute;j polityki młodzieżowej, efektem czego było przyjęcie &bdquo;Strategii Państwa dla Młodzieży na lata 2003&ndash;2012&rdquo;; z uwagi na brak zainteresowania kolejnych rząd&oacute;w, powyższy dokument pozostał zbiorem deklaracji; gł&oacute;wnymi słabościami strategii był brak organ&oacute;w partycypacji młodzieży we władzy, brak obecności młodzieży w organach doradczych, a także po stronie rządowej brak wydzielonej i odpowiednio umocowanej instytucji koordynującej politykę młodzieżową;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">W latach 2007-2015 rządy koalicji Platformy Obywatelskiej i Polskiego Stronnictwa Ludowego (premiera Donalda Tuska i premier Ewy Kopacz) pomimo licznych głos&oacute;w ekspert&oacute;w oraz środowisk młodzieżowych, miały lekceważący stosunek do polityki młodzieżowej; nie powołano w tym czasie żadnych organ&oacute;w partycypacji młodzieży we władzy, za reprezentację młodzieży arbitralnie uznano PROM (powstałą w 2011 roku), co było kwestionowane przez liczne środowiska młodzieżowe; w 2012 roku zakończono działalność Departamentu Młodzieży i Organizacji Pozarządowych powołanego dwa lata wcześniej w Ministerstwie Edukacji Narodowej w celu realizacji założeń polityki młodzieżowej, co dobitnie stanowi podsumowanie działalności rząd&oacute;w PO-PSL w zakresie polityki młodzieżowej;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Przejęcie władzy po 2015 roku przez Prawo i Sprawiedliwość spowodowało dynamiczny rozw&oacute;j polityki młodzieżowej (sensu stricto i sensu largo);</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Powołano trzy młodzieżowe rady o charakterze sektorowym (działające jako organy doradcze przy ministerstwach): Rada Dzieci i Młodzieży przy Ministerstwo Edukacji i Nauki, Młodzieżowa Rada Klimatyczna przy Ministerstwie Klimatu i Środowiska, Młodzieżowa Rada Sprawiedliwości przy Ministrze Sprawiedliwości; funkcjonowanie młodzieżowych rad sektorowych pozwala na partycypację młodzieży w sprawach o bardzo ścisłym i branżowym charakterze, co należy uznać za zaletę; ryzykiem wobec funkcjonowania młodzieżowych rad przy ministerstwach może być chęć wykorzystywania młodzieży przez ministerstwa instrumentalnie do cel&oacute;w bieżącej polityki, co może podważać zaufanie młodzieży do polityki młodzieżowej; aby ograniczyć ww. ryzyko, młodzieżowe rady przy ministerstwach zasadne jest, aby ww. rady były koordynowane przez ministerstwa oraz pełnomocnika rządu ds. polityki młodzieżowej oraz Radę Dialogu z Młodym Pokoleniem, jako organy wyspecjalizowane i dedykowane do realizacji polityki młodzieżowej;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rada Dialogu z Młodym Pokoleniem stała się gł&oacute;wnym organem partycypacji młodzieży we władzy i pomimo jej doradczego charakteru zyskała powszechne uznanie jako reprezentacja młodzieży; za niezasadne należy uznać pojedyncze głosy wskazujące na braku pluralizmu członk&oacute;w RDzMP, tym bardziej, że jest to organ co do zasady doradczy i konsultacyjny i ten charakter wyznacza r&oacute;wnież skład, kt&oacute;rego celem jest realizacja tej funkcji, a nie przenoszenie sporu politycznego na poziom polityki młodzieżowej, tym bardziej, że paradoksalnie to może negatywnie odbić się na postrzeganiu przez młodzież tej polityki publicznej oraz samej RDzMP;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Z uwagi na to, że RDzMP oraz młodzieżowe rady sektorowe mają charakter organ&oacute;w doradczych, kt&oacute;rych skład jest kreowany przez stronę rządową przy udziale czynnika społecznego (pozarządowego), zasadne wydaje się rozważenie wykorzystania potencjału młodzieży działającej w ramach młodzież&oacute;wek partyjnych oraz środowiskach politycznych związanych z partiami politycznymi, poprzez powołanie przy Sejmie RP (poprzez nowelizację Regulaminu Sejmu RP) stałego gremium, w skład kt&oacute;rego wchodzić będą młodzieżowi przedstawiciele partii politycznych w proporcji odpowiedniej do wynik&oacute;w wybor&oacute;w parlamentarnych; tak powołana rada/komisja w Sejmie RP stanowić będzie organ doradczy dla parlamentu, z uprawnieniem do opiniowania ustaw odnoszących się do młodzieży; taka zmiana może spowodować wzrost znaczenia młodzieży zaangażowanej politycznie; problem ten wymaga jednak szerszej dyskusji i określenia celowości z uwagi na to, że obecnie już partie polityczne mogą korzystać z doradczego głosu swoich młodzież&oacute;wek i nie wymaga to powoływania og&oacute;lnopolskiej reprezentacji;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kluczową funkcje w zakresie koordynowania polityki młodzieżowej pełni z sukcesem pełnomocnik rządu ds. polityki młodzieżowej; dwa lata działalności wykazały na skuteczność doboru takiej formuły koordynacji międzyresortowego charakteru tej polityki publicznej;</p>
</li>
<li class="wixui-rich-text__text">
<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Z uwagi na bardzo szeroki charakter i rozw&oacute;j polityki młodzieżowej zasadne wydaje się przeprowadzenie ewaluacji na początku 2024 roku i w zależności od jej wynik&oacute;w: bądź to utrzymanie formuły pełnomocnika rządu ds. polityki młodzieżowej przy jednoczesnym zwiększeniu jednostek organizacyjnych KPRM podlegających pełnomocnikowi lub włączenie polityki młodzieżowej do jednego z resort&oacute;w, w kt&oacute;rych pełnomocnikiem ds. polityki młodzieżowej byłby jeden z wiceministr&oacute;w jako działu administracji rządowej; to drugie rozwiązanie wydaje się być zabiegiem ryzykownym, gdyż z poziomu KPRM łatwiej o koordynację polityki młodzieżowej jako polityki wielosektorowej; wątpliwości budzi r&oacute;wnież wyodrębnienie polityki młodzieżowej jako działu administracji rządowej.</p>
</li>
</ul></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[1]</span> A. Kołomycew, Formalno-organizacyjne uwarunkowania polityki młodzieżowej na poziomie europejskim, krajowym i regionalnym, [w:] &bdquo;Polityka i Społeczeństwo&rdquo;, nr 4(11) / 2013, s. 33-34; A. Gąsior-Niemiec, A. Kołomycew, B. Kotarba, Polityka młodzieżowa &ndash; wymiar krajowy i europejski, Rzesz&oacute;w 2014, s. 10-11.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[2]</span> &bdquo;Biała księga. Nowe impulsy dla młodzieży europejskiej&rdquo;, przyjęta przez Komisję Europejską 21 listopada 2001 roku</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[3]</span> Strategia Państwa dla Młodzieży na lata 2003&ndash;2012.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[4]</span> A. Gąsior-Niemiec, A. Kołomycew, B. Kotarba, Polityka młodzieżowa &ndash; wymiar krajowy i europejski, Rzesz&oacute;w 2014, s. 58&ndash;60.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[5]</span> A. Kołomycew, op. cit., s.39.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[6]</span> A. Gąsior-Niemiec, A. Kołomycew, B. Kotarba, op. cit., s. 57&ndash;58</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[7]</span> A. Gąsior-Niemiec, A. Kołomycew, B. Kotarba, op. cit., s. 64&ndash;65;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[8]</span> G. Zielińska, Rola państwa w realizacji polityki młodzieżowej, [w:] &bdquo;Polityka młodzieżowa&rdquo;, red. G. Zielińska, &bdquo;Studia BAS. Biuro Analiz Sejmowych Kancelarii Sejmu&rdquo;, nr 2(18), Warszawa 2009, s. 144.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[9]</span> M. Konieczny, Polityka Młodzieżowa w Polsce &ndash; podstawowe zagadnienia, [w:] M. Jeżowski, J. Dąbrowska-Resiak (red.), Polityka młodzieżowa w Polsce. Encyklopedia Komisji Europejskiej Youth Wiki, Warszawa 2019, s. 16.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[10]</span> Krajowy Program na Rzecz Młodzieży. Aktywna Młodzież, Projekt z 16 września 2013 roku, Warszawa 2013.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[11]</span> Dalej jako: &bdquo;MPiPS&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[12]</span> Zarządzenia nr 31 z dnia 27 sierpnia 2015 roku MPiPS w sprawie przyjęcia Programu Aktywności Społecznej Młodzieży na 2015 r., Dziennik Urzędowy MPiPS z dnia 28 sierpnia 2015, poz. 34.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[13]</span> Dalej jako: &bdquo;RDiM&rdquo;. Aktualna nazwa to: Rada Dzieci i Młodzieży przy Ministrze Edukacji i Nauki.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[14]</span> Zarządzenie Ministra Edukacji i Nauki z dnia 11 stycznia 2022 r. w sprawie powołania Rady Dzieci i Młodzieży Rzeczypospolitej Polskiej przy Ministrze Edukacji i Nauki, Dziennik Urzędowy Ministra Edukacji i Nauki z dnia 11 stycznia 2022 r., poz. 2.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[15]</span> Dalej jako: &bdquo;RDzMP&rdquo;, &bdquo;Rada&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[16]</span> W szczeg&oacute;lności program &bdquo;Wizja Młodego Pokolenia&rdquo; z 2015 roku przygotowany przez Stowarzyszenie KoLiber, Stowarzyszenie Studenci dla Rzeczypospolitej oraz Stowarzyszenie Młodzi dla Polski.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[17]</span> Ustawa z dnia 19 lipca 2019 r. o zmianie ustawy o działalności pożytku publicznego i o wolontariacie, Dz.U. 2019 poz. 1570.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[18]</span> Dotychczas nie funkcjonował żaden organ w zakresie polityki młodzieżowej o tak znaczącej randze biorąc pod uwagę hierarchię źr&oacute;deł prawa.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[19]</span> Tak w doktrynie m.in. H. Taładaj, Rozważania de lege lata i de lege ferenda na bazie pierwszych doświadczeń z funkcjonowania Rady Dialogu z Młodym Pokoleniem, [w:] &bdquo;Przegląd Prawa Publicznego&rdquo;, 2021, nr 4, s. 100-112.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[20]</span> Ustawa z dnia 24 kwietnia 2003 r. o działalności pożytku publicznego i o wolontariacie, tj. Dz.U. z 2022 r. poz. 1327 z p&oacute;źn. zm.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[21]</span> &sect; 14 ust. 1 Rozporządzenia Przewodniczącego Komitetu do spraw Pożytku Publicznego z 10.09.2019 r. w sprawie Rady Dialogu z Młodym Pokoleniem (Dz.U. poz. 1743) oraz &sect; 2 ust. 1&ndash;3 Regulaminu RDzMP (przyjęty jako uchwała Rady).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[22]</span> H. Taładaj, Rozważania de lege lata i de lege ferenda na bazie pierwszych doświadczeń z funkcjonowania Rady Dialogu z Młodym Pokoleniem, [w:] &bdquo;Przegląd Prawa Publicznego&rdquo;, 2021, nr 4, s. 100-112.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[23]</span> Zarządzenie Ministra Klimatu z dnia 30 marca 2020 r. w sprawie powołania Młodzieżowej Rady Klimatycznej, Dziennik Urzędowy Ministerstw Klimatu i Środowiska z 2020 r., poz. 20.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[24]</span> Zarządzenie Ministra Sprawiedliwości z dnia 21 grudnia 2020 r. w sprawie powołania Młodzieżowej Rady Sprawiedliwości, Dziennik Urzędowy Ministerstwa Sprawiedliwości z 2020 r. poz. 264.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[25]</span> Model ten funkcjonował w Polsce w schyłkowym okresie PRL. W latach 1982-1989 za politykę młodzieżową odpowiadał minister ds. młodzieży. W zakresie kompetencji ministra ds. młodzieży należało inicjowanie i wsp&oacute;łpraca z organami państwowymi w prowadzeniu przedsięwzięć na rzecz młodych ludzi. Przedsięwzięcia te dotyczyły m.in. wychowania i kształcenia dzieci i młodzieży, ochrony zdrowia, sportu, rekreacji i wypoczynku, świadczeń socjalnych i ochrony młodej rodziny, polityki mieszkaniowej. Po transformacji ustrojowej w Polsce urząd ministra ds. młodzieży nie został już powołany. M. Raczek, Polityka na rzecz młodzieży w Polsce, [w:] Polityka młodzieżowa Unii Europejskiej, M. Boryń, B. Duraj, S. Mrozowska (red.), Toruń 2014 s. 142&ndash;144. Obecnie jako przykład koordynacji polityka ds. młodzieży w formie odrębnego ministerstwa wskazać można m.in. Federalne Ministerstwo do Spraw Kobiet, Młodzieży i Senior&oacute;w w Republice Federalnej Niemiec, Ministerstwo Zasob&oacute;w Ludzkich w Republice Węgier, Ministerstwo Edukacji Narodowej, Młodzieży i Sportu we Francji.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[26]</span> Jako przykład realizacji ten koncepcji posłużyć może m.in. Międzyresortowa Komisja ds. Młodzieży w Hiszpanii, Izba Młodzieży w Republice Czeskiej (mająca charakter mieszany &ndash; składa się z przedstawicieli rządu oraz strony pozarządowej).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[27]</span> Rozporządzenie Rady Ministr&oacute;w w sprawie ustanowienia Pełnomocnika Rządu do spraw polityki młodzieżowej z dnia 22 września 2020 r. (Dz.U. z 2020 r. poz. 1631).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[28]</span> &bdquo;Sprawozdanie z działalności Pełnomocnika Rządu do spraw polityki młodzieżowej Piotra Mazurka za okres od 1 stycznia 2021 r. do 31 grudnia 2021 r.&rdquo; Dostęp bezpośredni:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.gov.pl/web/dlamlodych/sprawozdanie-pelnomocnika-rzadu-ds-polityki-mlodziezowej-za-rok-2021" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.gov.pl/web/dlamlodych/sprawozdanie-pelnomocnika-rzadu-ds-polityki-mlodziezowej-za-rok-2021</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[29]</span> H.K. Liu, Crowdsourcing: Citizens as coproducersof public services, [w:] &bdquo;Policy&amp;Internet&rdquo;, Volume13, Issue2, June 2021, s. 315-331; S. Hajduk, Crowdsourcing obywatelski w zarządzaniu przestrzennym &ndash; przegląd działań samorząd&oacute;w, [w:] &bdquo;Zeszyty Naukowe Politechniki Poznańskiej&rdquo;, Nr 81, 2020 rok, 62-70; D. Rzeczkowski, Zastosowanie crowdsourcingu sieciowego w administracji publicznej, [w:] &bdquo;Roczniki Kolegium Analiz Ekonomicznych / Szkoła Gł&oacute;wna Handlowa&rdquo;, nr 36 pn. Kierunki rozwoju społeczeństwa informacyjnego w warunkach globalizacji, Warszawa 2015, s. 197-204.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[30]</span> Za przyjęciem rządowego projektu ustawy w Sejmie zagłosowało 446 posł&oacute;w (5 było przeciw), natomiast w Senacie aprobatę dla przyjęcia ustawy bez poprawek wyraziło 49 senator&oacute;w (48 było przeciw, 2 się wstrzymało). Ustawa została podpisana przez Prezydenta RP Andrzeja Dudę 1 czerwca podczas uroczystości w ogrodach Pałacu Prezydenckiego.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[31]</span> Poradnik &bdquo;Jak założyć młodzieżową radę?&rdquo;, <a data-auto-recognition="true" href="https://www.gov.pl/web/dlamlodych/mlodziezowerady" target="_blank" class="wixui-rich-text__text">https://www.gov.pl/web/dlamlodych/mlodziezowerady</a></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[32]</span> J. Zapolski-Downar, Wpływ pandemii COVID-19 na regulację działalności młodzieżowych rad w Polsce oraz ocena przyjętych rozwiązań, [w:] &bdquo;Studia z Polityki Publicznej&rdquo;, v. 9 nr. 3(35)/2022, s. 114.&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[33]</span> Uchwała Rady Ministr&oacute;w nr 159/2022 w sprawie przyjęcia programu wspierania rozwoju społeczeństwa obywatelskiego pod nazwą &bdquo;Rządowy Program Fundusz Młodzieżowy na lata 2022&ndash;2033&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Rządowy Program Fundusz Młodzieżowy na lata 2022&ndash;2033; Rządowy Program Fundusz Młodzieżowy na lata 2022&ndash;2033, dostęp bezpośredni: <span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.gov.pl/web/pozytek/rzadowy-program-fundusz-mlodziezowy-na-lata-20222034" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.gov.pl/web/pozytek/rzadowy-program-fundusz-mlodziezowy-na-lata-20222034</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[34]</span> Wyb&oacute;r dnia 19 września wynika z tego, że to właśnie 19 września 1990 roku powstała pierwsza w Polsce młodzieżowa rada miasta. Tego dnia Rada Miasta Częstochowy podjęła uchwałę, na mocy kt&oacute;rej powołała Rady: Dziecięcą i Młodzieżową Miasta Częstochowy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[35]</span> TFUE</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[36]</span> Rezolucja Rady Unii Europejskiej i przedstawicieli rząd&oacute;w państw członkowskich zebranych w Radzie w sprawie ram europejskiej wsp&oacute;łpracy na rzecz młodzieży: Strategia Unii Europejskiej na rzecz młodzieży 2019-2027, Dziennik Urzędowy Unii Europejskiej, C 456, 18 grudnia 2018 r.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[37]</span> Pochodzi z Bułgarii. Od 2010 roku jest urzędnikiem służby cywilnej Unii Europejskiej.</p></div><!--/$--></div></div></div><!--/$--></div></section><!--/$--><!--/$--></div></div></section><!--/$-->



