
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text"><span class="wixGuard wixui-rich-text__text">​</span></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Czy ten ptak kala gniazdo, co je kala,</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;Czy ten, co m&oacute;wić o tym nie pozwala?</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">C. K. Norwid</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">1. Uniwersytet tw&oacute;rczy (klasyczny) i uniwersytet merkantylny (nowoczesny)</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Od stu lat m&oacute;wi się o kryzysie uniwersytetu<span style="text-decoration:underline;" class="wixui-rich-text__text">[1]</span>, to jest o sukcesywnym jego przechodzeniu od modelu klasycznego (UK) do nowoczesnego (UN). W XXI wieku punkt krytyczny wszakże został przekroczony &ndash; i &bdquo;uniwersytet klasyczny (&hellip;) praktycznie przestaje istnieć&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[2]</span>. Tak stawia sprawę, przykładowo, prof. Jan Szmyd (podobnie prof. Bogusław Wolniewicz, o czym dalej będzie mowa). Czytamy, że UK &ndash; powołany w średniowieczu przez Kości&oacute;ł katolicki &ndash; stał na dw&oacute;ch ideach: &bdquo;niczym nie ograniczonej dostępności dla os&oacute;b do studiowania predysponowanych&rdquo; (w ich predyspozycjach tkwiła jego elitarność) oraz na &bdquo;samoistnej wartości studi&oacute;w&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[3]</span>. W uniwersytecie był obecny &bdquo;duch&rdquo; &ndash; co polegało na &bdquo;niezachwianym pragnieniu student&oacute;w &ndash; pozyskiwania wiedzy od wybranych przez siebie mistrz&oacute;w&rdquo;, a z drugiej strony &ndash; na wpajaniu młodzieży &bdquo;bezkompromisowego służenia prawdzie obiektywnej&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[4]</span>. &bdquo;Duch&rdquo; tkwił w więzi mistrz-uczeń. Taki model uniwersytetu uosabiali u nas jeszcze Kotarbiński czy Tatarkiewicz i było to nadal odczuwalne w latach 80. XX w. Uniwersytet dzisiejszy natomiast (UN) jest bezduszny i stale obniża poziom nauczania: &bdquo;przygotowuje &ndash; jedynie, ale masowo &ndash; zasoby ludzkie na rynek pracy&rdquo;. &bdquo;Ducha&rdquo; zabija w nim &bdquo;bezwzględny ekonomizm i ofensywny biurokratyzm, centralistyczny polityzm i nadmierne administrowanie, rygorystyczny rachunek ekonomiczny (&hellip;), (oraz &ndash; P. O.) ponowoczesny technologiczny mit pedagogiczny&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[5]</span>. Ot&oacute;ż nowoczesny uniwersytet &bdquo;toczą dwie groźne choroby: grantoza i punktoza&rdquo;, owocujące pseudoosiągnięciami; kwitnie w nim &bdquo;komercjalizacja nauki, konformizm, i marazm&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[6]</span>. Przy okazji przemiany uniwersytetu w merkantylny można wręcz m&oacute;wić o &bdquo;wielkim paradoksie&rdquo; &ndash; na tym polegającym, że wysoko rozwinięte społeczeństwo technologiczne, podlegając siłom przez siebie wytworzonym, ruguje z siebie to, co je powołało i co do własnego przetrwania jest niezbędne: tendencje tw&oacute;rcze<span style="text-decoration:underline;" class="wixui-rich-text__text">[7]</span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Podobnie stawia sprawę Bogusław Wolniewicz. Czytamy: &bdquo;(&hellip;) Uniwersytety utraciły już swoją duchową autonomię (&hellip;). (&hellip;) A najbardziej zatrważające jest to, że bezczelne zamachy biurokracji państwowej na wolność nauki i nauczania nie natrafiają wewnątrz uczelni na żaden prawie op&oacute;r. W każdym razie jest on mniej wyczuwalny dziś, niż był za komuny.&rdquo;. (&hellip;) (Z drugiej strony autor powiada o profesurze &ndash; P. O.:) &bdquo;Nowoczesna cywilizacja utrzymuje darmozjad&oacute;w&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[8]</span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Definitywne przejście od UK do UN (od tw&oacute;rczego do merkantylnego) zwykle charakteryzowane jest w literaturze &bdquo;objawowo&rdquo;, poprzez wskazywanie negatywnych efekt&oacute;w działalności dzisiejszych uniwersytet&oacute;w albo, jak u abp Wielgusa<span style="text-decoration:underline;" class="wixui-rich-text__text">[9]</span>, przez kazanie &ndash; wykład pozytywnych dyrektyw, kt&oacute;re zostały poniechane. Uczeni mianowicie nie troszczą się już o &bdquo;fakty światłodajne&rdquo;, a jedynie o &bdquo;owocodajne&rdquo; (F. Bacon). Przyczyny og&oacute;lne tej destrukcji są wiadome &ndash; to zasadnicza przemiana stylu życia na Zachodzie, z jego egalitaryzmem na czele. Jaki był wszak faktyczny mechanizm funkcjonowania UK, a jaki jest UN? Jakie konkretnie zmiany w mechanizmie działania uniwersytetu sprawiły tę destrukcyjną transformację: uwiąd wiedzy i dewastację kultury? Co sprawiło, m&oacute;wiąc słowami Mikołaja Wawiłowa, że &ndash; bez Gułagu &ndash; &bdquo;w nauce następuje dob&oacute;r ludzi bez genu przyzwoitości&rdquo;?<span style="text-decoration:underline;" class="wixui-rich-text__text">[10]</span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 2. Wymiana struktury uniwersytetu</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Uniwersytet (UK) to był universitas magistrorum et scholarum &ndash; &bdquo;og&oacute;ł nauczycieli i uczni&oacute;w&rdquo;, czyli tych &ndash; kt&oacute;rzy się do obu r&oacute;l nadają i faktycznie je wykonują. Z drugiej strony &ndash; universitas scientiarum et scholarum &ndash; &bdquo;wsp&oacute;lnota nauk i uczonych&rdquo;, gdzie nie o jedność uczonych między sobą chodziło, a o ich zasadniczą więź &ndash; każdego z osobna &ndash; z naukami. Po trzecie, uniwersytet to officina humanitatis &ndash; warsztat człowieczeństwa<span style="text-decoration:underline;" class="wixui-rich-text__text">[11]</span>, miejsce przysposabiające do wyższej kultury &ndash; jak m&oacute;wi Wolniewicz: wydające &bdquo;tych, kt&oacute;rzy (przynajmniej &ndash; P. O.) wytw&oacute;r geniuszu zdolni są pojąć i docenić&rdquo;.<span style="text-decoration:underline;" class="wixui-rich-text__text">[12]</span> Ot&oacute;ż uniwersytet (UK) miał, biorąc pod uwagę jego podstawową jednostkę organizacyjną, tj. wydział (W), następującą strukturę.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="text-align:center; font-size:18px;">Rys. 1. Rozkład sił (kolektywnych dążeń) w obrębie wydziału uniwersytetu (UK).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="text-align:center; font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Wydział tradycyjnie dzielił się na grupy zwolennik&oacute;w określonych styl&oacute;w myślowych, i jednocześnie życiowych. Zazwyczaj podział ten pokrywał się z administracyjnym &ndash; na zakłady czy katedry &ndash; ale zdarzały się też kolektywy tego typu międzyzakładowe. Na rysunku określiliśmy je umownie jako &bdquo;platończyk&oacute;w&rdquo;, &bdquo;stoik&oacute;w&rdquo; itd., choć w rzeczywistości byli to tomiści, egzystencjaliści, freudyści, marksiści czy scjentyści, a na dowolnym wydziale &ndash; X-iści albo Y-owcy, od nazwiska swego duchowego przyw&oacute;dcy<span style="text-decoration:underline;" class="wixui-rich-text__text">[13]</span>. Na czele każdej takiej formacji stał bowiem mistrz &ndash; herezjarcha (H), wok&oacute;ł kt&oacute;rego gromadzili się pracownicy naukowi, a dalej studenci, na zasadzie wsp&oacute;lnoty i jej sympatyk&oacute;w. (Nie zawsze herezjarcha był kierownikiem formalnie). Wydział (a więc i uniwersytet cały) stanowił stowarzyszenie wsp&oacute;lnot &ndash; samorzutnie wyrastających mocą łączących ich członk&oacute;w spontanicznych dążeń. (Stosujemy tu teoretyczne rozr&oacute;żnienie F. T&ouml;nniesa na wsp&oacute;lnoty i stowarzyszenia). Każda ze wsp&oacute;lnot zmierzała do obiektywnej prawdy w danej dziedzinie, jednakże osobną drogą. Łącznie stanowiły zaś stowarzyszenie &ndash; ustanowione przez ludzi deklarujących jako cel gł&oacute;wny wolne poszukiwanie prawdy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Wsp&oacute;lnoty poznawcze (W1, W2, itd.) rywalizowały ze sobą &bdquo;o prawdę&rdquo; (co symbolizują podw&oacute;jne między grupami wektory na rysunku) &ndash; osiągnięciami, poprzez własne idee ogłaszane w artykułach i książkach. Bywały te &bdquo;klany&rdquo; często zwaśnione. Jednocześnie solidarnie wydawały z siebie Radę Wydziału (RW &ndash; grono pracownik&oacute;w samodzielnych) jako &bdquo;starszyznę&rdquo; całego stowarzyszenia. Powoływały też jej głosami dziekana (Dz) jako reprezentanta woli RW. Ot&oacute;ż negatywna presja wywierana spoza uniwersytetu na jego pracownik&oacute;w &ndash; ze strony rządu czy Kościoła (P + K), a także centralnej administracji uczelni &ndash; blokowana była przez &bdquo;cichy, a stanowczy op&oacute;r&rdquo; Rady Wydziału (w tajnych głosowaniach) oraz wyartykułowane stanowisko dziekana. Hamowana była w ten spos&oacute;b przemożna siła ograniczająca samorządność uczelni, przede wszystkim usiłująca zniszczyć owo status quo &ndash; harmonijną acz dynamiczną r&oacute;wnowagę w strukturze duchowej wydziału. Dokąd RW złożona była z ludzi wybrednych (w opozycji do pospolitych &ndash; w sensie Ortegi), samorzutnie utrzymywała tę r&oacute;wnowagę &ndash; pro publico bono &ndash; zależało jej bowiem na promowaniu wybredności, zwłaszcza wok&oacute;ł siebie. I na tym polegała autonomia uniwersytetu, o kt&oacute;rej jeszcze Russell z podziwem pisał: &bdquo;(&hellip;) uniwersytet oksfordzki nie zgodził się uznać jurysdykcji papieża nad swoimi wykładowcami (przy okazji potępienia Wiklefa, w XIV w. &ndash; P.O.). (Nawet w tamtych czasach angielskie uniwersytety wierzyły w wolności akademickie)&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[14]</span>. Słowo &bdquo;nawet&rdquo; w cytacie brzmi dziś jak drwina. Wiary owej od dawna brak. Z pospolitości pleni się tylko pospolitość, za to jak perz.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Zbiorowość akademicka wytwarzała &bdquo;ducha wydziału&rdquo; (DW), tzn. wolę ochrony wolności słowa, i walki na słowa (w ryzach jedynie obyczajności) oraz sp&oacute;jną z nią wolę ochrony autorytet&oacute;w osobowych wraz z miłością do nich. I to się skończyło. Wytworzyła się bowiem trwale struktura uniwersytetu następująca.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="text-align:center; font-size:18px;">Rys. 2. Rozkład sił w obrębie wydziału uniwersytetu merkantylnego (UN).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="text-align:center; font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Ot&oacute;ż dawne wsp&oacute;lnoty (wolne konfraternie czy &bdquo;zakony&rdquo;) przemieniły się w stowarzyszenia. Spośr&oacute;d wielu wyłoniła się frakcja na wydziale dominująca (H), realizująca zadeklarowane, ale i niejawne cele. Są to z ducha &bdquo;świeccy humaniści&rdquo;, niekiedy też zwani &bdquo;zwolennikami Kościoła otwartego&rdquo;, a z litery to, choćby, &bdquo;kognitywiści, empiryści, bioetycy, analitycy, postmoderniści&rdquo; (co modniejsze szyldy). Hegemonowi (H) podporządkowane zostały stowarzyszenia nominalnie odmienne (jacyś tam &bdquo;platończycy&rdquo; itd.), a w istocie satelickie i homogeniczne ideowo. Rada wydziału i instytucja dziekana zostały zawłaszczone, i realizują wolę hegemona, posługując się komisjami wewnętrznymi i zewnętrznymi; przekazują tylko wykaz zdobytych punkt&oacute;w do centrali: od urzędnik&oacute;w szczebla średniego do urzędnik&oacute;w wyższego szczebla &ndash; przyznawanych przez urzędnik&oacute;w szczebla najniższego. Cały ten biurokratyczny aparat pozostaje zaś na pasku administracji państwowej (choćby i prawicowej, to niesuwerennej), czerpiąc od niej profity. Wszystkim zawiaduje natomiast centrala Unii Europejskiej &ndash; wiednie czy bezwiednie, ale w zgodzie z interesem wielkiego kapitału. Uniwersytet stał się stowarzyszeniem stowarzyszeń, tworem w pełni kontrolowanym i sterowanym. Zgaszono w nim wszelką spontaniczność, zatem &ndash; i wsp&oacute;lnotowość, i tw&oacute;rczość, zamieniając je na &bdquo;transfer punkt&oacute;w&rdquo;. &bdquo;Dzieła punktowane&rdquo; (czy raczej produkty) os&oacute;b bądź stowarzyszeń z uniwersytetu nie są już &ndash; jak dawniej &ndash; nagradzane &bdquo;po fakcie&rdquo; i przez og&oacute;ł wolnych ludzi rozumnych, ale przez garstkę zależnych urzędnik&oacute;w i &bdquo;przed faktem&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Proces ten zachodził kilkadziesiąt lat i miał charakter &bdquo;konia trojańskiego&rdquo;. Tę pułapkę wymuszały wprawdzie obiektywne i niezależne od ludzi zjawiska społeczne (przede wszystkim postęp technologiczny), ale była ta matnia na rękę konkretnym siłom (mianowicie kapitałowi). To tak jakby wiedząc, że idą powodzie, celowo nie umacniać wał&oacute;w. Chronologia zaś tego destrukcyjnego procesu była następująca. Wpierw sukcesywnie wzmagano napęd czy żer dla &bdquo;nowych pan&oacute;w&rdquo; &ndash; tj. biurokratycznie reglamentowane gratyfikacje. (U nas nastąpiło to za Gierka). Wiadomo wszakże, że uniwersytety zawsze składały się z ludzi &bdquo;żyjących nauką&rdquo; i &bdquo;żyjących z nauki&rdquo;. (Opisał to w XIX wieku Schopenhauer &ndash; na przykładzie &bdquo;żyjących filozofią&rdquo; i &bdquo;żyjących z filozofii&rdquo;)<span style="text-decoration:underline;" class="wixui-rich-text__text">[15]</span>. Stopniowo następowała więc demoralizacja ekonomiczna uniwersytet&oacute;w &ndash; ustawowo umożliwiająca wybranym &bdquo;robienie w nich pieniędzy&rdquo;: na grantach, doktoratach, recenzjach i &bdquo;turystyce naukowej&rdquo;. Przyciągało to na uczelnie &bdquo;łowc&oacute;w grant&oacute;w&rdquo;, kosztem miłujących prawdę. Rzekomo zwalczając pauperyzację, umożliwiono &bdquo;krezusoizację&rdquo;. Jednocześnie nasycano wyższe uczelnie ideologią lewackiej polit-poprawności, &bdquo;polityką r&oacute;wności&rdquo; (niezwykle popularną, zgodną z duchem czasu, a płynącą z zamożnego Zachodu). W wyniku tego uznawano kultywowanie autorytet&oacute;w za &bdquo;autorytaryzm i sekciarstwo&rdquo; albo &bdquo;kolesiostwo&rdquo;, a wolność słowa i antagonizmy duchowe &ndash; paradoksalnie, za pole walki kryptointeres&oacute;w i &bdquo;mowy nienawiści&rdquo;. Autorytety zastępowano więc rzekomo obiektywnymi komisjami eksperckimi, choć charyzmaty osobowe były jawne, zatem wystawione na rozliczanie, w przeciwieństwie do &bdquo;loży masońskich&rdquo; sterujących komisjami i rozdzielającymi pieniądze pokątnie. Sitwy pozorne a zwaśnione zamieniono na rzeczywiste, ale karne. (To samo gorszące ubezwłasnowolnienie miało miejsce na gruncie czasopism naukowych i wydawnictw &ndash; redaktora naczelnego i kolegium wyparli w decyzjach recenzenci i punkty).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; R&oacute;wnolegle uniwersytety umasowiono, liczba student&oacute;w gwałtownie wzrosła (np. w Niemczech, w latach 1950-1990, piętnastokrotnie; w Polsce tyleż samo w latach 1938-1995, a w kolejnej dekadzie jeszcze trzykrotnie)<span style="text-decoration:underline;" class="wixui-rich-text__text">[16]</span>, co wymogło ogrom dodatkowej pracy, więc i jej podział &ndash; oraz delegowanie w ręce dodatkowo opłacanych komisji. Zlikwidowano zarazem egzaminy wstępne, o przyjęciu na studia decydował odtąd wynik matury (także &bdquo;komisarycznej&rdquo;). Poziom nauczania musiał się w drakoński spos&oacute;b obniżyć<span style="text-decoration:underline;" class="wixui-rich-text__text">[17]</span>. Wystarczyło jeszcze tylko ustawowo zmienić strukturę wydziału &ndash; w zakresie promocji i awansu naukowego &ndash; aby dotychczasowe wzorce wybredności upadły definitywnie. I tak też się stało.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Oto tysiącletnia, subtelna i wyrafinowana, struktura uniwersytetu rozpadła się ostatecznie w wyniku zniszczenia instytucji autorytetu osobowego oraz autonomii Rady Wydziału. Tej ostatniej odebrano bowiem wyłączne prawo awansowania uczonych, a promotorowi &ndash; absolutną niezawisłość w promowaniu uczni&oacute;w, np. w wyznaczaniu recenzent&oacute;w (zanegowano w całości bezinteresowną życzliwość do swoich, jako &bdquo;nepotyzm&rdquo;). Władzę przejęły &bdquo;bezstronne&rdquo; komisje, tj. urzędnicy. A urzędnicy mają zawsze mocodawc&oacute;w, inaczej niż autorytety, choć nie zawsze jawnych. Tym samym unicestwiono nieprzywracalne dobrodziejstwo, złotą &bdquo;zasadę promowania nie gorszych od siebie&rdquo;. Działała ona wprawdzie stochastycznie &ndash; nie wszyscy ją stosowali, ale zawsze ktoś &ndash; gwarantując tym jednakże utrzymanie wysokiego średniego poziomu akademickiego. (Dzięki niej, obok przeciętnych, trafiali się na wydziałach lepsi od promujących). Dominacja osobowości pospolitych wyrugowała z uniwersytetu tę &bdquo;złotą zasadę&rdquo; &ndash; solidarnego głosowania w imię jednakich i stałych kryteri&oacute;w. Jakie to kryteria?</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-weight:bold;" class="wixui-rich-text__text">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 3. Promowanie nie gorszych</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Dwa lata przed wyrzuceniem z uniwersytetu, w artykule Krytyka naukowa i kryteria naukowości (1996) Wolniewicz pisał:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;W prawidłowo funkcjonującym środowisku naukowym (w UK &ndash; P.O.) dominują ci &ndash; bądź dysponując większością głos&oacute;w, bądź mając inaczej większe wpływy &ndash; kt&oacute;rzy skłonni są promować raczej tylko nie gorszych od siebie. (Na tym polega homeostat wysokiego &nbsp; średniego poziomu naukowego &ndash; P.O.). (&hellip;) W środowisku naukowym działa obecnie&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; (w UN &ndash; P.O.) negatywny mechanizm samooczyszczania (&hellip;) (promowanie&nbsp; tylko nie lepszych od siebie)<span style="text-decoration:underline;" class="wixui-rich-text__text">[18]</span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Ale na czym konkretnie polega promowanie &bdquo;nie gorszych od siebie&rdquo;? Potrafi to wprawdzie czynić większość nauczycieli, niejako z natury, choć zwykle bezwiednie. Ujmiemy tę sprawę expressis verbis, na podstawie autopsji: 30 lat własnej pracy naukowo-dydaktycznej, 20 lat &ndash; bycia promotorem (20 prac dyplomowych i 3 doktorskich) oraz 10 lat &ndash; bycia członkiem Rady Wydziału.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><br class="wixui-rich-text__text">
&nbsp; &nbsp; &nbsp; &nbsp; &bdquo;Nie gorszy ode mnie&rdquo; to taki, kt&oacute;ry:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="margin-left:40px; font-size:18px;">1/ nie mniej ode mnie raduje się z pracy w swojej dziedzinie, z własnych pogląd&oacute;w w sprawie (ma w niej czynną wrażliwość, interes osobniczy &ndash; jak upodobanie do konkretnych potraw &ndash; a to owocuje zapałem);</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="margin-left:40px; font-size:18px;">2/ ma &bdquo;potencjał&rdquo;, czyli podatny jest na krytykę mistrza i zdolny do doskonalenia (to predyspozycja ewidentnie intelektualna, ale także ambiwalentna charakterologicznie &ndash; zagrożona oportunizmem, co rozwiewa kryterium kolejne);</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="margin-left:40px; font-size:18px;">3/ wykazuje lojalność względem mistrza (ideową i osobową);</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="margin-left:40px; font-size:18px;">4/ cechuje się tolerancyjnością, rozumianą jako umiar między obojętnością a fanatyczną nienawiścią wobec oponent&oacute;w (nie bywa wobec nich bezwzględny). &bdquo;Nie gorszy&rdquo; zatem to taki, kt&oacute;ry &bdquo;m&oacute;głby mnie zastąpić&rdquo; &ndash; na zasadzie mniej czy bardziej rozległej sukcesji (o tym przez wieki myślano, w społeczności zatomizowanej zaprzestano).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Powyższe cztery predyspozycje ucznia widoczne są dobrze dla nauczyciela w osobistym i nieokazjonalnym z nim kontakcie, niewidoczne są zaś dla biurokracji, na bazie jedynie dokument&oacute;w. Weryfikowalne są one także dla Rady Wydziału &ndash; na podstawie relacji i reakcji promotora, oraz innych, znających osobę ocenianą. Przed Radą Wydziału bowiem, o ile prezentowane są tam osoby 1/ rozmiłowane w problematyce własnej dziedziny, 2/ z potencjałem, 3/ lojalne oraz 4/ umiarowione w postawach, zdobywają powszechne uznanie, niezależnie od przynależności ideowej i grupowej. Charakteryzują się bowiem dyspozycjami partykularnymi (inaczej być nie może), ale uniwersalnymi, wsp&oacute;lnototw&oacute;rczymi, tj. służącymi każdej wsp&oacute;lnocie (jeżeli je do dowolnej odnieść). I jeżeli nawet jakiś promotor daje się promowanemu oszukać (we wskazanych punktach) &ndash; nie ma to znaczenia globalnego. Odbywa się w grupie selekcja pozytywna. Natomiast dominacja pospolitych na uniwersytecie (więc i we wszelkich komisjach) skutkuje ekspansją ludzi: 1&rsquo;/ bez wrażliwości w uprawianej dziedzinie, czyli pozbawionych bezinteresownych skłonności, 2&rsquo;/ niepouczalnych albo służalczych, 3&rsquo;/ zdradliwych, i 4&rsquo;/ bezwzględnych<span style="text-decoration:underline;" class="wixui-rich-text__text">[19]</span>.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Ludzie stosują om&oacute;wione kryteria (1-4) dlatego, że są wybredni, a są wybredni dlatego, że je stosują. Niczego nie można się tej kwestii nauczyć, a jedynie zostać wybranym. Muszą wszak istnieć ramy prawne chroniące to stosowanie. I co ważniejsze &ndash; musi żyć obyczajność, kt&oacute;ra takie ramy ustanawia. A ona na Zachodzie zgasła: i duch wolności, i kult wielkich duch&oacute;w, i rycerskiej walki. Zapewne to wynik średniej życia dobiegającej 80 lat, koszt &bdquo;leczenia śmierci&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Ekspansja miernoty w uniwersytetach<span style="text-decoration:underline;" class="wixui-rich-text__text">[20]</span> przekroczyła &ndash; powt&oacute;rzmy &ndash; punkt krytyczny<span style="text-decoration:underline;" class="wixui-rich-text__text">[21]</span>. Infrastruktura duchowa uniwersytetu została zniszczona, a zmienić ten stan rzeczy mogłaby jedynie &ndash; chroń Panie Boże! &ndash; wojna. Bo ona, m&oacute;wiąc za Tocquevillem, &bdquo;każdego człowieka umieszcza na właściwym miejscu&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[22]</span>. Kiedy całkowicie odcięte zostałyby pieniądze, wszystkie szczury uciekłyby z pokładu,</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">a pozostała jedynie garstka uczonych-zakonnik&oacute;w. Czy nasz pogląd jest defetystyczny? Niekoniecznie. Jak m&oacute;wi Wolniewicz: &bdquo;sumienia nie da się wprawdzie udoskonalić, ale nie da się go też zniszczyć &ndash; nawet gdy ci ze złego nasienia przeważą i dorwą się do władzy&rdquo;<span style="text-decoration:underline;" class="wixui-rich-text__text">[23]</span>. Ale więcej &ndash; odradzanie się ducha może następować poza uniwersytetem (por.: Kartezjusz, Leibniz), dzięki drugiemu fundamentowi natury ludzkiej &ndash; &bdquo;towarzyskości&rdquo; człowieka. Ot&oacute;ż wsp&oacute;lnoty naukowe mogą się rodzić na obrzeżach sfery publicznej, niejako w katakumbach, p&oacute;źniej będąc do niej nawet z pompą inkorporowane (choćby przez Internet).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">2023 (pisane 3 lata) &ndash; tekst referowany był na Seminarium Wolniewiczowskim 2023 (17.06.23.).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text"><a href="https://www.youtube.com/watch?v=gLfFo4nM31s" target="_blank" rel="noreferrer noopener" class="wixui-rich-text__text">https://www.youtube.com/watch?v=gLfFo4nM31s</a></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[1]</span>&nbsp; &nbsp; &nbsp; M&oacute;wił już 200 lat temu Schopenhauer, lecz o kryzysie permanentnym, nie definitywnym (o jego &bdquo;chorobach&rdquo;, nie</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp;&nbsp; o &bdquo;śmierci&rdquo;. Por.: tenże, O filozofii uniwersyteckiej, w: tenże, W poszukiwaniu mądrości życia. Parerga i paralipomena, t.1., przeł. J. Garewicz. Warszawa 2002, s. 179-252.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[2]</span>&nbsp; &nbsp; &nbsp; J. Szmyd, Idea uniwersytetu klasycznego a jakość człowieka, &bdquo;Edukacja Filozoficzna&rdquo;. Wydanie specjalne, 2016, s. 47-76 (cytat, s. 59).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[3]</span>&nbsp; &nbsp; &nbsp; Por.: tamże, s. 64.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[4]</span>&nbsp; &nbsp; &nbsp; Por.: tamże, s. 48; 60.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[5]</span>&nbsp; &nbsp; &nbsp; Por.: tamże, s. 68.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[6]</span>&nbsp; &nbsp; &nbsp; Por.: tamże, s. 67.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[7]</span>&nbsp; &nbsp; &nbsp; Por.: tamże, s. 66.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[8]</span>&nbsp; &nbsp; &nbsp; T. Sommer, B. Wolniewicz, Wolniewicz. Zdanie własne, Warszawa 2010, s. 111-112; 87.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[9]</span>&nbsp; &nbsp; &nbsp; Abp S. Wielgus, Historyczne koncepcje i paradygmaty uniwersytetu oraz jego model na dziś i jutro, &bdquo;Studia Nauk Teologicznych&rdquo; 2008, t. 3, s. 11-22.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[10]</span>&nbsp; &nbsp; Por.: B. Wolniewicz, Filozofia i wartości, II. Warszawa 1998, s. 272.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[11]</span>&nbsp; Por.: abp S. Wielgus, dz. cyt., s. 16.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[12]</span> B. Wolniewicz, Z pedagogiki og&oacute;lnej (2010), w: tenże, Filozofia i wartości. Post factum. Komor&oacute;w 2021, s. 133. &nbsp;&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;&nbsp; W rozprawie tej zawarte są zasadnicze poglądy Profesora na szkolnictwo wyższe; por. też (obok tu cytowanych):</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; tenże, W stronę rozumu. Warszawa 2015 oraz Filozofia i wartości, I; III; IV.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[13]</span>&nbsp; &nbsp; Pamiętam, że w latach 80. w Instytucie Filozofii UW normą byli: &bdquo;legowiczowcy, pelcowcy, przełeńszczycy, kuczyńszczycy, augustynkowcy, jankowicze, siemkowcy czy wolniewiczowcy&rdquo; &ndash; r&oacute;żniący się spontanicznie<br class="wixui-rich-text__text">
i bezinteresownie. Dzisiaj studenci m&oacute;wią mi, że takie &bdquo;szkoły to absurd&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[14]</span>&nbsp; &nbsp; B. Russell, Dzieje filozofii Zachodu, przeł. T. Baszniak i in. Warszawa 2000, s. 560.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[15]</span>&nbsp; &nbsp; Por.: A. Schopenhauer, dz. cyt., s. 231.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[16]</span>&nbsp; &nbsp; Por.: abp S. Wielgus, dz. cyt., s. 14.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[17]</span>&nbsp; &nbsp; To dlatego, choćby, studenci przed dyplomem często proszą (przypadkowego) promotora &bdquo;o wskazanie tematu&rdquo;, kiedy jego zadaniem jest wyłącznie nadzorowanie i ocena sposobu prezentacji. Niekiedy &bdquo;tematy&rdquo; prac są studentom oficjalnie podawane, jak w sklepie czy fabryce.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[18]</span>&nbsp; &nbsp; B. Wolniewicz, Filozofia i wartości, II, dz. cyt., s. 271-271.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[19]</span>&nbsp; &nbsp; Przez 10 lat ani razu nie słyszałem na Radzie Wydziału o jakiejkolwiek &bdquo;wybitnej polskiej książce naukowej&rdquo;,</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp; &nbsp; &nbsp; &nbsp; a jedynie o &bdquo;prestiżowych nagrodach&rdquo;; o kryteriach 2/, 3/ i 4/ w og&oacute;le nie wspomnę.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[20]</span>&nbsp; &nbsp; Zdarzają się w uniwersytecie merkantylnym ludzie wybitni, ale ich los podobny jest do losu polskich patriot&oacute;w<br class="wixui-rich-text__text">
w państwach zaborczych.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[21]</span>&nbsp; &nbsp; Nie dotyczy to wydział&oacute;w nauk ścisłych uniwersytet&oacute;w najlepszych, prywatnych, zwłaszcza amerykańskich. Na nich struktura tradycyjna z autonomią została zachowana &ndash; jako jedyna efektywna. Tylko wysoki poziom nauki służyć może bowiem wprost interesom wielkiego kapitału; w przypadku humanistyki &ndash; niski poziom, i pośrednio.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[22]</span>&nbsp; &nbsp; A. de Tocqueville, O demokracji w Ameryce, przeł. M. Kr&oacute;l. Warszawa 1976, s. 443.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="text-decoration:underline;" class="wixui-rich-text__text">[23]</span>&nbsp; &nbsp; B. Wolniewicz, Parę uwag o naturze sumienia, w: tenże, Filozofia i wartości, II, dz. cyt., s. 205.</p></div><!--/$--><!--$--><div id="comp-llowbfrv" class="MazNVa comp-llowbfrv wixui-image"><div data-testid="linkElement" class="j7pOnl">




