
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Atak hakera, zgubiona korespondencja, niezabezpieczone dane na serwerze, a nawet pozostawione na chwilę bez opieki dokumenty czy telefon &ndash; są to sytuacje, w kt&oacute;rych osoby do tego nieuprawnione najczęściej wchodzą w posiadanie danych osobowych. Choć wiele os&oacute;b nadal stara się tego nie zauważać, Internet jest areną działań szpieg&oacute;w i cyberprzestępc&oacute;w z całego świata, ale nie tylko ich. Można śmiało postawić tezę, że wraz z rozwojem medi&oacute;w społecznościowych dane - zar&oacute;wno te jawne, jak i poufne, kt&oacute;re powinny być szczeg&oacute;lnie chronione - często są dostępne dosłownie na wyciągnięcie ręki. U podstaw problemu leży brak świadomości realności zagrożenia i jego skali. To z kolei powoduje, że jesteśmy skłonni do udostępniania informacji, kt&oacute;re jeszcze kilkadziesiąt, a nawet kilkanaście lat temu uzyskać było niezwykle trudno. Czym to grozi? Z tych informacji i wiedzy na nasz temat może korzystać bardzo wiele os&oacute;b dla własnych potrzeb. Mogą to być nasi biznesowi partnerzy, ale też rywale. Znajomi, a także wrogowie. A także (choć to zagrożenie jest zdecydowanie najniebezpieczniejsze) także przestępcy. Jak w takim razie chronić swoje dane, aby nie stać się ofiarą kradzieży tożsamości? Spr&oacute;bujmy znaleźć właściwą odpowiedź na to pytanie&hellip; Na przestrzeni ostatnich lat, a zwłaszcza wraz z dynamicznym rozwojem gospodarki cyfrowej kwestia bezpieczeństwa zyskała zupełnie inny wymiar. Przeniknęła bowiem do świata wirtualnego, wymuszając gruntowną zmianę podejścia w wielu sektorach strategicznych z punktu widzenia funkcjonowania państwa. Choć jeszcze niedawno zagrożenia występujące dziś z przedrostkiem &bdquo;cyber&rdquo; funkcjonowały raczej na kartach powieści science-fiction i w filmowych scenariuszach, obecnie raczej nikt nie ma już wątpliwości, że nie ograniczają się one jedynie do wirtualnej przestrzeni, lecz także - a może przede wszystkim - do świata realnego, stanowiąc przy tym jak najbardziej realne zagrożenie. Zdolny programista, mając do dyspozycji jedynie podłączony do Internetu komputer, jest w stanie doprowadzić do zdalnego wyłączenia prądu w całym regionie, unieszkodliwienia system&oacute;w obrony przeciwlotniczej, czy choćby do całkowitego paraliżu sektora bankowego.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;Jak byś się poczuł, gdyby okazało się, że tw&oacute;j sąsiad, a zarazem przyjaciel, od lat po kryjomu podgląda cię w twoim domu, dotąd uznawanym przez ciebie za bezpieczny azyl? Na dodatek za pomocą urządzeń, kt&oacute;rych nigdy nie podejrzewałbyś o możliwości szpiegowania? Zdarza się to coraz częściej, choć stanowi pogwałcenie naszej wolności i poczucia bezpieczeństwa. To brak należnego nam szacunku. Jedyna metoda, by się im przeciwstawić, to wzmocnienie cyberbezpieczeństwa, kt&oacute;rego podstawą jest edukacja na temat ochrony prywatności w codziennym życiu&rdquo;. &ndash; stwierdza Steve Wozniak, wsp&oacute;łzałożyciel Apple Inc. i trudno się z nim nie zgodzić.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:20px;"><span style="font-size:20px;" class="wixui-rich-text__text">Wirtualne zagrożenie i jego konsekwencje</span></h2></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-size:18px;" class="wixui-rich-text__text"><span class="wixGuard wixui-rich-text__text">​</span></span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Niedostrzeganie faktycznego problemu i skali potencjalnego ryzyka, zwłaszcza w sektorach rządowym i bankowym, stwarza bardzo poważne zagrożenie dla strategicznych części europejskiej infrastruktury internetowej. Dlatego wielokrotnie sugerowano podjęcie zdecydowanych działań, w celu poprawienia tej sytuacji. Choć przez wiele lat kwestia cyberbezpieczeństwa na wielu płaszczyznach często była bagatelizowana, to właśnie administracja i bankowość dość szybko dostrzegły powagę sytuacji. Zaczęto też tworzyć odpowiednie protokoły zabezpieczeń. Początkowo mocno zdecentralizowane, jednak z czasem znacznie bardziej uniwersalne. Jednak nawet, gdy wszystkie cyberzabezpieczenia działały poprawnie, często okazywało się, że problem nadal istnieje. Zgodnie ze stwierdzeniem jednego z najsłynniejszych haker&oacute;w na świecie Kevina Mitnicka, kt&oacute;ry przeszedł na drugą stronę i obecnie zajmuje się cyberbezpieczeństwem &ndash; najsłabszym ogniwem w kwestii bezpieczeństwa cyfrowego najczęściej jest&hellip; człowiek. Człowiek, kt&oacute;ry bardzo często jest kompletnie nieświadomy ryzyka, z jakim wiąże się korzystanie z urządzeń mobilnych oraz samego internetu.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Weźmy na przykład &bdquo;cyfrowy ślad&rdquo;. Na co dzień raczej nie zaprzątamy sobie głowy tym, że gdzieś w internecie krążą setki tysięcy danych na nasz temat. Jednak, jeśli zadamy sobie pytanie, czy kiedykolwiek zdarzyło się nam wypełnić internetową ankietę lub udostępnić swoje dane jakiejkolwiek organizacji, kt&oacute;ra opublikowała je w sieci &ndash; okazuje się, że dobrowolnie przekazaliśmy swoje dane osobom trzecim, kt&oacute;re mogą wykorzystać je wedle uznania. Teraz czas na złą wiadomość: istnieje duże prawdopodobieństwo, że część tych danych (możliwe, że nawet wszystkie) zostaną, bądź już zostały przejęte przez firmy gromadzące dane w celach komercyjnych. Drugą kategorię stanowią natomiast dane, kt&oacute;rych nie ujawniamy w sieci dobrowolnie, a mimo to są gromadzone &ndash; chociażby przez r&oacute;żnego rodzaju korporacje i agencje rządowe. Warto mieć świadomość, że w dzisiejszych czasach w zasadzie z każdym dniem pakiet danych na nasz temat się rozrasta.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;Wielu użytkownik&oacute;w internetu pytanych o kwestię danych i ryzyko kradzieży tożsamości twierdzi: &bdquo;nie mam nic do ukrycia&rdquo;. Tymczasem powinniśmy mieć świadomość, że każda informacja, kt&oacute;rą pozostawiamy w sieci, każdy wpis w mediach społecznościowych, zdjęcie wstawione na Facebooka, Instagram lub Twitter, a nawet nasz to, gdzie się w danej chwili znajdujemy, śledzone jest przez całą dobę przez miliony algorytm&oacute;w. To właśnie one odpowiadają za opracowanie naszego cyfrowego portretu i wnikliwą analizę behawioralną. Nie byłoby to możliwe, gdyby nie cyfrowy ślad, kt&oacute;ry za sobą w internecie zostawiamy. Jest to o tyle groźne zjawisko, że na tej podstawie algorytmy zaczynają w pewnym momencie decydować o tym, jakie wyniki wyszukiwania wyświetlą nam się w przeglądarce, co będziemy mogli przeczytać, obejrzeć i tak dalej. Zanim podejmiemy jakąś decyzję, jesteśmy odpowiednio prześwietlani, a następnie ukierunkowywani przez tysiące algorytm&oacute;w. Z doświadczenia wiem, że kwestia zbierania, a coraz częściej także wyłudzania danych osobowych i ich wykorzystywania dotyczy dzisiaj każdego, kto korzysta z telefonu czy komputera i ma konta w mediach społecznościowych. Przykład&oacute;w nie trzeba wcale daleko szukać. Przecież my sami bardzo często świadomie, a często nawet nieświadomie zgadzamy się na ich wykorzystywanie, nie mając do końca pewności do czego mogą zostać wykorzystane oraz kto ostatecznie uzyska do nich dostęp&rdquo; - wyjaśnia Maciej Karczyński, były rzecznik prasowy Komendanta Stołecznego Policji, a w latach 2012-2016 rzecznik Agencji Bezpieczeństwa Wewnętrznego.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Z reguły w tym momencie do głowy przychodzi najczęściej argument z kategorii: &bdquo;nic mi nie grozi, bo nie mam nic do ukrycia&rdquo;. Okazuje się jednak, że tego typu myślenie należy jak najszybciej odłożyć między bajki.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Skalę zagrożenia już w 1993 roku nakreślił amerykański socjolog i futurolog Alvin Toffler. W dużym uproszczeniu wygląda to mniej więcej tak:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&bdquo;Gdzieś na świecie programista wstukuje na klawiaturze kolejne linijki kodu, po czym umieszcza swoje dzieło w sieci. Po pewnym czasie w innym zakątku globu zapanowuje chaos. Przestaje funkcjonować sieć przekaz&oacute;w bankowych, zamiera rynek akcji i obligacji oraz systemy obrotu handlowego, zablokowana zostaje sieć kart kredytowych, linie telefoniczne, a nawet sieć transmisji danych. Przestaje działać giełda i łączność handlowa. Wszystkie zdobycze technologiczne ostatnich dekad stają się całkowicie bezużyteczne. Cały kraj ogarnia fala finansowego krachu, kt&oacute;ra rozprzestrzenia się na cały świat. A zaczęło się od zaledwie kilku kliknięć w klawiaturę&hellip;&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Niestety w skali krajowej, nadal istnieje zbyt niski poziom świadomości istniejących zagrożeń, zwłaszcza w sektorze prywatnym i biznesie, wśr&oacute;d małych i średnich przedsiębiorstw (ponad 65 proc. rynku ekonomicznego UE). Niechęć do ponoszenia nakład&oacute;w finansowych na zabezpieczenia sieci oraz na środki ochrony zasob&oacute;w powoduje, że struktury teleinformatyczne należące do tych przedsiębiorstw stają się &bdquo;najsłabszym ogniwem&rdquo; infrastruktury Internetu, kt&oacute;re w następstwie może zostać zaatakowane lub wykorzystane do pośredniczenia w innym, bardziej spektakularnym ataku. W tym zakresie Europejska Agencja ds. Bezpieczeństwa Sieci i Informacji (ENISA) widzi konieczność prowadzenia odpowiednich szkoleń oraz program&oacute;w uświadamiających.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ekspert ds. bezpieczeństwa cyberprzestrzeni i walki z terroryzmem Richard Clarke rzuca nieco więcej światła na kwestię wykorzystania nowoczesnych technologii w r&oacute;żnego rodzaju konfliktach (także gospodarczych). Cytowany przez &bdquo;The Economist&rdquo; ekspert wylicza, że obecnie poziom zaawansowania technologii informacyjnych i ich odpowiednie wykorzystanie przeciwko potencjalnym wrogom może doprowadzić, w ciągu zaledwie 15 minut, do katastrofalnej w skutkach awarii strategicznych system&oacute;w odpowiedzialnych za bezpieczeństwo państwa oraz całą jego infrastrukturę, transport i logistykę. Wirusy i tzw. robaki komputerowe są w stanie na przykład umożliwić manipulację danymi na światowych giełdach oraz posłużyć do odcięcia danej części kraju od dostaw energii elektrycznej, wizja eskalacji cyberzagrożeń staje się więc dość apokaliptyczna.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Richard Clarke stwierdza, że w takiej sytuacji społeczeństwo szybko się załamie, bo wypłacenie pieniędzy z bankomatu okaże się niemożliwe, a żywność stanie się towarem deficytowym. Drastycznym, a zarazem dobitnym przykładem obrazującym, do czego może doprowadzić choćby odcięcie obywateli od swobodnego korzystania z bankomat&oacute;w i uniemożliwienie im wypłacenia większych sum pieniędzy można było zaobserwować na przykładzie kryzysu w Grecji, albo w pierwszym miesiącu pandemii koronawirusa, gdy (także w Polsce) rozpowszechniano informacje o rzekomych limitach wypłat z bankomat&oacute;w i bank&oacute;w. Jedna informacja rozprzestrzeniająca się w Internecie lotem błyskawicy wystarczyła, by przed większością bankomat&oacute;w w dużych aglomeracjach ustawiły się spore kolejki.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:20px;"><span style="font-size:20px;" class="wixui-rich-text__text">Cyberpandemia</span></h2></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:20px;"><span class="inherit-font-size wixui-rich-text__text" style="font-size:20px;"><span class="wixGuard wixui-rich-text__text">​</span></span></h2></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:18px;"><span class="inherit-font-size wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></span></h2></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Warto zwr&oacute;cić uwagę, że zagrożenia związane z cyberprzestrzenią i komunikacją cyfrową nie dotyczą jedynie strategicznych system&oacute;w informatycznych danego państwa. W celu pozyskania informacji i niejawnych danych, hakerzy, cyberprzestępcy i służby specjalne r&oacute;żnych państw są w stanie posłużyć się komputerami os&oacute;b postronnych, aby za ich pośrednictwem zacierać ślady, mylić tropy, a co najważniejsze niepostrzeżenie uzyskać dostęp do pożądanych informacji. Napastnicy mają do wybory wiele narzędzi ataku m.in.: tysiące wirus&oacute;w, robak&oacute;w oraz mechanizm Distributed Denial of Service (DDoS). Jest to zmasowany atak na system komputerowy lub usługę sieciową w mający na celu uniemożliwienia działania poprzez zajęcie wszystkich wolnych zasob&oacute;w. Przeprowadza się go r&oacute;wnocześnie z wielu komputer&oacute;w doprowadzając do przeciążenia serwer&oacute;w (np. bank&oacute;w, stron administracji publicznej lub serwis&oacute;w informacyjnych). Atak DDoS stanowi odmianę ataku DoS polegającą na zaatakowaniu ofiary z wielu miejsc jednocześnie.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Malware - szkodliwe oprogramowanie. Najczęściej jest to cały pakiet program&oacute;w siejący spustoszenie w systemie komputerowym lub sieci.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ransomware - szczeg&oacute;lnie groźny typ szkodliwego oprogramowania, cieszący się ostatnio dużą popularnością wśr&oacute;d haker&oacute;w. Blokuje dostęp do systemu komputerowego lub uniemożliwia odczyt zapisanych w nim danych, a następnie żąda od ofiary okupu za przywr&oacute;cenie stanu pierwotnego. To czy dane w og&oacute;le odzyskamy (nawet po zapłaceniu okupu) zależy wyłącznie od kaprysu haker&oacute;w.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Trojany &ndash; rodzaj oprogramowania, kt&oacute;re udając przydatne lub ciekawe dla użytkownika aplikacje (często rzeczywiście nimi jest), dodatkowo instaluje i inicjuje w urządzeniu, r&oacute;żny ukryte przed użytkownikiem funkcje. Nazwa pochodzi od mitologicznego konia trojańskiego.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wirusy - programy lub elementy złowrogiego kodu, kt&oacute;ry dołącza się, nadpisuje lub zamienia inny program w celu powielania samego siebie bez zgody, a często nawet bez wiedzy użytkownika.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Robaki (worms) - szkodliwe oprogramowanie podobne do wirus&oacute;w, rozprzestrzeniające się tylko poprzez sieć. W przeciwieństwie do wirus&oacute;w nie potrzebują programu &bdquo;żywiciela&rdquo;. Często powielają się przez pocztę elektroniczną.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Spyware &ndash; oprogramowanie szpiegujące zbierające dane o osobie fizycznej lub prawnej bez uzyskania zgody. Tego rodzaju oprogramowanie może śledzić informacje o odwiedzanych stronach, dane dostępowe itp. Występuje często jako dodatkowy i ukryty komponent większego programu, odporny na usuwanie i ingerencję użytkownika. Co szczeg&oacute;lnie istotne spyware może wykonywać działania bez wiedzy użytkownika &ndash; zmieniać wpisy w rejestrze systemu operacyjnego, a nawet ustawienia użytkownika. Warto wiedzieć, że program szpiegujący może pobierać oraz uruchamiać pliki pobrane z sieci.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Exploit - kod umożliwiający bezpośrednie włamanie do komputera ofiary. Do wprowadzenia zmian lub przejęcia kontroli wykorzystuje się lukę w oprogramowaniu zainstalowanym na atakowanym komputerze. Mogą być użyte do ataku na strony internetowe (zmiana treści lub przejęcie kontroli administracyjnej), systemy operacyjnych (serwery i końc&oacute;wki klienckie) lub aplikacje (pakiety biurowe, przeglądarki internetowe lub inne oprogramowanie).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Keylogger &ndash; rejestrator klawiszy, kt&oacute;ry odczytuje i zapisuje wszystkie naciśnięcia klawiszy użytkownika. Dzięki temu adresy, kody i inne poufne dane mogą dostać się w niepowołane ręce. Warto jednak pamiętać, że keylogger może być zar&oacute;wno szkodliwym oprogramowaniem służącym do rozsyłania poufnych danych, jak i oprogramowaniem celowo zainstalowanym przez pracodawcę np. w celu kontrolowania aktywności pracownik&oacute;w.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jeśli natomiast chodzi o same zagrożenia, szczeg&oacute;lnie należy uważać na następujące pr&oacute;by oszustw i wyłudzenia danych:</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Phishing &ndash; metoda oszustwa, w kt&oacute;rej przestępca podszywa się pod inną osobę lub instytucję w celu wyłudzenia poufnych informacji, zainfekowania komputera szkodliwym oprogramowaniem czy też nakłonienia ofiary do określonych działań. Jest to rodzaj ataku opartego na inżynierii społecznej.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zdecydowana większość wiadomości phishingowych jest dostarczana za pośrednictwem poczty elektronicznej lub portali społecznościowych.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">hishing, kt&oacute;rego celem jest zdobycie informacji na temat karty płatniczej danej osoby, nadal należy do najpopularniejszych oszustw. Fałszywe wiadomości mogą być wysyłane w imieniu bank&oacute;w lub system&oacute;w płatności. Najczęściej temat tych wiadomości jest związany z blokowaniem konta lub &bdquo;podejrzaną aktywnością&rdquo; wykrytą na koncie osobistym odbiorcy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Pod pretekstem przywr&oacute;cenia dostępu, potwierdzenia tożsamości czy anulowania transakcji użytkownik jest proszony o wprowadzenie szczeg&oacute;łowych informacji dotyczących karty płatniczej (często kodu CVV/CVC) na fałszywej stronie banku. Po odebraniu tych danych przestępcy natychmiast wypłacają pieniądze z konta ofiary. Podobnie wygląda sytuacja z systemami płatności, jednak w&oacute;wczas ofiary są nakłaniane jedynie do zalogowania się do swojego konta.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">-Nie należy przesyłać mailem żadnych danych osobistych typu hasła, numery kart kredytowych itp. Prośby o podanie hasła i loginu w mailu należy zgłosić osobom odpowiedzialnym za bezpieczeństwo.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">-Banki i instytucje finansowe stosują protok&oacute;ł HTTPS tam, gdzie konieczne jest zalogowanie do systemu. Jeśli strona z logowaniem nie zawiera w adresie nazwy protokołu HTTPS, powinno się zgłosić to pracownikom banku i nie podawać na niej żadnych danych. -Nie zaleca się używania starszych przeglądarek internetowych (np. Internet Explorer 6), kt&oacute;re bywają często podatne na r&oacute;żne błędy. Alternatywnie można korzystać z innych program&oacute;w, jak Mozilla Firefox czy Opera lub Internet Explorer 9 i 10 (kt&oacute;rych najnowsze wersje wyposażone są w filtry antyphishingowe) albo z oprogramowania firm trzecich chroniącego przed phishingiem.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Whaling</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Część atak&oacute;w phishingowych została skierowana w szczeg&oacute;lności do kierownictwa wyższego szczebla i innych ważnych cel&oacute;w z branży biznesowej. Z tego powodu ataki te nazwano whaling (z języka angielskiego &bdquo;wielorybnictwo&rdquo;). W przypadku atak&oacute;w tego typu, sfałszowana witryna lub wiadomość jest tworzona z uwzględnieniem np. stanowiska ofiary w firmie. Treść e-maili często przypomina pisma pochodzące z kancelarii prawnych lub urzęd&oacute;w państwowych. Taka wiadomość może zawierać załącznik w postaci złośliwego oprogramowania i nakłaniać ofiarę do jego instalacji np. w celu uzyskania dostępu do ważnego dokumentu</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Pharming</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Bardziej niebezpieczna dla użytkownika oraz trudniejsza do wykrycia forma phishingu. Charakterystyczne dla pharmingu jest to, że nawet po wpisaniu prawidłowego adresu strony www, ofiara zostanie przekierowana na fałszywą (choć mogącą wyglądać tak samo) stronę WWW. Ma to na celu przejęcie wpisywanych przez użytkownika do zaufanych witryn haseł, numer&oacute;w kart kredytowych i innych poufnych danych.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Oszustwa w portalach społecznościowych</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Najczęściej polegają na tym, iż przestępcy internetowy włamują się na konto użytkownika np. Facebooka czy Naszej Klasy i rozsyłają w imieniu właściciela profilu maile do jego znajomych. Proszą o przesłanie jakiejś kwoty na podane konto (uzasadniają to chociażby tym, iż zostali oszukani za granicą i nie mają pieniędzy na powr&oacute;t do kraju). Wiele os&oacute;b przesyła środki finansowe, gdyż myśli, że prawdziwy przyjaciel jest w potrzebie. Aby uniknąć tego typu oszustw należy przede wszystkim stosować silne hasła, programy antywirusowe i antyszpiegowskie oraz posiadać świadomość możliwych do pojawienia się zagrożeń, związanych z portalami społecznościowymi.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Oszustwo na &bdquo;nigeryjskiego księcia&rdquo;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wreszcie dotarliśmy do ostatniego, jednego z najstarszych rodzaj&oacute;w spamu &mdash; obietnicy zdobycia fortuny od krewnego lub prawnika działających w imieniu zmarłego milionera w zamian za dokonanie płatności z g&oacute;ry. Niestety, to oszustwo nadal krąży w Sieci. W jednej z jego odmian oszust występuje pod postacią celebryty, kt&oacute;ry chwilowo jest w trudnej sytuacji. Ofierze obiecuje się ogromną nagrodę, jeśli zgodzi się pom&oacute;c pechowemu milionerowi wypłacić pieniądze ulokowane w kontach r&oacute;żnych bank&oacute;w. W tym celu należy oczywiście najpierw wysłać szczeg&oacute;łowe informacje na sw&oacute;j temat (informacje odnośnie paszportu, danych konta itp.) oraz niewielką kwotę na załatwienie formalności.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Kradzież tożsamości</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Złodzieje tożsamości wykorzystują dane osobowe (np. numery PESEL, informacje o koncie bankowym i numery karty kredytowych), aby podawać się za inną osobę. Może chodzić m.in. o otwarcie rachunku bankowego, wyczyszczenie istniejącego rachunku, złożenie wniosku o zwrot podatku lub pokrycie rachunku za usługi medyczne.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Skimming &ndash; przestępstwo polegające na nielegalnym skopiowaniu zawartości paska magnetycznego karty płatniczej bez wiedzy jej posiadacza w celu wytworzenia kopii i wykonywania nieuprawnionych płatności za towary i usługi lub wypłat z bankomat&oacute;w.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Obecnie skimming wymierzony jest także w karty chipowe z układami niechronionej klasy SDA, jak i układami klasy DDA uchodzącymi za bezpieczniejsze. Ponieważ skopiowana karta w elektronicznych systemach bankowych zachowuje się jak karta oryginalna, wszystkie operacje wykonane przy jej pomocy odbywają się kosztem posiadacza oryginalnej karty i obciążają jego rachunek.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Istnieją dwa rodzaje skimmingu: skimming w plac&oacute;wce handlowej oraz skimming bankomatowy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:20px;"><span style="font-size:20px;" class="wixui-rich-text__text">Kevin Mitnick: &bdquo;Łamałem ludzi, nie hasła&rdquo;</span></h2></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zatrzymajmy się nieco dłużej nad kwestią podstawowych zabezpieczeń wykorzystywanych przez większość użytkownik&oacute;w komputer&oacute;w i sprzętu mobilnego. O tym, jakie hasła do kont bankowych czy komputer&oacute;w firmowych są w powszechnym użyciu, bardzo dosadnie uświadomił atak hakerski na pewien portal randkowy przeprowadzony w lipcu 2015 roku. Spośr&oacute;d 11 milion&oacute;w upublicznionych wtedy haseł do kont użytkownik&oacute;w najczęściej powtarzały się takie oto kombinacje: &bdquo;123456&rdquo;, &bdquo;12345&rdquo;, &bdquo;password&rdquo;, &bdquo;DEAFULT&rdquo;, &bdquo;123456789&rdquo;, &bdquo;qwerty&rdquo;, &bdquo;12345678&rdquo;, &bdquo;abc123&rdquo; oraz &bdquo;1234567&rdquo;. Kevin Mitnick ostrzega, że jeśli wśr&oacute;d tych kombinacji dostrzegamy swoje hasło, lub hasło bardzo do niego podobne, istnieje duże ryzyko, że r&oacute;wnież możemy stać się ofiarą kradzieży danych. Okazuje się bowiem, że podobne ciągi znak&oacute;w przewiduje większość dostępnych w sieci narzędzi do łamania haseł.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Czy jest zatem jakiś spos&oacute;b na stworzenie haseł odpowiednio trudnych do złamania? Przede wszystkim warto zacząć od tworzenia dość złożonych i skomplikowanych kombinacji cyfr i liter. Nie bez znaczenia pozostaje też długość hasła. Im dłuższe, tym większa szansa, że jego złamanie zajmie więcej czasu. Wielu użytkownik&oacute;w rezygnuje obecnie z samodzielnego wymyślania hasła i decyduje się na skorzystanie z automatycznego generatora. Na rynku możemy znaleźć wiele zaufanych i cieszących się renomą aplikacji tego typu. Pozwalają one nie tylko tworzyć silne kombinacje znak&oacute;w i cyfr, lecz zebrać wszystkie hasła i dane logowań w bezpiecznym miejscu, do kt&oacute;rego dostęp daje jedno kliknięcie. Nawet to rozwiązanie obarczone jest jednak pewnym ryzykiem. Aplikacja wymaga jednego hasła gł&oacute;wnego, dającego dostęp do pozostałych haseł. Jest zatem oczywiste, że jeśli komputer lub urządzenie mobilne zostaną zainfekowane złośliwym oprogramowaniem kradnącym hasła (na przykład przy użyciu keyloggera), w&oacute;wczas nasz wirtualny &bdquo;sejf&rdquo; stoi przed cyberprzestępcami otworem. Za jednym razem włamywacz otrzymuje dostęp do wszystkich haseł zapisanych w aplikacji. Drugi problem związany z menadżerem haseł jest znacznie bardziej prozaiczny. Jeśli zdarzy się nam zapomnieć hasło gł&oacute;wne, w&oacute;wczas tracimy dostęp do wszystkich pozostałych haseł (a istnieje duże prawdopodobieństwo, że ich też nie pamiętamy, ponieważ były zapisane w bezpiecznym miejscu). Oczywiście pozostaje w&oacute;wczas tylko opcja resetu haseł na wszystkich stronach po kolei, ale jest to proces długotrwały i dość żmudny.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jak zatem stworzyć dobre hasło, kt&oacute;re trudno będzie nam zapomnieć? Były haker, a obecnie znany na całym świecie ekspert ds. cyberbezpieczeństwa Kevin Mitnick radzi, aby używać długich ciąg&oacute;w znak&oacute;w, co najmniej 20-25 i co szczeg&oacute;lnie istotne, niezawierających sł&oacute;w. Najlepiej, gdy są to przypadkowe zlepki, na przykład &bdquo;eh2raogh#sof&amp;skx!mt@l&rdquo;. Problem polega jednak na tym, że ludzki m&oacute;zg nie radzi sobie zbyt dobrze z zapamiętywaniem tego typu nic nie znaczących kombinacji. To z kolei zn&oacute;w prowadzi nas do menedżera haseł i możliwości automatycznego ich generowania. Jest to bezpieczniejsza metoda niż każdorazowe samodzielne ich wymyślanie.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Należy jednak pamiętać, aby nigdy nie używać tych samych haseł do r&oacute;żnych kont. Niestety często trudno jest tego uniknąć - zwłaszcza, że obecnie jesteśmy zmuszeni co chwila podawać gdzieś hasło w celu weryfikacji. Jest to kolejny argument przemawiający na korzyść użycia aplikacji, kt&oacute;ra wygeneruje za nas trudne do złamania hasła.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jeśli jednak mimo wszystko chcemy zapisywać hasła w spos&oacute;b tradycyjny (na przykład w notesie) warto notować je w inteligentny spos&oacute;b. Na pewno nie piszemy: &bdquo;Nazwa Banku: pEłnEH@$łodoB4nkU!&rdquo;. Nazwę banku można zastąpić jakimś dalekim skojarzeniem - na przykład &bdquo;skarpeta&rdquo; (żartobliwie m&oacute;wi się przecież o trzymaniu tam pieniędzy) z dopiskiem &bdquo;pEłnE&rdquo;. Jak widać hasło nie zostało użyte w całości, ale nie ma takiej potrzeby. Ma to być jedynie skojarzenie, pozwalające nam łatwiej zapamiętać drugą część hasła, a w przypadku utraty pierwszej jego części, ryzyko odgadnięcia reszty jest znacznie mniejsze.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Nie ulega wątpliwości, że zwłaszcza w kontekście bankowości elektronicznej stworzenie silnych haseł jest szczeg&oacute;lnie istotne. W przypadku, gdy ktoś fizycznie przejmie urządzenie, z kt&oacute;rego logujemy się na stronę banku, brak odpowiednich zabezpieczeń może narazić nas na spore straty. Dlatego właśnie warto pamiętać o zabezpieczeniu wszelkiego rodzaju urządzeń mobilnych, z kt&oacute;rych najczęściej korzystamy. Mają one to do siebie, że dość łatwo je zgubić i najczęściej w ostatnich latach badają łupem złodziei. Co ciekawe spora grupa os&oacute;b w dalszym ciągu nie stosuje w tego typu urządzeniach żadnych zabezpieczeń. Nawet tak prostych jak blokada ekranu czterocyfrowym kodem PIN.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W ostatnim czasie jednak coraz częściej odchodzi się od polityki bezpieczeństwa opartej wyłącznie na hasłach. Prosty przykład: pracownik banku wymyśla bardzo długie hasło, np. &ldquo;Li2oOjczyzn0M0ja7yJeste!JakZdrowie!&rdquo;. Do niedawna każdy szkoleniowiec zajmujący się cyberbezpieczeństwem by je pochwalił &ndash; długie, zawiera r&oacute;żne znaki, jest łatwe do zapamiętania. I nie byłoby w tym nic złego, gdyby nie fakt, że niezależnie od tego, jakie to hasło będzie, to i tak złodziej może je przejąć. R&oacute;wnie dobrze mogłoby to być &bdquo;123456&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Oczywiste jest, że odejście od haseł w firmach i instytucjach finansowych wcale nie jest takie łatwe, gł&oacute;wnie poprzez powiązanie ich z tożsamością użytkownik&oacute;w, bazami danych itp. Właśnie dlatego tak istotne jest, żeby w pierwszym etapie drogi do passwordless wszystkie organizacje zadbały o zabezpieczenie haseł silnym uwierzytelnianiem MFA. Najlepiej oczywiście, żeby od razu była to metoda skuteczna, czyli wieloskładnikowe uwierzytelnianie odporne na phishing.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wraz z rozwojem nowych technologii pojawiły się także nowe formy zabezpieczeń. Ciekawym aspektem jest na przykład możliwość blokowania urządzeń przenośnych tzw. wzorem blokującym. Na ekranie wyświetla się 9 kropek, kt&oacute;re połączone w odpowiedniej kolejności tworzą symbol funkcjonujący na zasadzie unikalnego kodu dającego dostęp do urządzenia. Tuż po wprowadzeniu tej metody, eksperci zwracali uwagę, że jest to rozwiązanie bezpieczne ze względu na liczbę możliwych kombinacji. Coś co miało być blokadą nie do przejścia pokonał jednak&hellip; czynnik ludzki, a w zasadzie lenistwo i brak kreatywności. Już na konferencji PasswordsCon z 2015 roku wykazano, że użytkownicy są dość przewidywalni i wybierają jedynie kilka (!) z aż 140 704 możliwych kombinacji. Jak się okazuje, najczęściej wzorem dającym dostęp do smartfona była&hellip; pr&oacute;ba nakreślenia pierwszej litery własnego imienia. Użytkownicy najczęściej wybierają także kropki środkowe, a nie narożne, ponieważ łatwiej jest sięgnąć do nich obsługując telefon jedną ręką.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Poprawę jakości zabezpieczeń miał dać także inny dość futurystyczny wynalazek, wcześniej znany jedynie z film&oacute;w szpiegowskich. Tymczasem po wejściu na rynek czytnika linii papilarnych Touch ID naukowcy ze zdumieniem odkryli, że niekt&oacute;re stare metody oszukiwania dawnych czytnik&oacute;w linii papilarnych&hellip; nadal się sprawdzają. Do złamania zabezpieczeń wystarczyło na przykład &bdquo;zebrać&rdquo; odcisk palca z czystej powierzchni używając na przykła zasypki dla niemowląt i taśmy klejącej.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">A co z modnymi ostatnio urządzeniami z funkcją rozpoznawania twarzy? Okazuje się, że tę blokadę także można obejść, wykorzystując na przykład zdjęcie właściciela urządzenia w odpowiednio wysokiej rozdzielczości.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Innowacyjne systemy identyfikacji biometrycznej w por&oacute;wnaniu nawet z tradycyjnymi hasłami w formie ciąg&oacute;w znak&oacute;w, zdają się być zatem dość podatne na ataki. Dlatego właśnie eksperci zajmujący się cyberbezpieczeństwem radzą, aby nie byłby to jedyne elementy całego procesu uwierzytelniania. Nie wystarczy przyłożyć palec do czytnika lub uśmiechnąć się do kamery. Najlepiej wpisać jeszcze kod lub nakreślić wz&oacute;r odblokowujący ekran. Tak dochodzimy do kwestii uwierzytelniania wieloskładnikowego.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Hasła i kody PIN to ważne elementy bezpieczeństwa, ale jak widać nie są niezawodne i można je złamać. Dlatego znacznie bezpieczniejsze jest użycie uwierzytelniania dwuskładnikowego, zwane r&oacute;wnież weryfikacją dwuetapową (2FA). Tego typu weryfikacja polega na tym, iż w procesie sprawdzania tożsamości użytkownika strony lub aplikacje wykorzystują dwa lub trzy elementy. Są to zazwyczaj: &bdquo;coś co masz&rdquo; - na przykład karta kredytowa lub debetowa z paskiem magnetycznym lub mikroprocesorem, &bdquo;coś co wiesz&rdquo; - na przykład PIN lub odpowiedź na pytanie bezpieczeństwa, oraz &bdquo;to kim jesteś&rdquo; - metody biometryczne takie jak np. analiza linii papilarnych, rozpoznawanie twarzy czy głosu itp. Im więcej element&oacute;w uwierzytelniania, tym większa pewność, że użytkownik rzeczywiście jest tym, za kogo się podaje.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Mogłoby się wydawać, że jest to dość nowatorskie rozwiązanie. Na przestrzeni zaledwie ostatnich kilku lat do korzystania z niego przyłączyły się praktycznie wszystkie banki w kraju i na świecie. Tymczasem weryfikacja typu 2FA towarzyszy nam już od grubo ponad 40 lat, choć często nie jesteśmy nawet świadomi jej istnienia. To właśnie ten typ weryfikacji tożsamości stosuje się między w bankomatach. Aby pobrać got&oacute;wkę musimy mieć przy sobie wydaną przez bank kartę (&bdquo;coś co masz) i kod PIN (&bdquo;coś co wiesz&rdquo;). W niekt&oacute;rych krajach działają już nawet bankomaty z dodatkowymi metodami weryfikacji np. systemem rozpoznawania twarzy lub żył dłoni. M&oacute;wimy w&oacute;wczas o uwierzytelnianiu wieloskładnikowym (MFA).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dobrze nam znana weryfikacja 2FA jest r&oacute;wnież wykorzystywana w internecie przez wiele instytucji finansowych, portali administracji publicznej, a także komercyjne serwisy pocztowe i społecznościowe. W tym przypadku łączy się hasło (&bdquo;coś co wiesz&rdquo;) na przykład z telefonem kom&oacute;rkowym (&bdquo;coś co masz&rdquo;) lub innym urządzeniem mobilnym. W sytuacji, gdy kom&oacute;rka jest powiązana z używanym urządzeniem lub serwisem, osoba nieuprawniona nie może wejść na tak zabezpieczone konta, nie mając jej fizycznie przy sobie.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Mając na uwadze powyższe metody zabezpieczania haseł, warto rozważyć dodatkową możliwość zabezpieczania operacji i transakcji finansowych za pośrednictwem internetu, a w szczeg&oacute;lności w kontekście bankowości elektronicznej i mobilnej.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wydawać by się mogło, że najprostszym rozwiązaniem jest kupno rocznej (lub innej długoterminowej) licencji programu antywirusowego oraz firewalla na trzy komputery. To nie do końca prawda. Okazuje się bowiem, że przeglądając strony internetowe, możemy załadować w swojej przeglądarce baner ze szkodliwym oprogramowaniem albo dostać je w e-mailu. W każdym z tych przypadk&oacute;w od chwili połączenia z internetem komputer jest nieustannie zagrożony wirusami, a oprogramowanie antywirusowe nie zawsze jest w stanie wyłapać wszystkie ich rodzaje. Kevin Mitnick proponuje inne rozwiązanie, z kt&oacute;rego sam korzysta. Chodzi o rozważenie kupna taniego tabletu lub Chromebooka. Domyślnie ma być to osobne urządzenie służące wyłącznie do przeprowadzenia transakcji finansowych w sieci. Dodatkową zaletą jest to, że na Chromebooku nie da się zainstalować żadnych aplikacji, jeśli wcześniej nie założymy konta w Gmailu. Jego funkcjonalność sprowadza się zatem jedynie do przeglądania stron internetowych.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Następnym krokiem jest ustawienie na danej stronie (na przykład stronie banku) weryfikacji dwuetapowej dla posiadanego urządzenia. Kluczem do sukcesu jest dyscyplina. Po skończeniu załatwiania spraw w banku należy sprzęt od razu wyłączyć i nie używać do niczego innego &ndash; zwłaszcza do przeglądania internetu.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Początkowo pomysł ten nie wygląda może zbyt zachęcająco i posiada jedną kluczową wadę: decydując się na takie rozwiązanie tracimy dostęp do swojego banku z innych urządzeń. Ma to jednak wiele dobrych stron. Dzięki takiej praktyce znacząco minimalizujemy ryzyko włamania się na konto bankowe. Jeśli będziemy konsekwentnie używać jednego urządzenia wyłącznie w celach finansowych i nie odwiedzać na nim żadnych innych stron internetowych, poza bankiem &ndash; mamy w&oacute;wczas prawie 100 procent pewności, że urządzenia nie zaatakują wirusy lub inne szkodliwe aplikacje.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tymczasem według przeprowadzonego w II kwartale 2020 przez Krajowy Rejestr Dług&oacute;w Biuro Informacji Gospodarczej i serwis ChronPESEL.pl badania, ponad połowa Polak&oacute;w jest przekonana, że dobrze chroni swoje dane osobowe (52 proc.), jednocześnie co trzeci ankietowany miał problem z oceną, czy zapewnia swoim danym należytą ochronę (38 proc.) 55 proc. Polak&oacute;w obawia się kradzieży tożsamości; jednocześnie co trzeci nie potrafi ocenić, czy w spos&oacute;b właściwy chroni swoje dane osobowe - wynika z badania &quot;Jak Polacy chronią swoje dane osobowe?&quot;. Ankietowani za największe zagrożenie uznają działalność oszust&oacute;w w internecie.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W opinii badanych, złodzieje tożsamości pobierają dane osobowe gł&oacute;wnie w drodze wyłudzenia, na przykład poprzez fałszywe strony logowania lub fałszywe e-maile (74,5 proc.). R&oacute;wnocześnie ponad połowa ankietowanych uważa, że oszuści zyskują dostęp do danych poprzez kradzież dokument&oacute;w papierowych i plastikowych (50,3 proc.). Z kolei ponad 41 proc. Polak&oacute;w obawia się, że przestępcy wykorzystają ich dane osobowe podrabiając dokumenty lub karty płatnicze.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:20px;"><span style="font-size:20px;" class="wixui-rich-text__text">Kto ma informacje, ten ma władzę</span></h2></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dopiero w latach 90. zrobiło się głośno o grupach haker&oacute;w, kt&oacute;rzy dokonywali atak&oacute;w na systemy operacyjne, komputery lub strony internetowe. Jak wspomina w swojej autobiografii Kevin Mitnick, początkowo chodziło gł&oacute;wnie o zabawę i swego rodzaju wyzwanie. Hakerzy sprawdzali się nawzajem wyznaczając sobie coraz trudniejsze cele. Z pozoru niewinna, a niekiedy r&oacute;wnież prostacka zabawa ewoluowała. Praktycznie nieograniczone możliwości działania sprawiły, że w pierwszej kolejności cyberprzestępcy wykorzystywali swoje umiejętności w celu zdobywania majątk&oacute;w i powiększania zdobytych już fortun. Szybko jednak okazało się, że informacje przechowywane na komputerach oraz publikowane w Internecie są łakomym kąskiem dla wszelkiego rodzaju działalności szpiegowskiej. Nie bez znaczenia pozostaje r&oacute;wnież fakt, że coraz częściej dane te oraz usługi haker&oacute;w lub pospolitych cyberprzestępc&oacute;w zaczęto wykorzystywać r&oacute;wnież w kampaniach politycznych. Wiedza, kt&oacute;rą do tej pory trzeba było gromadzić godzinami, a nawet miesiącami, w przypadku Internetu i komputer&oacute;w, była dosłownie na wyciągnięcie ręki. Odpowiednio użyta mogła wpłynąć pozytywnie na czyjąś karierę, rozw&oacute;j firmy, wizerunek lub wręcz przeciwnie &ndash; mogła się stać podstawą tzw. czarnego PR. Nic więc dziwnego, że zaczęto rozważać zastosowanie tych wszystkich umiejętności i mechanizm&oacute;w w sferze militarnej.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Choć wiele os&oacute;b nadal stara się tego nie zauważać, to właśnie media społecznościowe stały się obecnie areną działań szpieg&oacute;w z całego świata. Dane, zar&oacute;wno te jawne, jak i tajne często są dosłownie na wyciągnięcie ręki, a brak świadomości realnego zagrożenia powoduje, że wielu użytkownik&oacute;w Internetu udostępnia informacje, kt&oacute;re jeszcze kilkadziesiąt, a nawet kilkanaście lat temu uzyskać było niezwykle trudno.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Łatwość w dostępie do tego typu informacji zachęca służby wywiadowcze na całym świecie do wykorzystywania cyberprzestrzeni na szeroką skalę.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">O skali zagrożenia zrobiło się głośno po ujawnieniu informacji o programie PRISM. Zgodnie z informacjami przekazanymi mediom przez Edwarda Snowdena od 2007 roku służby specjalne zbierały dane z serwer&oacute;w m.in. Google, Facebook, Yahoo, Paltalk, AOL, Skype, YouTube i Apple. Nie trzeba chyba nikogo przekonywać, że dostęp do tego typu danych oznacza, że służby specjalne mogą dowiedzieć się o internautach wszystkiego, począwszy od gustu muzycznego czy kulinarnego przez upodobania seksualne, aż po zainteresowania i hobby, zwłaszcza te mogące zostać uznane za zagrożenie dla bezpieczeństwa kraju.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Snowden błyskawicznie stał się wrogiem publicznym, jednak w obliczu poparcia ze strony WikiLeaks ujawnił dalsze szczeg&oacute;ły dotyczące inwigilacji w Internecie. Ujawniając dokumenty Agencji Bezpieczeństwa Narodowego (NSA), dla kt&oacute;rej do niedawna pracował, Snowden ujawnił istnienie systemu XKeyscore, kt&oacute;ry swoim zasięgiem i możliwościami przyćmiewa nawet budzący liczne kontrowersje PRISM. XKeyscore zapewnia dostęp do niemal wszystkiego, co typowy użytkownik robi w internecie i pozwala penetrować bazy danych, na kt&oacute;rych zgromadzone są informacje na temat tego, co dzieje się w sieci w wymiarze globalnym. Dzięki temu, w prosty spos&oacute;b można odnaleźć adresy e-mailowe, ściągnięte z Internetu pliki, a nawet numery telefon&oacute;w i treści rozm&oacute;w z internetowych czat&oacute;w. Edward Snowden uciekł z USA i ukrywa się na terenie Rosji, gdzie wystąpił o azyl. Choć Snowden praktycznie zniknął, dając o sobie znać jedynie co jakiś czas, wywołany przez niego problem pozostał.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Coraz częściej też, to właśnie sami użytkownicy &ndash; świadomie lub nieświadomie &ndash; ujawniają w sieci coraz więcej informacji na sw&oacute;j temat. Czym grozi tego typu wirtualny ekshibicjonizm i gdzie leży granica pomiędzy rozrywką a bezpieczeństwem? Odpowiedź na te pytania jest kluczem do świadomego funkcjonowania w cyberprzestrzeni i budowania społeczeństwa obywatelskiego o wiele bardziej odpornego na zagrożenia płynące z cyberprzestrzeni.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Przy obecnej potędze medi&oacute;w społecznościowych, wpadnięcie w pułapkę rozrywki w przestrzeni wirtualnej jest tylko kwestią czasu. Wraz ze swoim pojawieniem się na rynku Facebook, Twitter, a do niedawna także komunikator Gadu-Gadu czy serwis Nasza Klasa, oferowały użytkownikom praktycznie nieograniczone możliwości aktywnego funkcjonowania w cyberprzestrzeni. To właśnie media społecznościowe dają nam możliwość błyskawicznego kontaktu z osobami oddalonymi o setki tysięcy kilometr&oacute;w. Wypełniają nam wolny czas oferując r&oacute;żnego rodzaju gry, filmy lub muzykę, a także dają nieograniczony dostęp do informacji (co wykorzystuje się r&oacute;wnież w wojnie informacyjnej w celach kampanii dezinformacji).</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wreszcie, media społecznościowe to potężne narzędzie promocji. Dziś nie trzeba już płacić za ogłoszenia w prasie, dzwonić do znajomych czy wysyłać setki e-maili. Użytkownicy mają wszystko dosłownie na wyciągnięcie ręki, dostępne za pomocą kilku kliknięć. Pomimo niewątpliwych korzyści wynikających z powszechnej dostępności nowych technologii, a także medi&oacute;w społecznościowych, coraz rzadziej zwraca się uwagę na zagrożenia, kt&oacute;re się z nimi wiążą &ndash; a szczerze m&oacute;wiąc, jest ich całe mn&oacute;stwo. Problem polega na tym, że nowe technologie i nowe media, dla wsp&oacute;łczesnego pokolenia przestały być zupełnie nowe, a co za tym idzie coraz częściej zaczęto bagatelizować oczywiste zagrożenia płynące z cyberprzestrzeni.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Nie ulega wątpliwości, że wizerunek danej osoby zależy od wielu czynnik&oacute;w takich jak na przykład ubi&oacute;r, aparycja, zachowanie, a nawet zainteresowania. Ogromny wpływ na nasz wizerunek ma także aktywność w sieci. O ile świadomość możliwości odpowiedniego kreowania wizerunku staje się powoli coraz powszechniejsza, o tyle nadal jeszcze wiele os&oacute;b nie nie zdaje sobie sprawy z oczywistej wręcz zależności &ndash; udostępniane w internecie treści nawet po ich usunięciu pozostawiają ślady. Gdy dziś czytamy wpisy na forach internetowych lub sprawdzamy posty umieszczone na łamach serwis&oacute;w społecznościowych kilka, a nawet kilkanaście lat temu, często ogarnia nas zażenowanie. Jest to jedynie wierzchołek g&oacute;ry lodowej. Prawdziwe problemy mogą zacząć się, gdy treści te zobaczą nasi obecni znajomi, koledzy i koleżanki z pracy a może nawet przyszły potencjalny pracodawca...</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wraz z rozwojem serwis&oacute;w społecznościowych w internecie zapanował wirtualny ekshibicjonizm. Jego realne konsekwencje obserwować będziemy przez najbliższe dziesięciolecia.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:20px;"><span style="font-size:20px;" class="wixui-rich-text__text">Ł</span><span style="font-size:20px;" class="wixui-rich-text__text">owy na wyborcę. Behawioralny model kampanii i programowanie przyszłych głos&oacute;w</span></h2></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:20px;">&nbsp;</h2></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:20px;">&nbsp;</h2></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Dziś nie jest już żadną tajemnicą, że wybory coraz częściej wygrywa się&hellip; w internecie. Obok programu partii, wizerunek ugrupowania oraz poszczeg&oacute;lnych polityk&oacute;w jest tym, co wyr&oacute;żnia poszczeg&oacute;lne formacje na scenie politycznej. Coraz częściej to właśnie wizerunek polityczny, a nie koncepcje zawarte w programie wyborczym decydują o poparciu wyborc&oacute;w i głosie oddanym w wyborach. Dlaczego tak się dzieje? Wystarczy spojrzeć na statystyki i szanse na złowienie wyborc&oacute;w z sieci nomen omen we własne sieci. Chociaż może bardziej trafne byłoby stwierdzenie o łapani wyborc&oacute;w w sidła. Cały proces do złudzenia przypomina bowiem patenty kłusownik&oacute;w. Miliony polskich internaut&oacute;w stanowią dość łatwy cel dla specjalist&oacute;w od propagandy. Począwszy od reklamy i marketingu, przez medialną dezinformację, aż po świat wielkiej polityki, praktycznie codziennie wszyscy narażeni jesteśmy na r&oacute;żne formy manipulacji.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Obietnice wyborcze, lepszy lub gorsze programy poszczeg&oacute;lnych partii, konferencje prasowe, PR-owe sztuczki i marketing polityczny w czystej postaci. Politycy ścigają się w licytacji na to, kto ma fajniejsze pomysły i na kogo warto oddać sw&oacute;j głos. Co z tego wszystkiego wynika? Co wynika z tych marketingowych sztuczek, obietnic i spotkań z wyborcami? Czasem nie wynika po prostu nic. Czasem jednak mamy prawdziwy polityczny hit.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Choć brzmi to dość niepokojąco, obserwując polską scenę polityczną można odnieść wrażenie, że coraz mniej liczy się jakikolwiek program czy oferta wyborcza. W dzisiejszych czasach w cenie są sztuczki socjotechniczne i możliwość pozyskania zainteresowania potencjalnych wyborc&oacute;w nawet w sytuacji, gdy dana partia nie ma zupełnie nic do zaoferowania. Jak inaczej wytłumaczyć obecność niekt&oacute;rych &bdquo;eksperyment&oacute;w&rdquo; politycznych w polskim parlamencie?</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Z najbardziej aktualnego badania Mediapanel za kwiecień 2023 (wynik&oacute;w za maj w chwili pisania tego tekstu jeszcze nie opublikowano) opracowanego prze PBI/Gemius wynika, że liczba internaut&oacute;w wyniosła w Polsce 29,6 mln. Średnio dziennie korzystało z tego medium 25,7 mln os&oacute;b. Choć oczywiście nie wszyscy z tej grupy mają czynne prawo wyborcze, grupa docelowa i tak pozostaje ogromna. A co z niepełnoletnimi użytkownikami sieci? Oni r&oacute;wnież stanowią łakomy kąsek dla partyjnych spin doktor&oacute;w. Co prawda osoby poniżej 18 roku życia jeszcze nie głosowały w wyborach, ale kiedyś przecież będą &ndash; a to oznacza, że jest jeszcze trochę czasu, żeby przygotować pod to głosowanie podatny grunt. Resztą zajmą się algorytmy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W celu zrozumienia powagi sytuacji, warto jest spr&oacute;bować odpowiedzieć na proste pytanie. Zr&oacute;bmy mały eksperyment myślowy i zastan&oacute;wmy się, jakie informacje na sw&oacute;j temat udostępniamy r&oacute;żnym firmom i stronom trzecim klikając &bdquo;lubię to&rdquo; lub udostępniając poszczeg&oacute;lne treści w mediach społecznościowych. Zapewne w pierwszej chwili uznamy, że są to nic nie znaczące dane &ndash; bo przecież nie mamy nic do ukrycia. Nic bardziej mylnego. To właśnie na podstawie tych z pozoru nic nie znaczących danych algorytmy tworzą nasze profile psychologiczne i behawioralne. To z kolei umożliwia wielkim koncernom, firmom, a także partiom politycznym poznanie naszych upodobań&hellip; i to w skali globalnej. Poznanie preferencji użytkownika to jednak zaledwie pierwszy krok. Następnym jest wykorzystanie tej wiedzy w opracowaniu szytych na miarę kampanii socjotechnicznych, dzięki kt&oacute;rym możliwe będzie wpływanie na podejmowane przez nas decyzje. Każdy, kto zastanawiał się w sklepie nad wyborem produktu X lub Y powinien doskonale wiedzieć, co mam na myśli. Warto zadać sobie pytanie, na ile świadome są dokonywane przez nas codzienne wybory, a na ile jest to wypadkowa kampanii marketingowych i socjotechnicznych sztuczek, na kt&oacute;re jesteśmy niezwykle podatni.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Nie da się ukryć, że żyjąc w czasach internetu, jesteśmy w sporym zakresie zależni od wszechobecnych algorytm&oacute;w. Choć do niedawna była to koncepcja rodem z film&oacute;w science-fiction, dziś rozwiązania te pozwalają na dostarczanie treści dostosowanych do naszych zainteresowań i niestety grozi zamknięciem w bańce informacyjnej. Każda informacja, kt&oacute;rą pozostawiamy w sieci, każde słowo, ruch śledzony jest przez miliony algorytm&oacute;w, kt&oacute;re tworzą nasz cyfrowy portret, decydują o tym, co widzimy, z kim się komunikujemy, co czytamy i jakie decyzje podejmujemy.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Już kilka lat temu odbierając nagrodę Crunchie Award, Mark Zuckerberg stwierdził, że &bdquo;prywatność przestała być normą społeczną&rdquo;. Przekonywał w&oacute;wczas, że potwierdzają to zachowania użytkownik&oacute;w Facebooka. Okazało się, że ważniejsza jest dla nich możliwość komunikacji i wymiany informacji niż ochrona swojego życia prywatnego.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Największy problem polega na tym, że o ile sami nie doceniamy wartości danych na nasz temat &ndash; nie oznacza to, że są one bezwartościowe. Są one bowiem kluczowe dla biznesu i środowisk politycznych. Praktycznie z dnia na dzień zostaliśmy sprofilowani i z konsument&oacute;w zmieniliśmy się w towar. Szczeg&oacute;ły tego procesu opisuje dokładnie profesor Harvardu Shoshana Zuboff w książce &bdquo;Wiek kapitalizmu inwigilacji&rdquo;, a w spos&oacute;b bardziej przystępny popkulturowo ukazuje serial &bdquo;Westworld&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Czy tego chcemy czy nie, dziś musimy liczyć się z tym, że praktycznie w każdej chwili jesteśmy inwigilowani, a każdy nasz ruch w sieci jest pod stałą kontrolą. Kawałek po kawałku algorytmy uczą się naszych zachowań i składają nasz behawioralny model.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Big data, czyli przetwarzanie ogromnych ilości danych, wkracza w kolejne dziedziny i branże - od badań z zakresu fizyki, przez ekonomię, po psychologię czy medycynę. Warto jednak pamiętać, że z pomocą tych właśnie technik można r&oacute;wnież z zadziwiającą precyzją badać nastroje społeczne i preferencje nie tyle złożonych grup, lecz nawet pojedynczych os&oacute;b. Skoro technologię tego typu można wykorzystywać do analizowania i przewidywania wynik&oacute;w wybor&oacute;w, zasadne wydaje się r&oacute;wnież pytanie, czy te same działania można wykorzystać do wpływania na ich wyniki&hellip;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zajmujący się tymi kwestiami naukowcy nie mają już dziś wątpliwości, że masowa analiza danych z pomocą sztucznej inteligencji i innych skomplikowanych metod pozwala obecnie już dość dokładnie przewidzieć wynik wybor&oacute;w i maksymalnie skutecznie oddziaływać na wyborc&oacute;w.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zainteresowane tego typu działaniami podmioty w zasadzie bez trudu mogą dotrzeć do dostępnych publicznie w internecie baz danych z informacjami na temat wyborc&oacute;w. Znajdziemy tam sporo cennych informacji od tego, kim są, jakie mają preferencje, po oczekiwania od polityk&oacute;w, kt&oacute;rym w najbliższych kampaniach będzie trzeba sprostać.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Analiza tych danych możliwa jest dzięki r&oacute;żnym metodom eksploracji danych, technikom uczenia maszynowego oraz technikom ekonometrycznym. Korzystając z tych technik można bez większego trudu opracować najlepszą kampanię wyborczą i prowadzić ją między innymi z tzw. mikrotargetowaniem.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">To właśnie mikrotargetowanie pozwala opracować możliwie najlepiej dopasowaną do indywidualnych potrzeb wersję kampanii wyborczej. Oznacza to, że r&oacute;żne osoby mogą otrzymać r&oacute;żne warianty tej samej kampanii. Każdy zobaczy dokładnie to, co będzie chciał zobaczyć/usłyszeć od polityka lub to, co partia będzie chciała pokazać. To nic innego, jak zamknięcie wyborc&oacute;w w bańce informacyjnej na sterydach, wspieranej przez sztuczną inteligencję.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Model mikrotargetowanej kampanii wyborczej</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">1. Określenie grupy odbiorc&oacute;w o danych preferencjach</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">2. Przygotowanie treści dopasowanych pod konkretne preferencje grupy docelowej (nawet pojedynczego wyborcy)</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">3. Udostępnienie treści wyborczych na zasadach zbliżonych do targowania reklamy internetowej.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">4. Potencjalny wyborca widzi jedynie te treści, kt&oacute;re zostały dopasowane do jego profilu behawioralnego.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">No dobrze, ale skąd poszczeg&oacute;lne firmy i instytucje czerpią te wszystkie dane na nasz temat? Okazuje się, że źr&oacute;deł jest naprawdę sporo. Na przykład ze spis&oacute;w powszechnych można wyciągnąć informacje na temat dochod&oacute;w, wykształcenia, liczby dzieci lub pochodzenia etnicznego obywateli. Gdy dodamy do tego informacje z medi&oacute;w społecznościowych, kt&oacute;re można analizować pod kątem konkretnych sł&oacute;w kluczowych lub fraz otrzymujemy niezwykle cenny materiał źr&oacute;dłowy. Należy podkreślić, że dane tego typu są praktycznie og&oacute;lnodostępne i w zasadzie darmowe. Kolejny stopień wtajemniczenia stanowią płatne bazy danych dotyczące poszczeg&oacute;lnych preferencji konsument&oacute;w. Tam znajdziemy m.in. numery telefon&oacute;w, maile, dane o hipotekach oraz historiach zakup&oacute;w. A to jeszcze nie wszystko. Do tego dochodzą jeszcze dane gromadzone bezpośrednio przez partie, na przykład o ludzi przekazujących darowizny lub wspierających działania partii w ramach wolontariatu. Nie należy zapominać r&oacute;wnież o r&oacute;żnego rodzajach newsletterach i listach mailingowych. Mając dostęp do tego typu danych, przy wykorzystaniu odpowiednich narzędzi analitycznych można sprawdzić, czy dany wyborca częściej otwiera maile dotyczące podatk&oacute;w, praw człowieka, czy sądownictwa. Wiedza na ten temat pozwala następnie dobrać dla takiej osoby odpowiednio dopasowane treści.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Czy jest zatem możliwe, że konkretny polityk lub partia osiąga wyborczy sukces dzięki danym gromadzonym z internetu? To bardzo ryzykowna diagnoza. Gdyby dostęp do tego typu technologii miała wyłącznie jedna partia polityczna w obrębie danego kraju, można byłoby zaryzykować stwierdzenie, że faktycznie tak właśnie się dzieje. Musimy jednak pamiętać o tzw. czynniku ludzkim.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Niezależnie od tego, jak skuteczna lub nieskuteczna jest kampania - to nie dane wygrywają wybory. To nie dane idą do urn i oddają głos. W taką narrację radziłbym nie wchodzić, ponieważ łatwo jest wysunąć zbyt daleko idące wnioski. Doskonale wiemy, że nie od dziś w kampaniach wyborczych używa się r&oacute;żnego rodzaju zabieg&oacute;w socjotechnicznych, a wizerunek polityk&oacute;w często kreowany jest właśnie na podstawie badania opinii. To jeden z filar&oacute;w kampanii PR. Od lat politycy i ich sztaby zamawiali i zamawiają sondaże. One też wybor&oacute;w nie wygrywały, nie wygrywają i nie będą wygrywały. Jeśli jednak obudujemy to wszystko odpowiednią socjotechniką i dodamy do tego zasady wywierania wpływu opisane przez Roberta Cialdiniego, otrzymamy potężne narzędzie do sterowania nastrojami potencjalnych wyborc&oacute;w i przed wrzuceniem głosu do urny wyborczej staniemy przed podobnym dylematem, jak przywołany już przeze mnie przykład ze sklepu. Czym kierujemy się wybierając produkt z niebieską etykietą, a czym z czerwoną? Czy jesteśmy w stanie przebić się przez otaczająco nas bańkę informacyjną? Na te pytanie każdy musi odpowiedzieć sobie indywidualnie.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span style="font-size:18px;" class="wixui-rich-text__text"><span class="wixGuard wixui-rich-text__text">​</span></span></p></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:20px;"><span style="font-size:20px;" class="wixui-rich-text__text">Człowiek kontra sztuczna inteligencja</span></h2></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W dzisiejszych czasach rozw&oacute;j technologiczny umożliwił stworzenie coraz bardziej zaawansowanych robot&oacute;w i sztucznej inteligencji. Jednak r&oacute;wnocześnie na horyzoncie pojawiają się zupełnie nowe wyzwania natury etycznej i prawnej związane z używaniem i wprowadzaniem nowoczesnych technologii w naszym codziennym życiu. Jeszcze na długo przed rozwojem sztucznej inteligencji i powstaniem pierwszych robot&oacute;w zaczęto się zastanawiać, czy w przyszłości nie będzie to stanowić zagrożenia dla ludzkości. Niekt&oacute;rzy naukowcy i filozofowie od lat ostrzegają przed możliwością, że sztuczna inteligencja może stać się zbyt inteligentna i przejąć kontrolę nad ludźmi. Jak bumerang wraca r&oacute;wnież lęk przed buntem maszyn. Są jednak tacy, kt&oacute;rzy uważają, że rozwoju sztucznej inteligencji i robotyzacji nie należy przerywać, lecz ograniczyć systemem konkretnych praw i nakaz&oacute;w.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tymczasem okazuje się, że wraz z rozwojem sztucznej inteligencji człowieka będzie coraz łatwiej oszukać, a maszynę coraz trudniej. Już dziś cyberprzestępcom najłatwiej jest oszukać człowieka, nie walczyć z r&oacute;żnego rodzaju maszynami i cyfrowymi zabezpieczeniami. Dlatego aż 80% wszystkich włamań do system&oacute;w i aplikacji zaczyna się od przejęcia konta lub wrażliwych danych. Ta liczba niestety będzie wciąż wzrastać, ponieważ dzięki rozwiązaniom AI, takim jak m.in. ChatGPT czy midjourney, ataki polegające na socjotechnice stają się jeszcze prostsze. Skan twarzy, odcisk palca, fizyczny klucz to dzisiaj jedyne sposoby, kt&oacute;re są w stanie skutecznie przeszkodzić takim procederom. Hasła już od dawna nie są dla przestępc&oacute;w żadną barierą.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Przejmowanie kolejnych działań &ndash; czy to w biznesie, czy w sferze prywatnej &ndash; przez technologię to kierunek nieodwracalny. Niestety dotyczy to r&oacute;wnież tych, kt&oacute;re niekoniecznie są dobre i etyczne. Już dziś rozwiązania takie, jak ChatGPT bardzo przydają się i są używane przez cyberprzestępc&oacute;w. Szczeg&oacute;lnie przez takich, kt&oacute;rzy nie mają zbyt rozwiniętych umiejętności technicznych. Dla nich to oszczędność pieniędzy i czasu.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Na co powinny więc zwr&oacute;cić uwagę banki czy inne organizacje, kt&oacute;rych pracownicy chcą na co dzień używać generator&oacute;w typu ChatGPT w swojej pracy? Trudno jednoznacznie odpowiedzieć na to pytanie, ponieważ dla wszystkich to, co dziś się dzieje, jest nowością. Jesteśmy na początku tej specyficznej ery. Na pewno jednak każda firma powinna przywiązywać ogromną wagę do tego zagadnienia, tym bardziej że coraz więcej os&oacute;b pracuje zdalnie, często na źle zabezpieczonym sprzęcie, łącząc się z podejrzanymi sieciami. To przecież pierwszy krok do utraty danych uwierzytelniających, kt&oacute;ry otwiera intruzowi bramę do wewnętrznej sieci banku.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Patrząc na zachowania poszczeg&oacute;lnych państw, łatwo zauważyć problem ze zdiagnozowaniem nowego fenomenu. Władze same nie wiedzą, jak do niego podejść. Włochy pierwotnie zablokowały ChatGPT tylko po to, aby kilka tygodni p&oacute;źniej przywr&oacute;cić możliwość jego użytkowania.Wielka Brytania z kolei uznała, że nie powinno się nic regulować i w nic ingerować. Platformy AI mogą być cennymi narzędziami np. do automatyzacji funkcji, wsparciem w kreowaniu pomysł&oacute;w, mogą też sugerować nowy kod i poprawki dla uszkodzonych aplikacji. Sam Gartner przewiduje, że do 2025 roku rynek oprogramowania AI osiągnie prawie 134,8 mld USD, a wzrost rynku ma przyspieszyć z 14,4% w 2021 roku do 31,1% w 2025 roku, znacznie przewyższając og&oacute;lny wzrost na rynku oprogramowania. Zanim jednak firmy przejdą do szybkiego działania, konieczne są środki ostrożności.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W dzisiejszych czasach firmy muszą zmierzyć się z rosnącymi zagrożeniami w obszarze cyberbezpieczeństwa. Wraz z rozwojem technologii pojawiają się coraz bardziej zaawansowane metody atak&oacute;w, kt&oacute;re mogą doprowadzić do wycieku danych i uszkodzenia reputacji przedsiębiorstwa. Jak więc zapewnić odpowiedni poziom zabezpieczeń? Odpowiedzią na to pytanie może być filozofia bezpieczeństwa Zero Trust oraz wykorzystanie sztucznej inteligencji.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Model Zero Trust zakłada podejście oparte na silnym uwierzytelnianiu i maksymalnym ograniczeniu uprawnień użytkownik&oacute;w. Jego gł&oacute;wnym celem jest zapewnienie bezpieczeństwa poprzez wielopoziomowe zabezpieczenia, takie jak uwierzytelnianie, autoryzacja i szyfrowanie danych. W ramach tego modelu każda osoba, nawet ta działająca wewnątrz organizacji, jest traktowana jako potencjalne zagrożenie dla sieci. Dzięki temu podejściu możliwe jest skuteczne ograniczenie ryzyka atak&oacute;w i wyciek&oacute;w informacji.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Model Zero Trust jest szczeg&oacute;lnie przydatny w kontekście rosnącej liczby pracownik&oacute;w pracujących zdalnie i korzystających z r&oacute;żnych urządzeń. W takiej sytuacji, ryzyko atak&oacute;w hakerskich i wyciek&oacute;w danych znacząco wzrasta. Dlatego przedsiębiorstwa coraz częściej szukają rozwiązań, kt&oacute;re pozwolą im zwiększyć poziom ochrony i bezpieczeństwa. Model Zero Trust jest uważany za jedno z najskuteczniejszych podejść w tym zakresie.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wsp&oacute;łczesny świat biznesu coraz bardziej polega na sztucznej inteligencji i innowacyjnych rozwiązaniach. W tym kontekście narzędzia takie jak ChatGPT odgrywają istotną rolę, rewolucjonizując spos&oacute;b działania firm. Wraz z rozwojem tych technologii, konieczne staje się wprowadzanie coraz lepszych zabezpieczeń. Jednym z takich rozwiązań jest wdrażanie kompleksowego silnego uwierzytelniania w całej organizacji.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Co ważne, silne uwierzytelnianie będzie rozwijać się w taki spos&oacute;b, że dla przeciętnego użytkownika stanie się ono zupełnie niezauważalne. Coraz częściej zamiast haseł będziemy korzystać z biometrycznego uwierzytelniania, takiego jak skanowanie linii papilarnych czy rozpoznawanie twarzy. Takie rozwiązania są nie tylko bardziej bezpieczne, ale także bardziej wygodne dla użytkownik&oacute;w.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><h2 class="font_2 wixui-rich-text__text" style="font-size:20px;"><span style="font-size:20px;" class="wixui-rich-text__text">Podsumowanie</span></h2></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Żyjemy w społeczeństwie informacyjnym. Obrazowo można nawet powiedzieć, że pływamy po przepełnionym oceanie danych. Szacunki pokazują, że do 2025 roku globalna produkcja danych wzrośnie do ponad 180 zettabajt&oacute;w. Zastanawiając się przez chwilę nad tym, jak objąć umysłem taki ogrom treści docieramy do znacznie poważniejszego wyzwania &ndash; co zrobić z tymi wszystkimi danymi? Kto może z nich korzystać? A może znacznie bardziej zasadne byłoby pytanie, kto może wykorzystać je przeciwko nam?</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Robert Cialdini - profesor psychologii Uniwersytetu Stanowego w Arizonie, kt&oacute;ry zyskał ogromną popularność na całym świecie m.in. za sprawą książki Wywieranie wpływu na ludzi. Teoria i Praktyka opisał znane od lat zasady wywierania wpływu wywierania wpływu. Co może się stać, gdy mając świadomość niezwykłej skuteczności tych reguł przeniesiemy je w obszar cyberprzestrzeni?</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Użytkownicy medi&oacute;w społecznościowych najczęściej nie mają najmniejszych nawet opor&oacute;w przed publikacją w mediach społecznościowych bardzo osobistych, czy wręcz intymnych zdjęć &ndash; dopiero po latach okazuje się, jak poważny jest to problem i jakie niesie ze sobą konsekwencje. Gdy czytamy Rok 1984 George&rsquo;a Orwella lub Nowy wspaniały świat Aldous&rsquo;a Huxleya może się wydawać dziwne, jak można funkcjonować w świecie praktycznie pozbawionym prywatności. Tymczasem właśnie w takim świecie dziś żyjemy. Prywatność praktycznie przestaje istnieć na naszych oczach. Staje się atrakcyjnym towarem, a dotychczasowych konsument&oacute;w zmienia w&hellip; produkt.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Nie ulega wątpliwości, że na przestrzeni ostatniej dekady kluczową rolę w kontekście form komunikowania zaczęły pełnić media społecznościowe, zawłaszczając sporą część przestrzeni medialnej zarezerwowanej przez lata właśnie dla wszelkiego rodzaju ekspert&oacute;w. W ciągu zaledwie kilku lat eksperci stanęli przed dylematem, czy swoją dotychczasową aktywność przenieść do cyberprzestrzeni i medi&oacute;w społecznościowych czy też nie.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zgodnie z definicją Andreasa Kaplana i Michaela Haenleina, media społecznościowe są &bdquo;grupą bazujących na internetowych rozwiązaniach aplikacji, kt&oacute;re opierają się na ideologicznych i technologicznych podstawach Web 2.0 i kt&oacute;re to umożliwiają tworzenie i wymianę wygenerowanych przez użytkownik&oacute;w treści&rdquo;. Największe portale społecznościowe tworzone były, jako media służące do interakcji międzyludzkiej i w zasadzie już od chwili powstania dysponowały rozbudowanym zestawem narzędzi komunikacyjnych, kt&oacute;re wykraczały poza dotychczasową komunikację społecznościową. Wykorzystanie nowych technologii spowodowało daleko idące zmiany w sposobie komunikacji i komunikowania nie tylko na płaszczyźnie indywidualnej, całych grup, organizacji, a nawet społeczności.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Konkretnych dowod&oacute;w na to, w jaki spos&oacute;b media społecznościowe usprawniły komunikację i znacznie ułatwiły kontakty międzyludzkie, dostarczyło badanie zrealizowane przez psycholog&oacute;w Stanleya Milgrama i Jeffreya Traversa w 1969 roku. Badacze poprosili mieszkańc&oacute;w stanu Nebraska w USA o przekazanie przez swoich znajomych, a następnie przez ich znajomych, paczki dla mieszkańca Bostonu. Następnie prześledzili łańcuch znajomości, dzięki kt&oacute;remu wędrowała przesyłka. Dzięki temu badacze doszli do wniosku, że dw&oacute;ch dowolnych mieszkańc&oacute;w tego stanu dzieli 6,2 znajomego. Badanie te stało się podstawą rozważań dla wielu innych socjolog&oacute;w. Od 2000 roku badacze medi&oacute;w społecznościowych nawiązują do tej myśli. W 2011 roku Johan Ugander, były stażysta w firmie Facebooka, przeprowadził badanie, w kt&oacute;rym udowodnił, że użytkownicy Facebooka są od siebie oddaleni o 4,74 stopnie znajomości. Przykład ten dobitnie pokazuje, w jaki spos&oacute;b rozw&oacute;j medi&oacute;w społecznościowych oraz ich upowszechnienie i popularyzacja zwłaszcza wśr&oacute;d użytkownik&oacute;w młodszego pokolenia internaut&oacute;w zmieniły naturę relacji i sposobu, w jaki je w og&oacute;le nawiązujemy.</p></div><!--/$--></div></div></div><!--/$--></div></section><!--/$--><!--/$--></div></div></section><!--/$--><!--$-->



