

<p class="font_8 wixui-rich-text__text" style="font-size:18px;">Solidarność 2023</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">W ciągu ostatnich ośmiu lat doszło w Polsce do znaczącej korekty modelu rozwoju gospodarki. Pożegnaliśmy (czy na dobre?) neoliberalnego prymusa zgadującego oczekiwania zachodnich inwestor&oacute;w oraz rodzimego biznesu. Witamy model szukania przewag w większej solidarności społecznej i rozwoju własnych strategicznych zasob&oacute;w. Jakby tego było mało zmiana ta jest dość unikalna w skali całego bogatego Zachodu.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Szukając głębszych źr&oacute;deł tej zmiany warto cofnąć się jeszcze głębiej. To znaczy do roku 1980, strajk&oacute;w i powstania &bdquo;Solidarności&rdquo;. Ale przede wszystkim do Porozumień Sierpniowych. Władza i społeczeństwo zawarli w&oacute;wczas ze sobą ważną społeczną umowę, kt&oacute;ra stała na dw&oacute;ch r&oacute;wnie ważnych nogach: politycznej i ekonomicznej. Ta polityczna noga z czasem zaczęła być uważana za kluczową i najważniejsza. Zaś ekonomiczne aspekty Porozumień Sierpniowych zeszły na drugi plan.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">A jednak ekonomia była przecież mocno obecna w 21 stoczniowych postulatach roku 1980. &bdquo;Podnieść wynagrodzenie zasadnicze każdego pracownika (&hellip;) jako rekompensatę dotychczasowego wzrostu cen&rdquo; - głosił postulat &oacute;smy. W dziewiątym strajkujący domagali się zaś automatycznego wzrostu płac &bdquo;r&oacute;wnolegle do wzrostu cen i spadku wartości pieniądza&rdquo;. W dalszej części była zaś mowa o rozbudowie państwa dobrobytu, kt&oacute;ry miał zapewnić Polkom i Polakom możliwość łączenia obowiązk&oacute;w zawodowych oraz rodzinnych (&bdquo;zapewnić odpowiednią liczbę miejsc w żłobkach i przedszkolach&rdquo;, &bdquo;wprowadzić urlop macierzyński płatny przez trzy lata&rdquo;). Mowa jest tu nawet o zmniejszeniu obciążenia pracą i o bardziej solidarystycznej międzypokoleniowej um&oacute;wię społecznej (&bdquo;obniżyć wiek emerytalny&rdquo;). Jednak już dekadę p&oacute;źniej w trakcie faktycznego procesu przechodzenia od PRL do III RP reformy gospodarczo-społeczne, kt&oacute;rych domagała się &bdquo;Solidarność&rdquo; w roku 1980 zostały zdradzone i złożone na ołtarzu &bdquo;skoku w kapitalizm&rdquo; oraz balcerowiczowskiej &bdquo;terapii szokowej&rdquo;. Właśnie na tym polegała faktyczna &bdquo;zdrada ideał&oacute;w Sierpnia&rdquo; - kt&oacute;rą tak często zarzucano potem ojcom założycielom III Rzeczpospolitej. <span style="font-weight:bold;" class="wixui-rich-text__text">Zdjęcie nr. 1</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Pod wieloma względami zmiany ostatnich lat są więc pr&oacute;bą odwr&oacute;cenia tamtych decyzji. Oczywiście rozgrywa się to kilkadziesiąt lat p&oacute;źniej i w odmiennym kontekście politycznym oraz ekonomicznym. Sedno sporu o polskim model rozwoju gospodarczego pozostał jednak taki sam. To właśnie tutaj zaszła w ostatnich latach faktyczna zmiana. I chyba tylko najbardziej rozgorączkowani heroldzi polskiego sporu medialno-politycznego będą chcieli tę zmianę zanegować. Wznieśmy się jednak ponad emocje, sympatie i antypatie. Przyjrzyjmy się liczbom i procesom zaczynając od pracy. A to dlatego, że dekadę temu to właśnie ona stanowiło - jak się powszechnie wydawało - piętę achillesową polskiego modelu transformacji społecznej i gospodarczej. A m&oacute;wiąc konkretnie jego &oacute;wczesnej - jednoznacznie neoliberalnej - fazy. Bezrobocie było uparcie wysokie - aż do 2015 roku permanentnie powyżej 10 proc. I to pomimo trwającej od momentu wejścia Polski do UE (2004 rok) wielkoskalowej migracji zarobkowej Polak&oacute;w na Zach&oacute;d, kt&oacute;rej skutkiem był wyjazd z kraju nawet 2 milion&oacute;w ludzi - zwłaszcza młodych we wczesnym wieku produkcyjnym.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ci, kt&oacute;rzy w&oacute;wczas nie wyjechali funkcjonować musieli na trudnym i nieprzyjaznym rynku pracy z niskimi i dość nier&oacute;wnomiernie ułożonymi płacami. Było to szczeg&oacute;lnie dotkliwe dla obywateli zarabiających w okolicach płacy minimalnej. To tu kwitły najmocniej patologie &bdquo;uśmieciowienia&rdquo;. Czyli pracy superelastycznej, w zasadzie na akord, bez stałych um&oacute;w i bez dostępu do podstawowych zdobyczy socjalnych gwarantowanych przez kodeks pracy (urlop, ubezpiecznie, składka emerytalna). To w tych &bdquo;zaklętych rewirach&rdquo; polskiego rynku zatrudnienia na porządku dziennym były płace na poziomie 3-4 zł za godzinę i praca nawet po 80=90 godzin w miesiącu. Tu pracodawca był kr&oacute;lem, kt&oacute;ry - nierzadko i w związku z permanentną strukturalną przewagą nad pracownikiem - oczekiwał, że pracownik podejmie prace na dowolnych warunkach i jeszcze wykaże się za to wdzięcznością. Zaś na każdy postulat poprawy relacji zatrudnienia pracownik słyszał zazwyczaj: &bdquo;Na twoje miejsce mam pięciu takich, co zrobią to szybciej i taniej. Więc jak się nie podoba to droga wolna. Nikt tu nikogo pod pistoletem nie trzyma!&rdquo;.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">I tu faktycznie w ciagu tej minionej dekady zaszła potężną zmiana. Widać ją już choćby patrząc na samą dynamikę płac. Zacznijmy od płacy minimalnej. W roku 2015 wynosiła 1750 zł. Od 1 lipca sięga 3600 zł. Co oznacza, że urosła o 105 procent. Praca za takie pieniądze dotyczy ok. 2,5 miliona pracujących Polak&oacute;w (jakieś 16 proc. wszystkich zatrudnionych). Nie można jej więc żadną miarą lekceważyć.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Idźmy jednak dalej. Co miesiąc GUS publikuje dane dotyczące średniego wynagrodzenia w tzw. sektorze przedsiębiorstw. Krytycy narzekają na ten wskaźnik podkreślając, że dotyczy wyłącznie firm większych powyżej 9 pracownik&oacute;w - czyli takich kt&oacute;re regularnie raportują dane dotyczące stanu zatrudnienia. Zostawmy na boku fakt, że nie jest to wina albo zła wola urzędu statystycznego. Lecz tego, że małe i średnie przedsiębiorstwa rękami i nogami bronią się przed koniecznością regularnego raportowania swoich danych (w tym płac). A każda pr&oacute;ba nakłonienia ich do tego kończy się wyrzutem na nadmierna biurokratzyację. Ale nawet przy wszystkich tych zastrzeżeniach i narzekaniach płace w sektorze przedsiębiorstw to nie jest - jak by chcieli krytycy - zbi&oacute;r mały albo nieistotny. Pokazuje nam bowiem wynagrodzenia ok. 6,5 mln (40 proc.) pracujących Polak&oacute;w. I w tym właśnie sektorze średnie wynagrodzenie w roku 2015 wynosiło 4121 zł. W czerwcu 2023 (najnowsze dane) sięgnęło 7333 zł. Mamy tu więc wzrost na poziomie 78 proc.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Ale i to nie koniec. Mamy jeszcze miarę zwaną &bdquo;wynagrodzenia w gospodarce narodowej&rdquo;. Te dane podawane są rzadziej - a to dlatego, że wylicza się je na podstawie zeznań podatkowych. Ta miara jest jednak szersza i obejmuje nie tylko sektor przedsiębiorstw, ale także małe i średnie przedsiębiorstwa. W sumie jakieś 11 mln (a więc już większość) pracujących Polak&oacute;w. Średnie wynagrodzenie w tej grupie wynosiło w roku 2015 3899 zł. Dziś (pierwszy kwartał 2023 roku) sięga 7124 zł. Do g&oacute;ry o 82 proc. <span style="font-weight:bold;" class="wixui-rich-text__text">Wykres nr.1</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Możemy tę wyliczankę liczbami ciągnąć dalej. I zestawiać na przykład medianę zarobk&oacute;w (czyli tzw. wartość środkowa, płacę ustawioną w szeregu uporządkowanym, powyżej i poniżej kt&oacute;rej znajduje się jednakowa liczba obserwacji). Tu będziemy mieli zmianę z 3511 zł (rok 2015) do 5617 zł (2023) czyli wzrost o 60 proc. Albo weźmy tzw. dominantę (czyli najcześciej występującą w polskiej gospodarce płacę). Ta w roku 2016 wynosiła 2074 zł. W 2023 (szacunki) zaś 3328 zł. Wzrost o 65 proc.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Oczywiście uważny obserwator zwr&oacute;ci uwagę na inflację, kt&oacute;ra faktycznie zmniejsza realną wartość tych podwyżek. Trzeba przy tym uczciwie zaznaczyć, że inflacja w Polsce lat 2015-2023 faktycznie była wyższa niż w poprzednich latach. Jej przyczyną stał się splot dw&oacute;ch czynnik&oacute;w. Jeden z nich (typowo polski) to efekt&nbsp; wspomnianego wcześniej wzrostu płac. W gospodarce rynkowej to proces dość naturalny. Gdy płace rosną dynamicznie i długo to nie ma siły. W jakiejś mierze odbije się to na wzroście cen. Stanie się tak dlatego, że producenci i sprzedawcy będą szukać sposob&oacute;w na to, by chronić swoje marże zysku. W większości przypadk&oacute;w są oni przecież r&oacute;wnocześnie pracodawcami, kt&oacute;ry ponoszą koszty wzrostu płac. Na dodatek producenci nie są głusi ani ślepi. Widzą, że w gospodarce narodowej zwiększa się siła nabywcza obywateli. I byliby głupcami, gdyby nie pr&oacute;bowali z tego skorzystać.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Jednak ta presja cenowa tłumaczy nam zaledwie część zjawiska inflacji z minionej dekady. I to tę cześć mniejszą. M&oacute;wimy więc zwłaszcza o dynamice cenowej z lat 2015-2021, kt&oacute;ra nie była niepokojąca. Ceny zaś - jak pamiętamy - przekroczyły średnioroczną dynamikę 10 proc. wzrostu dopiero w latach 2021-2023.&nbsp; A to był już oczywiście efekt szok&oacute;w zewnętrznych. W tym pandemii covid-19, kt&oacute;ra naruszyła łańcuchy handlu międzynarodowego - sprawiając, że wiele kluczowych towar&oacute;w i surowc&oacute;w (ropa)&nbsp; stało się przez to droższe. Dzieła dokończyło zaś geopolityczne starcie z Rosją, kt&oacute;ra - pr&oacute;bując zmusić Zach&oacute;d do uległości w sprawie Ukrainy - podniosła ceny gazu. W pewnym momencie nawet o 300 proc. To nie mogło się nie przełożyć na inflację konsumencką. A Polska - jak wszystkie inne kraje regionu - dostała tu rykoszetem.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Wr&oacute;ćmy jednak do płac. Przyjmijmy, że skumulowana polska inflację za lata 2015-2023 to jakieś 40-45 proc. Por&oacute;wnanie tej inflacji ze wspomnianymi wzrostami wynagrodzeń w Polsce pokazuje, że polskie płace realne z lat 2015-2023 i tak są na znacznym plusie. I to jest doświadczenie wręcz unikalne w skali zachodnioeuropejskiej. W starej Unii płace realne mają bowiem w ciągu minionych 15 lat dynamikę dokładnie odwrotną. Tam mamy potężną stagnację. A nawet spadki. W gospodarkach (i to niemałych) takich jak Włochy czy Wielka Brytania poziom dochod&oacute;w realnych wręcz spadł o jakieś 5-10 proc.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">M&oacute;wiąc o płacach w Polsce należy pamiętać jeszcze o jednym. Uległy one bowiem ostatnio znaczącemu spłaszczeniu. Widać to obserwując na przykład samą dynamikę płacy minimalnej. Trzeba bowiem przypomnieć, że jeszcze w roku&nbsp; 2004 płaca minimalna stanowiła ledwie 36 proc. polskiej średniej krajowej. W roku 2023 - po raz pierwszy w historii III RP - ustawowa płaca minimalna stanowiła już ponad 50 proc. średniego wynagrodzenia. Ta relacja płac minimalnej i średniej to nie są tylko detale i didaskalia. Ona jest istotna, bo pokazuje czy gospodarka nastawiona jest na solidarność i zmniejszanie produkowanych przez realny kapitalizm nier&oacute;wności dochodowych. Czy też państwo o te sprawy nie dba i zostawia je &bdquo;niewidzialnej ręce rynku&rdquo;. M&oacute;wiąc kr&oacute;tko: w pierwszej fazie polskiej transformacji (do roku 2015) działo się to drugie. Ostatnio przeszliśmy jednak do pierwszego modelu. Efekty widać w por&oacute;wnywanych liczbach. <span style="font-weight:bold;" class="wixui-rich-text__text">Wykres nr. 2</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Oczywiście istnieje tyle sposob&oacute;w badania nier&oacute;wności społecznych ilu jest badających je ośrodk&oacute;w. Każda miara ma zaś swoje plusy i minusy. Spośr&oacute;d wielu ja preferuję dane Eurostatu dotyczące dochodu rozporządzalnego (equivalised disposable income). Gł&oacute;wnie dlatego, że są one najpełniejsze i najbardziej aktualne. Wielu badaczy regularnie odgraża się, że zrobi lepsze. Ale dop&oacute;ki takowych nie ma, dop&oacute;ty trzeba się opierać na tym, co mamy.&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Patrząc na te dane widać, że Polska stała się w ostatnich latach krajem r&oacute;wniejszym niż była jeszcze nie tak dawno temu. Przypomnijmy, że nier&oacute;wności liczy się tzw. wsp&oacute;łczynnikiem Giniego. Bada on rozkład dochodu dla populacji lokując go w przedziale od 1 do 100. W takim ujęciu: im niżej tym r&oacute;wniej. Kraj z Ginim na poziomie 1 byłby idealnie r&oacute;wny. Poziom 100 oznaczałby, że jedna osoba ma wszystko, a pozostali nie mają nic. Tak liczony Gini wyni&oacute;sł w Polsce w roku 2021 (najnowsze pełne dane) 26,8. To sytuuje Polskę w gronie tych r&oacute;wniejszych kraj&oacute;w bogatego Zachodu. R&oacute;wniej jest - wedle Eurostatu - w Słowenii, Belgii, Czechach, Finlandii, Holandii i Austrii. Najr&oacute;wniejsi (Słowenia, Belgia) mają Giniego na poziomie 23-24. Za nami są takie kraje jak Dania (27), Francja (29), Niemcy (31), Włochy (32,9) czy Hiszpania (33). Wszystkie one są mniej r&oacute;wne od dzisiejszej Polski. Nie trzeba siedzieć w temacie badania nier&oacute;wności szczeg&oacute;lnie głęboko, by wiedzieć, że to jest jednak spora zmiana. Wcześniej (lata 90) Polska miała nielichy problem z gwałtownym wzrostem nier&oacute;wności. Potem ten proces się zatrzymał. A nier&oacute;wności stanęły na na poziomie średniowysokim - ze wsp&oacute;łczynnikiem Giniego powyżej 30. Spadek zaczął się ewidentnie po roku 2015. Od tamtej pory Gini spadł z właśnie z 30,6 do wspomnianych 26,8.&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Obraz ten można oczywiście uzupełniać o r&oacute;żne barwy i odcienie. W zależności od zainteresowania. Mogą one dotyczyć sytuacji budżetu państwa (spadający udział &bdquo;niebezpiecznego&rdquo; zadłużenia zagranicznego na rzecz &bdquo;bezpieczniejszego&rdquo; długu wewnętrznego albo zmniejszający się rozmiar tzw. luki VAT). Albo pokazywać dynamikę produktywności (Polska ma jeden z lepszych wzrost&oacute;w tzw. wsp&oacute;łczynnika TFP w całej UE). Można też przywołać dane pokazujące, że sporo dzieje się w temacie rozbudowy tych obszar&oacute;w polskiego państwa dobrobytu, kt&oacute;re dotyczą młodszego pokolenia. To znaczy tego, kt&oacute;re pr&oacute;buje łączyć życie zawodowe z obowiązkami rodzicielskimi. W tym kontekście warto przypomnieć, że w latach 2016-2022 liczba żłobk&oacute;w w Polsce zwiększyła się o prawie 100 proc. A wzrost ten dotyczy zar&oacute;wno plac&oacute;wek publicznych jak i prywatnych. Zwiększenie puli tych pierwszych to efekt konkretnych inwestycji publicznych na r&oacute;żnych szczeblach. Wzrost liczby tych drugich nie byłby zaś możliwy bez zwiększenia się siły nabywczej pracujących Polak&oacute;w. <span style="font-weight:bold;" class="wixui-rich-text__text">Wykres nr. 3</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Liczba żłobk&oacute;w i klub&oacute;w dziecięcych w Polsce w latach 2016-2022. źr&oacute;dło: opracowanie własne PIE na podstawie danych GUS, Tygodnik Gospodarczy PIE nr 26/2023</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Warto jednak podsumować sprawę i pokazać, że wszystko to nie zdarzyło się przypadkiem. Tylko jest właśnie efektem wspomnianej zmiany sposobu filozofii ekonomicznej. M&oacute;wiąc najprościej jak się da. Przed rokiem 2015 dominowało u nas przekonanie, że gospodarka jest jak ciasto. Najpierw to ciasto musi wyrosnąć, a dopiero potem wolno je dzielić. Takie patrzenie na sprawę było oczywiście bardzo na rękę wielu potężnym grupom interesu. Akumulacja kapitału pozwalała nielicznym - ale dobrze osadzonym na szczycie kapitalistycznej kolejności dziobania - stale się bogacić. To bogacenie dotyczyło także działającego w Polsce kapitału zagranicznego. Zwycięzcy umieli zaś dobrze wynagradzać tych, co m&oacute;wili, że&hellip; tak jak jest, jest dobrze. I tak przez wiele lat koło się kręciło.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Zmiana tego paradygmatu na bardziej solidarnościowy była więc sporą rewolucją. Robiąc tę zmianę rządząca w ostatnich ośmiu latach Zjednoczona Prawica zakwestionowała przekonanie o gospodarce jako o ciastku, kt&oacute;re najpierw musi wyrosnąć. Ono zaordynowali dzielenie. Oczywiście zwolennicy starego porządku zareagowali rwetesem, że tylko patrzeć wszystko się teraz zawali. Osiem lat p&oacute;źniej widać jednak, że się nie zawaliło. Więcej nawet - całkiem niezły rozw&oacute;j jaki notuje polska gospodarka (i to mimo trudnych warunk&oacute;w zewnętrznych) pokazuje, że rośnięcie jest możliwe także w oparciu o mocniejsze dzielenie oraz rozbudowę własnych zasob&oacute;w. Większa r&oacute;wność poszerza bazę uczestnik&oacute;w aktywnego życia gospodarczego i pobudza popyt wewnętrzny. Polska zaś z modelu neoliberalnego przenosi się w kierunku nowego wzorca. I jeśli już ten nowy model do czegokolwiek por&oacute;wnywać to punktem odniesienia powinien być stary dobry Zach&oacute;d z &bdquo;trzech wspaniałych dekad kapitalizmu&rdquo; zaraz po drugiej wojnie. Gdy zachodni kapitalizm umiał być zawieszony pomiędzy solidaryzmem społecznym a ekonomicznym keynesizmem. I kt&oacute;ry przyni&oacute;sł Zachodowi budowę bogactwa publicznego, z kt&oacute;rego korzysta do dziś.</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;"><span class="wixGuard wixui-rich-text__text">​</span></p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Tę zmianę warto podkreślać, by nie zaginęła w błotku bieżących spor&oacute;w. Bez dw&oacute;ch zdań doceni ją r&oacute;wnież historia.&nbsp;</p></p>
<p style='text-align: justify;'><p class="font_8 wixui-rich-text__text" style="font-size:18px;">Solidarność 2023</p></p>



