<?php

return array (
  0 => 'balcerowski',
  1 => 'kochman',
  2 => 'rosolowski',
  3 => 'luczuk',
  4 => 'domanska',
  5 => 'lewandowski',
  6 => 'kochan',
  7 => 'wos',
  8 => 'gursztyn',
  9 => 'kita',
  10 => 'swietlik',
  11 => 'rutke',
  12 => 'bochenek',
  13 => 'trochanowska',
  14 => 'bruszewski',
  15 => 'okolowski',
  16 => 'lempicka-wyszynska',
  17 => 'horoszko',
  18 => 'giera',
  19 => 'pietr',
  20 => 'rak',
  21 => 'dakowski',
  22 => 'rowinski',
  23 => 'feszler',
  24 => 'ratynski',
  25 => 'trabinski',
);
